import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Shopping
    {"id": "ja_shopping_beginner", "languageCode": "ja", "title": "買い物", "subtitle": "Mua sắm - Beginner", "iconEmoji": "🛒", "level": "Beginner", "colorHex": "#F59E0B", "cardCount": 30},
    {"id": "ja_shopping_intermediate", "languageCode": "ja", "title": "買い物", "subtitle": "Mua sắm - Intermediate", "iconEmoji": "🛒", "level": "Intermediate", "colorHex": "#D97706", "cardCount": 30},
    {"id": "ja_shopping_advanced", "languageCode": "ja", "title": "買い物", "subtitle": "Mua sắm - Advanced", "iconEmoji": "🛒", "level": "Advanced", "colorHex": "#B45309", "cardCount": 30},
    {"id": "ja_shopping_expert", "languageCode": "ja", "title": "買い物", "subtitle": "Mua sắm - Expert", "iconEmoji": "🛒", "level": "Expert", "colorHex": "#92400E", "cardCount": 30},
    
    # Health
    {"id": "ja_health_beginner", "languageCode": "ja", "title": "健康", "subtitle": "Sức khoẻ - Beginner", "iconEmoji": "🏥", "level": "Beginner", "colorHex": "#EF4444", "cardCount": 30},
    {"id": "ja_health_intermediate", "languageCode": "ja", "title": "健康", "subtitle": "Sức khoẻ - Intermediate", "iconEmoji": "🏥", "level": "Intermediate", "colorHex": "#DC2626", "cardCount": 30},
    {"id": "ja_health_advanced", "languageCode": "ja", "title": "健康", "subtitle": "Sức khoẻ - Advanced", "iconEmoji": "🏥", "level": "Advanced", "colorHex": "#B91C1C", "cardCount": 30},
    {"id": "ja_health_expert", "languageCode": "ja", "title": "健康", "subtitle": "Sức khoẻ - Expert", "iconEmoji": "🏥", "level": "Expert", "colorHex": "#991B1B", "cardCount": 30}
]

vocab_data = [
    # ---- SHOPPING ----
    # Beginner (0)
    ("買い物", "Kaimono", "noun", "買い物に行く。", "Mua sắm", "Đi mua sắm.", "Việc mua đồ", "ja_shopping_beginner"),
    ("店", "Mise", "noun", "新しい店。", "Cửa hàng", "Cửa hàng mới.", "Nơi bán hàng", "ja_shopping_beginner"),
    ("スーパー", "Sūpā", "noun", "スーパーで買う。", "Siêu thị", "Mua ở siêu thị.", "Chợ lớn", "ja_shopping_beginner"),
    ("デパート", "Depāto", "noun", "デパートに行く。", "Cửa hàng bách hóa", "Đi đến bách hóa.", "Khu mua sắm lớn", "ja_shopping_beginner"),
    ("コンビニ", "Konbini", "noun", "コンビニが便利。", "Cửa hàng tiện lợi", "Cửa hàng tiện lợi.", "Quán 24h", "ja_shopping_beginner"),
    ("買う", "Kau", "verb", "パンを買う。", "Mua", "Mua bánh mì.", "Lấy đồ trả tiền", "ja_shopping_beginner"),
    ("売る", "Uru", "verb", "車を売る。", "Bán", "Bán xe ô tô.", "Đưa đồ nhận tiền", "ja_shopping_beginner"),
    ("お金", "Okane", "noun", "お金がない。", "Tiền", "Không có tiền.", "Dùng để mua", "ja_shopping_beginner"),
    ("円", "En", "noun", "100円です。", "Yên Nhật (tiền)", "Giá 100 yên.", "Đồng tiền Nhật", "ja_shopping_beginner"),
    ("値段", "Nedan", "noun", "値段が高い。", "Giá cả", "Giá cao.", "Mức tiền", "ja_shopping_beginner"),
    ("高い", "Takai", "adjective", "高い鞄。", "Đắt", "Cái túi đắt.", "Nhiều tiền", "ja_shopping_beginner"),
    ("安い", "Yasui", "adjective", "安い服。", "Rẻ", "Quần áo rẻ.", "Ít tiền", "ja_shopping_beginner"),
    ("レジ", "Reji", "noun", "レジに並ぶ。", "Quầy thu ngân", "Xếp hàng ở quầy thu ngân.", "Nơi tính tiền", "ja_shopping_beginner"),
    ("財布", "Saifu", "noun", "財布を開ける。", "Ví tiền", "Mở ví tiền.", "Đựng tiền", "ja_shopping_beginner"),
    ("カバン", "Kaban", "noun", "カバンに入れる。", "Túi xách", "Bỏ vào túi xách.", "Túi xách", "ja_shopping_beginner"),
    ("品物", "Shinamono", "noun", "品物を選ぶ。", "Hàng hóa", "Chọn hàng hóa.", "Đồ vật", "ja_shopping_beginner"),
    ("袋", "Fukuro", "noun", "袋をください。", "Túi, bao", "Cho tôi cái túi.", "Đựng đồ", "ja_shopping_beginner"),
    ("おつり", "Otsuri", "noun", "おつりをもらう。", "Tiền thừa", "Nhận tiền thừa.", "Tiền thối lại", "ja_shopping_beginner"),
    ("払う", "Harau", "verb", "お金を払う。", "Trả tiền", "Thanh toán tiền.", "Đưa tiền", "ja_shopping_beginner"),
    ("見る", "Miru", "verb", "商品を見る。", "Nhìn, xem", "Xem sản phẩm.", "Quan sát", "ja_shopping_beginner"),
    ("探す", "Sagasu", "verb", "時計を探す。", "Tìm kiếm", "Tìm đồng hồ.", "Cố gắng tìm", "ja_shopping_beginner"),
    ("選ぶ", "Erabu", "verb", "好きな服を選ぶ。", "Chọn", "Chọn áo quần thích.", "Lựa chọn", "ja_shopping_beginner"),
    ("欲しい", "Hoshii", "adjective", "カメラが欲しい。", "Muốn có", "Muốn có cái máy ảnh.", "Khát khao", "ja_shopping_beginner"),
    ("カード", "Kādo", "noun", "カードで払う。", "Thẻ", "Trả bằng thẻ.", "Thẻ ngân hàng", "ja_shopping_beginner"),
    ("現金", "Genkin", "noun", "現金で払う。", "Tiền mặt", "Trả bằng tiền mặt.", "Tiền giấy, xu", "ja_shopping_beginner"),
    ("いくら", "Ikura", "adverb/noun", "これはいくらですか。", "Bao nhiêu tiền", "Cái này bao nhiêu tiền?", "Hỏi giá", "ja_shopping_beginner"),
    ("安売り", "Yasuuri", "noun", "安売りをする。", "Bán hạ giá", "Bán giảm giá.", "Bán rẻ", "ja_shopping_beginner"),
    ("試着", "Shichaku", "noun/verb", "試着する。", "Mặc thử", "Thử quần áo.", "Mặc xem", "ja_shopping_beginner"),
    ("お客様", "Okyakusama", "noun", "お客様が来る。", "Khách hàng", "Khách hàng đến.", "Người mua", "ja_shopping_beginner"),
    ("店員", "Ten'in", "noun", "店員に聞く。", "Nhân viên bán hàng", "Hỏi nhân viên.", "Người bán", "ja_shopping_beginner"),

    # Intermediate (1)
    ("ショッピング", "Shoppingu", "noun", "ショッピングを楽しむ。", "Mua sắm", "Thưởng thức mua sắm.", "Mua sắm tiếng Anh", "ja_shopping_intermediate"),
    ("商店街", "Shoutengai", "noun", "商店街を歩く。", "Khu phố mua sắm", "Đi bộ ở khu phố.", "Khu nhiều cửa hàng", "ja_shopping_intermediate"),
    ("市場", "Ichiba", "noun", "市場で魚を買う。", "Chợ", "Mua cá ở chợ.", "Nơi họp chợ", "ja_shopping_intermediate"),
    ("バーゲン", "Bāgen", "noun", "バーゲンセール。", "Bán giảm giá", "Giảm giá đặc biệt.", "Đợt sale", "ja_shopping_intermediate"),
    ("割引", "Waribiki", "noun", "20%割引。", "Giảm giá", "Giảm giá 20%.", "Khấu trừ", "ja_shopping_intermediate"),
    ("半額", "Hangaku", "noun", "半額で買う。", "Nửa giá", "Mua với nửa giá.", "Giảm 50%", "ja_shopping_intermediate"),
    ("セール", "Sēru", "noun", "夏のセール。", "Đợt khuyến mãi", "Khuyến mãi mùa hè.", "Sự kiện giảm giá", "ja_shopping_intermediate"),
    ("価格", "Kakaku", "noun", "価格を比較する。", "Giá cả (trang trọng)", "So sánh giá cả.", "Mức giá", "ja_shopping_intermediate"),
    ("定価", "Teika", "noun", "定価で買う。", "Giá niêm yết", "Mua bằng giá gốc.", "Giá cố định", "ja_shopping_intermediate"),
    ("消費税", "Shouhizei", "noun", "消費税が上がる。", "Thuế tiêu dùng", "Thuế tăng lên.", "Thuế mua hàng", "ja_shopping_intermediate"),
    ("領収書", "Ryoushuusho", "noun", "領収書をください。", "Hóa đơn, biên lai", "Cho tôi xin hóa đơn.", "Giấy biên nhận", "ja_shopping_intermediate"),
    ("レシート", "Reshīto", "noun", "レシートをもらう。", "Hóa đơn (lẻ)", "Nhận hóa đơn.", "Phiếu thu tiền", "ja_shopping_intermediate"),
    ("返品", "Henpin", "noun/verb", "商品を返品する。", "Trả lại hàng", "Trả lại sản phẩm.", "Gửi trả", "ja_shopping_intermediate"),
    ("交換", "Koukan", "noun/verb", "サイズを交換する。", "Đổi hàng", "Đổi kích cỡ.", "Trao đổi", "ja_shopping_intermediate"),
    ("注文", "Chuumon", "noun/verb", "ネットで注文する。", "Đặt hàng", "Đặt hàng trên mạng.", "Yêu cầu mua", "ja_shopping_intermediate"),
    ("予約", "Yoyaku", "noun/verb", "予約を入れる。", "Đặt trước", "Đặt trước.", "Giữ chỗ", "ja_shopping_intermediate"),
    ("お買い得", "Okaidoku", "noun", "お買い得な商品。", "Món hời", "Sản phẩm món hời.", "Đáng mua", "ja_shopping_intermediate"),
    ("品切れ", "Shinagire", "noun", "その商品は品切れです。", "Hết hàng", "Sản phẩm đó đã hết.", "Không còn hàng", "ja_shopping_intermediate"),
    ("入荷", "Nyuuka", "noun/verb", "新商品が入荷する。", "Nhập hàng", "Hàng mới về.", "Hàng vào kho", "ja_shopping_intermediate"),
    ("在庫", "Zaiko", "noun", "在庫を確認する。", "Tồn kho", "Kiểm tra tồn kho.", "Hàng còn lại", "ja_shopping_intermediate"),
    ("試食", "Shishoku", "noun/verb", "試食をする。", "Ăn thử", "Ăn thử đồ ăn.", "Nếm", "ja_shopping_intermediate"),
    ("試飲", "Shiin", "noun/verb", "ワインを試飲する。", "Uống thử", "Uống thử rượu vang.", "Thử đồ uống", "ja_shopping_intermediate"),
    ("包装", "Housou", "noun/verb", "綺麗に包装する。", "Gói quà", "Gói đẹp mắt.", "Bọc ngoài", "ja_shopping_intermediate"),
    ("送料", "Souryou", "noun", "送料は無料です。", "Phí vận chuyển", "Miễn phí vận chuyển.", "Tiền gửi hàng", "ja_shopping_intermediate"),
    ("無料", "Muryou", "noun", "無料でもらえる。", "Miễn phí", "Có thể nhận miễn phí.", "Không tính tiền", "ja_shopping_intermediate"),
    ("有料", "Yuuryou", "noun", "レジ袋は有料です。", "Có tính phí", "Túi ni lông tính phí.", "Phải trả tiền", "ja_shopping_intermediate"),
    ("両替", "Ryougae", "noun/verb", "お金を両替する。", "Đổi tiền", "Đổi tiền.", "Quy đổi", "ja_shopping_intermediate"),
    ("専門店", "Senmonten", "noun", "靴の専門店。", "Cửa hàng chuyên", "Cửa hàng chuyên bán giày.", "Quán chuyên", "ja_shopping_intermediate"),
    ("薬局", "Yakkyoku", "noun", "薬局で薬を買う。", "Hiệu thuốc", "Mua thuốc ở hiệu thuốc.", "Nhà thuốc", "ja_shopping_intermediate"),
    ("本屋", "Hon'ya", "noun", "本屋で雑誌を買う。", "Hiệu sách", "Mua tạp chí ở nhà sách.", "Tiệm sách", "ja_shopping_intermediate"),

    # Advanced (2)
    ("小売店", "Kouriten", "noun", "地元の小売店。", "Cửa hàng bán lẻ", "Cửa hàng bán lẻ địa phương.", "Bán từng món", "ja_shopping_advanced"),
    ("卸売", "Oroshiuri", "noun", "卸売業者。", "Bán buôn", "Nhà bán buôn.", "Bán số lượng lớn", "ja_shopping_advanced"),
    ("量販店", "Ryouhanten", "noun", "家電量販店。", "Siêu thị (bán số lượng)", "Siêu thị điện máy.", "Cửa hàng bán nhiều", "ja_shopping_advanced"),
    ("直営店", "Chokueiten", "noun", "ブランドの直営店。", "Cửa hàng trực thuộc", "Cửa hàng trực thuộc của thương hiệu.", "Chi nhánh chính", "ja_shopping_advanced"),
    ("代理店", "Dairiten", "noun", "販売代理店。", "Đại lý", "Đại lý bán hàng.", "Nơi phân phối", "ja_shopping_advanced"),
    ("偽物", "Nisemono", "noun", "偽物に注意。", "Hàng giả", "Chú ý hàng giả.", "Hàng fake", "ja_shopping_advanced"),
    ("本物", "Honmono", "noun", "本物のダイヤ。", "Hàng thật", "Kim cương thật.", "Hàng auth", "ja_shopping_advanced"),
    ("中古品", "Chuukohin", "noun", "中古品を買う。", "Hàng cũ", "Mua đồ cũ.", "Đồ secondhand", "ja_shopping_advanced"),
    ("新品", "Shinpin", "noun", "新品同様。", "Hàng mới", "Giống như mới.", "Chưa sử dụng", "ja_shopping_advanced"),
    ("限定品", "Genteihin", "noun", "数量限定品。", "Hàng giới hạn", "Hàng giới hạn số lượng.", "Bản limit", "ja_shopping_advanced"),
    ("日用品", "Nichiyouhin", "noun", "日用品を買いだめする。", "Đồ dùng hàng ngày", "Tích trữ đồ dùng hàng ngày.", "Nhu yếu phẩm", "ja_shopping_advanced"),
    ("贅沢品", "Zeitakuhin", "noun", "贅沢品には税金がかかる。", "Hàng xa xỉ", "Hàng xa xỉ bị đánh thuế.", "Đồ đắt tiền", "ja_shopping_advanced"),
    ("特売品", "Tokubaihin", "noun", "今日の特売品。", "Hàng bán hạ giá đặc biệt", "Mặt hàng đặc biệt hôm nay.", "Đồ sale", "ja_shopping_advanced"),
    ("見切り品", "Mikirihin", "noun", "見切り品を買う。", "Hàng thanh lý", "Mua hàng thanh lý.", "Hàng bán nốt", "ja_shopping_advanced"),
    ("粗悪品", "Soakuhin", "noun", "粗悪品をつかまされる。", "Hàng kém chất lượng", "Bị dí hàng kém chất lượng.", "Đồ dởm", "ja_shopping_advanced"),
    ("品質", "Hinshitsu", "noun", "品質の良い服。", "Chất lượng", "Quần áo chất lượng tốt.", "Phẩm chất hàng", "ja_shopping_advanced"),
    ("保証書", "Hoshousho", "noun", "保証書を保管する。", "Giấy bảo hành", "Bảo quản giấy bảo hành.", "Giấy cam kết", "ja_shopping_advanced"),
    ("返品期限", "Henpin kigen", "noun", "返品期限を過ぎる。", "Hạn đổi trả", "Quá hạn đổi trả.", "Thời hạn trả", "ja_shopping_advanced"),
    ("決済", "Kessai", "noun/verb", "カードで決済する。", "Thanh toán", "Thanh toán bằng thẻ.", "Trả tiền quyết toán", "ja_shopping_advanced"),
    ("分割払い", "Bunkatsubarai", "noun", "分割払いで買う。", "Trả góp", "Mua trả góp.", "Chia nhỏ trả", "ja_shopping_advanced"),
    ("一括払い", "Ikkatsubarai", "noun", "一括払いで支払う。", "Trả một lần", "Trả toàn bộ một lần.", "Trả thẳng", "ja_shopping_advanced"),
    ("請求書", "Seikyuusho", "noun", "請求書が届く。", "Hóa đơn thanh toán", "Hóa đơn đã đến.", "Giấy đòi tiền", "ja_shopping_advanced"),
    ("見積もり", "Mitsumori", "noun", "見積もりを取る。", "Báo giá", "Nhận báo giá.", "Bảng dự tính tiền", "ja_shopping_advanced"),
    ("発注", "Hatchuu", "noun/verb", "商品を発注する。", "Đặt hàng", "Phát đơn đặt hàng.", "Order số lượng", "ja_shopping_advanced"),
    ("仕入れ", "Shiire", "noun", "商品の仕入れ。", "Nhập hàng", "Việc nhập hàng.", "Mua sỉ", "ja_shopping_advanced"),
    ("利益", "Rieki", "noun", "利益を出す。", "Lợi nhuận", "Tạo ra lợi nhuận.", "Lãi", "ja_shopping_advanced"),
    ("赤字", "Akaji", "noun", "今月は赤字だ。", "Lỗ", "Tháng này bị lỗ.", "Tiền hụt", "ja_shopping_advanced"),
    ("黒字", "Kuroji", "noun", "黒字に転じる。", "Lãi", "Chuyển sang có lãi.", "Có lời", "ja_shopping_advanced"),
    ("相場", "Souba", "noun", "相場を調べる。", "Giá thị trường", "Tìm hiểu giá cả thị trường.", "Giá chung", "ja_shopping_advanced"),
    ("顧客", "Kokyaku", "noun", "顧客満足度。", "Khách hàng", "Độ hài lòng của khách hàng.", "Thượng đế", "ja_shopping_advanced"),

    # Expert (3)
    ("購買意欲", "Koubai iyoku", "noun", "購買意欲をそそる。", "Ý muốn mua sắm", "Kích thích ý muốn mua sắm.", "Ham mua", "ja_shopping_expert"),
    ("衝動買い", "Shoudougai", "noun/verb", "衝動買いをする。", "Mua sắm bốc đồng", "Mua sắm bốc đồng.", "Mua không tính trước", "ja_shopping_expert"),
    ("大人買い", "Otonagai", "noun/verb", "漫画を大人買いする。", "Mua sỉ/gom hàng", "Mua trọn bộ truyện tranh.", "Mua kiểu có tiền", "ja_shopping_expert"),
    ("ウィンドウショッピング", "Windou shoppingu", "noun", "ウィンドウショッピングを楽しむ。", "Đi ngắm đồ", "Thích đi ngắm đồ.", "Ngắm nhưng không mua", "ja_shopping_expert"),
    ("ネット通販", "Netto tsuuhan", "noun", "ネット通販を利用する。", "Mua sắm qua mạng", "Sử dụng mua sắm online.", "Mua online", "ja_shopping_expert"),
    ("電子マネー", "Denshi manē", "noun", "電子マネーで払う。", "Tiền điện tử", "Trả bằng tiền điện tử.", "Tiền mạng", "ja_shopping_expert"),
    ("クーポン", "Kūpon", "noun", "クーポンを使う。", "Phiếu giảm giá", "Sử dụng mã giảm giá.", "Mã ưu đãi", "ja_shopping_expert"),
    ("ポイント還元", "Pointo kangen", "noun", "ポイント還元率が高い。", "Hoàn điểm", "Tỷ lệ hoàn điểm cao.", "Trả lại điểm", "ja_shopping_expert"),
    ("キャッシュレス", "Kyasshuresu", "noun", "キャッシュレス決済。", "Thanh toán không tiền mặt", "Thanh toán không dùng tiền mặt.", "Không dùng tiền giấy", "ja_shopping_expert"),
    ("マーケティング", "Māketingu", "noun", "マーケティング戦略。", "Tiếp thị", "Chiến lược tiếp thị.", "Marketing", "ja_shopping_expert"),
    ("ターゲット層", "Tāgetto sou", "noun", "ターゲット層を絞る。", "Khách hàng mục tiêu", "Thu hẹp đối tượng mục tiêu.", "Đối tượng nhắm tới", "ja_shopping_expert"),
    ("顧客ロイヤルティ", "Kokyaku roiyaruti", "noun", "顧客ロイヤルティを高める。", "Lòng trung thành", "Nâng cao lòng trung thành của khách.", "Sự gắn bó", "ja_shopping_expert"),
    ("ニッチ市場", "Nicchi shijou", "noun", "ニッチ市場を狙う。", "Thị trường ngách", "Nhắm vào thị trường ngách.", "Phân khúc nhỏ", "ja_shopping_expert"),
    ("競合他社", "Kyougou tasha", "noun", "競合他社と差別化する。", "Đối thủ cạnh tranh", "Tạo sự khác biệt với đối thủ.", "Công ty đối thủ", "ja_shopping_expert"),
    ("独占禁止法", "Dokusen kinshihou", "noun", "独占禁止法に違反する。", "Luật chống độc quyền", "Vi phạm luật chống độc quyền.", "Luật cạnh tranh", "ja_shopping_expert"),
    ("消費者保護", "Shouhisha hogo", "noun", "消費者保護法。", "Bảo vệ người tiêu dùng", "Luật bảo vệ người tiêu dùng.", "Quyền lợi khách", "ja_shopping_expert"),
    ("クーリングオフ", "Kūringu ofu", "noun", "クーリングオフ制度。", "Quyền hủy mua bán", "Chế độ hủy hợp đồng mua bán.", "Từ chối mua", "ja_shopping_expert"),
    ("悪徳商法", "Akutoku shouhou", "noun", "悪徳商法に騙される。", "Kinh doanh gian lận", "Bị lừa bởi kinh doanh xấu xa.", "Buôn bán gian ác", "ja_shopping_expert"),
    ("詐欺", "Sagi", "noun", "詐欺に遭う。", "Lừa đảo", "Gặp phải lừa đảo.", "Móc túi lừa tiền", "ja_shopping_expert"),
    ("偽装", "Gisou", "noun/verb", "産地偽装。", "Ngụy tạo", "Làm giả xuất xứ.", "Làm giả mạo", "ja_shopping_expert"),
    ("リコール", "Rikōru", "noun/verb", "車をリコールする。", "Thu hồi sản phẩm", "Thu hồi xe ô tô.", "Gọi về sửa", "ja_shopping_expert"),
    ("品質管理", "Hinshitsu kanri", "noun", "徹底した品質管理。", "Quản lý chất lượng", "Quản lý chất lượng triệt để.", "Kiểm soát chất", "ja_shopping_expert"),
    ("サプライチェーン", "Sapuraichēn", "noun", "サプライチェーンの分断。", "Chuỗi cung ứng", "Sự đứt gãy chuỗi cung ứng.", "Đường đi hàng", "ja_shopping_expert"),
    ("物流", "Butsuryuu", "noun", "物流業界。", "Kho vận", "Ngành vận tải kho bãi.", "Lưu thông hàng", "ja_shopping_expert"),
    ("在庫管理", "Zaiko kanri", "noun", "在庫管理システム。", "Quản lý tồn kho", "Hệ thống quản lý tồn kho.", "Kiểm soát kho", "ja_shopping_expert"),
    ("棚卸し", "Tanaoroshi", "noun/verb", "月末の棚卸し。", "Kiểm kê", "Kiểm kê cuối tháng.", "Đếm hàng", "ja_shopping_expert"),
    ("資金繰り", "Shikinguri", "noun", "資金繰りが悪化する。", "Xoay sở vốn", "Vấn đề dòng tiền xấu đi.", "Lưu động vốn", "ja_shopping_expert"),
    ("破産", "Hasan", "noun/verb", "会社が破産する。", "Phá sản", "Công ty phá sản.", "Vỡ nợ", "ja_shopping_expert"),
    ("倒産", "Tousan", "noun/verb", "倒産の危機。", "Phá sản (doanh nghiệp)", "Khủng hoảng phá sản.", "Sập tiệm", "ja_shopping_expert"),
    ("買収", "Baishuu", "noun/verb", "企業を買収する。", "Mua lại", "Thâu tóm doanh nghiệp.", "Thua mua", "ja_shopping_expert"),

    # ---- HEALTH ----
    # Beginner (0)
    ("体", "Karada", "noun", "体に良い。", "Cơ thể", "Tốt cho cơ thể.", "Thân thể", "ja_health_beginner"),
    ("頭", "Atama", "noun", "頭が痛い。", "Đầu", "Đau đầu.", "Phần trên cùng", "ja_health_beginner"),
    ("顔", "Kao", "noun", "顔を洗う。", "Khuôn mặt", "Rửa mặt.", "Mặt mũi", "ja_health_beginner"),
    ("目", "Me", "noun", "目を開ける。", "Mắt", "Mở mắt.", "Dùng để nhìn", "ja_health_beginner"),
    ("耳", "Mimi", "noun", "耳が遠い。", "Tai", "Tai lãng (nghe kém).", "Dùng để nghe", "ja_health_beginner"),
    ("鼻", "Hana", "noun", "鼻水が出る。", "Mũi", "Chảy nước mũi.", "Dùng để ngửi", "ja_health_beginner"),
    ("口", "Kuchi", "noun", "口を閉じる。", "Miệng", "Ngậm miệng lại.", "Dùng để ăn/nói", "ja_health_beginner"),
    ("歯", "Ha", "noun", "歯を磨く。", "Răng", "Đánh răng.", "Nhai thức ăn", "ja_health_beginner"),
    ("手", "Te", "noun", "手を洗う。", "Bàn tay", "Rửa tay.", "Cánh tay", "ja_health_beginner"),
    ("足", "Ashi", "noun", "足が痛い。", "Chân", "Đau chân.", "Giúp di chuyển", "ja_health_beginner"),
    ("髪", "Kami", "noun", "髪を切る。", "Tóc", "Cắt tóc.", "Lông trên đầu", "ja_health_beginner"),
    ("病気", "Byouki", "noun", "病気になる。", "Bệnh tật", "Bị ốm.", "Không khỏe", "ja_health_beginner"),
    ("痛い", "Itai", "adjective", "お腹が痛い。", "Đau", "Đau bụng.", "Cảm giác nhức", "ja_health_beginner"),
    ("風邪", "Kaze", "noun", "風邪を引く。", "Cảm cúm", "Bị cảm.", "Sổ mũi, ho", "ja_health_beginner"),
    ("薬", "Kusuri", "noun", "薬を飲む。", "Thuốc", "Uống thuốc.", "Chữa bệnh", "ja_health_beginner"),
    ("病院", "Byouin", "noun", "病院に行く。", "Bệnh viện", "Đi bệnh viện.", "Nơi khám bệnh", "ja_health_beginner"),
    ("医者", "Isha", "noun", "医者に診てもらう。", "Bác sĩ", "Đi khám bác sĩ.", "Người chữa bệnh", "ja_health_beginner"),
    ("元気", "Genki", "adjective/noun", "元気です。", "Khỏe mạnh", "Tôi khỏe.", "Đầy sức sống", "ja_health_beginner"),
    ("疲れる", "Tsukareru", "verb", "仕事で疲れる。", "Mệt mỏi", "Mệt vì công việc.", "Hết sức", "ja_health_beginner"),
    ("休む", "Yasumu", "verb", "少し休む。", "Nghỉ ngơi", "Nghỉ một chút.", "Nghỉ xả hơi", "ja_health_beginner"),
    ("寝る", "Neru", "verb", "早く寝る。", "Ngủ", "Ngủ sớm.", "Lên giường", "ja_health_beginner"),
    ("起きる", "Okiru", "verb", "朝早く起きる。", "Thức dậy", "Sáng dậy sớm.", "Ngủ dậy", "ja_health_beginner"),
    ("食べる", "Taberu", "verb", "ご飯を食べる。", "Ăn", "Ăn cơm.", "Dùng bữa", "ja_health_beginner"),
    ("飲む", "Nomu", "verb", "水を飲む。", "Uống", "Uống nước.", "Cho nước vào miệng", "ja_health_beginner"),
    ("血", "Chi", "noun", "血が出る。", "Máu", "Chảy máu.", "Chất lỏng màu đỏ", "ja_health_beginner"),
    ("熱", "Netsu", "noun", "熱がある。", "Sốt", "Bị sốt.", "Nhiệt độ cao", "ja_health_beginner"),
    ("咳", "Seki", "noun", "咳が出る。", "Ho", "Bị ho.", "Khạc ra hơi", "ja_health_beginner"),
    ("喉", "Nodo", "noun", "喉が渇く。", "Cổ họng", "Khát nước.", "Bên trong cổ", "ja_health_beginner"),
    ("お腹", "Onaka", "noun", "お腹が空いた。", "Bụng", "Tôi đói bụng.", "Dạ dày", "ja_health_beginner"),
    ("指", "Yubi", "noun", "指を切る。", "Ngón tay", "Cắt đứt ngón tay.", "Phần nhỏ ở bàn tay", "ja_health_beginner"),

    # Intermediate (1)
    ("健康", "Kenkou", "noun/adjective", "健康に気をつける。", "Sức khỏe", "Chú ý sức khỏe.", "Trạng thái khỏe", "ja_health_intermediate"),
    ("体調", "Taichou", "noun", "体調が悪い。", "Tình trạng cơ thể", "Thể trạng không tốt.", "Tình hình sức khỏe", "ja_health_intermediate"),
    ("具合", "Guai", "noun", "具合はどうですか。", "Tình trạng", "Tình trạng thế nào?", "Tình hình", "ja_health_intermediate"),
    ("症状", "Shoujou", "noun", "風邪の症状。", "Triệu chứng", "Triệu chứng cảm.", "Dấu hiệu bệnh", "ja_health_intermediate"),
    ("吐き気", "Hakike", "noun", "吐き気がする。", "Buồn nôn", "Có cảm giác buồn nôn.", "Muốn ói", "ja_health_intermediate"),
    ("めまい", "Memai", "noun", "めまいがする。", "Chóng mặt", "Bị chóng mặt.", "Xây xẩm mặt mày", "ja_health_intermediate"),
    ("寒気", "Samuke", "noun", "寒気がする。", "Ớn lạnh", "Bị ớn lạnh.", "Cảm thấy lạnh", "ja_health_intermediate"),
    ("息切れ", "Ikigire", "noun", "息切れがする。", "Khó thở", "Bị hụt hơi, khó thở.", "Thở dốc", "ja_health_intermediate"),
    ("アレルギー", "Arerugī", "noun", "猫アレルギー。", "Dị ứng", "Dị ứng mèo.", "Phản ứng cơ thể", "ja_health_intermediate"),
    ("怪我", "Kega", "noun/verb", "足に怪我をする。", "Vết thương", "Bị thương ở chân.", "Chấn thương", "ja_health_intermediate"),
    ("骨折", "Kossetsu", "noun/verb", "腕を骨折する。", "Gãy xương", "Bị gãy tay.", "Khớp xương gãy", "ja_health_intermediate"),
    ("出血", "Shukketsu", "noun/verb", "大量に出血する。", "Chảy máu", "Chảy máu nhiều.", "Máu ra ngoài", "ja_health_intermediate"),
    ("手術", "Shujutsu", "noun/verb", "手術を受ける。", "Phẫu thuật", "Nhận phẫu thuật.", "Mổ xẻ", "ja_health_intermediate"),
    ("入院", "Nyuuin", "noun/verb", "病院に入院する。", "Nhập viện", "Vào viện nằm.", "Vào viện", "ja_health_intermediate"),
    ("退院", "Taiin", "noun/verb", "明日退院する。", "Xuất viện", "Ngày mai xuất viện.", "Ra viện", "ja_health_intermediate"),
    ("注射", "Chuusha", "noun/verb", "注射を打つ。", "Tiêm", "Đi tiêm.", "Chích thuốc", "ja_health_intermediate"),
    ("点滴", "Tenteki", "noun/verb", "点滴を受ける。", "Truyền dịch", "Truyền dịch IV.", "Truyền nước", "ja_health_intermediate"),
    ("検査", "Kensa", "noun/verb", "血液検査。", "Xét nghiệm", "Xét nghiệm máu.", "Kiểm tra", "ja_health_intermediate"),
    ("治療", "Chiryou", "noun/verb", "虫歯の治療。", "Điều trị", "Chữa sâu răng.", "Chữa bệnh", "ja_health_intermediate"),
    ("予防", "Yobou", "noun/verb", "病気を予防する。", "Phòng ngừa", "Ngừa bệnh.", "Chống bệnh", "ja_health_intermediate"),
    ("診察", "Shinsatsu", "noun/verb", "医者の診察。", "Khám bệnh", "Bác sĩ khám.", "Xem bệnh", "ja_health_intermediate"),
    ("処方箋", "Shohousen", "noun", "処方箋をもらう。", "Đơn thuốc", "Nhận đơn thuốc.", "Kê toa", "ja_health_intermediate"),
    ("薬局", "Yakkyoku", "noun", "薬局で薬を買う。", "Hiệu thuốc", "Mua thuốc ở tiệm.", "Nơi bán thuốc", "ja_health_intermediate"),
    ("看護師", "Kangoshi", "noun", "優しい看護師。", "Y tá", "Y tá hiền lành.", "Người chăm bệnh", "ja_health_intermediate"),
    ("患者", "Kanja", "noun", "病院の患者。", "Bệnh nhân", "Bệnh nhân trong viện.", "Người ốm", "ja_health_intermediate"),
    ("救急車", "Kyuukyuusha", "noun", "救急車を呼ぶ。", "Xe cứu thương", "Gọi xe cấp cứu.", "Xe chở bệnh", "ja_health_intermediate"),
    ("睡眠", "Suimin", "noun", "睡眠不足。", "Giấc ngủ", "Thiếu ngủ.", "Việc ngủ", "ja_health_intermediate"),
    ("栄養", "Eiyou", "noun", "栄養のバランス。", "Dinh dưỡng", "Cân bằng dinh dưỡng.", "Chất bổ", "ja_health_intermediate"),
    ("体重", "Taijuu", "noun", "体重を量る。", "Cân nặng", "Đo cân nặng.", "Sức nặng cơ thể", "ja_health_intermediate"),
    ("身長", "Shinchou", "noun", "身長が伸びる。", "Chiều cao", "Chiều cao tăng lên.", "Độ cao cơ thể", "ja_health_intermediate"),

    # Advanced (2)
    ("診断", "Shindan", "noun/verb", "医師の診断。", "Chẩn đoán", "Chẩn đoán của bác sĩ.", "Bắt bệnh", "ja_health_advanced"),
    ("内科", "Naika", "noun", "内科を受診する。", "Khoa nội", "Đi khám khoa nội.", "Bệnh bên trong", "ja_health_advanced"),
    ("外科", "Geka", "noun", "外科の手術。", "Khoa ngoại", "Phẫu thuật ngoại khoa.", "Bệnh mổ xẻ", "ja_health_advanced"),
    ("小児科", "Shounika", "noun", "小児科へ行く。", "Khoa nhi", "Đi đến khoa nhi.", "Khám trẻ em", "ja_health_advanced"),
    ("歯科", "Shika", "noun", "歯科に行く。", "Nha khoa", "Đi nha sĩ.", "Khám răng", "ja_health_advanced"),
    ("精神科", "Seishinka", "noun", "精神科の病院。", "Khoa tâm thần", "Bệnh viện tâm thần.", "Khám thần kinh", "ja_health_advanced"),
    ("産婦人科", "Sanfujinka", "noun", "産婦人科に通う。", "Khoa sản", "Đi khám khoa sản.", "Khám thai/phụ khoa", "ja_health_advanced"),
    ("感染", "Kansen", "noun/verb", "ウイルスに感染する。", "Lây nhiễm", "Bị nhiễm virus.", "Nhiễm bệnh", "ja_health_advanced"),
    ("伝染病", "Densenbyou", "noun", "伝染病が流行する。", "Bệnh truyền nhiễm", "Bệnh truyền nhiễm lây lan.", "Bệnh lây lan", "ja_health_advanced"),
    ("免疫", "Men'eki", "noun", "免疫力が落ちる。", "Miễn dịch", "Khả năng miễn dịch giảm.", "Đề kháng", "ja_health_advanced"),
    ("抗生物質", "Kousei busshitsu", "noun", "抗生物質を飲む。", "Thuốc kháng sinh", "Uống kháng sinh.", "Thuốc diệt khuẩn", "ja_health_advanced"),
    ("副作用", "Fukusayou", "noun", "薬の副作用。", "Tác dụng phụ", "Tác dụng phụ của thuốc.", "Tác động ngoài ý", "ja_health_advanced"),
    ("鎮痛剤", "Chintsuuzai", "noun", "鎮痛剤を飲む。", "Thuốc giảm đau", "Uống thuốc giảm đau.", "Cắt cơn đau", "ja_health_advanced"),
    ("麻酔", "Masui", "noun", "麻酔をかける。", "Thuốc mê, gây tê", "Tiêm thuốc tê.", "Làm mất cảm giác", "ja_health_advanced"),
    ("慢性", "Mansei", "noun/adj", "慢性の病気。", "Mãn tính", "Bệnh mãn tính.", "Lâu năm khó khỏi", "ja_health_advanced"),
    ("急性", "Kyuusei", "noun/adj", "急性アルコール中毒。", "Cấp tính", "Ngộ độc cồn cấp tính.", "Phát bệnh đột ngột", "ja_health_advanced"),
    ("炎症", "Enshou", "noun", "喉に炎症を起こす。", "Viêm", "Bị viêm họng.", "Sưng tấy", "ja_health_advanced"),
    ("腫瘍", "Shuyou", "noun", "悪性腫瘍。", "Khối u", "Khối u ác tính.", "Cục bướu", "ja_health_advanced"),
    ("癌", "Gan", "noun", "癌の治療。", "Ung thư", "Điều trị ung thư.", "Bệnh nan y", "ja_health_advanced"),
    ("脳卒中", "Nousotchu", "noun", "脳卒中で倒れる。", "Đột quỵ", "Gục do đột quỵ.", "Tắc mạch máu não", "ja_health_advanced"),
    ("心筋梗塞", "Shinkin kousoku", "noun", "心筋梗塞の発作。", "Nhồi máu cơ tim", "Cơn đau tim.", "Đứng tim", "ja_health_advanced"),
    ("糖尿病", "Tounyoubyou", "noun", "糖尿病の予防。", "Bệnh tiểu đường", "Phòng chống tiểu đường.", "Đường trong máu cao", "ja_health_advanced"),
    ("高血圧", "Kouketsuatsu", "noun", "高血圧に注意する。", "Huyết áp cao", "Chú ý bệnh huyết áp cao.", "Máu bơm mạnh", "ja_health_advanced"),
    ("肥満", "Himan", "noun/verb", "肥満は万病の元。", "Béo phì", "Béo phì là mầm mống bệnh.", "Quá mập", "ja_health_advanced"),
    ("寿命", "Jumyou", "noun", "平均寿命。", "Tuổi thọ", "Tuổi thọ trung bình.", "Mức sống lâu", "ja_health_advanced"),
    ("遺伝", "Iden", "noun/verb", "遺伝的な病気。", "Di truyền", "Bệnh di truyền.", "Truyền từ cha mẹ", "ja_health_advanced"),
    ("鬱病", "Utsubyou", "noun", "鬱病を患う。", "Bệnh trầm cảm", "Mắc bệnh trầm cảm.", "Bệnh tâm lý", "ja_health_advanced"),
    ("ストレス", "Sutoresu", "noun", "ストレスが溜まる。", "Căng thẳng", "Căng thẳng tích tụ.", "Áp lực", "ja_health_advanced"),
    ("カウンセリング", "Kaunseringu", "noun", "カウンセリングを受ける。", "Tư vấn tâm lý", "Nhận tư vấn tâm lý.", "Lời khuyên tâm lý", "ja_health_advanced"),
    ("リハビリ", "Rihabiri", "noun", "怪我のリハビリ。", "Phục hồi chức năng", "Tập phục hồi chấn thương.", "Tập vật lý", "ja_health_advanced"),

    # Expert (3)
    ("臨床", "Rinshou", "noun", "臨床試験。", "Lâm sàng", "Thử nghiệm lâm sàng.", "Thực tế người bệnh", "ja_health_expert"),
    ("病理", "Byouri", "noun", "病理検査。", "Bệnh lý", "Kiểm tra bệnh lý.", "Cơ chế bệnh", "ja_health_expert"),
    ("疫学", "Ekigaku", "noun", "疫学調査。", "Dịch tễ học", "Điều tra dịch tễ.", "Khoa học dịch bệnh", "ja_health_expert"),
    ("予防接種", "Yobou sesshu", "noun", "ワクチンの予防接種。", "Tiêm chủng", "Tiêm chủng vắc-xin.", "Tiêm phòng", "ja_health_expert"),
    ("抗体", "Koutai", "noun", "抗体が作られる。", "Kháng thể", "Kháng thể được tạo ra.", "Chất chống bệnh", "ja_health_expert"),
    ("遺伝子", "Idenshi", "noun", "遺伝子治療。", "Gen", "Trị liệu bằng gen.", "Yếu tố di truyền", "ja_health_expert"),
    ("染色体", "Senshokutai", "noun", "染色体の異常。", "Nhiễm sắc thể", "Bất thường nhiễm sắc thể.", "Vật chất di truyền", "ja_health_expert"),
    ("幹細胞", "Kansaibou", "noun", "幹細胞研究。", "Tế bào gốc", "Nghiên cứu tế bào gốc.", "Tế bào nguồn", "ja_health_expert"),
    ("臓器移植", "Zouki ishoku", "noun", "臓器移植のドナー。", "Ghép tạng", "Người hiến tạng.", "Thay nội tạng", "ja_health_expert"),
    ("拒絶反応", "Kyozetsu hannou", "noun", "拒絶反応を抑える。", "Phản ứng đào thải", "Ức chế phản ứng đào thải.", "Cơ thể đẩy ra", "ja_health_expert"),
    ("緩和ケア", "Kanwa kea", "noun", "緩和ケア病棟。", "Chăm sóc giảm nhẹ", "Khu chăm sóc giảm nhẹ.", "Làm dịu đau đớn", "ja_health_expert"),
    ("尊厳死", "Songenshi", "noun", "尊厳死を選ぶ。", "Trợ tử", "Lựa chọn cái chết tự nhiên.", "Chết có phẩm giá", "ja_health_expert"),
    ("インフォームドコンセント", "Infōmudo konsento", "noun", "インフォームドコンセントを徹底する。", "Đồng ý sau khi thông tin", "Bảo đảm đồng ý có hiểu biết.", "Đồng thuận y khoa", "ja_health_expert"),
    ("セカンドオピニオン", "Sekando opinion", "noun", "セカンドオピニオンを求める。", "Ý kiến thứ hai", "Xin ý kiến bác sĩ khác.", "Tham khảo chuyên gia khác", "ja_health_expert"),
    ("医療過誤", "Iryou kago", "noun", "医療過誤の裁判。", "Sai sót y khoa", "Xét xử sai sót y khoa.", "Lỗi khám chữa", "ja_health_expert"),
    ("診療報酬", "Shinryou houshuu", "noun", "診療報酬の改定。", "Viện phí", "Chỉnh sửa mức viện phí.", "Phí y tế", "ja_health_expert"),
    ("健康保険", "Kenkou hoken", "noun", "健康保険証。", "Bảo hiểm y tế", "Thẻ bảo hiểm y tế.", "Quỹ y tế", "ja_health_expert"),
    ("メタボリックシンドローム", "Metaborikku shindorōmu", "noun", "メタボ予防。", "Hội chứng chuyển hóa", "Phòng hội chứng chuyển hóa.", "Béo phì, cao máu", "ja_health_expert"),
    ("認知症", "Ninchishou", "noun", "認知症の予防。", "Bệnh mất trí nhớ", "Phòng chống đãng trí.", "Lú lẫn", "ja_health_expert"),
    ("合併症", "Gappeishou", "noun", "合併症を引き起こす。", "Biến chứng", "Gây ra biến chứng.", "Bệnh phụ sinh ra", "ja_health_expert"),
    ("潜伏期間", "Senpuku kikan", "noun", "ウイルスの潜伏期間。", "Thời gian ủ bệnh", "Thời kỳ ủ bệnh virus.", "Lúc chưa phát bệnh", "ja_health_expert"),
    ("パンデミック", "Pandemikku", "noun", "パンデミックの発生。", "Đại dịch", "Đại dịch xảy ra.", "Bệnh toàn cầu", "ja_health_expert"),
    ("クラスター", "Kurasutā", "noun", "クラスターが発生する。", "Ổ dịch", "Ổ dịch bùng phát.", "Nhóm lây nhiễm", "ja_health_expert"),
    ("自己免疫疾患", "Jikomen'eki shikkan", "noun", "自己免疫疾患の治療。", "Bệnh tự miễn", "Điều trị bệnh tự miễn.", "Miễn dịch đánh lại cơ thể", "ja_health_expert"),
    ("ホルモン", "Horumon", "noun", "ホルモンバランス。", "Hormone", "Cân bằng nội tiết tố.", "Nội tiết", "ja_health_expert"),
    ("新陳代謝", "Shinchintaisha", "noun", "新陳代謝が活発だ。", "Trao đổi chất", "Trao đổi chất rất mạnh.", "Làm mới tế bào", "ja_health_expert"),
    ("交感神経", "Koukan shinkei", "noun", "交感神経が優位になる。", "Dây thần kinh giao cảm", "Thần kinh giao cảm chi phối.", "Thần kinh kích thích", "ja_health_expert"),
    ("プラセボ効果", "Purasebo kouka", "noun", "プラセボ効果によるもの。", "Hiệu ứng giả dược", "Do hiệu ứng giả dược.", "Hiệu ứng thuốc giả", "ja_health_expert"),
    ("安楽死", "Anrakushi", "noun", "安楽死の議論。", "Cái chết êm dịu", "Tranh luận về cái chết êm dịu.", "Euthanasia", "ja_health_expert"),
    ("バイタルサイン", "Baitaru sain", "noun", "バイタルサインをチェックする。", "Dấu hiệu sinh tồn", "Kiểm tra dấu hiệu sinh tồn.", "Nhịp tim, huyết áp", "ja_health_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_ja, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "ja",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_ja,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Shopping & Health - Japanese) to DB!")
