import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Fashion
    {"id": "ja_fashion_beginner", "languageCode": "ja", "title": "ファッション", "subtitle": "Thời trang - Beginner", "iconEmoji": "👗", "level": "Beginner", "colorHex": "#EC4899", "cardCount": 30},
    {"id": "ja_fashion_intermediate", "languageCode": "ja", "title": "ファッション", "subtitle": "Thời trang - Intermediate", "iconEmoji": "👗", "level": "Intermediate", "colorHex": "#DB2777", "cardCount": 30},
    {"id": "ja_fashion_advanced", "languageCode": "ja", "title": "ファッション", "subtitle": "Thời trang - Advanced", "iconEmoji": "👗", "level": "Advanced", "colorHex": "#BE185D", "cardCount": 30},
    {"id": "ja_fashion_expert", "languageCode": "ja", "title": "ファッション", "subtitle": "Thời trang - Expert", "iconEmoji": "👗", "level": "Expert", "colorHex": "#9D174D", "cardCount": 30},
    
    # Family
    {"id": "ja_family_beginner", "languageCode": "ja", "title": "家族", "subtitle": "Gia đình - Beginner", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Beginner", "colorHex": "#10B981", "cardCount": 30},
    {"id": "ja_family_intermediate", "languageCode": "ja", "title": "家族", "subtitle": "Gia đình - Intermediate", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Intermediate", "colorHex": "#059669", "cardCount": 30},
    {"id": "ja_family_advanced", "languageCode": "ja", "title": "家族", "subtitle": "Gia đình - Advanced", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Advanced", "colorHex": "#047857", "cardCount": 30},
    {"id": "ja_family_expert", "languageCode": "ja", "title": "家族", "subtitle": "Gia đình - Expert", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Expert", "colorHex": "#065F46", "cardCount": 30}
]

vocab_data = [
    # ---- FASHION ----
    # Beginner (0)
    ("服", "Fuku", "noun", "服を着る。", "Quần áo", "Mặc quần áo.", "Trang phục", "ja_fashion_beginner"),
    ("洋服", "Youfuku", "noun", "洋服を買う。", "Quần áo (kiểu Âu)", "Mua quần áo.", "Đồ Âu", "ja_fashion_beginner"),
    ("靴", "Kutsu", "noun", "靴を履く。", "Giày", "Mang giày.", "Giày dép", "ja_fashion_beginner"),
    ("帽子", "Boushi", "noun", "帽子をかぶる。", "Mũ, nón", "Đội mũ.", "Đội trên đầu", "ja_fashion_beginner"),
    ("傘", "Kasa", "noun", "傘をさす。", "Ô, dù", "Che ô.", "Che mưa nắng", "ja_fashion_beginner"),
    ("シャツ", "Shatsu", "noun", "白いシャツ。", "Áo sơ mi", "Áo sơ mi trắng.", "Áo có cổ", "ja_fashion_beginner"),
    ("パンツ", "Pantsu", "noun", "パンツをはく。", "Quần, quần lót", "Mặc quần.", "Mặc phần dưới", "ja_fashion_beginner"),
    ("スカート", "Sukāto", "noun", "スカートをはく。", "Váy", "Mặc váy.", "Váy nữ", "ja_fashion_beginner"),
    ("靴下", "Kutsushita", "noun", "靴下をはく。", "Tất, vớ", "Đi tất.", "Mang ở chân", "ja_fashion_beginner"),
    ("時計", "Tokei", "noun", "時計を見る。", "Đồng hồ", "Xem đồng hồ.", "Xem giờ", "ja_fashion_beginner"),
    ("眼鏡", "Megane", "noun", "眼鏡をかける。", "Kính mắt", "Đeo kính.", "Đeo ở mắt", "ja_fashion_beginner"),
    ("カバン", "Kaban", "noun", "カバンを持つ。", "Túi xách, cặp", "Cầm túi xách.", "Đựng đồ", "ja_fashion_beginner"),
    ("着る", "Kiru", "verb", "シャツを着る。", "Mặc (phần trên)", "Mặc áo sơ mi.", "Hành động mặc", "ja_fashion_beginner"),
    ("履く", "Haku", "verb", "靴を履く。", "Mặc, đi (dưới)", "Đi giày.", "Xỏ vào", "ja_fashion_beginner"),
    ("脱ぐ", "Nugu", "verb", "服を脱ぐ。", "Cởi", "Cởi quần áo.", "Lột ra", "ja_fashion_beginner"),
    ("かぶる", "Kaburu", "verb", "帽子をかぶる。", "Đội", "Đội mũ.", "Đội lên đầu", "ja_fashion_beginner"),
    ("かける", "Kakeru", "verb", "眼鏡をかける。", "Đeo", "Đeo kính.", "Treo/Đeo lên", "ja_fashion_beginner"),
    ("ネクタイ", "Nekutai", "noun", "ネクタイを締める。", "Cà vạt", "Thắt cà vạt.", "Dây thắt cổ áo", "ja_fashion_beginner"),
    ("コート", "Kōto", "noun", "コートを着る。", "Áo khoác", "Mặc áo khoác.", "Áo ngoài", "ja_fashion_beginner"),
    ("セーター", "Sētā", "noun", "セーターを着る。", "Áo len", "Mặc áo len.", "Áo ấm", "ja_fashion_beginner"),
    ("スーツ", "Sūtsu", "noun", "スーツを着る。", "Bộ vest", "Mặc vest.", "Đồ âu phục", "ja_fashion_beginner"),
    ("ポケット", "Poketto", "noun", "ポケットに入れる。", "Túi (quần áo)", "Bỏ vào túi.", "Túi áo quần", "ja_fashion_beginner"),
    ("ボタン", "Botan", "noun", "ボタンを押す。", "Nút, khuy", "Bấm nút.", "Nút gài", "ja_fashion_beginner"),
    ("指輪", "Yubiwa", "noun", "指輪をはめる。", "Nhẫn", "Đeo nhẫn.", "Đeo ngón tay", "ja_fashion_beginner"),
    ("財布", "Saifu", "noun", "財布を落とす。", "Ví tiền", "Đánh rơi ví.", "Đựng tiền", "ja_fashion_beginner"),
    ("黒", "Kuro", "noun", "黒い服。", "Màu đen", "Quần áo đen.", "Màu tối", "ja_fashion_beginner"),
    ("白", "Shiro", "noun", "白い靴。", "Màu trắng", "Giày trắng.", "Màu sáng", "ja_fashion_beginner"),
    ("赤", "Aka", "noun", "赤いシャツ。", "Màu đỏ", "Áo sơ mi đỏ.", "Màu rực", "ja_fashion_beginner"),
    ("青", "Ao", "noun", "青い空。", "Màu xanh dương", "Bầu trời xanh.", "Màu biển", "ja_fashion_beginner"),
    ("着物", "Kimono", "noun", "着物を着る。", "Áo Kimono", "Mặc Kimono.", "Đồ truyền thống", "ja_fashion_beginner"),

    # Intermediate (1)
    ("流行", "Ryuukou", "noun", "流行の服。", "Thịnh hành, mốt", "Quần áo thịnh hành.", "Xu hướng", "ja_fashion_intermediate"),
    ("ファッション", "Fasshon", "noun", "ファッションに興味がある。", "Thời trang", "Có hứng thú với thời trang.", "Phong cách", "ja_fashion_intermediate"),
    ("サイズ", "Saizu", "noun", "サイズが合う。", "Kích cỡ", "Kích cỡ vừa vặn.", "Độ lớn", "ja_fashion_intermediate"),
    ("デザイン", "Dezain", "noun", "デザインが良い。", "Thiết kế", "Thiết kế đẹp.", "Kiểu dáng", "ja_fashion_intermediate"),
    ("ブランド", "Burando", "noun", "ブランド品。", "Thương hiệu", "Hàng hiệu.", "Tên tuổi", "ja_fashion_intermediate"),
    ("派手", "Hade", "adjective", "派手な色。", "Sặc sỡ", "Màu sặc sỡ.", "Nổi bật", "ja_fashion_intermediate"),
    ("地味", "Jimi", "adjective", "地味な服。", "Giản dị", "Quần áo giản dị.", "Trầm, không nổi", "ja_fashion_intermediate"),
    ("おしゃれ", "Oshare", "adjective", "おしゃれな人。", "Sành điệu", "Người sành điệu.", "Ăn diện", "ja_fashion_intermediate"),
    ("似合う", "Niau", "verb", "その服、似合うね。", "Hợp", "Bộ đồ đó hợp với bạn đấy.", "Vừa vặn, tôn dáng", "ja_fashion_intermediate"),
    ("着替える", "Kigaeru", "verb", "パジャマに着替える。", "Thay quần áo", "Thay đồ ngủ.", "Đổi đồ", "ja_fashion_intermediate"),
    ("試着", "Shichaku", "noun/verb", "試着室。", "Mặc thử", "Phòng thử đồ.", "Mặc xem vừa không", "ja_fashion_intermediate"),
    ("模様", "Moyou", "noun", "花の模様。", "Hoa văn", "Họa tiết hoa.", "Hình trang trí", "ja_fashion_intermediate"),
    ("無地", "Muji", "noun", "無地のシャツ。", "Trơn", "Áo sơ mi trơn.", "Không họa tiết", "ja_fashion_intermediate"),
    ("柄", "Gara", "noun", "派手な柄。", "Hoa văn", "Hoa văn sặc sỡ.", "Kiểu cách", "ja_fashion_intermediate"),
    ("生地", "Kiji", "noun", "生地が厚い。", "Vải", "Vải dày.", "Chất liệu", "ja_fashion_intermediate"),
    ("綿", "Men", "noun", "綿のシャツ。", "Bông, cotton", "Áo cotton.", "Vải mát", "ja_fashion_intermediate"),
    ("絹", "Kinu", "noun", "絹のスカーフ。", "Lụa", "Khăn lụa.", "Vải bóng, sang", "ja_fashion_intermediate"),
    ("ウール", "Ūru", "noun", "ウールのセーター。", "Len", "Áo lenウール.", "Sợi lông", "ja_fashion_intermediate"),
    ("皮", "Kawa", "noun", "皮の靴。", "Da", "Giày da.", "Da động vật", "ja_fashion_intermediate"),
    ("袖", "Sode", "noun", "袖が長い。", "Ống tay áo", "Ống tay áo dài.", "Phần bọc tay", "ja_fashion_intermediate"),
    ("襟", "Eri", "noun", "襟を正す。", "Cổ áo", "Chỉnh lại cổ áo.", "Phần cổ áo", "ja_fashion_intermediate"),
    ("裾", "Suso", "noun", "ズボンの裾。", "Gấu quần, vạt áo", "Gấu quần.", "Mép dưới", "ja_fashion_intermediate"),
    ("紐", "Himo", "noun", "靴の紐を結ぶ。", "Dây", "Buộc dây giày.", "Sợi dây", "ja_fashion_intermediate"),
    ("ベルト", "Beruto", "noun", "ベルトを締める。", "Thắt lưng", "Thắt dây nịt.", "Dây nịt", "ja_fashion_intermediate"),
    ("手袋", "Tebukuro", "noun", "手袋をする。", "Găng tay", "Đeo găng tay.", "Bao tay", "ja_fashion_intermediate"),
    ("マフラー", "Mafurā", "noun", "マフラーを巻く。", "Khăn quàng cổ", "Quàng khăn.", "Khăn ấm", "ja_fashion_intermediate"),
    ("アクセサリー", "Akusesarī", "noun", "アクセサリーをつける。", "Đồ trang sức", "Đeo trang sức.", "Phụ kiện", "ja_fashion_intermediate"),
    ("化粧", "Keshou", "noun/verb", "化粧をする。", "Trang điểm", "Trang điểm.", "Làm đẹp mặt", "ja_fashion_intermediate"),
    ("香水", "Kousui", "noun", "香水をつける。", "Nước hoa", "Xịt nước hoa.", "Chất thơm", "ja_fashion_intermediate"),
    ("美容院", "Biyouin", "noun", "美容院に行く。", "Thẩm mỹ viện", "Đến tiệm làm tóc.", "Chỗ làm đẹp", "ja_fashion_intermediate"),

    # Advanced (2)
    ("縫う", "Nuu", "verb", "服を縫う。", "Khâu, may", "May quần áo.", "Dùng kim chỉ", "ja_fashion_advanced"),
    ("裁縫", "Saihou", "noun", "裁縫が得意だ。", "Việc khâu vá", "Giỏi may vá.", "Nghề may", "ja_fashion_advanced"),
    ("染める", "Someru", "verb", "髪を染める。", "Nhuộm", "Nhuộm tóc.", "Làm đổi màu", "ja_fashion_advanced"),
    ("洗濯", "Sentaku", "noun/verb", "洗濯をする。", "Giặt giũ", "Giặt quần áo.", "Làm sạch", "ja_fashion_advanced"),
    ("クリーニング", "Kurīningu", "noun", "クリーニングに出す。", "Giặt ủi", "Mang đi giặt ủi.", "Giặt ngoài tiệm", "ja_fashion_advanced"),
    ("縮む", "Chijimu", "verb", "セーターが縮む。", "Co lại", "Áo len bị co lại.", "Nhỏ đi", "ja_fashion_advanced"),
    ("破れる", "Yabureru", "verb", "服が破れる。", "Bị rách", "Quần áo bị rách.", "Rách nát", "ja_fashion_advanced"),
    ("ほどける", "Hodokeru", "verb", "靴紐がほどける。", "Tuột ra", "Dây giày bị tuột.", "Lỏng ra", "ja_fashion_advanced"),
    ("コーディネート", "Kōdinēto", "noun/verb", "服をコーディネートする。", "Phối đồ", "Phối hợp trang phục.", "Kết hợp đồ", "ja_fashion_advanced"),
    ("カジュアル", "Kajuaru", "adjective", "カジュアルな服装。", "Thông thường", "Trang phục thoải mái.", "Mặc hằng ngày", "ja_fashion_advanced"),
    ("フォーマル", "Fōmaru", "adjective", "フォーマルな場。", "Trang trọng", "Dịp trang trọng.", "Lịch sự", "ja_fashion_advanced"),
    ("上品", "Jouhin", "adjective", "上品なデザイン。", "Thanh lịch", "Thiết kế tao nhã.", "Sang trọng", "ja_fashion_advanced"),
    ("下品", "Gehin", "adjective", "下品な色。", "Thô tục", "Màu sắc kém sang.", "Không thanh lịch", "ja_fashion_advanced"),
    ("奇抜", "Kibatsu", "adjective", "奇抜なファッション。", "Kỳ dị, lạ", "Thời trang độc lạ.", "Khác thường", "ja_fashion_advanced"),
    ("流行遅れ", "Ryuukou okure", "noun", "流行遅れの服。", "Lỗi mốt", "Quần áo lỗi thời.", "Hết hot", "ja_fashion_advanced"),
    ("オーダーメイド", "Ōdā meido", "noun", "オーダーメイドのスーツ。", "Đồ may đo", "Bộ vest may đo.", "Làm theo yêu cầu", "ja_fashion_advanced"),
    ("既製服", "Kiseifuku", "noun", "既製服を買う。", "Quần áo may sẵn", "Mua đồ may sẵn.", "Có sẵn size", "ja_fashion_advanced"),
    ("試着室", "Shichakushitsu", "noun", "試着室はどこですか。", "Phòng thử đồ", "Phòng thử đồ ở đâu?", "Nơi mặc thử", "ja_fashion_advanced"),
    ("姿見", "Sugatami", "noun", "姿見で確認する。", "Gương toàn thân", "Soi gương toàn thân.", "Gương đứng", "ja_fashion_advanced"),
    ("裾上げ", "Susoage", "noun/verb", "裾上げを頼む。", "Lên lai quần", "Nhờ lên gấu quần.", "Cắt bớt gấu", "ja_fashion_advanced"),
    ("ほつれる", "Hotsureru", "verb", "糸がほつれる。", "Bị sờn, xổ chỉ", "Chỉ bị xổ ra.", "Tưa chỉ", "ja_fashion_advanced"),
    ("シワ", "Shiwa", "noun", "服のシワを伸ばす。", "Nếp nhăn", "Làm phẳng nếp nhăn.", "Đường gấp", "ja_fashion_advanced"),
    ("アイロン", "Airon", "noun", "アイロンをかける。", "Bàn là", "Là quần áo.", "Bàn ủi", "ja_fashion_advanced"),
    ("ハンガー", "Hangā", "noun", "ハンガーにかける。", "Mắc áo", "Treo lên mắc áo.", "Móc treo", "ja_fashion_advanced"),
    ("タンス", "Tansu", "noun", "タンスにしまう。", "Tủ quần áo", "Cất vào tủ.", "Tủ đồ", "ja_fashion_advanced"),
    ("着こなす", "Kikonasu", "verb", "スーツを着こなす。", "Mặc đẹp", "Mặc vest rất tôn dáng.", "Biết cách mặc", "ja_fashion_advanced"),
    ("シルエット", "Shiruetto", "noun", "美しいシルエット。", "Hình bóng, dáng", "Dáng áo đẹp.", "Đường nét", "ja_fashion_advanced"),
    ("トレンド", "Torendo", "noun", "最新のトレンド。", "Xu hướng", "Xu hướng mới nhất.", "Hot trend", "ja_fashion_advanced"),
    ("ヴィンテージ", "Vintēji", "noun", "ヴィンテージの服。", "Đồ cổ điển", "Quần áo phong cách cũ.", "Hàng xưa", "ja_fashion_advanced"),
    ("コレクション", "Korekushon", "noun", "パリ・コレクション。", "Bộ sưu tập", "Bộ sưu tập Paris.", "Tập hợp", "ja_fashion_advanced"),

    # Expert (3)
    ("服飾", "Fukushoku", "noun", "服飾デザイン。", "Phục sức", "Thiết kế thời trang.", "Ngành thời trang", "ja_fashion_expert"),
    ("縫製", "Housei", "noun", "縫製工場。", "Sự may vá", "Nhà máy may mặc.", "May công nghiệp", "ja_fashion_expert"),
    ("紡績", "Bouseki", "noun", "紡績業。", "Dệt sợi", "Ngành dệt sợi.", "Kéo sợi", "ja_fashion_expert"),
    ("織物", "Orimono", "noun", "伝統的な織物。", "Vải dệt", "Vải dệt truyền thống.", "Đồ dệt", "ja_fashion_expert"),
    ("染料", "Senryou", "noun", "天然の染料。", "Thuốc nhuộm", "Thuốc nhuộm tự nhiên.", "Chất tạo màu", "ja_fashion_expert"),
    ("漂白", "Hyouhaku", "noun/verb", "服を漂白する。", "Tẩy trắng", "Tẩy trắng quần áo.", "Làm trắng", "ja_fashion_expert"),
    ("採寸", "Saisun", "noun/verb", "スーツの採寸。", "Lấy số đo", "Lấy số đo may vest.", "Đo kích thước", "ja_fashion_expert"),
    ("試作", "Shisaku", "noun/verb", "服の試作。", "May thử", "May thử quần áo.", "Sản xuất nháp", "ja_fashion_expert"),
    ("裁断", "Saidan", "noun/verb", "布を裁断する。", "Cắt vải", "Cắt vải theo mẫu.", "Cắt xén", "ja_fashion_expert"),
    ("型紙", "Katagami", "noun", "型紙を作る。", "Rập (mẫu giấy)", "Tạo mẫu rập.", "Khuôn giấy", "ja_fashion_expert"),
    ("縫い代", "Nuishiro", "noun", "縫い代を取る。", "Mép may", "Chừa mép may.", "Đường dư để may", "ja_fashion_expert"),
    ("裏地", "Uraji", "noun", "裏地をつける。", "Lớp lót", "May lớp lót.", "Vải mặt trong", "ja_fashion_expert"),
    ("表地", "Omoteji", "noun", "表地の素材。", "Lớp ngoài", "Chất liệu mặt ngoài.", "Vải mặt ngoài", "ja_fashion_expert"),
    ("透け感", "Sukekan", "noun", "透け感のある素材。", "Độ xuyên thấu", "Chất liệu hơi xuyên thấu.", "Thấy mờ mờ", "ja_fashion_expert"),
    ("着心地", "Kigokochi", "noun", "着心地が良い。", "Cảm giác mặc", "Cảm giác mặc rất thích.", "Thoải mái khi mặc", "ja_fashion_expert"),
    ("肌触り", "Hadazawari", "noun", "肌触りが柔らかい。", "Cảm giác chạm", "Chạm vào thấy mềm.", "Cảm giác ở da", "ja_fashion_expert"),
    ("伸縮性", "Shinshukusei", "noun", "伸縮性のある生地。", "Tính co giãn", "Vải có tính co giãn.", "Kéo dãn được", "ja_fashion_expert"),
    ("耐久性", "Taikyusei", "noun", "耐久性が高い。", "Độ bền", "Độ bền cao.", "Sử dụng lâu dài", "ja_fashion_expert"),
    ("撥水", "Hassui", "noun", "撥水加工。", "Chống thấm nước", "Xử lý chống thấm.", "Đẩy nước", "ja_fashion_expert"),
    ("保温", "Hoon", "noun", "保温性が高い。", "Giữ nhiệt", "Tính giữ nhiệt cao.", "Giữ ấm", "ja_fashion_expert"),
    ("通気性", "Tsuukisei", "noun", "通気性が良い。", "Độ thoáng khí", "Độ thoáng khí tốt.", "Mát mẻ", "ja_fashion_expert"),
    ("吸水性", "Kyuusuisei", "noun", "吸水性に優れる。", "Khả năng thấm hút", "Thấm hút cực tốt.", "Hút nước", "ja_fashion_expert"),
    ("色落ち", "Iroochi", "noun", "洗濯で色落ちする。", "Phai màu", "Phai màu khi giặt.", "Mất màu", "ja_fashion_expert"),
    ("毛玉", "Kedama", "noun", "毛玉ができる。", "Xù lông", "Bị xù lông.", "Vón cục lông", "ja_fashion_expert"),
    ("虫食い", "Mushikui", "noun", "服の虫食い。", "Bị mọt ăn", "Quần áo bị mọt ăn.", "Sâu cắn", "ja_fashion_expert"),
    ("防虫剤", "Bouchuuzai", "noun", "防虫剤を入れる。", "Thuốc chống côn trùng", "Bỏ thuốc chống mọt.", "Chống sâu bọ", "ja_fashion_expert"),
    ("洗濯表示", "Sentaku hyouji", "noun", "洗濯表示を確認。", "Ký hiệu giặt ủi", "Kiểm tra ký hiệu giặt.", "Chỉ dẫn giặt", "ja_fashion_expert"),
    ("ドライクリーニング", "Dorai kurīningu", "noun", "ドライクリーニング専用。", "Giặt khô", "Chỉ dùng giặt khô.", "Giặt bằng hóa chất", "ja_fashion_expert"),
    ("オートクチュール", "Ōto kuchūru", "noun", "オートクチュールのドレス。", "Thời trang cao cấp", "Váy may đo cao cấp.", "May đo riêng", "ja_fashion_expert"),
    ("プレタポルテ", "Pureta porute", "noun", "プレタポルテのコレクション。", "Thời trang may sẵn cao cấp", "Bộ sưu tập may sẵn.", "May sẵn hàng hiệu", "ja_fashion_expert"),


    # ---- FAMILY ----
    # Beginner (0)
    ("家族", "Kazoku", "noun", "私の家族。", "Gia đình", "Gia đình của tôi.", "Người cùng nhà", "ja_family_beginner"),
    ("両親", "Ryoushin", "noun", "両親に会う。", "Bố mẹ", "Gặp bố mẹ.", "Phụ huynh", "ja_family_beginner"),
    ("父", "Chichi", "noun", "私の父。", "Bố (của mình)", "Bố tôi.", "Cha đẻ", "ja_family_beginner"),
    ("母", "Haha", "noun", "私の母。", "Mẹ (của mình)", "Mẹ tôi.", "Mẹ đẻ", "ja_family_beginner"),
    ("お父さん", "Otousan", "noun", "お父さん、ありがとう。", "Bố (gọi)", "Cảm ơn bố.", "Cách gọi tôn kính", "ja_family_beginner"),
    ("お母さん", "Okaasan", "noun", "お母さんは優しい。", "Mẹ (gọi)", "Mẹ rất hiền.", "Cách gọi tôn kính", "ja_family_beginner"),
    ("兄弟", "Kyoudai", "noun", "兄弟がいますか。", "Anh chị em", "Bạn có anh chị em không?", "Anh em trong nhà", "ja_family_beginner"),
    ("兄", "Ani", "noun", "私の兄。", "Anh trai (của mình)", "Anh trai tôi.", "Con trai lớn hơn", "ja_family_beginner"),
    ("姉", "Ane", "noun", "私の姉。", "Chị gái (của mình)", "Chị gái tôi.", "Con gái lớn hơn", "ja_family_beginner"),
    ("弟", "Otouto", "noun", "私の弟。", "Em trai (của mình)", "Em trai tôi.", "Con trai nhỏ hơn", "ja_family_beginner"),
    ("妹", "Imouto", "noun", "私の妹。", "Em gái (của mình)", "Em gái tôi.", "Con gái nhỏ hơn", "ja_family_beginner"),
    ("お兄さん", "Oniisan", "noun", "彼のお兄さん。", "Anh trai (người khác)", "Anh trai của anh ấy.", "Gọi tôn trọng", "ja_family_beginner"),
    ("お姉さん", "Oneesan", "noun", "彼女のお姉さん。", "Chị gái (người khác)", "Chị gái của cô ấy.", "Gọi tôn trọng", "ja_family_beginner"),
    ("夫", "Otto", "noun", "私の夫。", "Chồng (của mình)", "Chồng tôi.", "Người nam kết hôn", "ja_family_beginner"),
    ("妻", "Tsuma", "noun", "私の妻。", "Vợ (của mình)", "Vợ tôi.", "Người nữ kết hôn", "ja_family_beginner"),
    ("主人", "Shujin", "noun", "私の主人。", "Chồng (của mình)", "Chồng tôi.", "Chủ gia đình", "ja_family_beginner"),
    ("奥さん", "Okusan", "noun", "彼の奥さん。", "Vợ (người khác)", "Vợ của anh ấy.", "Gọi vợ người khác", "ja_family_beginner"),
    ("子供", "Kodomo", "noun", "子供が遊ぶ。", "Trẻ con, con cái", "Bọn trẻ đang chơi.", "Người chưa lớn", "ja_family_beginner"),
    ("息子", "Musuko", "noun", "私の息子。", "Con trai", "Con trai tôi.", "Con trai đẻ", "ja_family_beginner"),
    ("娘", "Musume", "noun", "私の娘。", "Con gái", "Con gái tôi.", "Con gái đẻ", "ja_family_beginner"),
    ("祖父", "Sofu", "noun", "私の祖父。", "Ông (của mình)", "Ông của tôi.", "Bố của bố/mẹ", "ja_family_beginner"),
    ("祖母", "Sobo", "noun", "私の祖母。", "Bà (của mình)", "Bà của tôi.", "Mẹ của bố/mẹ", "ja_family_beginner"),
    ("おじいさん", "Ojiisan", "noun", "おじいさん。", "Ông (gọi)", "Ông ơi.", "Gọi ông", "ja_family_beginner"),
    ("おばあさん", "Obaasan", "noun", "おばあさん。", "Bà (gọi)", "Bà ơi.", "Gọi bà", "ja_family_beginner"),
    ("叔父", "Oji", "noun", "私の叔父。", "Chú/bác trai (mình)", "Chú của tôi.", "Anh/em của bố/mẹ", "ja_family_beginner"),
    ("叔母", "Oba", "noun", "私の叔母。", "Cô/dì (mình)", "Dì của tôi.", "Chị/em của bố/mẹ", "ja_family_beginner"),
    ("おじさん", "Ojisan", "noun", "彼のおじさん。", "Chú/bác (gọi)", "Chú của anh ấy.", "Gọi người lớn tuổi nam", "ja_family_beginner"),
    ("おばさん", "Obasan", "noun", "彼女のおばさん。", "Cô/dì (gọi)", "Dì của cô ấy.", "Gọi người lớn tuổi nữ", "ja_family_beginner"),
    ("いとこ", "Itoko", "noun", "私のいとこ。", "Anh chị em họ", "Anh chị em họ của tôi.", "Con của cô/chú/bác", "ja_family_beginner"),
    ("親戚", "Shinseki", "noun", "親戚が集まる。", "Họ hàng", "Họ hàng tụ họp.", "Những người cùng dòng máu", "ja_family_beginner"),

    # Intermediate (1)
    ("夫婦", "Fuufu", "noun", "若い夫婦。", "Vợ chồng", "Vợ chồng trẻ.", "Cặp đôi kết hôn", "ja_family_intermediate"),
    ("孫", "Mago", "noun", "孫と遊ぶ。", "Cháu", "Chơi với cháu.", "Con của con mình", "ja_family_intermediate"),
    ("甥", "Oi", "noun", "私の甥。", "Cháu trai", "Cháu trai của tôi.", "Con trai của anh chị em", "ja_family_intermediate"),
    ("姪", "Mei", "noun", "私の姪。", "Cháu gái", "Cháu gái của tôi.", "Con gái của anh chị em", "ja_family_intermediate"),
    ("義理", "Giri", "noun", "義理の兄。", "Theo pháp luật, nghĩa", "Anh rể/Anh vợ.", "Không cùng huyết thống", "ja_family_intermediate"),
    ("家事", "Kaji", "noun", "家事をする。", "Việc nhà", "Làm việc nhà.", "Việc dọn dẹp", "ja_family_intermediate"),
    ("育児", "Ikuji", "noun", "育児に忙しい。", "Nuôi dạy trẻ", "Bận rộn chăm con.", "Chăm sóc em bé", "ja_family_intermediate"),
    ("長男", "Chounan", "noun", "彼は長男です。", "Con trai trưởng", "Anh ấy là con cả.", "Con trai đầu lòng", "ja_family_intermediate"),
    ("長女", "Choujo", "noun", "彼女は長女です。", "Con gái trưởng", "Cô ấy là con gái lớn.", "Con gái đầu lòng", "ja_family_intermediate"),
    ("次男", "Jinan", "noun", "次男が生まれました。", "Con trai thứ hai", "Con trai thứ hai đã ra đời.", "Con trai thứ", "ja_family_intermediate"),
    ("次女", "Jijo", "noun", "次女の結婚式。", "Con gái thứ hai", "Đám cưới con gái thứ 2.", "Con gái thứ", "ja_family_intermediate"),
    ("末っ子", "Suekko", "noun", "末っ子は甘えん坊だ。", "Con út", "Con út hay nhõng nhẽo.", "Đứa con cuối", "ja_family_intermediate"),
    ("一人っ子", "Hitorikko", "noun", "私は一人っ子です。", "Con một", "Tôi là con một.", "Không có anh chị em", "ja_family_intermediate"),
    ("双子", "Futago", "noun", "双子の兄弟。", "Sinh đôi", "Anh em sinh đôi.", "Đẻ cùng lúc", "ja_family_intermediate"),
    ("仲", "Naka", "noun", "兄弟の仲が良い。", "Mối quan hệ", "Anh em rất hòa thuận.", "Sự thân thiết", "ja_family_intermediate"),
    ("愛情", "Aijou", "noun", "親の愛情。", "Tình yêu thương", "Tình thương của cha mẹ.", "Tình cảm", "ja_family_intermediate"),
    ("尊敬", "Sonkei", "noun/verb", "両親を尊敬する。", "Kính trọng", "Kính trọng bố mẹ.", "Sự tôn trọng", "ja_family_intermediate"),
    ("世話", "Sewa", "noun/verb", "子供の世話をする。", "Chăm sóc", "Chăm sóc con cái.", "Lo lắng cho", "ja_family_intermediate"),
    ("留守番", "Rusuban", "noun", "家で留守番をする。", "Trông nhà", "Ở nhà trông nhà.", "Giữ nhà", "ja_family_intermediate"),
    ("団らん", "Danran", "noun", "家族の団らん。", "Sum họp", "Gia đình sum họp.", "Quây quần", "ja_family_intermediate"),
    ("帰省", "Kisei", "noun/verb", "お盆に帰省する。", "Về quê", "Về quê dịp Obon.", "Về thăm quê", "ja_family_intermediate"),
    ("親孝行", "Oyakoukou", "noun/adj", "親孝行な息子。", "Hiếu thảo", "Người con trai hiếu thảo.", "Báo hiếu", "ja_family_intermediate"),
    ("反抗期", "Hankouki", "noun", "息子は反抗期だ。", "Thời kỳ nổi loạn", "Con trai đang tuổi nổi loạn.", "Tuổi bướng bỉnh", "ja_family_intermediate"),
    ("叱る", "Shikaru", "verb", "子供を叱る。", "Mắng", "La mắng con cái.", "Trách mắng", "ja_family_intermediate"),
    ("褒める", "Homeru", "verb", "子供を褒める。", "Khen ngợi", "Khen ngợi con cái.", "Biểu dương", "ja_family_intermediate"),
    ("甘やかす", "Amayakasu", "verb", "子供を甘やかす。", "Nuông chiều", "Nuông chiều con.", "Chiều chuộng", "ja_family_intermediate"),
    ("しつけ", "Shitsuke", "noun", "厳格なしつけ。", "Dạy dỗ", "Sự dạy dỗ nghiêm khắc.", "Rèn vào khuôn phép", "ja_family_intermediate"),
    ("成長", "Seichou", "noun/verb", "子供の成長。", "Trưởng thành", "Sự lớn lên của con.", "Lớn khôn", "ja_family_intermediate"),
    ("自立", "Jiritsu", "noun/verb", "親から自立する。", "Tự lập", "Tự lập khỏi cha mẹ.", "Đứng trên đôi chân", "ja_family_intermediate"),
    ("結婚", "Kekkon", "noun/verb", "結婚して家族を持つ。", "Kết hôn", "Kết hôn và có gia đình.", "Lập gia đình", "ja_family_intermediate"),

    # Advanced (2)
    ("世帯", "Setai", "noun", "二世代世帯。", "Hộ gia đình", "Gia đình 2 thế hệ.", "Đơn vị gia đình", "ja_family_advanced"),
    ("家計", "Kakei", "noun", "家計を支える。", "Tài chính gia đình", "Gánh vác tài chính gia đình.", "Tiền chi tiêu", "ja_family_advanced"),
    ("共働き", "Tomobataraki", "noun", "共働きの夫婦。", "Vợ chồng cùng đi làm", "Vợ chồng đều đi làm.", "Cả hai kiếm tiền", "ja_family_advanced"),
    ("専業主婦", "Sengyou shufu", "noun", "彼女は専業主婦だ。", "Nội trợ toàn thời gian", "Cô ấy làm nội trợ.", "Chỉ ở nhà làm việc nhà", "ja_family_advanced"),
    ("核家族", "Kakukazoku", "noun", "核家族化が進む。", "Gia đình hạt nhân", "Xu hướng gia đình hạt nhân hóa.", "Gia đình nhỏ", "ja_family_advanced"),
    ("大家族", "Daikazoku", "noun", "大家族で育った。", "Gia đình đông người", "Lớn lên trong gia đình đông đúc.", "Nhiều thế hệ", "ja_family_advanced"),
    ("少子化", "Shoushika", "noun", "少子化問題。", "Giảm tỷ lệ sinh", "Vấn đề tỷ lệ sinh giảm.", "Ít trẻ em", "ja_family_advanced"),
    ("高齢化", "Koureika", "noun", "高齢化社会。", "Già hóa dân số", "Xã hội già hóa.", "Nhiều người già", "ja_family_advanced"),
    ("介護", "Kaigo", "noun/verb", "親の介護。", "Chăm sóc người bệnh/già", "Chăm sóc bố mẹ già.", "Hộ lý", "ja_family_advanced"),
    ("老後", "Rougo", "noun", "老後の生活。", "Tuổi già", "Cuộc sống khi về già.", "Sau khi nghỉ hưu", "ja_family_advanced"),
    ("相続", "Souzoku", "noun/verb", "遺産を相続する。", "Kế thừa", "Kế thừa di sản.", "Thừa kế", "ja_family_advanced"),
    ("遺産", "Isan", "noun", "莫大な遺産。", "Di sản", "Di sản khổng lồ.", "Tài sản để lại", "ja_family_advanced"),
    ("墓参り", "Hakamairi", "noun", "お墓参りに行く。", "Viếng mộ", "Đi tảo mộ.", "Thăm mộ tổ tiên", "ja_family_advanced"),
    ("冠婚葬祭", "Kankonsousai", "noun", "冠婚葬祭のマナー。", "4 nghi lễ lớn", "Quy tắc trong 4 nghi lễ lớn.", "Quan, Hôn, Tang, Tế", "ja_family_advanced"),
    ("絆", "Kizuna", "noun", "家族の絆。", "Sự gắn kết", "Sự gắn kết gia đình.", "Sợi dây liên kết", "ja_family_advanced"),
    ("縁", "En", "noun", "血の縁。", "Duyên, mối liên hệ", "Quan hệ huyết thống.", "Sự ràng buộc", "ja_family_advanced"),
    ("養子", "Youshi", "noun", "養子を迎える。", "Con nuôi", "Nhận con nuôi.", "Con không cùng máu mủ", "ja_family_advanced"),
    ("継母", "Keibo", "noun", "継母に育てられる。", "Mẹ kế", "Được mẹ kế nuôi dưỡng.", "Mẹ ghẻ", "ja_family_advanced"),
    ("継父", "Keifu", "noun", "継父との関係。", "Bố dượng", "Mối quan hệ với bố dượng.", "Chồng sau của mẹ", "ja_family_advanced"),
    ("里帰り", "Satogaeri", "noun/verb", "出産のために里帰りする。", "Về nhà đẻ", "Về quê mẹ để sinh con.", "Về nhà ngoại", "ja_family_advanced"),
    ("跡取り", "Atotori", "noun", "家の跡取り。", "Người nối dõi", "Người nối dõi dòng họ.", "Người thừa kế", "ja_family_advanced"),
    ("姑", "Shuutome", "noun", "姑との関係。", "Mẹ chồng", "Quan hệ với mẹ chồng.", "Mẹ của chồng", "ja_family_advanced"),
    ("舅", "Shuuto", "noun", "舅を尊敬する。", "Bố chồng", "Kính trọng bố chồng.", "Bố của chồng", "ja_family_advanced"),
    ("小姑", "Kojuutome", "noun", "小姑が口出しする。", "Chị/em chồng", "Chị em chồng hay xen vào.", "Chị em của chồng", "ja_family_advanced"),
    ("嫁", "Yome", "noun", "息子の嫁。", "Con dâu", "Con dâu.", "Vợ của con trai", "ja_family_advanced"),
    ("婿", "Muko", "noun", "娘の婿。", "Con rể", "Con rể.", "Chồng của con gái", "ja_family_advanced"),
    ("別居", "Bekkyo", "noun/verb", "夫婦が別居する。", "Ly thân", "Vợ chồng sống riêng.", "Ở riêng", "ja_family_advanced"),
    ("離婚", "Rikon", "noun/verb", "離婚してシングルマザーになる。", "Ly hôn", "Ly hôn và làm mẹ đơn thân.", "Bỏ nhau", "ja_family_advanced"),
    ("再婚", "Saikon", "noun/verb", "彼女は再婚した。", "Tái hôn", "Cô ấy đã tái hôn.", "Cưới lần nữa", "ja_family_advanced"),
    ("未婚", "Mikon", "noun", "未婚の女性。", "Chưa kết hôn", "Phụ nữ chưa chồng.", "Độc thân", "ja_family_advanced"),

    # Expert (3)
    ("戸籍", "Koseki", "noun", "戸籍を登録する。", "Hộ tịch", "Đăng ký hộ tịch.", "Sổ hộ khẩu", "ja_family_expert"),
    ("住民票", "Juuminhyou", "noun", "住民票を移す。", "Giấy đăng ký cư trú", "Chuyển giấy đăng ký cư trú.", "Sổ tạm trú", "ja_family_expert"),
    ("本籍", "Honseki", "noun", "本籍地は東京だ。", "Nguyên quán", "Nguyên quán ở Tokyo.", "Quê quán gốc", "ja_family_expert"),
    ("続柄", "Tsuzukigara", "noun", "続柄を記入する。", "Mối quan hệ", "Điền mối quan hệ họ hàng.", "Quan hệ với chủ hộ", "ja_family_expert"),
    ("扶養", "Fuyou", "noun/verb", "扶養家族。", "Nuôi dưỡng", "Gia đình phụ thuộc.", "Cấp dưỡng", "ja_family_expert"),
    ("親権", "Shinken", "noun", "親権を争う。", "Quyền nuôi con", "Tranh giành quyền nuôi con.", "Quyền làm cha mẹ", "ja_family_expert"),
    ("虐待", "Gyakutai", "noun/verb", "児童虐待。", "Bạo hành", "Bạo hành trẻ em.", "Ngược đãi", "ja_family_expert"),
    ("育児放棄", "Ikuji houki", "noun", "育児放棄が社会問題だ。", "Bỏ bê con cái", "Bỏ bê trẻ em là vấn đề xã hội.", "Bỏ mặc con", "ja_family_expert"),
    ("ＤＶ", "Dī bui", "noun", "ＤＶ被害者。", "Bạo lực gia đình", "Nạn nhân bạo lực gia đình.", "Đánh đập trong nhà", "ja_family_expert"),
    ("過保護", "Kahogo", "noun/adj", "過保護に育てる。", "Bảo bọc quá mức", "Nuôi dạy bảo bọc thái quá.", "Quá che chở", "ja_family_expert"),
    ("放任主義", "Hounin shugi", "noun", "放任主義の親。", "Chủ nghĩa để mặc", "Cha mẹ phó mặc con cái.", "Không can thiệp", "ja_family_expert"),
    ("晩婚化", "Bankonka", "noun", "晩婚化が進む。", "Kết hôn muộn", "Xu hướng kết hôn muộn đang tăng.", "Cưới muộn", "ja_family_expert"),
    ("非婚化", "Hikonka", "noun", "非婚化社会。", "Lười kết hôn", "Xã hội không màng kết hôn.", "Không muốn cưới", "ja_family_expert"),
    ("孤立死", "Koritsushi", "noun", "高齢者の孤立死。", "Chết trong cô độc", "Người già chết trong cô độc.", "Chết không ai biết", "ja_family_expert"),
    ("孤独死", "Kodokushi", "noun", "孤独死を防ぐ。", "Chết một mình", "Ngăn chặn việc chết một mình.", "Qua đời một mình", "ja_family_expert"),
    ("遺言", "Yuigon", "noun", "遺言書を作成する。", "Di chúc", "Lập di chúc.", "Lời trăng trối", "ja_family_expert"),
    ("形見", "Katami", "noun", "祖母の形見。", "Kỷ vật", "Kỷ vật của bà.", "Đồ để lại", "ja_family_expert"),
    ("法事", "Houji", "noun", "法事に出席する。", "Lễ truy điệu", "Tham dự đám giỗ.", "Lễ cúng người mất", "ja_family_expert"),
    ("喪中", "Mochuu", "noun", "喪中のため新年の挨拶を控える。", "Đang chịu tang", "Tránh chúc Tết vì đang có tang.", "Trong thời kì tang", "ja_family_expert"),
    ("墓守", "Hakamori", "noun", "墓守をする。", "Người giữ mộ", "Làm người coi mộ.", "Chăm sóc mộ", "ja_family_expert"),
    ("菩提寺", "Bodaiji", "noun", "先祖代々の菩提寺。", "Chùa thờ tổ tiên", "Ngôi chùa thờ cúng nhiều đời.", "Chùa của dòng họ", "ja_family_expert"),
    ("氏神", "Ujigami", "noun", "氏神様に祈る。", "Thần bản địa", "Cầu nguyện thần bản địa.", "Thần cai quản vùng", "ja_family_expert"),
    ("家父長制", "Kafuchousei", "noun", "家父長制の名残。", "Chế độ gia trưởng", "Tàn dư của chế độ gia trưởng.", "Đàn ông làm chủ", "ja_family_expert"),
    ("母系社会", "Bokei shakai", "noun", "母系社会の文化。", "Xã hội mẫu hệ", "Văn hóa xã hội mẫu hệ.", "Phụ nữ làm chủ", "ja_family_expert"),
    ("姻戚", "Inseki", "noun", "姻戚関係。", "Quan hệ thông gia", "Quan hệ xui gia.", "Bà con bên vợ/chồng", "ja_family_expert"),
    ("血族", "Ketsuzoku", "noun", "血族結婚を避ける。", "Huyết thống", "Tránh kết hôn cùng huyết thống.", "Cùng dòng máu", "ja_family_expert"),
    ("同棲", "Dousei", "noun/verb", "恋人と同棲する。", "Sống thử", "Sống thử với người yêu.", "Sống chung chưa cưới", "ja_family_expert"),
    ("事実婚", "Jijitsukon", "noun", "事実婚を選ぶ。", "Hôn nhân thực tế", "Chọn hôn nhân không đăng ký.", "Sống như vợ chồng", "ja_family_expert"),
    ("選択的夫婦別姓", "Sentakuteki fuufu bessei", "noun", "選択的夫婦別姓の議論。", "Chọn khác họ", "Tranh luận về việc chọn khác họ.", "Giữ họ riêng", "ja_family_expert"),
    ("毒親", "Dokuoya", "noun", "毒親から逃れる。", "Bố mẹ độc hại", "Chạy trốn khỏi bố mẹ độc hại.", "Phụ huynh tiêu cực", "ja_family_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_ja, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "ja",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_ja,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Fashion & Family - Japanese) to DB!")
