import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Technology
    {"id": "ja_tech_beginner", "languageCode": "ja", "title": "テクノロジー", "subtitle": "Công nghệ - Beginner", "iconEmoji": "💻", "level": "Beginner", "colorHex": "#8B5CF6", "cardCount": 30},
    {"id": "ja_tech_intermediate", "languageCode": "ja", "title": "テクノロジー", "subtitle": "Công nghệ - Intermediate", "iconEmoji": "💻", "level": "Intermediate", "colorHex": "#7C3AED", "cardCount": 30},
    {"id": "ja_tech_advanced", "languageCode": "ja", "title": "テクノロジー", "subtitle": "Công nghệ - Advanced", "iconEmoji": "💻", "level": "Advanced", "colorHex": "#6D28D9", "cardCount": 30},
    {"id": "ja_tech_expert", "languageCode": "ja", "title": "テクノロジー", "subtitle": "Công nghệ - Expert", "iconEmoji": "💻", "level": "Expert", "colorHex": "#5B21B6", "cardCount": 30},
    
    # Travel
    {"id": "ja_travel_beginner", "languageCode": "ja", "title": "旅行", "subtitle": "Du lịch - Beginner", "iconEmoji": "✈️", "level": "Beginner", "colorHex": "#06B6D4", "cardCount": 30},
    {"id": "ja_travel_intermediate", "languageCode": "ja", "title": "旅行", "subtitle": "Du lịch - Intermediate", "iconEmoji": "✈️", "level": "Intermediate", "colorHex": "#0891B2", "cardCount": 30},
    {"id": "ja_travel_advanced", "languageCode": "ja", "title": "旅行", "subtitle": "Du lịch - Advanced", "iconEmoji": "✈️", "level": "Advanced", "colorHex": "#0E7490", "cardCount": 30},
    {"id": "ja_travel_expert", "languageCode": "ja", "title": "旅行", "subtitle": "Du lịch - Expert", "iconEmoji": "✈️", "level": "Expert", "colorHex": "#155E75", "cardCount": 30}
]

vocab_data = [
    # ---- TECHNOLOGY ----
    # Beginner (0)
    ("パソコン", "Pasokon", "noun", "パソコンを使う。", "Máy tính cá nhân", "Sử dụng máy tính cá nhân.", "PC", "ja_tech_beginner"),
    ("スマホ", "Sumaho", "noun", "スマホを見る。", "Điện thoại thông minh", "Nhìn điện thoại.", "Smartphone", "ja_tech_beginner"),
    ("電話", "Denwa", "noun/verb", "電話をかける。", "Điện thoại", "Gọi điện thoại.", "Thiết bị liên lạc", "ja_tech_beginner"),
    ("携帯", "Keitai", "noun", "携帯を忘れた。", "Điện thoại di động", "Quên điện thoại di động.", "Cầm theo người", "ja_tech_beginner"),
    ("テレビ", "Terebi", "noun", "テレビを見る。", "Tivi", "Xem Tivi.", "Màn hình chiếu", "ja_tech_beginner"),
    ("カメラ", "Kamera", "noun", "カメラで撮る。", "Máy ảnh", "Chụp bằng máy ảnh.", "Chụp hình", "ja_tech_beginner"),
    ("時計", "Tokei", "noun", "デジタル時計。", "Đồng hồ", "Đồng hồ kỹ thuật số.", "Báo giờ", "ja_tech_beginner"),
    ("電池", "Denchi", "noun", "電池を交換する。", "Pin", "Thay pin.", "Cục cung cấp điện", "ja_tech_beginner"),
    ("画面", "Gamen", "noun", "画面が暗い。", "Màn hình", "Màn hình tối.", "Bề mặt hiển thị", "ja_tech_beginner"),
    ("ボタン", "Botan", "noun", "ボタンを押す。", "Nút bấm", "Bấm nút.", "Công tắc", "ja_tech_beginner"),
    ("インターネット", "Intānetto", "noun", "インターネットにつなぐ。", "Internet", "Kết nối Internet.", "Mạng lưới", "ja_tech_beginner"),
    ("ネット", "Netto", "noun", "ネットで調べる。", "Mạng", "Tra cứu trên mạng.", "Viết tắt của internet", "ja_tech_beginner"),
    ("メール", "Mēru", "noun/verb", "メールを送る。", "Email", "Gửi email.", "Thư điện tử", "ja_tech_beginner"),
    ("ゲーム", "Gēmu", "noun", "ゲームをする。", "Trò chơi điện tử", "Chơi game.", "Giải trí", "ja_tech_beginner"),
    ("アプリ", "Apuri", "noun", "アプリを入れる。", "Ứng dụng", "Cài ứng dụng.", "Phần mềm", "ja_tech_beginner"),
    ("写真", "Shashin", "noun", "写真を撮る。", "Bức ảnh", "Chụp ảnh.", "Lưu lại khoảnh khắc", "ja_tech_beginner"),
    ("動画", "Douga", "noun", "動画を見る。", "Video, clip", "Xem video.", "Hình ảnh động", "ja_tech_beginner"),
    ("電源", "Dengen", "noun", "電源を入れる。", "Nguồn điện", "Bật nguồn.", "Nút Power", "ja_tech_beginner"),
    ("音", "Oto", "noun", "音を大きくする。", "Âm thanh", "Vặn to tiếng.", "Nghe được", "ja_tech_beginner"),
    ("機械", "Kikai", "noun", "機械を動かす。", "Máy móc", "Vận hành máy móc.", "Thiết bị cứng", "ja_tech_beginner"),
    ("動く", "Ugoku", "verb", "時計が動く。", "Hoạt động, di chuyển", "Đồng hồ vẫn chạy.", "Chạy", "ja_tech_beginner"),
    ("止まる", "Tomaru", "verb", "時計が止まる。", "Dừng lại", "Đồng hồ dừng.", "Không chạy nữa", "ja_tech_beginner"),
    ("使う", "Tsukau", "verb", "パソコンを使う。", "Sử dụng", "Sử dụng máy tính.", "Làm cho hoạt động", "ja_tech_beginner"),
    ("壊れる", "Kowareru", "verb", "スマホが壊れる。", "Bị hỏng", "Điện thoại hỏng.", "Hư", "ja_tech_beginner"),
    ("治る", "Naoru", "verb", "パソコンが治る。", "Được sửa xong", "Máy tính được sửa.", "Hết hỏng", "ja_tech_beginner"),
    ("調べる", "Shiraberu", "verb", "ネットで調べる。", "Tìm hiểu, tra cứu", "Tra cứu trên mạng.", "Tìm tòi", "ja_tech_beginner"),
    ("送る", "Okuru", "verb", "メッセージを送る。", "Gửi", "Gửi tin nhắn.", "Đưa đi", "ja_tech_beginner"),
    ("開く", "Hiraku", "verb", "ファイルを開く。", "Mở (file, trang)", "Mở file ra.", "Mở thư mục", "ja_tech_beginner"),
    ("閉じる", "Tojiru", "verb", "画面を閉じる。", "Đóng (file, trang)", "Đóng màn hình.", "Gập lại", "ja_tech_beginner"),
    ("新しい", "Atarashii", "adjective", "新しいスマホ。", "Mới", "Điện thoại thông minh mới.", "Không cũ", "ja_tech_beginner"),

    # Intermediate (1)
    ("検索", "Kensaku", "noun/verb", "情報を検索する。", "Tìm kiếm", "Tìm kiếm thông tin.", "Search", "ja_tech_intermediate"),
    ("情報", "Jouhou", "noun", "情報を得る。", "Thông tin", "Thu thập thông tin.", "Dữ liệu tin tức", "ja_tech_intermediate"),
    ("入力", "Nyuuryoku", "noun/verb", "パスワードを入力する。", "Nhập liệu", "Nhập mật khẩu.", "Đánh phím vào", "ja_tech_intermediate"),
    ("変換", "Henkan", "noun/verb", "漢字に変換する。", "Chuyển đổi", "Chuyển đổi sang chữ Hán.", "Đổi định dạng", "ja_tech_intermediate"),
    ("保存", "Hozon", "noun/verb", "データを保存する。", "Lưu trữ", "Lưu dữ liệu.", "Save", "ja_tech_intermediate"),
    ("削除", "Sakujo", "noun/verb", "ファイルを削除する。", "Xóa", "Xóa tệp tin.", "Delete", "ja_tech_intermediate"),
    ("設定", "Settei", "noun/verb", "設定を変える。", "Cài đặt", "Thay đổi thiết lập.", "Setting", "ja_tech_intermediate"),
    ("接続", "Setsuzoku", "noun/verb", "Wi-Fiに接続する。", "Kết nối", "Kết nối Wi-Fi.", "Link với nhau", "ja_tech_intermediate"),
    ("受信", "Jushin", "noun/verb", "メールを受信する。", "Nhận", "Nhận email.", "Receive", "ja_tech_intermediate"),
    ("返信", "Henshin", "noun/verb", "メールに返信する。", "Trả lời", "Trả lời email.", "Reply", "ja_tech_intermediate"),
    ("転送", "Tensou", "noun/verb", "データを転送する。", "Chuyển tiếp", "Chuyển dữ liệu đi.", "Forward", "ja_tech_intermediate"),
    ("添付", "Tenpu", "noun/verb", "画像を添付する。", "Đính kèm", "Đính kèm hình ảnh.", "Attach", "ja_tech_intermediate"),
    ("ダウンロード", "Daunrōdo", "noun/verb", "アプリをダウンロード。", "Tải về", "Tải ứng dụng.", "Download", "ja_tech_intermediate"),
    ("インストール", "Insutōru", "noun/verb", "ソフトをインストールする。", "Cài đặt", "Cài phần mềm.", "Install", "ja_tech_intermediate"),
    ("コピー", "Kopī", "noun/verb", "文章をコピーする。", "Sao chép", "Sao chép đoạn văn.", "Copy", "ja_tech_intermediate"),
    ("貼り付け", "Haritsuke", "noun/verb", "テキストを貼り付ける。", "Dán (paste)", "Dán văn bản.", "Paste", "ja_tech_intermediate"),
    ("印刷", "Insatsu", "noun/verb", "書類を印刷する。", "In ấn", "In tài liệu.", "Print", "ja_tech_intermediate"),
    ("充電", "Juuden", "noun/verb", "スマホを充電する。", "Sạc pin", "Sạc pin điện thoại.", "Charge", "ja_tech_intermediate"),
    ("画面", "Gamen", "noun", "液晶画面。", "Màn hình", "Màn hình tinh thể lỏng.", "Mặt hiển thị", "ja_tech_intermediate"),
    ("キーボード", "Kībōdo", "noun", "キーボードを打つ。", "Bàn phím", "Gõ bàn phím.", "Keyboard", "ja_tech_intermediate"),
    ("マウス", "Mausu", "noun", "マウスを動かす。", "Chuột máy tính", "Di chuột.", "Mouse", "ja_tech_intermediate"),
    ("プリンター", "Purintā", "noun", "プリンターで印刷する。", "Máy in", "In bằng máy in.", "Printer", "ja_tech_intermediate"),
    ("パスワード", "Pasuwādo", "noun", "パスワードを忘れた。", "Mật khẩu", "Quên mật khẩu.", "Password", "ja_tech_intermediate"),
    ("アカウント", "Akaunto", "noun", "アカウントを作る。", "Tài khoản", "Tạo tài khoản.", "Account", "ja_tech_intermediate"),
    ("ログイン", "Roguin", "noun/verb", "サイトにログインする。", "Đăng nhập", "Đăng nhập trang web.", "Log in", "ja_tech_intermediate"),
    ("ログアウト", "Roguauto", "noun/verb", "システムからログアウトする。", "Đăng xuất", "Đăng xuất khỏi hệ thống.", "Log out", "ja_tech_intermediate"),
    ("再起動", "Saikidou", "noun/verb", "パソコンを再起動する。", "Khởi động lại", "Khởi động lại máy tính.", "Restart", "ja_tech_intermediate"),
    ("フリーズ", "Furīzu", "noun/verb", "画面がフリーズした。", "Bị treo, đóng băng", "Màn hình bị đơ.", "Freeze", "ja_tech_intermediate"),
    ("電波", "Denpa", "noun", "電波が悪い。", "Sóng (điện thoại)", "Sóng yếu.", "Sóng vô tuyến", "ja_tech_intermediate"),
    ("修理", "Shuuri", "noun/verb", "パソコンを修理に出す。", "Sửa chữa", "Mang máy đi sửa.", "Khắc phục lỗi", "ja_tech_intermediate"),

    # Advanced (2)
    ("開発", "Kaihatsu", "noun/verb", "ソフトを開発する。", "Phát triển", "Phát triển phần mềm.", "Development", "ja_tech_advanced"),
    ("技術", "Gijutsu", "noun", "最新の技術。", "Công nghệ, kỹ thuật", "Công nghệ tiên tiến nhất.", "Technology", "ja_tech_advanced"),
    ("人工知能", "Jinkou chinou", "noun", "人工知能の研究。", "Trí tuệ nhân tạo (AI)", "Nghiên cứu trí tuệ nhân tạo.", "AI", "ja_tech_advanced"),
    ("仮想現実", "Kasou genjitsu", "noun", "仮想現実を体験する。", "Thực tế ảo (VR)", "Trải nghiệm thực tế ảo.", "VR", "ja_tech_advanced"),
    ("拡張現実", "Kakuchou genjitsu", "noun", "拡張現実のアプリ。", "Thực tế tăng cường (AR)", "Ứng dụng thực tế tăng cường.", "AR", "ja_tech_advanced"),
    ("端末", "Tanmatsu", "noun", "携帯端末。", "Thiết bị đầu cuối", "Thiết bị di động.", "Device", "ja_tech_advanced"),
    ("機器", "Kiki", "noun", "精密機器。", "Thiết bị", "Thiết bị chính xác.", "Equipment", "ja_tech_advanced"),
    ("装置", "Souchi", "noun", "安全装置。", "Hệ thống, đồ lắp đặt", "Hệ thống an toàn.", "Thiết lập máy", "ja_tech_advanced"),
    ("基盤", "Kiban", "noun", "ITの基盤。", "Nền tảng", "Cơ sở hạ tầng IT.", "Infrastructure", "ja_tech_advanced"),
    ("ネットワーク", "Nettowāku", "noun", "ネットワークを構築する。", "Mạng lưới", "Thiết lập mạng lưới.", "Network", "ja_tech_advanced"),
    ("サーバー", "Sābā", "noun", "サーバーがダウンする。", "Máy chủ", "Máy chủ bị sập.", "Server", "ja_tech_advanced"),
    ("クラウド", "Kuraudo", "noun", "クラウドに保存する。", "Đám mây", "Lưu vào đám mây.", "Cloud", "ja_tech_advanced"),
    ("データベース", "Dētabēsu", "noun", "データベースを管理する。", "Cơ sở dữ liệu", "Quản lý cơ sở dữ liệu.", "Database", "ja_tech_advanced"),
    ("プログラミング", "Puroguramingu", "noun", "プログラミングを学ぶ。", "Lập trình", "Học lập trình.", "Programming", "ja_tech_advanced"),
    ("アルゴリズム", "Arugorizumu", "noun", "検索アルゴリズム。", "Thuật toán", "Thuật toán tìm kiếm.", "Algorithm", "ja_tech_advanced"),
    ("バグ", "Bagu", "noun", "バグを修正する。", "Lỗi phần mềm", "Sửa lỗi phần mềm.", "Bug", "ja_tech_advanced"),
    ("アップデート", "Appudēto", "noun/verb", "システムをアップデートする。", "Cập nhật", "Cập nhật hệ thống.", "Update", "ja_tech_advanced"),
    ("アップグレード", "Appugurēdo", "noun/verb", "PCをアップグレードする。", "Nâng cấp", "Nâng cấp PC.", "Upgrade", "ja_tech_advanced"),
    ("バックアップ", "Bakkuappu", "noun/verb", "データのバックアップを取る。", "Sao lưu", "Sao lưu dữ liệu.", "Backup", "ja_tech_advanced"),
    ("セキュリティ", "Sekyuriti", "noun", "セキュリティ対策。", "Bảo mật", "Giải pháp bảo mật.", "Security", "ja_tech_advanced"),
    ("ウイルス", "Uirusu", "noun", "ウイルスに感染する。", "Virus", "Bị nhiễm virus.", "Virus", "ja_tech_advanced"),
    ("パスワード", "Pasuwādo", "noun", "パスワードを認証する。", "Mật khẩu", "Xác thực mật khẩu.", "Password", "ja_tech_advanced"),
    ("暗号化", "Angouka", "noun/verb", "データを暗号化する。", "Mã hóa", "Mã hóa dữ liệu.", "Encryption", "ja_tech_advanced"),
    ("解読", "Kaidoku", "noun/verb", "暗号を解読する。", "Giải mã", "Giải mã đoạn mã.", "Decryption", "ja_tech_advanced"),
    ("不正アクセス", "Fusei akusesu", "noun", "不正アクセスを防ぐ。", "Truy cập trái phép", "Ngăn truy cập trái phép.", "Unauthorized access", "ja_tech_advanced"),
    ("漏洩", "Rouei", "noun/verb", "情報が漏洩する。", "Rò rỉ", "Thông tin bị rò rỉ.", "Leak", "ja_tech_advanced"),
    ("互換性", "Gokansei", "noun", "互換性がある。", "Tính tương thích", "Có tính tương thích.", "Compatibility", "ja_tech_advanced"),
    ("仕様", "Shiyou", "noun", "システムの仕様。", "Thông số kỹ thuật", "Đặc điểm kỹ thuật hệ thống.", "Specification", "ja_tech_advanced"),
    ("効率", "Kouritsu", "noun", "作業の効率を上げる。", "Hiệu suất", "Tăng hiệu suất công việc.", "Efficiency", "ja_tech_advanced"),
    ("自動化", "Jidouka", "noun/verb", "作業を自動化する。", "Tự động hóa", "Tự động hóa quy trình.", "Automation", "ja_tech_advanced"),

    # Expert (3)
    ("量子コンピュータ", "Ryoushi konpyūta", "noun", "量子コンピュータの計算。", "Máy tính lượng tử", "Tính toán của máy tính lượng tử.", "Quantum computer", "ja_tech_expert"),
    ("深層学習", "Shinsou gakushuu", "noun", "深層学習のモデル。", "Học sâu", "Mô hình học sâu.", "Deep learning", "ja_tech_expert"),
    ("機械学習", "Kikai gakushuu", "noun", "機械学習を導入する。", "Học máy", "Đưa vào học máy.", "Machine learning", "ja_tech_expert"),
    ("ブロックチェーン", "Burokku chēn", "noun", "ブロックチェーン技術。", "Chuỗi khối", "Công nghệ chuỗi khối.", "Blockchain", "ja_tech_expert"),
    ("暗号資産", "Angou shisan", "noun", "暗号資産の取引。", "Tài sản mã hóa", "Giao dịch tiền ảo.", "Crypto", "ja_tech_expert"),
    ("モノのインターネット", "Mono no intānetto", "noun", "IoT（モノのインターネット）。", "Internet vạn vật", "Kết nối vạn vật qua mạng.", "IoT", "ja_tech_expert"),
    ("自動運転", "Jidou unten", "noun", "自動運転車。", "Lái xe tự động", "Xe ô tô tự lái.", "Autonomous driving", "ja_tech_expert"),
    ("ドローン", "Dorōn", "noun", "ドローンで配達する。", "Máy bay không người lái", "Giao hàng bằng drone.", "UAV", "ja_tech_expert"),
    ("生体認証", "Seitai ninshou", "noun", "生体認証システム。", "Xác thực sinh trắc học", "Hệ thống bảo mật sinh trắc học.", "Biometric authentication", "ja_tech_expert"),
    ("顔認証", "Kao ninshou", "noun", "顔認証でロックを解除。", "Nhận diện khuôn mặt", "Mở khóa bằng khuôn mặt.", "Facial recognition", "ja_tech_expert"),
    ("脆弱性", "Zeijakusei", "noun", "システムの脆弱性。", "Lỗ hổng bảo mật", "Điểm yếu của hệ thống.", "Vulnerability", "ja_tech_expert"),
    ("サイバー攻撃", "Saibā kougeki", "noun", "サイバー攻撃を受ける。", "Tấn công mạng", "Bị tấn công trên mạng.", "Cyber attack", "ja_tech_expert"),
    ("マルウェア", "Maruwea", "noun", "マルウェアに感染。", "Phần mềm độc hại", "Bị nhiễm mã độc.", "Malware", "ja_tech_expert"),
    ("フィッシング詐欺", "Fisshingu sagi", "noun", "フィッシング詐欺に注意。", "Lừa đảo qua mạng", "Cẩn thận lừa đảo Phishing.", "Phishing scam", "ja_tech_expert"),
    ("著作権", "Chosakuken", "noun", "デジタル著作権。", "Bản quyền", "Bản quyền kỹ thuật số.", "Copyright", "ja_tech_expert"),
    ("オープンソース", "Ōpun sōsu", "noun", "オープンソースのソフト。", "Mã nguồn mở", "Phần mềm nguồn mở.", "Open-source", "ja_tech_expert"),
    ("デジタルトランスフォーメーション", "Dejitaru toransufōmēshon", "noun", "DXを推進する。", "Chuyển đổi số", "Thúc đẩy chuyển đổi số.", "DX", "ja_tech_expert"),
    ("テレワーク", "Terewāku", "noun", "テレワークが普及する。", "Làm việc từ xa", "Làm việc từ xa trở nên phổ biến.", "Telework", "ja_tech_expert"),
    ("クラウドソーシング", "Kuraudosōshingu", "noun", "クラウドソーシングで発注。", "Nguồn cung cộng đồng", "Đặt hàng qua crowdsourcing.", "Crowdsourcing", "ja_tech_expert"),
    ("ビッグデータ", "Biggu dēta", "noun", "ビッグデータを解析する。", "Dữ liệu lớn", "Phân tích dữ liệu lớn.", "Big data", "ja_tech_expert"),
    ("ウェアラブル端末", "Wearaburu tanmatsu", "noun", "ウェアラブル端末をつける。", "Thiết bị đeo", "Sử dụng thiết bị đeo thông minh.", "Wearable device", "ja_tech_expert"),
    ("サブスクリプション", "Sabusukuripushon", "noun", "サブスクリプション契約。", "Đăng ký thuê bao", "Hợp đồng trả phí định kỳ.", "Subscription", "ja_tech_expert"),
    ("ユビキタス", "Yubikitasu", "noun", "ユビキタス社会。", "Mọi lúc mọi nơi", "Xã hội kết nối vạn vật.", "Ubiquitous", "ja_tech_expert"),
    ("メタバース", "Metabāsu", "noun", "メタバース空間で遊ぶ。", "Vũ trụ ảo", "Chơi trong không gian ảo.", "Metaverse", "ja_tech_expert"),
    ("拡張現実", "Kakuchou genjitsu", "noun", "AR（拡張現実）。", "Thực tế tăng cường", "Ứng dụng AR.", "AR", "ja_tech_expert"),
    ("第五世代移動通信システム", "Daigo sedai idou tsuushin shisutemu", "noun", "5G（第5世代移動通信）。", "Mạng 5G", "Công nghệ mạng 5G.", "5G", "ja_tech_expert"),
    ("ハプティクス", "Haputikusu", "noun", "ハプティクス技術。", "Phản hồi xúc giác", "Công nghệ xúc giác ảo.", "Haptics", "ja_tech_expert"),
    ("スーパーコンピュータ", "Sūpā konpyūta", "noun", "スーパーコンピュータ「富岳」。", "Siêu máy tính", "Siêu máy tính Fugaku.", "Supercomputer", "ja_tech_expert"),
    ("マイクロチップ", "Maikurochippu", "noun", "マイクロチップを埋め込む。", "Vi mạch", "Cấy ghép vi mạch.", "Microchip", "ja_tech_expert"),
    ("ナノテクノロジー", "Nanotekunorojī", "noun", "ナノテクノロジーの研究。", "Công nghệ Nano", "Nghiên cứu về Nano.", "Nanotech", "ja_tech_expert"),

    # ---- TRAVEL ----
    # Beginner (0)
    ("旅行", "Ryokou", "noun/verb", "旅行に行く。", "Du lịch", "Đi du lịch.", "Đi xa chơi", "ja_travel_beginner"),
    ("旅", "Tabi", "noun", "長い旅。", "Chuyến đi", "Một chuyến đi dài.", "Hành trình", "ja_travel_beginner"),
    ("海", "Umi", "noun", "海を泳ぐ。", "Biển", "Bơi ở biển.", "Đại dương", "ja_travel_beginner"),
    ("山", "Yama", "noun", "山に登る。", "Núi", "Leo núi.", "Vùng cao", "ja_travel_beginner"),
    ("川", "Kawa", "noun", "川で遊ぶ。", "Sông", "Chơi ở sông.", "Dòng nước", "ja_travel_beginner"),
    ("国", "Kuni", "noun", "外国の国。", "Quốc gia", "Nước ngoài.", "Đất nước", "ja_travel_beginner"),
    ("日本", "Nihon", "noun", "日本に行く。", "Nhật Bản", "Đi Nhật.", "Nước Nhật", "ja_travel_beginner"),
    ("外国", "Gaikoku", "noun", "外国の人。", "Nước ngoài", "Người ngoại quốc.", "Nước khác", "ja_travel_beginner"),
    ("飛行機", "Hikouki", "noun", "飛行機に乗る。", "Máy bay", "Đi máy bay.", "Tàu bay", "ja_travel_beginner"),
    ("電車", "Densha", "noun", "電車で来る。", "Tàu điện", "Đến bằng tàu điện.", "Tàu chạy điện", "ja_travel_beginner"),
    ("バス", "Basu", "noun", "バスを待つ。", "Xe buýt", "Đợi xe buýt.", "Xe ô tô lớn", "ja_travel_beginner"),
    ("駅", "Eki", "noun", "駅で会う。", "Nhà ga", "Gặp nhau ở ga.", "Nơi chờ tàu", "ja_travel_beginner"),
    ("切符", "Kippu", "noun", "切符を買う。", "Vé", "Mua vé.", "Giấy lên xe", "ja_travel_beginner"),
    ("ホテル", "Hoteru", "noun", "ホテルに泊まる。", "Khách sạn", "Nghỉ ở khách sạn.", "Nơi nghỉ ngơi", "ja_travel_beginner"),
    ("部屋", "Heya", "noun", "部屋に入る。", "Căn phòng", "Vào phòng.", "Phòng ở", "ja_travel_beginner"),
    ("お風呂", "Ofuro", "noun", "お風呂に入る。", "Bồn tắm", "Đi tắm.", "Tắm bồn", "ja_travel_beginner"),
    ("写真", "Shashin", "noun", "写真を撮る。", "Bức ảnh", "Chụp hình.", "Hình ảnh", "ja_travel_beginner"),
    ("お土産", "Omiyage", "noun", "お土産を買う。", "Quà lưu niệm", "Mua quà mang về.", "Quà mua khi đi chơi", "ja_travel_beginner"),
    ("荷物", "Nimotsu", "noun", "荷物を持つ。", "Hành lý", "Mang hành lý.", "Đồ đạc", "ja_travel_beginner"),
    ("カバン", "Kaban", "noun", "旅行のカバン。", "Túi xách", "Túi du lịch.", "Đồ đựng", "ja_travel_beginner"),
    ("泊まる", "Tomaru", "verb", "ホテルに泊まる。", "Trọ lại", "Ngủ lại khách sạn.", "Nghỉ qua đêm", "ja_travel_beginner"),
    ("乗る", "Noru", "verb", "電車に乗る。", "Lên xe", "Lên tàu.", "Đi xe", "ja_travel_beginner"),
    ("降りる", "Oriru", "verb", "バスを降りる。", "Xuống xe", "Xuống xe buýt.", "Rời khỏi xe", "ja_travel_beginner"),
    ("歩く", "Aruku", "verb", "たくさん歩く。", "Đi bộ", "Đi bộ rất nhiều.", "Đi bằng chân", "ja_travel_beginner"),
    ("行く", "Iku", "verb", "日本へ行く。", "Đi", "Đi đến Nhật Bản.", "Tiến tới", "ja_travel_beginner"),
    ("来る", "Kuru", "verb", "友達が来る。", "Đến", "Bạn bè tới.", "Lại gần", "ja_travel_beginner"),
    ("帰る", "Kaeru", "verb", "家に帰る。", "Trở về", "Đi về nhà.", "Về chỗ cũ", "ja_travel_beginner"),
    ("楽しい", "Tanoshii", "adjective", "楽しい旅行。", "Vui vẻ", "Chuyến đi thú vị.", "Cảm thấy vui", "ja_travel_beginner"),
    ("面白い", "Omoshiroi", "adjective", "面白い話。", "Thú vị", "Câu chuyện hay.", "Hay ho", "ja_travel_beginner"),
    ("遠い", "Tooi", "adjective", "遠い国。", "Xa", "Một đất nước xa xôi.", "Khoảng cách lớn", "ja_travel_beginner"),

    # Intermediate (1)
    ("観光", "Kankou", "noun/verb", "京都を観光する。", "Tham quan", "Đi tham quan Kyoto.", "Du lãm", "ja_travel_intermediate"),
    ("名所", "Meisho", "noun", "観光名所。", "Danh lam thắng cảnh", "Địa điểm du lịch nổi tiếng.", "Nơi nổi danh", "ja_travel_intermediate"),
    ("景色", "Keshiki", "noun", "景色が綺麗だ。", "Cảnh sắc", "Cảnh vật rất đẹp.", "Phong cảnh", "ja_travel_intermediate"),
    ("温泉", "Onsen", "noun", "温泉に入る。", "Suối nước nóng", "Tắm suối nước nóng.", "Nước nóng thiên nhiên", "ja_travel_intermediate"),
    ("旅館", "Ryokan", "noun", "日本の旅館。", "Lữ quán", "Nhà trọ kiểu Nhật.", "Khách sạn truyền thống", "ja_travel_intermediate"),
    ("予約", "Yoyaku", "noun/verb", "ホテルを予約する。", "Đặt trước", "Đặt phòng khách sạn.", "Book chỗ", "ja_travel_intermediate"),
    ("計画", "Keikaku", "noun/verb", "旅行を計画する。", "Kế hoạch", "Lên kế hoạch du lịch.", "Tính toán trước", "ja_travel_intermediate"),
    ("準備", "Junbi", "noun/verb", "旅行の準備をする。", "Chuẩn bị", "Soạn đồ đi du lịch.", "Sửa soạn", "ja_travel_intermediate"),
    ("空港", "Kuukou", "noun", "空港に着く。", "Sân bay", "Đến sân bay.", "Bến máy bay", "ja_travel_intermediate"),
    ("パスポート", "Pasupōto", "noun", "パスポートを見せる。", "Hộ chiếu", "Trình hộ chiếu.", "Giấy thông hành", "ja_travel_intermediate"),
    ("ビザ", "Biza", "noun", "ビザを取る。", "Visa", "Xin thị thực.", "Thị thực nhập cảnh", "ja_travel_intermediate"),
    ("案内", "Annai", "noun/verb", "道を案内する。", "Hướng dẫn", "Chỉ đường.", "Dẫn đường", "ja_travel_intermediate"),
    ("地図", "Chizu", "noun", "地図を見る。", "Bản đồ", "Xem bản đồ.", "Hình vẽ địa lý", "ja_travel_intermediate"),
    ("迷う", "Mayou", "verb", "道に迷う。", "Lạc đường", "Bị lạc đường.", "Mất phương hướng", "ja_travel_intermediate"),
    ("出発", "Shuppatsu", "noun/verb", "10時に出発する。", "Xuất phát", "Khởi hành lúc 10 giờ.", "Bắt đầu đi", "ja_travel_intermediate"),
    ("到着", "Touchaku", "noun/verb", "駅に到着する。", "Đến nơi", "Tới nhà ga.", "Tới đích", "ja_travel_intermediate"),
    ("日帰り", "Higaeri", "noun", "日帰り旅行。", "Đi về trong ngày", "Du lịch về trong ngày.", "Đi sáng về tối", "ja_travel_intermediate"),
    ("宿泊", "Shukuhaku", "noun/verb", "2泊宿泊する。", "Ngủ lại", "Ở lại 2 đêm.", "Trọ qua đêm", "ja_travel_intermediate"),
    ("時刻表", "Jikokuhyou", "noun", "時刻表を調べる。", "Thời gian biểu", "Tra lịch tàu chạy.", "Lịch xe cộ", "ja_travel_intermediate"),
    ("運賃", "Unchin", "noun", "バスの運賃。", "Giá vé", "Giá cước xe buýt.", "Tiền đi xe", "ja_travel_intermediate"),
    ("乗り換える", "Norikaeru", "verb", "電車を乗り換える。", "Đổi chuyến", "Đổi tàu điện.", "Đổi phương tiện", "ja_travel_intermediate"),
    ("交通", "Koutsuu", "noun", "交通が便利だ。", "Giao thông", "Giao thông tiện lợi.", "Việc đi lại", "ja_travel_intermediate"),
    ("案内所", "Annaijo", "noun", "観光案内所。", "Quầy thông tin", "Quầy thông tin du lịch.", "Trạm hỗ trợ", "ja_travel_intermediate"),
    ("ガイド", "Gaido", "noun", "ツアーガイド。", "Người hướng dẫn", "Hướng dẫn viên tour.", "Guide", "ja_travel_intermediate"),
    ("記念", "Kinen", "noun", "記念写真を撮る。", "Kỷ niệm", "Chụp ảnh lưu niệm.", "Ghi nhớ", "ja_travel_intermediate"),
    ("思い出", "Omoide", "noun", "旅行の思い出。", "Hồi ức", "Kỷ niệm về chuyến đi.", "Ký ức đẹp", "ja_travel_intermediate"),
    ("名物", "Meibutsu", "noun", "その土地の名物。", "Đặc sản", "Đặc sản của vùng đó.", "Sản vật địa phương", "ja_travel_intermediate"),
    ("体験", "Taiken", "noun/verb", "文化を体験する。", "Trải nghiệm", "Trải nghiệm văn hóa.", "Làm thử thực tế", "ja_travel_intermediate"),
    ("交流", "Kouryuu", "noun/verb", "現地の人と交流する。", "Giao lưu", "Tiếp xúc với người bản địa.", "Làm quen kết bạn", "ja_travel_intermediate"),
    ("言葉", "Kotoba", "noun", "外国の言葉。", "Ngôn ngữ", "Ngôn ngữ nước ngoài.", "Tiếng nói", "ja_travel_intermediate"),

    # Advanced (2)
    ("滞在", "Taizai", "noun/verb", "3日間滞在する。", "Lưu trú", "Ở lại trong 3 ngày.", "Ở một nơi tạm", "ja_travel_advanced"),
    ("渡航", "Tokou", "noun/verb", "海外へ渡航する。", "Xuất ngoại", "Đi nước ngoài.", "Vượt biên giới", "ja_travel_advanced"),
    ("入国", "Nyuukoku", "noun/verb", "入国審査を受ける。", "Nhập cảnh", "Làm thủ tục nhập cảnh.", "Vào nước khác", "ja_travel_advanced"),
    ("出国", "Shukkoku", "noun/verb", "出国手続き。", "Xuất cảnh", "Làm thủ tục xuất cảnh.", "Rời khỏi nước", "ja_travel_advanced"),
    ("税関", "Zeikan", "noun", "税関を通る。", "Hải quan", "Đi qua trạm hải quan.", "Kiểm tra đồ", "ja_travel_advanced"),
    ("免税", "Menzei", "noun", "免税店で買う。", "Miễn thuế", "Mua sắm ở cửa hàng miễn thuế.", "Duty-free", "ja_travel_advanced"),
    ("為替", "Kawase", "noun", "外国為替相場。", "Tỷ giá hối đoái", "Tỉ giá đổi tiền nước ngoài.", "Đổi tiền", "ja_travel_advanced"),
    ("時差", "Jisa", "noun", "時差ボケになる。", "Chênh lệch múi giờ", "Bị mệt do lệch múi giờ.", "Lệch giờ", "ja_travel_advanced"),
    ("添乗員", "Tenjouin", "noun", "ツアーの添乗員。", "Hướng dẫn viên", "Người dẫn đoàn du lịch.", "Trưởng đoàn", "ja_travel_advanced"),
    ("日程", "Nittei", "noun", "厳しい日程。", "Lịch trình", "Lịch trình dày đặc.", "Kế hoạch ngày giờ", "ja_travel_advanced"),
    ("行程", "Koutei", "noun", "旅行の行程表。", "Hành trình", "Bản lịch trình chuyến đi.", "Đường đi nước bước", "ja_travel_advanced"),
    ("航空券", "Koukuuken", "noun", "航空券を予約する。", "Vé máy bay", "Đặt mua vé máy bay.", "Vé bay", "ja_travel_advanced"),
    ("搭乗", "Toujou", "noun/verb", "飛行機に搭乗する。", "Lên máy bay", "Làm thủ tục lên máy bay.", "Lên khoang", "ja_travel_advanced"),
    ("満室", "Manshitsu", "noun", "ホテルが満室だ。", "Hết phòng", "Khách sạn đã kín phòng.", "Kín chỗ", "ja_travel_advanced"),
    ("避暑地", "Hishochi", "noun", "避暑地で過ごす。", "Nơi nghỉ mát", "Qua mùa hè ở nơi mát mẻ.", "Nơi tránh nóng", "ja_travel_advanced"),
    ("秘境", "Hikyou", "noun", "秘境を訪れる。", "Vùng bí ẩn", "Đến vùng đất hoang sơ.", "Nơi vắng dấu chân", "ja_travel_advanced"),
    ("絶景", "Zekkei", "noun", "絶景を眺める。", "Cảnh tuyệt đẹp", "Ngắm phong cảnh tuyệt đẹp.", "View đẹp", "ja_travel_advanced"),
    ("世界遺産", "Sekai isan", "noun", "世界遺産を巡る。", "Di sản thế giới", "Thăm thú các di sản thế giới.", "UNESCO", "ja_travel_advanced"),
    ("遺跡", "Iseki", "noun", "古代の遺跡。", "Di tích", "Di tích thời cổ đại.", "Dấu vết xưa", "ja_travel_advanced"),
    ("史跡", "Shiseki", "noun", "史跡を訪ねる。", "Di tích lịch sử", "Thăm di tích lịch sử.", "Nơi ghi dấu sử", "ja_travel_advanced"),
    ("異文化", "Ibunka", "noun", "異文化に触れる。", "Văn hóa khác", "Tiếp xúc nền văn hóa mới.", "Văn hóa ngoại", "ja_travel_advanced"),
    ("民泊", "Minpaku", "noun", "民泊を利用する。", "Homestay", "Dịch vụ ở nhờ nhà dân.", "Airbnb", "ja_travel_advanced"),
    ("旅券", "Ryoken", "noun", "旅券の発行。", "Hộ chiếu", "Việc cấp phát hộ chiếu.", "Passport", "ja_travel_advanced"),
    ("査証", "Sashou", "noun", "査証を申請する。", "Visa", "Xin cấp visa.", "Thị thực", "ja_travel_advanced"),
    ("密航", "Mikkou", "noun/verb", "船で密航する。", "Vượt biên trái phép", "Trốn theo tàu biển.", "Đi chui", "ja_travel_advanced"),
    ("帰省", "Kisei", "noun/verb", "実家に帰省する。", "Về thăm quê", "Về thăm nhà bố mẹ đẻ.", "Về nhà cũ", "ja_travel_advanced"),
    ("慰安旅行", "Ian ryokou", "noun", "会社の慰安旅行。", "Du lịch nghỉ dưỡng", "Chuyến đi thư giãn của công ty.", "Company trip", "ja_travel_advanced"),
    ("視察", "Shisatsu", "noun/verb", "海外視察に行く。", "Thị sát", "Đi công tác khảo sát nước ngoài.", "Xem xét thực tế", "ja_travel_advanced"),
    ("周遊", "Shuuyuu", "noun/verb", "ヨーロッパを周遊する。", "Đi vòng quanh", "Du ngoạn khắp châu Âu.", "Du lịch quanh", "ja_travel_advanced"),
    ("縦断", "Juudan", "noun/verb", "アメリカ大陸を縦断する。", "Xuyên suốt (Bắc-Nam)", "Đi dọc châu Mỹ.", "Đi xuyên quốc gia", "ja_travel_advanced"),

    # Expert (3)
    ("インバウンド", "Inbaundo", "noun", "インバウンド需要。", "Khách quốc tế", "Du khách nước ngoài đến.", "Inbound", "ja_travel_expert"),
    ("アウトバウンド", "Autobaundo", "noun", "アウトバウンド市場。", "Du lịch ra nước ngoài", "Thị trường du lịch ra nước ngoài.", "Outbound", "ja_travel_expert"),
    ("マイクロツーリズム", "Maikuro tsūrizumu", "noun", "マイクロツーリズムが流行る。", "Du lịch gần nhà", "Xu hướng du lịch địa phương.", "Du lịch tại chỗ", "ja_travel_expert"),
    ("エコツーリズム", "Ekotsūrizumu", "noun", "エコツーリズムに参加する。", "Du lịch sinh thái", "Tham gia du lịch xanh.", "Eco-tourism", "ja_travel_expert"),
    ("ワーケーション", "Wākēshon", "noun", "リゾートでワーケーション。", "Du lịch làm việc", "Vừa làm việc vừa nghỉ dưỡng.", "Workation", "ja_travel_expert"),
    ("オーバーツーリズム", "Ōbātsūrizumu", "noun", "オーバーツーリズムの弊害。", "Quá tải du lịch", "Vấn đề của việc du lịch quá tải.", "Overtourism", "ja_travel_expert"),
    ("ツーリズム", "Tsūrizumu", "noun", "ダークツーリズム。", "Ngành du lịch", "Du lịch đen (thăm thảm họa).", "Tourism", "ja_travel_expert"),
    ("パスポートコントロール", "Pasupōtokontorōru", "noun", "パスポートコントロールを通過。", "Trạm kiểm tra hộ chiếu", "Qua trạm kiểm tra hộ chiếu.", "Passport control", "ja_travel_expert"),
    ("トランジット", "Toranjitto", "noun", "トランジットで待つ。", "Quá cảnh", "Đợi chuyến bay quá cảnh.", "Transit", "ja_travel_expert"),
    ("チェックイン", "Chekkuin", "noun/verb", "ホテルでチェックインする。", "Nhận phòng", "Làm thủ tục nhận phòng.", "Check-in", "ja_travel_expert"),
    ("チェックアウト", "Chekkuauto", "noun/verb", "朝早くチェックアウトする。", "Trả phòng", "Trả phòng khách sạn sớm.", "Check-out", "ja_travel_expert"),
    ("コンシェルジュ", "Konshieruju", "noun", "コンシェルジュに頼む。", "Nhân viên hỗ trợ", "Nhờ nhân viên sảnh hỗ trợ.", "Concierge", "ja_travel_expert"),
    ("クーリングオフ", "Kūringu ofu", "noun", "旅行契約のクーリングオフ。", "Quyền hủy hợp đồng", "Hủy hợp đồng du lịch miễn phí.", "Cooling-off", "ja_travel_expert"),
    ("コードシェア便", "Kōdosheabin", "noun", "コードシェア便を利用。", "Chuyến bay liên danh", "Dùng chuyến bay hợp tác hãng.", "Codeshare flight", "ja_travel_expert"),
    ("オープンチケット", "Ōpunchiketto", "noun", "オープンチケットで帰る。", "Vé mở", "Dùng vé ngày về tự do.", "Open ticket", "ja_travel_expert"),
    ("ノーショー", "Nōshō", "noun", "予約客のノーショー。", "Vắng mặt không báo", "Khách đã đặt phòng nhưng không đến.", "No-show", "ja_travel_expert"),
    ("マイレージ", "Mairēji", "noun", "マイレージを貯める。", "Điểm thưởng dặm bay", "Tích lũy dặm bay.", "Mileage", "ja_travel_expert"),
    ("LCC", "Eru-shī-shī", "noun", "LCCで安く行く。", "Hàng không giá rẻ", "Đi vé máy bay giá rẻ.", "Low-Cost Carrier", "ja_travel_expert"),
    ("ゲストハウス", "Gesutohausu", "noun", "安いゲストハウス。", "Nhà khách", "Nhà khách giá bình dân.", "Guesthouse", "ja_travel_expert"),
    ("ホステル", "Hosteru", "noun", "ホステルで相部屋。", "Ký túc xá du lịch", "Ở chung phòng trong hostel.", "Hostel", "ja_travel_expert"),
    ("ドミトリー", "Domitorī", "noun", "ドミトリーに泊まる。", "Phòng tập thể", "Ngủ trong phòng giường tầng.", "Dormitory", "ja_travel_expert"),
    ("パッケージツアー", "Pakkēji tsuā", "noun", "パッケージツアーに申し込む。", "Tour trọn gói", "Đăng ký đi tour trọn gói.", "Package tour", "ja_travel_expert"),
    ("スケルトンツアー", "Sukeruton tsuā", "noun", "スケルトンツアーを選ぶ。", "Tour tự do", "Chỉ mua vé máy bay và phòng.", "Skeleton tour", "ja_travel_expert"),
    ("オプショナルツアー", "Opushonaru tsuā", "noun", "オプショナルツアーを追加。", "Tour tùy chọn thêm", "Tham gia thêm tour ngắn ngoài.", "Optional tour", "ja_travel_expert"),
    ("ランドオペレーター", "Rando operētā", "noun", "現地のランドオペレーター。", "Nhà điều hành tour", "Đối tác tour ở nước sở tại.", "Land operator", "ja_travel_expert"),
    ("モビリティ", "Mobiriti", "noun", "モビリティの進化。", "Phương tiện di chuyển", "Sự tiến hóa của giao thông.", "Mobility", "ja_travel_expert"),
    ("MaaS", "Māsu", "noun", "MaaSの導入。", "Dịch vụ di chuyển", "Mobility as a Service.", "MaaS", "ja_travel_expert"),
    ("パンデミック", "Pandemikku", "noun", "パンデミックで旅行中止。", "Đại dịch toàn cầu", "Hủy chuyến do đại dịch.", "Pandemic", "ja_travel_expert"),
    ("リトリート", "Ritorīto", "noun", "週末はリトリートへ。", "Du lịch phục hồi", "Du lịch cân bằng lại bản thân.", "Retreat", "ja_travel_expert"),
    ("サステナブルツーリズム", "Sasutenaburu tsūrizumu", "noun", "サステナブルツーリズムの推進。", "Du lịch bền vững", "Du lịch bảo vệ môi trường.", "Sustainable tourism", "ja_travel_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_ja, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "ja",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_ja,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Technology & Travel - Japanese) to DB!")
