import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Education
    {"id": "ko_edu_beginner", "languageCode": "ko", "title": "교육", "subtitle": "Giáo dục - Beginner", "iconEmoji": "📚", "level": "Beginner", "colorHex": "#3B82F6", "cardCount": 30},
    {"id": "ko_edu_intermediate", "languageCode": "ko", "title": "교육", "subtitle": "Giáo dục - Intermediate", "iconEmoji": "📚", "level": "Intermediate", "colorHex": "#2563EB", "cardCount": 30},
    {"id": "ko_edu_advanced", "languageCode": "ko", "title": "교육", "subtitle": "Giáo dục - Advanced", "iconEmoji": "📚", "level": "Advanced", "colorHex": "#1D4ED8", "cardCount": 30},
    {"id": "ko_edu_expert", "languageCode": "ko", "title": "교육", "subtitle": "Giáo dục - Expert", "iconEmoji": "📚", "level": "Expert", "colorHex": "#1E40AF", "cardCount": 30},
    
    # Fashion
    {"id": "ko_fashion_beginner", "languageCode": "ko", "title": "패션", "subtitle": "Thời trang - Beginner", "iconEmoji": "👗", "level": "Beginner", "colorHex": "#EC4899", "cardCount": 30},
    {"id": "ko_fashion_intermediate", "languageCode": "ko", "title": "패션", "subtitle": "Thời trang - Intermediate", "iconEmoji": "👗", "level": "Intermediate", "colorHex": "#DB2777", "cardCount": 30},
    {"id": "ko_fashion_advanced", "languageCode": "ko", "title": "패션", "subtitle": "Thời trang - Advanced", "iconEmoji": "👗", "level": "Advanced", "colorHex": "#BE185D", "cardCount": 30},
    {"id": "ko_fashion_expert", "languageCode": "ko", "title": "패션", "subtitle": "Thời trang - Expert", "iconEmoji": "👗", "level": "Expert", "colorHex": "#9D174D", "cardCount": 30}
]

vocab_data = [
    # ---- EDUCATION ----
    # Beginner (0)
    ("학교", "Hakgyo", "noun", "학교에 가다.", "Trường học", "Đi đến trường.", "School", "ko_edu_beginner"),
    ("학생", "Haksaeng", "noun", "저는 학생입니다.", "Học sinh, sinh viên", "Tôi là học sinh.", "Student", "ko_edu_beginner"),
    ("선생님", "Seonsaengnim", "noun", "선생님 안녕하세요.", "Giáo viên", "Chào thầy/cô ạ.", "Teacher", "ko_edu_beginner"),
    ("교실", "Gyosil", "noun", "교실에 있다.", "Phòng học", "Ở trong phòng học.", "Classroom", "ko_edu_beginner"),
    ("책", "Chaek", "noun", "책을 읽다.", "Sách", "Đọc sách.", "Book", "ko_edu_beginner"),
    ("공책", "Gongchaek", "noun", "공책에 쓰다.", "Vở", "Viết vào vở.", "Notebook", "ko_edu_beginner"),
    ("연필", "Yeonpil", "noun", "연필로 쓰다.", "Bút chì", "Viết bằng bút chì.", "Pencil", "ko_edu_beginner"),
    ("볼펜", "Bolpen", "noun", "볼펜을 사다.", "Bút bi", "Mua bút bi.", "Ballpoint pen", "ko_edu_beginner"),
    ("지우개", "Jiugae", "noun", "지우개로 지우다.", "Cục tẩy", "Tẩy bằng cục tẩy.", "Eraser", "ko_edu_beginner"),
    ("칠판", "Chilpan", "noun", "칠판을 보다.", "Bảng đen", "Nhìn lên bảng.", "Blackboard", "ko_edu_beginner"),
    ("책상", "Chaeksang", "noun", "책상에 앉다.", "Bàn học", "Ngồi vào bàn học.", "Desk", "ko_edu_beginner"),
    ("의자", "Uija", "noun", "의자가 편하다.", "Cái ghế", "Cái ghế rất thoải mái.", "Chair", "ko_edu_beginner"),
    ("수업", "Sueop", "noun", "수업이 끝났다.", "Tiết học, buổi học", "Buổi học kết thúc rồi.", "Class/Lesson", "ko_edu_beginner"),
    ("공부", "Gongbu", "noun/verb", "한국어를 공부하다.", "Học tập", "Học tiếng Hàn.", "Study", "ko_edu_beginner"),
    ("숙제", "Sukje", "noun", "숙제를 하다.", "Bài tập về nhà", "Làm bài tập về nhà.", "Homework", "ko_edu_beginner"),
    ("시험", "Siheom", "noun", "시험을 보다.", "Kì thi, bài kiểm tra", "Làm bài kiểm tra.", "Exam/Test", "ko_edu_beginner"),
    ("질문", "Jilmun", "noun", "질문이 있어요.", "Câu hỏi", "Em có câu hỏi ạ.", "Question", "ko_edu_beginner"),
    ("대답", "Daedap", "noun/verb", "질문에 대답하다.", "Câu trả lời", "Trả lời câu hỏi.", "Answer", "ko_edu_beginner"),
    ("사전", "Sajeon", "noun", "사전을 찾다.", "Từ điển", "Tra từ điển.", "Dictionary", "ko_edu_beginner"),
    ("글자", "Geulja", "noun", "글자를 쓰다.", "Chữ cái", "Viết chữ.", "Letter/Character", "ko_edu_beginner"),
    ("쉬다", "Swida", "verb", "10분 쉬다.", "Nghỉ ngơi", "Nghỉ giải lao 10 phút.", "Rest", "ko_edu_beginner"),
    ("배우다", "Baeuda", "verb", "피아노를 배우다.", "Học", "Học đàn piano.", "Learn", "ko_edu_beginner"),
    ("가르치다", "Gareuchida", "verb", "영어를 가르치다.", "Dạy", "Dạy tiếng Anh.", "Teach", "ko_edu_beginner"),
    ("알다", "Alda", "verb", "정답을 알다.", "Biết", "Biết câu trả lời đúng.", "Know", "ko_edu_beginner"),
    ("모르다", "Moreuda", "verb", "저는 모릅니다.", "Không biết", "Tôi không biết.", "Not know", "ko_edu_beginner"),
    ("맞다", "Matda", "verb", "정답이 맞다.", "Đúng", "Đáp án đúng rồi.", "Correct", "ko_edu_beginner"),
    ("틀리다", "Teullida", "verb", "계산이 틀리다.", "Sai", "Tính toán sai rồi.", "Wrong/Incorrect", "ko_edu_beginner"),
    ("어렵다", "Eoryeopda", "adjective", "수학이 어렵다.", "Khó", "Môn toán rất khó.", "Difficult", "ko_edu_beginner"),
    ("쉽다", "Swipda", "adjective", "이 문제는 쉽다.", "Dễ", "Bài toán này dễ.", "Easy", "ko_edu_beginner"),
    ("재미있다", "Jaemiitda", "adjective", "수업이 재미있다.", "Thú vị", "Buổi học rất thú vị.", "Interesting", "ko_edu_beginner"),

    # Intermediate (1)
    ("대학교", "Daehakgyo", "noun", "대학교에 입학하다.", "Trường đại học", "Nhập học đại học.", "University", "ko_edu_intermediate"),
    ("전공", "Jeongong", "noun", "전공이 무엇입니까?", "Chuyên ngành", "Chuyên ngành của bạn là gì?", "Major", "ko_edu_intermediate"),
    ("학기", "Hakgi", "noun", "새 학기가 시작되다.", "Học kỳ", "Học kỳ mới bắt đầu.", "Semester", "ko_edu_intermediate"),
    ("방학", "Banghak", "noun", "여름방학.", "Kỳ nghỉ (hè, đông)", "Kỳ nghỉ hè.", "Vacation", "ko_edu_intermediate"),
    ("졸업", "Joreop", "noun/verb", "대학을 졸업하다.", "Tốt nghiệp", "Tốt nghiệp đại học.", "Graduation", "ko_edu_intermediate"),
    ("유학", "Yuhak", "noun/verb", "미국으로 유학 가다.", "Du học", "Đi du học Mỹ.", "Study abroad", "ko_edu_intermediate"),
    ("동아리", "Dongari", "noun", "댄스 동아리.", "Câu lạc bộ (trường học)", "Câu lạc bộ nhảy.", "Club", "ko_edu_intermediate"),
    ("선배", "Seonbae", "noun", "학교 선배.", "Tiền bối, đàn anh/chị", "Tiền bối cùng trường.", "Senior", "ko_edu_intermediate"),
    ("후배", "Hubae", "noun", "학교 후배.", "Hậu bối, đàn em", "Hậu bối cùng trường.", "Junior", "ko_edu_intermediate"),
    ("동급생", "Donggeupsaeng", "noun", "우리는 동급생이다.", "Bạn cùng lớp", "Chúng tôi là bạn cùng lớp.", "Classmate", "ko_edu_intermediate"),
    ("성적", "Seongjeok", "noun", "성적이 오르다.", "Thành tích, điểm số", "Thành tích học tập tăng lên.", "Grades", "ko_edu_intermediate"),
    ("점수", "Jeomsu", "noun", "백 점을 받다.", "Điểm số", "Nhận được điểm 100.", "Score/Points", "ko_edu_intermediate"),
    ("장학금", "Janghakgeum", "noun", "장학금을 받다.", "Học bổng", "Nhận học bổng.", "Scholarship", "ko_edu_intermediate"),
    ("기숙사", "Gisuksa", "noun", "기숙사에 살다.", "Ký túc xá", "Sống ở ký túc xá.", "Dormitory", "ko_edu_intermediate"),
    ("도서관", "Doseogwan", "noun", "도서관에서 책을 빌리다.", "Thư viện", "Mượn sách ở thư viện.", "Library", "ko_edu_intermediate"),
    ("교과서", "Gyogwaseo", "noun", "교과서를 읽다.", "Sách giáo khoa", "Đọc sách giáo khoa.", "Textbook", "ko_edu_intermediate"),
    ("예습", "Yeseup", "noun/verb", "내일 배울 내용을 예습하다.", "Chuẩn bị bài", "Xem trước nội dung ngày mai học.", "Preparation", "ko_edu_intermediate"),
    ("복습", "Bokseup", "noun/verb", "수업 후에 복습하다.", "Ôn tập", "Ôn tập lại sau buổi học.", "Review", "ko_edu_intermediate"),
    ("강의", "Ganuui", "noun", "교수의 강의를 듣다.", "Bài giảng", "Nghe bài giảng của giáo sư.", "Lecture", "ko_edu_intermediate"),
    ("설명", "Seolmyeong", "noun/verb", "자세히 설명하다.", "Giải thích", "Giải thích một cách chi tiết.", "Explanation", "ko_edu_intermediate"),
    ("발표", "Balpyo", "noun/verb", "수업에서 발표하다.", "Phát biểu, thuyết trình", "Thuyết trình trong giờ học.", "Presentation", "ko_edu_intermediate"),
    ("토론", "Toron", "noun/verb", "주제에 대해 토론하다.", "Thảo luận", "Thảo luận về chủ đề.", "Discussion", "ko_edu_intermediate"),
    ("이해하다", "Ihaehada", "verb", "내용을 이해하다.", "Hiểu", "Hiểu nội dung.", "Understand", "ko_edu_intermediate"),
    ("암기하다", "Amgihada", "verb", "단어를 암기하다.", "Ghi nhớ, học thuộc lòng", "Học thuộc từ vựng.", "Memorize", "ko_edu_intermediate"),
    ("집중하다", "Jipjunghada", "verb", "공부에 집중하다.", "Tập trung", "Tập trung vào việc học.", "Concentrate", "ko_edu_intermediate"),
    ("지각하다", "Jigakhada", "verb", "학교에 지각하다.", "Đi học muộn", "Đến trường muộn.", "Be late", "ko_edu_intermediate"),
    ("결석하다", "Gyeolseokhada", "verb", "병으로 결석하다.", "Nghỉ học", "Nghỉ học vì bị ốm.", "Be absent", "ko_edu_intermediate"),
    ("합격하다", "Hapgyeokhada", "verb", "시험에 합격하다.", "Thi đỗ", "Thi đỗ kỳ thi.", "Pass", "ko_edu_intermediate"),
    ("불합격하다", "Bulhapgyeokhada", "verb", "면접에서 불합격하다.", "Thi trượt", "Trượt vòng phỏng vấn.", "Fail", "ko_edu_intermediate"),
    ("등록금", "Deungnokgeum", "noun", "등록금을 내다.", "Học phí", "Đóng tiền học phí.", "Tuition fee", "ko_edu_intermediate"),

    # Advanced (2)
    ("교육", "Gyoyuk", "noun", "공교육.", "Giáo dục", "Giáo dục công lập.", "Education", "ko_edu_advanced"),
    ("학력", "Hangnyeok", "noun", "학력 위조.", "Học vấn", "Làm giả bằng cấp học vấn.", "Educational background", "ko_edu_advanced"),
    ("수능", "Suneung", "noun", "수능 시험을 보다.", "Kỳ thi đại học (CSAT)", "Tham gia kỳ thi đại học Suneung.", "CSAT", "ko_edu_advanced"),
    ("내신", "Naesin", "noun", "내신 성적.", "Điểm trung bình môn (học bạ)", "Điểm tổng kết trên học bạ.", "School grades", "ko_edu_advanced"),
    ("경쟁력", "Gyeongjaengnyeok", "noun", "경쟁력을 키우다.", "Năng lực cạnh tranh", "Nuôi dưỡng năng lực cạnh tranh.", "Competitiveness", "ko_edu_advanced"),
    ("사교육", "Sagyoyuk", "noun", "사교육비가 비싸다.", "Giáo dục tư nhân (học thêm)", "Chi phí học thêm rất đắt đỏ.", "Private education", "ko_edu_advanced"),
    ("학원", "Hagwon", "noun", "영어 학원에 다니다.", "Trung tâm dạy thêm", "Đi học ở trung tâm tiếng Anh.", "Cram school/Academy", "ko_edu_advanced"),
    ("논술", "Nonsul", "noun", "논술 시험.", "Tự luận, bài luận", "Bài thi tự luận.", "Essay test", "ko_edu_advanced"),
    ("객관식", "Gaekgwansik", "noun", "객관식 문제.", "Trắc nghiệm khách quan", "Câu hỏi trắc nghiệm (chọn đáp án).", "Multiple-choice", "ko_edu_advanced"),
    ("주관식", "Jugwansik", "noun", "주관식 문제.", "Trắc nghiệm tự luận", "Câu hỏi tự luận.", "Subjective question", "ko_edu_advanced"),
    ("수료", "Suryo", "noun/verb", "과정을 수료하다.", "Hoàn thành khóa học", "Hoàn thành chương trình học.", "Completion", "ko_edu_advanced"),
    ("논문", "Nonmun", "noun", "졸업 논문을 쓰다.", "Luận văn", "Viết luận văn tốt nghiệp.", "Thesis/Paper", "ko_edu_advanced"),
    ("학위", "Hagwi", "noun", "석사 학위를 받다.", "Học vị, bằng cấp", "Nhận bằng Thạc sĩ.", "Degree", "ko_edu_advanced"),
    ("지도교수", "Jidogyosu", "noun", "나의 지도교수님.", "Giáo sư hướng dẫn", "Giáo sư hướng dẫn của tôi.", "Academic advisor", "ko_edu_advanced"),
    ("연구", "Yeongu", "noun/verb", "과학 연구.", "Nghiên cứu", "Nghiên cứu khoa học.", "Research", "ko_edu_advanced"),
    ("실습", "Silseup", "noun/verb", "현장 실습.", "Thực hành", "Thực tập tại hiện trường.", "Practice/Training", "ko_edu_advanced"),
    ("교양", "Gyoyang", "noun", "교양 과목.", "Kiến thức đại cương", "Môn học đại cương.", "General education", "ko_edu_advanced"),
    ("필수", "Pilsu", "noun", "필수 과목.", "Bắt buộc", "Môn học bắt buộc.", "Required", "ko_edu_advanced"),
    ("선택", "Seontaek", "noun", "선택 과목.", "Tự chọn", "Môn học tự chọn.", "Elective", "ko_edu_advanced"),
    ("수강신청", "Sugang sincheong", "phrase", "수강신청을 하다.", "Đăng ký tín chỉ", "Đăng ký môn học.", "Course registration", "ko_edu_advanced"),
    ("학점", "Hakjeom", "noun", "학점이 높다.", "Tín chỉ", "Điểm tín chỉ cao.", "Credit/Grade", "ko_edu_advanced"),
    ("재수", "Jaesu", "noun/verb", "재수생.", "Thi lại đại học", "Học sinh ôn thi lại đại học.", "Study for second attempt", "ko_edu_advanced"),
    ("자격증", "Jagyeokjeung", "noun", "자격증을 따다.", "Bằng cấp, chứng chỉ", "Thi lấy chứng chỉ nghề.", "Certificate", "ko_edu_advanced"),
    ("어학연수", "Eohagyeonsu", "noun", "어학연수를 가다.", "Đi học tiếng ở nước ngoài", "Ra nước ngoài học ngoại ngữ.", "Language study abroad", "ko_edu_advanced"),
    ("편입", "Pyeonip", "noun/verb", "다른 대학으로 편입하다.", "Chuyển trường, học liên thông", "Chuyển ngang sang trường đại học khác.", "Transfer", "ko_edu_advanced"),
    ("적성", "Jeokseong", "noun", "적성에 맞다.", "Năng khiếu, sở trường", "Phù hợp với năng khiếu sở trường.", "Aptitude", "ko_edu_advanced"),
    ("진로", "Jillo", "noun", "진로를 결정하다.", "Con đường tương lai", "Quyết định hướng đi tương lai.", "Career path", "ko_edu_advanced"),
    ("취업", "Chwieop", "noun/verb", "취업을 준비하다.", "Xin việc, tìm việc", "Chuẩn bị tìm việc làm.", "Employment", "ko_edu_advanced"),
    ("면접", "Myeonjeop", "noun", "면접을 보다.", "Phỏng vấn", "Đi phỏng vấn.", "Interview", "ko_edu_advanced"),
    ("이력서", "Iryeokseo", "noun", "이력서를 쓰다.", "Sơ yếu lý lịch", "Viết CV sơ yếu lý lịch.", "Resume/CV", "ko_edu_advanced"),

    # Expert (3)
    ("교육부", "Gyoyukbu", "noun", "교육부 장관.", "Bộ Giáo dục", "Bộ trưởng Bộ Giáo dục.", "Ministry of Education", "ko_edu_expert"),
    ("입시", "Ipsi", "noun", "입시 지옥.", "Thi tuyển sinh", "Địa ngục thi cử (áp lực thi vào đại học).", "Entrance exam", "ko_edu_expert"),
    ("주입식", "Juipsik", "noun/adjective", "주입식 교육.", "Phương pháp học nhồi nhét", "Giáo dục theo kiểu nhồi nhét.", "Cramming method", "ko_edu_expert"),
    ("창의력", "Chang-uiryeok", "noun", "창의력을 기르다.", "Sức sáng tạo", "Bồi dưỡng khả năng sáng tạo.", "Creativity", "ko_edu_expert"),
    ("문해력", "Munhaeryeok", "noun", "요즘 아이들의 문해력 저하.", "Khả năng đọc hiểu", "Sự suy giảm khả năng đọc hiểu của trẻ em hiện nay.", "Literacy", "ko_edu_expert"),
    ("평생교육", "Pyeongsaeng gyoyuk", "noun", "평생교육 프로그램.", "Giáo dục suốt đời", "Chương trình giáo dục thường xuyên.", "Lifelong education", "ko_edu_expert"),
    ("의무교육", "Uimu gyoyuk", "noun", "중학교까지 의무교육.", "Giáo dục bắt buộc", "Giáo dục bắt buộc đến cấp THCS.", "Compulsory education", "ko_edu_expert"),
    ("대안학교", "Daeanhakgyo", "noun", "대안학교에 다니다.", "Trường học thay thế", "Theo học tại một trường học thay thế (ngoài hệ thống công).", "Alternative school", "ko_edu_expert"),
    ("학벌주의", "Hakbeoljuui", "noun", "학벌주의 사회.", "Chủ nghĩa trọng bằng cấp", "Xã hội quá coi trọng xuất thân trường lớp.", "Academic cliqueism", "ko_edu_expert"),
    ("일타강사", "Iltagangsa", "noun", "유명한 일타강사.", "Giáo viên ngôi sao", "Giảng viên luyện thi top 1 nổi tiếng.", "Top instructor", "ko_edu_expert"),
    ("선행학습", "Seonhaenghakseup", "noun", "선행학습 금지.", "Học trước chương trình", "Cấm việc dạy và học trước chương trình.", "Prior learning", "ko_edu_expert"),
    ("스펙", "Seupek", "noun", "스펙을 쌓다.", "Spec (chứng chỉ, kinh nghiệm)", "Tích lũy bằng cấp, kinh nghiệm để làm đẹp hồ sơ.", "Qualifications/Specs", "ko_edu_expert"),
    ("표절", "Pyojeol", "noun/verb", "논문 표절 논란.", "Đạo văn", "Tranh cãi xoay quanh việc đạo văn luận án.", "Plagiarism", "ko_edu_expert"),
    ("문과", "Mungwa", "noun", "문과 학생.", "Khối khoa học xã hội", "Học sinh khối Xã hội (Văn khoa).", "Liberal arts", "ko_edu_expert"),
    ("이과", "Igwa", "noun", "이과를 선택하다.", "Khối khoa học tự nhiên", "Chọn theo khối Tự nhiên (Lý khoa).", "Sciences", "ko_edu_expert"),
    ("절대평가", "Jeoldae pyeongga", "noun", "절대평가 방식.", "Đánh giá tuyệt đối", "Phương thức đánh giá điểm tuyệt đối.", "Absolute evaluation", "ko_edu_expert"),
    ("상대평가", "Sangdae pyeongga", "noun", "상대평가로 성적을 주다.", "Đánh giá tương đối", "Cho điểm theo phương pháp xếp hạng tương đối.", "Relative evaluation", "ko_edu_expert"),
    ("장수생", "Jangsusaeng", "noun", "공무원 시험 장수생.", "Người thi trượt nhiều năm", "Người lận đận thi công chức nhiều năm liền.", "Long-time test taker", "ko_edu_expert"),
    ("고시", "Gosi", "noun", "사법 고시.", "Kỳ thi cấp quốc gia", "Kỳ thi tư pháp cấp quốc gia.", "National exam", "ko_edu_expert"),
    ("반수", "Bansu", "noun/verb", "대학에 다니며 반수하다.", "Vừa học đại học vừa ôn thi lại", "Vừa đi học đại học vừa âm thầm ôn thi lại trường khác.", "Study for exam while in college", "ko_edu_expert"),
    ("학자금 대출", "Hakjageum daechul", "phrase", "학자금 대출을 받다.", "Vay vốn sinh viên", "Đăng ký khoản vay học phí cho sinh viên.", "Student loan", "ko_edu_expert"),
    ("교권", "Gyogwon", "noun", "교권 추락.", "Quyền uy của giáo viên", "Sự sa sút trong quyền hạn của nhà giáo.", "Teachers' authority", "ko_edu_expert"),
    ("체벌", "Chebeol", "noun/verb", "학생 체벌 금지.", "Phạt thể xác", "Cấm dùng nhục hình, đòn roi với học sinh.", "Corporal punishment", "ko_edu_expert"),
    ("공교육 정상화", "Gonggyoyuk jeongsanghwa", "phrase", "공교육 정상화 방안.", "Bình thường hóa giáo dục công", "Phương án vực dậy nền giáo dục công lập.", "Normalization of public education", "ko_edu_expert"),
    ("융합교육", "Yunghap gyoyuk", "noun", "STEAM 융합교육.", "Giáo dục tích hợp", "Chương trình giáo dục tích hợp STEAM.", "Convergence education", "ko_edu_expert"),
    ("지식재산권", "Jisik jaesangwon", "noun", "지식재산권 보호.", "Quyền sở hữu trí tuệ", "Bảo vệ quyền sở hữu trí tuệ.", "Intellectual property rights", "ko_edu_expert"),
    ("학술지", "Haksulji", "noun", "학술지에 논문을 게재하다.", "Tạp chí học thuật", "Đăng tải luận văn lên tạp chí khoa học chuyên ngành.", "Academic journal", "ko_edu_expert"),
    ("연구비", "Yeongubi", "noun", "연구비 지원.", "Kinh phí nghiên cứu", "Tài trợ chi phí nghiên cứu.", "Research fund", "ko_edu_expert"),
    ("산학협력", "Sanhak hyeomnyeok", "noun", "산학협력 프로젝트.", "Hợp tác viện trường - doanh nghiệp", "Dự án hợp tác giữa nhà trường và doanh nghiệp.", "Industry-academia cooperation", "ko_edu_expert"),
    ("조기교육", "Jogigyoyuk", "noun", "지나친 조기교육.", "Giáo dục sớm", "Tình trạng giáo dục sớm thái quá cho trẻ mầm non.", "Early childhood education", "ko_edu_expert"),

    # ---- FASHION ----
    # Beginner (0)
    ("옷", "Ot", "noun", "옷을 입다.", "Quần áo", "Mặc quần áo vào.", "Clothes", "ko_fashion_beginner"),
    ("치마", "Chima", "noun", "치마를 입다.", "Váy (chân váy)", "Mặc váy.", "Skirt", "ko_fashion_beginner"),
    ("바지", "Baji", "noun", "청바지.", "Quần", "Quần jeans (quần bò).", "Pants", "ko_fashion_beginner"),
    ("티셔츠", "Tisyeocheu", "noun", "하얀 티셔츠.", "Áo thun (T-shirt)", "Chiếc áo phông màu trắng.", "T-shirt", "ko_fashion_beginner"),
    ("셔츠", "Syeocheu", "noun", "셔츠를 다리다.", "Áo sơ mi", "Là (ủi) áo sơ mi.", "Shirt", "ko_fashion_beginner"),
    ("원피스", "Wonpiseu", "noun", "예쁜 원피스.", "Váy liền (Dress)", "Chiếc váy đầm rất đẹp.", "Dress", "ko_fashion_beginner"),
    ("신발", "Sinbal", "noun", "신발을 신다.", "Giày dép", "Xỏ giày vào.", "Shoes", "ko_fashion_beginner"),
    ("운동화", "Undonghwa", "noun", "운동화를 신고 뛰다.", "Giày thể thao", "Đi giày thể thao chạy bộ.", "Sneakers", "ko_fashion_beginner"),
    ("구두", "Gudu", "noun", "구두를 닦다.", "Giày da, giày tây", "Đánh bóng giày da.", "Dress shoes", "ko_fashion_beginner"),
    ("양말", "Yangmal", "noun", "양말을 벗다.", "Tất, vớ", "Cởi tất ra.", "Socks", "ko_fashion_beginner"),
    ("모자", "Moja", "noun", "모자를 쓰다.", "Mũ, nón", "Đội mũ.", "Hat", "ko_fashion_beginner"),
    ("안경", "Angyeong", "noun", "안경을 쓰다.", "Kính mắt", "Đeo kính mắt.", "Glasses", "ko_fashion_beginner"),
    ("가방", "Gabang", "noun", "가방을 들다.", "Túi xách, balo", "Xách túi lên.", "Bag", "ko_fashion_beginner"),
    ("지갑", "Jigap", "noun", "지갑을 잃어버리다.", "Cái ví", "Đánh mất ví tiền rồi.", "Wallet", "ko_fashion_beginner"),
    ("시계", "Sigye", "noun", "시계를 차다.", "Đồng hồ", "Đeo đồng hồ đeo tay.", "Watch", "ko_fashion_beginner"),
    ("코트", "Koteu", "noun", "겨울 코트.", "Áo khoác dạ (Coat)", "Áo khoác mùa đông.", "Coat", "ko_fashion_beginner"),
    ("패딩", "Paeding", "noun", "패딩을 입다.", "Áo phao", "Mặc áo phao cho ấm.", "Padded jacket", "ko_fashion_beginner"),
    ("속옷", "Sogot", "noun", "속옷을 빨다.", "Đồ lót", "Giặt đồ lót.", "Underwear", "ko_fashion_beginner"),
    ("수영복", "Suyeongbok", "noun", "수영복을 사다.", "Đồ bơi", "Mua quần áo bơi.", "Swimsuit", "ko_fashion_beginner"),
    ("입다", "Ipda", "verb", "옷을 입다.", "Mặc (áo, quần)", "Mặc quần áo.", "Put on (clothes)", "ko_fashion_beginner"),
    ("벗다", "Beotda", "verb", "신발을 벗다.", "Cởi (áo, giày)", "Cởi giày ra.", "Take off", "ko_fashion_beginner"),
    ("신다", "Sinda", "verb", "양말을 신다.", "Đi, xỏ (giày, tất)", "Xỏ tất vào.", "Put on (shoes/socks)", "ko_fashion_beginner"),
    ("쓰다", "Sseuda", "verb", "모자를 쓰다.", "Đội (mũ), đeo (kính)", "Đội mũ bảo hiểm.", "Wear (hat/glasses)", "ko_fashion_beginner"),
    ("끼다", "Kkida", "verb", "장갑을 끼다.", "Đeo (găng tay, nhẫn)", "Đeo găng tay len.", "Put on (gloves/ring)", "ko_fashion_beginner"),
    ("차다", "Chada", "verb", "시계를 차다.", "Đeo (đồng hồ)", "Đeo chiếc đồng hồ mới.", "Wear (watch)", "ko_fashion_beginner"),
    ("크다", "Keuda", "adjective", "옷이 크다.", "Rộng, to", "Quần áo bị rộng quá.", "Big", "ko_fashion_beginner"),
    ("작다", "Jakda", "adjective", "신발이 작다.", "Chật, nhỏ", "Đôi giày này hơi chật.", "Small", "ko_fashion_beginner"),
    ("길다", "Gilda", "adjective", "치마가 길다.", "Dài", "Chiếc váy này dài quá.", "Long", "ko_fashion_beginner"),
    ("짧다", "Jjalpda", "adjective", "바지가 짧다.", "Ngắn", "Cái quần này bị ngắn.", "Short", "ko_fashion_beginner"),
    ("예쁘다", "Yeppeuda", "adjective", "옷이 예쁘다.", "Đẹp", "Bộ quần áo rất đẹp.", "Pretty", "ko_fashion_beginner"),

    # Intermediate (1)
    ("유행", "Yuhaeng", "noun", "유행을 따르다.", "Xu hướng, mốt", "Chạy theo xu hướng mốt.", "Trend", "ko_fashion_intermediate"),
    ("패션", "Paesyeon", "noun", "패션 감각.", "Thời trang", "Có gu thẩm mỹ thời trang.", "Fashion", "ko_fashion_intermediate"),
    ("스타일", "Seutail", "noun", "자신만의 스타일.", "Phong cách", "Có phong cách riêng của bản thân.", "Style", "ko_fashion_intermediate"),
    ("브랜드", "Beuraendeu", "noun", "명품 브랜드.", "Thương hiệu", "Thương hiệu cao cấp sang trọng.", "Brand", "ko_fashion_intermediate"),
    ("디자인", "Dijain", "noun", "디자인이 독특하다.", "Thiết kế", "Thiết kế rất độc đáo mới lạ.", "Design", "ko_fashion_intermediate"),
    ("색깔", "Saekkkal", "noun", "밝은 색깔.", "Màu sắc", "Màu sắc tươi sáng rực rỡ.", "Color", "ko_fashion_intermediate"),
    ("무늬", "Munui", "noun", "꽃무늬 치마.", "Hoa văn, họa tiết", "Chân váy in họa tiết hoa.", "Pattern", "ko_fashion_intermediate"),
    ("사이즈", "Saijeu", "noun", "사이즈가 맞다.", "Kích cỡ", "Size này mặc vừa khít.", "Size", "ko_fashion_intermediate"),
    ("치수", "Chisu", "noun", "허리 치수를 재다.", "Số đo", "Đo thử vòng eo xem sao.", "Measurement", "ko_fashion_intermediate"),
    ("어울리다", "Eoullida", "verb", "이 옷이 잘 어울려요.", "Phù hợp, hợp (mắt)", "Bộ đồ này hợp với bạn lắm.", "Suit/Look good", "ko_fashion_intermediate"),
    ("세련되다", "Seryeondoeda", "adjective", "스타일이 세련되다.", "Sành điệu, thanh lịch", "Phong cách rất thanh lịch và sành điệu.", "Sophisticated/Chic", "ko_fashion_intermediate"),
    ("촌스럽다", "Chonseureopda", "adjective", "옷차림이 촌스럽다.", "Quê mùa, lỗi thời", "Cách ăn mặc hơi quê mùa một chút.", "Tacky/Out of style", "ko_fashion_intermediate"),
    ("화려하다", "Hwaryeohada", "adjective", "화려한 색.", "Sặc sỡ, lộng lẫy", "Màu sắc sặc sỡ chói lóa.", "Flashy/Glamorous", "ko_fashion_intermediate"),
    ("단정하다", "Danjeonghada", "adjective", "옷차림이 단정하다.", "Chỉnh tề, gọn gàng", "Ăn mặc rất gọn gàng chỉnh tề.", "Neat/Tidy", "ko_fashion_intermediate"),
    ("편안하다", "Pyeonanhada", "adjective", "편안한 운동복.", "Thoải mái", "Bộ đồ thể thao mặc rất thoải mái.", "Comfortable", "ko_fashion_intermediate"),
    ("화장", "Hwajang", "noun", "화장을 하다.", "Trang điểm", "Trang điểm nhẹ nhàng.", "Makeup", "ko_fashion_intermediate"),
    ("향수", "Hyangsu", "noun", "향수를 뿌리다.", "Nước hoa", "Xịt một chút nước hoa.", "Perfume", "ko_fashion_intermediate"),
    ("목걸이", "Mokgeori", "noun", "목걸이를 하다.", "Dây chuyền", "Đeo sợi dây chuyền.", "Necklace", "ko_fashion_intermediate"),
    ("귀걸이", "Gwigeori", "noun", "귀걸이를 하다.", "Bông tai", "Đeo khuyên tai.", "Earrings", "ko_fashion_intermediate"),
    ("반지", "Banji", "noun", "반지를 끼다.", "Nhẫn", "Đeo nhẫn cưới.", "Ring", "ko_fashion_intermediate"),
    ("스카프", "Seukapeu", "noun", "스카프를 두르다.", "Khăn quàng (mỏng)", "Quàng chiếc khăn lụa.", "Scarf (light)", "ko_fashion_intermediate"),
    ("목도리", "Mokdori", "noun", "목도리를 하다.", "Khăn len (quàng cổ)", "Quàng khăn len cho ấm cổ.", "Scarf (thick/winter)", "ko_fashion_intermediate"),
    ("장갑", "Janggap", "noun", "장갑을 끼다.", "Găng tay", "Đeo găng tay vào.", "Gloves", "ko_fashion_intermediate"),
    ("정장", "Jeongjang", "noun", "정장을 입다.", "Com-lê (Suit)", "Mặc một bộ đồ suit.", "Suit", "ko_fashion_intermediate"),
    ("넥타이", "Nektai", "noun", "넥타이를 매다.", "Cà vạt", "Thắt cà vạt cẩn thận.", "Necktie", "ko_fashion_intermediate"),
    ("블라우스", "Beullauseu", "noun", "실크 블라우스.", "Áo sơ mi nữ (Blouse)", "Áo blouse bằng vải lụa.", "Blouse", "ko_fashion_intermediate"),
    ("가디건", "Gadigeon", "noun", "가디건을 걸치다.", "Áo khoác len (Cardigan)", "Khoác chiếc áo len mỏng bên ngoài.", "Cardigan", "ko_fashion_intermediate"),
    ("니트", "Niteu", "noun", "니트 스웨터.", "Đồ len (Knitwear)", "Chiếc áo len đan.", "Knitwear", "ko_fashion_intermediate"),
    ("면", "Myeon", "noun", "100% 면 소재.", "Vải cotton", "Chất liệu 100% cotton thoáng mát.", "Cotton", "ko_fashion_intermediate"),
    ("가죽", "Gajuk", "noun", "가죽 가방.", "Da (Leather)", "Túi xách bằng da thật.", "Leather", "ko_fashion_intermediate"),

    # Advanced (2)
    ("의류", "Uiryu", "noun", "의류 매장.", "Đồ may mặc (Apparel)", "Cửa hàng bán đồ may mặc.", "Clothing/Apparel", "ko_fashion_advanced"),
    ("섬유", "Seomyu", "noun", "합성 섬유.", "Sợi vải", "Sợi vải tổng hợp hóa học.", "Fiber", "ko_fashion_advanced"),
    ("직물", "Jingmul", "noun", "직물 공장.", "Vải vóc, đồ dệt", "Nhà máy dệt may.", "Textile", "ko_fashion_advanced"),
    ("재질", "Jaejil", "noun", "옷의 재질이 좋다.", "Chất liệu", "Chất liệu của cái áo này rất tốt.", "Material", "ko_fashion_advanced"),
    ("실크", "Silkeu", "noun", "실크 스카프.", "Lụa (Silk)", "Khăn quàng cổ bằng lụa.", "Silk", "ko_fashion_advanced"),
    ("린넨", "Rinnen", "noun", "여름엔 린넨.", "Vải lanh (Linen)", "Mùa hè thì nên mặc đồ vải lanh.", "Linen", "ko_fashion_advanced"),
    ("코디", "Kodi", "noun/verb", "옷을 코디하다.", "Phối đồ (Coordinate)", "Mix match và phối đồ cho đẹp.", "Coordinate", "ko_fashion_advanced"),
    ("착장", "Chakjang", "noun", "오늘의 착장 (OOTD).", "Trang phục (Outfit)", "Gợi ý trang phục cho ngày hôm nay.", "Outfit", "ko_fashion_advanced"),
    ("맞춤복", "Matchumbok", "noun", "맞춤복을 주문하다.", "Quần áo may đo", "Đặt may riêng một bộ quần áo.", "Custom-made clothes", "ko_fashion_advanced"),
    ("기성복", "Giseongbok", "noun", "기성복을 사다.", "Quần áo may sẵn", "Mua quần áo may công nghiệp.", "Ready-to-wear", "ko_fashion_advanced"),
    ("신상품", "Sinsangpum", "noun", "봄 신상품.", "Hàng mới về", "Bộ sưu tập hàng mới về dịp mùa Xuân.", "New arrival", "ko_fashion_advanced"),
    ("한정판", "Hanjeongpan", "noun", "한정판 운동화.", "Phiên bản giới hạn", "Đôi giày thể thao phiên bản limited.", "Limited edition", "ko_fashion_advanced"),
    ("명품", "Myeongpum", "noun", "명품 가방.", "Hàng hiệu", "Túi xách hàng hiệu xa xỉ.", "Luxury goods", "ko_fashion_advanced"),
    ("짝퉁", "Jjaktung", "noun", "짝퉁을 팔다.", "Hàng fake, hàng nhái", "Buôn bán hàng nhái kém chất lượng.", "Knock-off/Fake", "ko_fashion_advanced"),
    ("트렌드", "Teurendeu", "noun", "최신 트렌드.", "Xu hướng (Trend)", "Bắt kịp xu hướng thời trang mới nhất.", "Trend", "ko_fashion_advanced"),
    ("복고풍", "Bokgopung", "noun", "복고풍 패션.", "Phong cách hoài cổ (Retro)", "Phong cách thời trang retro của thập niên 90.", "Retro style", "ko_fashion_advanced"),
    ("수선", "Suseon", "noun/verb", "옷을 수선하다.", "Sửa chữa (quần áo)", "Mang quần áo ra tiệm để sửa lại.", "Alteration", "ko_fashion_advanced"),
    ("드라이클리닝", "Deuraikeullining", "noun", "코트를 드라이클리닝 맡기다.", "Giặt khô", "Mang áo khoác dạ ra tiệm giặt khô.", "Dry cleaning", "ko_fashion_advanced"),
    ("옷걸이", "Otgeori", "noun", "옷걸이에 걸다.", "Mắc áo", "Treo áo lên chiếc móc quần áo.", "Hanger", "ko_fashion_advanced"),
    ("행거", "Haenggeo", "noun", "행거에 옷을 걸다.", "Giá treo quần áo", "Treo đồ lên giá treo cho thẳng nếp.", "Clothes rack", "ko_fashion_advanced"),
    ("옷장", "Otjang", "noun", "옷장을 정리하다.", "Tủ quần áo", "Dọn dẹp lại tủ quần áo cho gọn.", "Closet/Wardrobe", "ko_fashion_advanced"),
    ("패션쇼", "Paesyeonsyo", "noun", "패션쇼를 열다.", "Buổi trình diễn thời trang", "Tổ chức show diễn thời trang ra mắt BST.", "Fashion show", "ko_fashion_advanced"),
    ("모델", "Model", "noun", "패션 모델.", "Người mẫu", "Người mẫu trình diễn trên sàn catwalk.", "Model", "ko_fashion_advanced"),
    ("핏", "Pit", "noun", "옷의 핏이 좋다.", "Dáng áo (Fit)", "Phom dáng của chiếc áo này tôn dáng lắm.", "Fit", "ko_fashion_advanced"),
    ("헐렁하다", "Heolleonghada", "adjective", "옷이 너무 헐렁하다.", "Thùng thình", "Cái áo này mặc lên bị rộng thùng thình.", "Loose/Baggy", "ko_fashion_advanced"),
    ("꽉 끼다", "Kkwak kkida", "phrase", "바지가 꽉 끼다.", "Bó sát", "Cái quần jeans này bó sát quá, khó cử động.", "Tight", "ko_fashion_advanced"),
    ("소매", "Somae", "noun", "소매를 걷다.", "Ống tay áo", "Xắn ống tay áo lên cho gọn gàng.", "Sleeve", "ko_fashion_advanced"),
    ("옷깃", "Otgit", "noun", "옷깃을 세우다.", "Cổ áo", "Dựng cổ áo lên để chắn gió.", "Collar", "ko_fashion_advanced"),
    ("단추", "Danchu", "noun", "단추를 채우다.", "Cúc áo", "Cài cúc áo lại cẩn thận.", "Button", "ko_fashion_advanced"),
    ("지퍼", "Jipeo", "noun", "지퍼를 올리다.", "Khóa kéo", "Kéo khóa áo khoác lên.", "Zipper", "ko_fashion_advanced"),

    # Expert (3)
    ("오뜨꾸뛰르", "Otteukkuttwireu", "noun", "오뜨꾸뛰르 컬렉션.", "Thời trang cao cấp (Haute couture)", "Bộ sưu tập Haute Couture đắt đỏ.", "Haute couture", "ko_fashion_expert"),
    ("기성복 (프레타포르테)", "Peuretapaporeute", "noun", "프레타포르테 쇼.", "Thời trang may sẵn cao cấp", "Show diễn thời trang Prêt-à-porter.", "Prêt-à-porter", "ko_fashion_expert"),
    ("패스트패션", "Paeseuteupaesyeon", "noun", "패스트패션 브랜드의 문제점.", "Thời trang nhanh (Fast fashion)", "Các vấn đề môi trường của thời trang ăn liền.", "Fast fashion", "ko_fashion_expert"),
    ("슬로우패션", "Seulloupaesyeon", "noun", "지속 가능한 슬로우패션.", "Thời trang chậm (bền vững)", "Hướng tới xu hướng thời trang bền vững.", "Slow fashion", "ko_fashion_expert"),
    ("업사이클링", "Eopsaikeulling", "noun", "업사이클링 패션.", "Tái chế thời trang", "Thời trang tái chế từ vật liệu cũ thành mới.", "Upcycling", "ko_fashion_expert"),
    ("아방가르드", "Abanggareudeu", "noun", "아방가르드 패션.", "Thời trang phá cách (Avant-garde)", "Phong cách dị biệt, đi trước thời đại.", "Avant-garde", "ko_fashion_expert"),
    ("미니멀리즘", "Minimeollijeum", "noun", "패션의 미니멀리즘.", "Chủ nghĩa tối giản", "Phong cách minimalism tiết chế chi tiết.", "Minimalism", "ko_fashion_expert"),
    ("맥시멀리즘", "Maeksimeollijeum", "noun", "화려한 맥시멀리즘.", "Chủ nghĩa tối đa", "Phong cách maximalism phô trương rực rỡ.", "Maximalism", "ko_fashion_expert"),
    ("스트릿 패션", "Seuteurit paesyeon", "noun", "힙합 스트릿 패션.", "Thời trang đường phố", "Gu thời trang bụi bặm phong cách đường phố.", "Street fashion", "ko_fashion_expert"),
    ("애슬레저", "Aeseullejeo", "noun", "애슬레저 룩이 유행이다.", "Trang phục thể thao ứng dụng", "Xu hướng mặc đồ thể thao dạo phố Athleisure.", "Athleisure", "ko_fashion_expert"),
    ("믹스매치", "Mikseumaechi", "noun", "옷을 믹스매치하다.", "Phối đồ ngẫu hứng (Mix and match)", "Trộn lẫn các item trái ngược để tạo sự phá cách.", "Mix and match", "ko_fashion_expert"),
    ("톤온톤", "Tononton", "noun", "톤온톤 코디.", "Phối màu cùng tông", "Cách mix đồ tone-sur-tone đậm nhạt hài hòa.", "Tone on tone", "ko_fashion_expert"),
    ("비스포크", "Biseupokeu", "noun", "비스포크 수트.", "May đo độc bản (Bespoke)", "Bộ suit bespoke được cắt may hoàn toàn thủ công.", "Bespoke", "ko_fashion_expert"),
    ("테일러링", "Teilleoring", "noun", "정교한 테일러링.", "Kỹ thuật may đo", "Nghệ thuật cắt may sắc sảo tôn lên vóc dáng.", "Tailoring", "ko_fashion_expert"),
    ("실루엣", "Silluet", "noun", "아름다운 실루엣.", "Phom dáng (Silhouette)", "Đường nét phom dáng tổng thể của bộ trang phục.", "Silhouette", "ko_fashion_expert"),
    ("패턴", "Paeteon", "noun", "옷의 패턴을 뜨다.", "Bản rập (Pattern)", "Kỹ thuật thiết kế và ra rập giấy cho trang phục.", "Pattern making", "ko_fashion_expert"),
    ("드레이핑", "Deureiping", "noun", "입체적인 드레이핑 기술.", "Kỹ thuật dựng phom", "Dựng phom 3D trực tiếp trên manơcanh (Draping).", "Draping", "ko_fashion_expert"),
    ("디자이너", "Dijaineo", "noun", "수석 디자이너.", "Nhà thiết kế", "Giám đốc sáng tạo của một hãng thời trang.", "Designer", "ko_fashion_expert"),
    ("룩북", "Rukbuk", "noun", "이번 시즌 룩북.", "Bộ ảnh thời trang (Lookbook)", "Xem qua ảnh Lookbook bộ sưu tập mùa này.", "Lookbook", "ko_fashion_expert"),
    ("컬렉션", "Keolleksyeon", "noun", "SS 컬렉션 발표.", "Bộ sưu tập (Collection)", "Ra mắt bộ sưu tập thời trang Xuân-Hè.", "Collection", "ko_fashion_expert"),
    ("런웨이", "Reonwei", "noun", "런웨이를 걷다.", "Sàn diễn thời trang (Runway)", "Những người mẫu sải bước tự tin trên sàn Runway.", "Runway", "ko_fashion_expert"),
    ("셀럽", "Selleop", "noun", "셀럽들이 입는 옷.", "Người nổi tiếng (Celebrity)", "Gu ăn mặc đẳng cấp của giới Celeb showbiz.", "Celebrity", "ko_fashion_expert"),
    ("앰버서더", "Aembeoseodeo", "noun", "브랜드 글로벌 앰버서더.", "Đại sứ thương hiệu", "Gương mặt đại diện toàn cầu cho thương hiệu.", "Brand ambassador", "ko_fashion_expert"),
    ("완판", "Wanpan", "noun/verb", "출시되자마자 완판되다.", "Bán sạch (Sold out)", "Mẫu túi cháy hàng ngay từ khi vừa ra mắt.", "Sold out", "ko_fashion_expert"),
    ("퍼스널 컬러", "Peoseuneol keolleo", "noun", "퍼스널 컬러 진단을 받다.", "Màu sắc cá nhân", "Phân tích tông màu da cá nhân để chọn đồ phù hợp.", "Personal color", "ko_fashion_expert"),
    ("쿨톤", "Kulton", "noun", "쿨톤 메이크업.", "Tông lạnh", "Trang phục dành cho những người có tông da lạnh.", "Cool tone", "ko_fashion_expert"),
    ("웜톤", "Womton", "noun", "웜톤에 어울리는 옷.", "Tông ấm", "Màu son hợp với cô gái mang tông da ấm.", "Warm tone", "ko_fashion_expert"),
    ("드레스코드", "Deureseukodeu", "noun", "파티의 드레스코드.", "Quy định trang phục", "Quy định Dress code của bữa tiệc là trắng và đen.", "Dress code", "ko_fashion_expert"),
    ("TPO (티피오)", "Tipio", "noun", "TPO에 맞게 옷을 입다.", "Thời gian, địa điểm, bối cảnh", "Nghệ thuật ăn mặc phù hợp với TPO (Time, Place, Occasion).", "TPO", "ko_fashion_expert"),
    ("패셔니스타", "Paesyeonisita", "noun", "그녀는 진정한 패셔니스타다.", "Tín đồ thời trang", "Cô ấy quả đúng là một Fashionista thực thụ.", "Fashionista", "ko_fashion_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_ko, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "ko",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_ko,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Education & Fashion - Korean) to DB!")
