import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Weather
    {"id": "ja_weather_beginner", "languageCode": "ja", "title": "天気", "subtitle": "Thời tiết - Beginner", "iconEmoji": "☀️", "level": "Beginner", "colorHex": "#38BDF8", "cardCount": 30},
    {"id": "ja_weather_intermediate", "languageCode": "ja", "title": "天気", "subtitle": "Thời tiết - Intermediate", "iconEmoji": "☀️", "level": "Intermediate", "colorHex": "#0EA5E9", "cardCount": 30},
    {"id": "ja_weather_advanced", "languageCode": "ja", "title": "天気", "subtitle": "Thời tiết - Advanced", "iconEmoji": "☀️", "level": "Advanced", "colorHex": "#0284C7", "cardCount": 30},
    {"id": "ja_weather_expert", "languageCode": "ja", "title": "天気", "subtitle": "Thời tiết - Expert", "iconEmoji": "☀️", "level": "Expert", "colorHex": "#0369A1", "cardCount": 30},
    
    # Food & Drinks
    {"id": "ja_food_beginner", "languageCode": "ja", "title": "食べ物", "subtitle": "Đồ ăn-uống - Beginner", "iconEmoji": "🍔", "level": "Beginner", "colorHex": "#F97316", "cardCount": 30},
    {"id": "ja_food_intermediate", "languageCode": "ja", "title": "食べ物", "subtitle": "Đồ ăn-uống - Intermediate", "iconEmoji": "🍔", "level": "Intermediate", "colorHex": "#EA580C", "cardCount": 30},
    {"id": "ja_food_advanced", "languageCode": "ja", "title": "食べ物", "subtitle": "Đồ ăn-uống - Advanced", "iconEmoji": "🍔", "level": "Advanced", "colorHex": "#C2410C", "cardCount": 30},
    {"id": "ja_food_expert", "languageCode": "ja", "title": "食べ物", "subtitle": "Đồ ăn-uống - Expert", "iconEmoji": "🍔", "level": "Expert", "colorHex": "#9A3412", "cardCount": 30}
]

vocab_data = [
    # ---- WEATHER ----
    # Beginner (0)
    ("天気", "Tenki", "noun", "天気が良い。", "Thời tiết", "Thời tiết tốt.", "Tình trạng bầu trời", "ja_weather_beginner"),
    ("晴れ", "Hare", "noun", "今日は晴れだ。", "Nắng, trời quang", "Hôm nay trời nắng.", "Mặt trời chiếu", "ja_weather_beginner"),
    ("曇り", "Kumori", "noun", "明日は曇りだ。", "Có mây", "Ngày mai trời nhiều mây.", "Trời âm u", "ja_weather_beginner"),
    ("雨", "Ame", "noun", "雨が降る。", "Mưa", "Trời mưa.", "Nước rơi từ trời", "ja_weather_beginner"),
    ("雪", "Yuki", "noun", "雪が降る。", "Tuyết", "Tuyết rơi.", "Bông tuyết trắng", "ja_weather_beginner"),
    ("風", "Kaze", "noun", "風が吹く。", "Gió", "Gió thổi.", "Không khí chuyển động", "ja_weather_beginner"),
    ("空", "Sora", "noun", "空が青い。", "Bầu trời", "Bầu trời xanh.", "Phía trên đầu", "ja_weather_beginner"),
    ("太陽", "Taiyou", "noun", "太陽が昇る。", "Mặt trời", "Mặt trời mọc.", "Ngôi sao sáng ban ngày", "ja_weather_beginner"),
    ("星", "Hoshi", "noun", "星が見える。", "Ngôi sao", "Có thể nhìn thấy sao.", "Đốm sáng ban đêm", "ja_weather_beginner"),
    ("月", "Tsuki", "noun", "月がきれい。", "Mặt trăng", "Mặt trăng đẹp.", "Vệ tinh của Trái Đất", "ja_weather_beginner"),
    ("暑い", "Atsui", "adjective", "今日は暑い。", "Nóng (thời tiết)", "Hôm nay trời nóng.", "Nhiệt độ cao", "ja_weather_beginner"),
    ("寒い", "Samui", "adjective", "冬は寒い。", "Lạnh (thời tiết)", "Mùa đông lạnh.", "Nhiệt độ thấp", "ja_weather_beginner"),
    ("暖かい", "Atatakai", "adjective", "春は暖かい。", "Ấm áp", "Mùa xuân ấm áp.", "Dễ chịu", "ja_weather_beginner"),
    ("涼しい", "Suzushii", "adjective", "秋は涼しい。", "Mát mẻ", "Mùa thu mát mẻ.", "Hơi lạnh dễ chịu", "ja_weather_beginner"),
    ("降る", "Furu", "verb", "雨が降る。", "Rơi (mưa, tuyết)", "Trời mưa.", "Rơi từ trên xuống", "ja_weather_beginner"),
    ("吹く", "Fuku", "verb", "風が吹く。", "Thổi (gió)", "Gió thổi.", "Luồng khí bay", "ja_weather_beginner"),
    ("傘", "Kasa", "noun", "傘をさす。", "Ô, dù", "Che ô.", "Che mưa", "ja_weather_beginner"),
    ("季節", "Kisetsu", "noun", "好きな季節。", "Mùa", "Mùa yêu thích.", "Xuân hạ thu đông", "ja_weather_beginner"),
    ("春", "Haru", "noun", "春が来た。", "Mùa xuân", "Mùa xuân đã đến.", "Hoa nở", "ja_weather_beginner"),
    ("夏", "Natsu", "noun", "夏休み。", "Mùa hè", "Nghỉ hè.", "Nóng nực", "ja_weather_beginner"),
    ("秋", "Aki", "noun", "秋の空。", "Mùa thu", "Bầu trời mùa thu.", "Lá vàng", "ja_weather_beginner"),
    ("冬", "Fuyu", "noun", "冬の雪。", "Mùa đông", "Tuyết mùa đông.", "Rất lạnh", "ja_weather_beginner"),
    ("朝", "Asa", "noun", "朝早く起きる。", "Buổi sáng", "Thức dậy sớm vào buổi sáng.", "Lúc mặt trời mọc", "ja_weather_beginner"),
    ("昼", "Hiru", "noun", "昼にご飯を食べる。", "Buổi trưa", "Ăn cơm trưa.", "Giữa ngày", "ja_weather_beginner"),
    ("夜", "Yoru", "noun", "夜は暗い。", "Buổi tối, đêm", "Ban đêm trời tối.", "Mặt trời lặn", "ja_weather_beginner"),
    ("今", "Ima", "noun", "今、雨が降っている。", "Bây giờ", "Bây giờ đang mưa.", "Lúc này", "ja_weather_beginner"),
    ("今日", "Kyou", "noun", "今日の天気。", "Hôm nay", "Thời tiết hôm nay.", "Ngày hiện tại", "ja_weather_beginner"),
    ("明日", "Ashita", "noun", "明日は晴れる。", "Ngày mai", "Ngày mai trời sẽ nắng.", "Ngày hôm sau", "ja_weather_beginner"),
    ("昨日", "Kinou", "noun", "昨日は雨だった。", "Hôm qua", "Hôm qua trời đã mưa.", "Ngày hôm trước", "ja_weather_beginner"),
    ("雲", "Kumo", "noun", "白い雲。", "Đám mây", "Đám mây trắng.", "Hơi nước tụ lại", "ja_weather_beginner"),

    # Intermediate (1)
    ("天気予報", "Tenki yohou", "noun", "天気予報を見る。", "Dự báo thời tiết", "Xem dự báo thời tiết.", "Tin thời tiết", "ja_weather_intermediate"),
    ("気温", "Kion", "noun", "気温が高い。", "Nhiệt độ (thời tiết)", "Nhiệt độ cao.", "Độ nóng lạnh", "ja_weather_intermediate"),
    ("湿度", "Shitsudo", "noun", "湿度が高い。", "Độ ẩm", "Độ ẩm cao.", "Hơi nước trong không khí", "ja_weather_intermediate"),
    ("台風", "Taifuu", "noun", "台風が来る。", "Bão", "Bão đang đến.", "Cơn bão lớn", "ja_weather_intermediate"),
    ("雷", "Kaminari", "noun", "雷が鳴る。", "Sấm sét", "Sấm nổ.", "Ánh sáng và tiếng nổ trên trời", "ja_weather_intermediate"),
    ("虹", "Niji", "noun", "虹が出る。", "Cầu vồng", "Cầu vồng xuất hiện.", "Bảy sắc trên trời", "ja_weather_intermediate"),
    ("霧", "Kiri", "noun", "霧が濃い。", "Sương mù", "Sương mù dày đặc.", "Lớp mù", "ja_weather_intermediate"),
    ("嵐", "Arashi", "noun", "嵐が過ぎる。", "Cơn bão, giông", "Cơn bão trôi qua.", "Mưa to gió lớn", "ja_weather_intermediate"),
    ("梅雨", "Tsuyu", "noun", "梅雨に入る。", "Mùa mưa (Nhật Bản)", "Bước vào mùa mưa.", "Tháng 6 mưa nhiều", "ja_weather_intermediate"),
    ("気候", "Kikou", "noun", "日本の気候。", "Khí hậu", "Khí hậu Nhật Bản.", "Tình trạng thời tiết dài hạn", "ja_weather_intermediate"),
    ("快晴", "Kaisei", "noun", "快晴の空。", "Trời quang đãng", "Bầu trời trong xanh.", "Không một bóng mây", "ja_weather_intermediate"),
    ("にわか雨", "Niwaka ame", "noun", "にわか雨が降る。", "Mưa rào bất chợt", "Cơn mưa rào ập đến.", "Mưa đột ngột", "ja_weather_intermediate"),
    ("大雨", "Oouame", "noun", "大雨警報。", "Mưa lớn", "Cảnh báo mưa lớn.", "Mưa rất to", "ja_weather_intermediate"),
    ("大雪", "Ooyuki", "noun", "大雪が降る。", "Tuyết lớn", "Tuyết rơi dày.", "Tuyết rất dày", "ja_weather_intermediate"),
    ("洪水", "Kouzui", "noun", "洪水が起きる。", "Lũ lụt", "Lũ lụt xảy ra.", "Nước ngập", "ja_weather_intermediate"),
    ("日差し", "Hizashi", "noun", "日差しが強い。", "Ánh nắng", "Ánh nắng chói chang.", "Nắng chiếu", "ja_weather_intermediate"),
    ("紫外線", "Shigaisen", "noun", "紫外線を防ぐ。", "Tia cực tím", "Chống tia UV.", "Tia UV", "ja_weather_intermediate"),
    ("乾燥", "Kansou", "noun/verb", "空気が乾燥する。", "Khô hanh", "Không khí khô hanh.", "Thiếu độ ẩm", "ja_weather_intermediate"),
    ("蒸し暑い", "Mushiatsui", "adjective", "今日は蒸し暑い。", "Nóng nực, oi bức", "Hôm nay thật oi bức.", "Nóng và ẩm", "ja_weather_intermediate"),
    ("吹雪", "Fubuki", "noun", "吹雪の中を歩く。", "Bão tuyết", "Đi trong bão tuyết.", "Gió cuốn tuyết", "ja_weather_intermediate"),
    ("氷", "Koori", "noun", "氷が張る。", "Băng, đá", "Đóng băng.", "Nước đông đặc", "ja_weather_intermediate"),
    ("溶ける", "Tokeru", "verb", "雪が溶ける。", "Tan chảy", "Tuyết tan.", "Hóa lỏng", "ja_weather_intermediate"),
    ("凍る", "Kooru", "verb", "水が凍る。", "Đóng băng", "Nước đóng băng.", "Nước thành đá", "ja_weather_intermediate"),
    ("夕立", "Yuudachi", "noun", "夕立に遭う。", "Mưa rào chiều tối", "Gặp cơn mưa chiều.", "Mưa mùa hè", "ja_weather_intermediate"),
    ("警報", "Keihou", "noun", "警報が出る。", "Cảnh báo", "Phát cảnh báo.", "Báo động mức độ nguy hiểm", "ja_weather_intermediate"),
    ("注意報", "Chuuihou", "noun", "波浪注意報。", "Thông báo chú ý", "Thông báo chú ý sóng lớn.", "Nhắc nhở nguy hiểm nhẹ", "ja_weather_intermediate"),
    ("波", "Nami", "noun", "波が高い。", "Sóng", "Sóng cao.", "Mặt biển nhấp nhô", "ja_weather_intermediate"),
    ("地震", "Jishin", "noun", "地震が起きる。", "Động đất", "Động đất xảy ra.", "Mặt đất rung lắc", "ja_weather_intermediate"),
    ("津波", "Tsunami", "noun", "津波が来る。", "Sóng thần", "Sóng thần kéo tới.", "Sóng biển khổng lồ", "ja_weather_intermediate"),
    ("防災", "Bousai", "noun", "防災訓練。", "Phòng chống thiên tai", "Diễn tập phòng chống thiên tai.", "Chống thảm họa", "ja_weather_intermediate"),

    # Advanced (2)
    ("異常気象", "Ijou kishou", "noun", "異常気象が続く。", "Thời tiết bất thường", "Thời tiết bất thường tiếp diễn.", "Khí tượng khác thường", "ja_weather_advanced"),
    ("地球温暖化", "Chikyuu ondanka", "noun", "地球温暖化の影響。", "Trái Đất nóng lên", "Ảnh hưởng của biến đổi khí hậu.", "Nhiệt độ toàn cầu tăng", "ja_weather_advanced"),
    ("気圧", "Kiatsu", "noun", "低気圧。", "Áp suất không khí", "Áp suất thấp.", "Khí áp", "ja_weather_advanced"),
    ("前線", "Zensen", "noun", "寒冷前線。", "Frông, luồng khí", "Luồng không khí lạnh.", "Ranh giới khối khí", "ja_weather_advanced"),
    ("高気圧", "Koukiatsu", "noun", "高気圧に覆われる。", "Áp cao", "Được bao phủ bởi áp cao.", "Khí áp cao", "ja_weather_advanced"),
    ("低気圧", "Teikiatsu", "noun", "低気圧が近づく。", "Áp thấp", "Áp thấp đang đến gần.", "Khí áp thấp", "ja_weather_advanced"),
    ("降水量", "Kousuiryou", "noun", "年間降水量。", "Lượng mưa", "Lượng mưa hàng năm.", "Mức nước mưa", "ja_weather_advanced"),
    ("降水確率", "Kousui kakuritsu", "noun", "降水確率は50％。", "Xác suất có mưa", "Xác suất mưa là 50%.", "Tỉ lệ mưa", "ja_weather_advanced"),
    ("熱帯夜", "Nettaiya", "noun", "熱帯夜で眠れない。", "Đêm oi bức", "Đêm quá oi bức không ngủ được.", "Đêm nhiệt đới (trên 25°C)", "ja_weather_advanced"),
    ("猛暑", "Mousho", "noun", "猛暑日が続く。", "Nóng bức dữ dội", "Chuỗi ngày nắng nóng khốc liệt.", "Rất nóng", "ja_weather_advanced"),
    ("寒波", "Kanpa", "noun", "大寒波が到来する。", "Đợt lạnh", "Một đợt rét đậm tràn về.", "Đợt khí lạnh", "ja_weather_advanced"),
    ("豪雨", "Gouu", "noun", "ゲリラ豪雨。", "Mưa như trút", "Mưa rào lớn đột ngột.", "Mưa cực to", "ja_weather_advanced"),
    ("土砂崩れ", "Doshakuzure", "noun", "土砂崩れの危険。", "Sạt lở đất", "Nguy cơ sạt lở đất.", "Đất đá sụp xuống", "ja_weather_advanced"),
    ("竜巻", "Tatsumaki", "noun", "竜巻が発生する。", "Lốc xoáy", "Lốc xoáy xuất hiện.", "Gió xoáy hình phễu", "ja_weather_advanced"),
    ("突風", "Toppuu", "noun", "突風が吹く。", "Gió giật", "Cơn gió giật thổi qua.", "Gió mạnh bất ngờ", "ja_weather_advanced"),
    ("ひょう", "Hyou", "noun", "ひょうが降る。", "Mưa đá", "Trời mưa đá.", "Đá rơi từ trời", "ja_weather_advanced"),
    ("みぞれ", "Mizore", "noun", "みぞれ交じりの雨。", "Mưa tuyết", "Mưa lẫn tuyết.", "Tuyết đang tan", "ja_weather_advanced"),
    ("濃霧", "Noumu", "noun", "濃霧で前が見えない。", "Sương mù dày đặc", "Sương mù dày đặc không thấy đường.", "Sương rất đặc", "ja_weather_advanced"),
    ("霜", "Shimo", "noun", "霜が降りる。", "Sương giá", "Sương giá buông xuống.", "Băng đóng trên cỏ", "ja_weather_advanced"),
    ("露", "Tsuyu", "noun", "朝露。", "Sương mai", "Giọt sương sớm.", "Nước đọng ban mai", "ja_weather_advanced"),
    ("避難", "Hinan", "noun/verb", "避難所に避難する。", "Sơ tán", "Sơ tán đến nơi trú ẩn.", "Lánh nạn", "ja_weather_advanced"),
    ("被害", "Higai", "noun", "被害が拡大する。", "Thiệt hại", "Thiệt hại ngày càng lan rộng.", "Sự phá hủy", "ja_weather_advanced"),
    ("復旧", "Fukkyuu", "noun/verb", "ライフラインが復旧する。", "Phục hồi", "Hệ thống sống còn được khôi phục.", "Sửa lại như cũ", "ja_weather_advanced"),
    ("災害", "Saigai", "noun", "自然災害。", "Thảm họa, thiên tai", "Thảm họa thiên nhiên.", "Thiên tai", "ja_weather_advanced"),
    ("観測", "Kansoku", "noun/verb", "気象観測。", "Quan trắc", "Quan trắc khí tượng.", "Theo dõi đo đạc", "ja_weather_advanced"),
    ("平年", "Heinen", "noun", "平年並みの気温。", "Năm bình thường", "Nhiệt độ tương đương các năm trước.", "Trung bình nhiều năm", "ja_weather_advanced"),
    ("季節風", "Kisetsufuu", "noun", "冬の季節風。", "Gió mùa", "Gió mùa mùa đông.", "Gió đổi hướng theo mùa", "ja_weather_advanced"),
    ("偏西風", "Henseifuu", "noun", "偏西風の影響。", "Gió Tây ôn đới", "Ảnh hưởng của gió Tây.", "Luồng gió Tây", "ja_weather_advanced"),
    ("梅雨明け", "Tsuyuake", "noun", "梅雨明けが発表される。", "Hết mùa mưa", "Thông báo kết thúc mùa mưa.", "Kết thúc mùa Tsuyu", "ja_weather_advanced"),
    ("小春日和", "Koharu biyori", "noun", "今日は小春日和だ。", "Ngày thu nắng ấm", "Hôm nay là một ngày thu ấm áp như xuân.", "Ấm áp cuối thu", "ja_weather_advanced"),

    # Expert (3)
    ("気象庁", "Kishouchou", "noun", "気象庁の発表。", "Cục khí tượng", "Thông báo của Cục khí tượng.", "Cơ quan thời tiết", "ja_weather_expert"),
    ("アメダス", "Amedasu", "noun", "アメダスのデータ。", "Hệ thống AMEDAS", "Dữ liệu AMeDAS.", "Hệ thống quan trắc tự động", "ja_weather_expert"),
    ("降雨帯", "Kouutai", "noun", "降雨帯が通過する。", "Dải mưa", "Dải mưa đi qua.", "Khu vực có mưa", "ja_weather_expert"),
    ("積乱雲", "Sekiran'un", "noun", "積乱雲が発達する。", "Mây vũ tích", "Đám mây vũ tích phát triển.", "Mây dông", "ja_weather_expert"),
    ("乱層雲", "Ransou'un", "noun", "乱層雲が広がる。", "Mây vũ tầng", "Mây vũ tầng lan rộng.", "Mây gây mưa lâu", "ja_weather_expert"),
    ("高層天気図", "Kousou tenkizu", "noun", "高層天気図を解析する。", "Bản đồ thời tiết trên cao", "Phân tích bản đồ thời tiết tầng cao.", "Sơ đồ khí tượng cao", "ja_weather_expert"),
    ("気団", "Kidan", "noun", "オホーツク海気団。", "Khối khí", "Khối khí biển Okhotsk.", "Khối không khí lớn", "ja_weather_expert"),
    ("エルニーニョ現象", "Erunīnyo genshou", "noun", "エルニーニョ現象が発生。", "Hiện tượng El Nino", "El Nino xảy ra.", "El Nino", "ja_weather_expert"),
    ("ラニーニャ現象", "Ranīnya genshou", "noun", "ラニーニャ現象の影響。", "Hiện tượng La Nina", "Ảnh hưởng của La Nina.", "La Nina", "ja_weather_expert"),
    ("ヒートアイランド現象", "Hītoairando genshou", "noun", "ヒートアイランド現象の対策。", "Hiện tượng đảo nhiệt", "Biện pháp chống đảo nhiệt đô thị.", "Đô thị nóng hơn", "ja_weather_expert"),
    ("フェーン現象", "Fēn genshou", "noun", "フェーン現象で気温が上がる。", "Hiện tượng phơn", "Nhiệt độ tăng do hiệu ứng phơn.", "Gió Lào/Gió nóng", "ja_weather_expert"),
    ("放射冷却", "Housha reikyaku", "noun", "放射冷却で冷え込む。", "Làm lạnh bức xạ", "Lạnh buốt do làm lạnh bức xạ.", "Mặt đất mất nhiệt", "ja_weather_expert"),
    ("線状降水帯", "Senjou kousuitai", "noun", "線状降水帯による豪雨。", "Dải mưa hình tuyến tính", "Mưa lớn do dải mây đối lưu.", "Dải mưa cố định", "ja_weather_expert"),
    ("記録的短時間大雨情報", "Kirokuteki tanjikan oouame jouhou", "noun", "記録的短時間大雨情報が出た。", "Cảnh báo mưa kỷ lục cục bộ", "Phát cảnh báo mưa lớn kỷ lục trong thời gian ngắn.", "Cảnh báo cực kì khẩn cấp", "ja_weather_expert"),
    ("警戒レベル", "Keikai reberu", "noun", "警戒レベル4。", "Mức độ cảnh báo", "Mức cảnh báo số 4.", "Cấp độ nguy hiểm", "ja_weather_expert"),
    ("避難指示", "Hinan shiji", "noun", "避難指示が発令される。", "Lệnh sơ tán", "Lệnh sơ tán được ban hành.", "Bắt buộc di tản", "ja_weather_expert"),
    ("特別警報", "Tokubetsu keihou", "noun", "特別警報が発表される。", "Cảnh báo đặc biệt", "Phát cảnh báo mức cao nhất.", "Cảnh báo thảm họa cấp quốc gia", "ja_weather_expert"),
    ("ハザードマップ", "Hazādomappu", "noun", "ハザードマップを確認する。", "Bản đồ rủi ro thiên tai", "Kiểm tra bản đồ rủi ro.", "Bản đồ cảnh báo ngập lụt", "ja_weather_expert"),
    ("異常乾燥", "Ijou kansou", "noun", "異常乾燥注意報。", "Khô hanh bất thường", "Cảnh báo khô hanh mức độ cao.", "Nguy cơ cháy rừng", "ja_weather_expert"),
    ("融雪洪水", "Yuusetsu kouzui", "noun", "融雪洪水に警戒する。", "Lũ lụt do tuyết tan", "Đề phòng lũ lụt vì tuyết tan.", "Lũ do băng tan", "ja_weather_expert"),
    ("局地的大雨", "Kyokuchiteki oouame", "noun", "局地的大雨に注意。", "Mưa lớn cục bộ", "Chú ý mưa cực to ở một số vùng.", "Mưa một vùng nhỏ", "ja_weather_expert"),
    ("降雪量", "Kousetsuryou", "noun", "予想降雪量。", "Lượng tuyết rơi", "Lượng tuyết dự báo.", "Độ dày tuyết", "ja_weather_expert"),
    ("日照時間", "Nisshou jikan", "noun", "日照時間が短い。", "Thời gian chiếu sáng", "Thời gian có nắng rất ngắn.", "Thời lượng nắng", "ja_weather_expert"),
    ("体感温度", "Taikan ondo", "noun", "体感温度はもっと低い。", "Nhiệt độ cảm nhận", "Nhiệt độ cảm nhận ngoài trời còn thấp hơn.", "Nhiệt độ cơ thể thấy", "ja_weather_expert"),
    ("微小粒子状物質", "Bishou ryuushijou busshitsu", "noun", "PM2.5（微小粒子状物質）。", "Bụi mịn PM2.5", "Ô nhiễm hạt bụi siêu nhỏ.", "Bụi siêu mịn", "ja_weather_expert"),
    ("光化学スモッグ", "Koukagaku sumoggu", "noun", "光化学スモッグ注意報。", "Sương mù quang hóa", "Cảnh báo sương mù quang hóa.", "Sương mù độc hại", "ja_weather_expert"),
    ("黄砂", "Kousa", "noun", "黄砂が飛来する。", "Cát vàng", "Cát vàng bay tới.", "Cát bụi từ sa mạc", "ja_weather_expert"),
    ("気候変動", "Kikou hendou", "noun", "気候変動枠組条約。", "Biến đổi khí hậu", "Công ước về biến đổi khí hậu.", "Thay đổi khí hậu Trái Đất", "ja_weather_expert"),
    ("脱炭素社会", "Datsutanso shakai", "noun", "脱炭素社会の実現。", "Xã hội phi carbon", "Hiện thực hóa xã hội không carbon.", "Xã hội giảm thải CO2", "ja_weather_expert"),
    ("再生可能エネルギー", "Saisei kanou enerugī", "noun", "再生可能エネルギーの普及。", "Năng lượng tái tạo", "Phổ cập năng lượng tái tạo.", "Năng lượng xanh", "ja_weather_expert"),

    # ---- FOOD & DRINKS ----
    # Beginner (0)
    ("食べ物", "Tabemono", "noun", "食べ物を買う。", "Đồ ăn", "Mua đồ ăn.", "Thức ăn", "ja_food_beginner"),
    ("飲み物", "Nomimono", "noun", "冷たい飲み物。", "Đồ uống", "Đồ uống lạnh.", "Thức uống", "ja_food_beginner"),
    ("ご飯", "Gohan", "noun", "ご飯を食べる。", "Cơm, bữa ăn", "Ăn cơm.", "Lương thực chính", "ja_food_beginner"),
    ("パン", "Pan", "noun", "パンを焼く。", "Bánh mì", "Nướng bánh mì.", "Làm từ bột mì", "ja_food_beginner"),
    ("肉", "Niku", "noun", "肉が好き。", "Thịt", "Tôi thích thịt.", "Động vật", "ja_food_beginner"),
    ("魚", "Sakana", "noun", "魚を釣る。", "Cá", "Câu cá.", "Sống dưới nước", "ja_food_beginner"),
    ("野菜", "Yasai", "noun", "野菜を切る。", "Rau", "Thái rau.", "Thực vật", "ja_food_beginner"),
    ("果物", "Kudamono", "noun", "果物を食べる。", "Hoa quả", "Ăn trái cây.", "Trái cây", "ja_food_beginner"),
    ("卵", "Tamago", "noun", "卵を割る。", "Trứng", "Đập trứng.", "Sinh ra từ gà/chim", "ja_food_beginner"),
    ("牛乳", "Gyuunyuu", "noun", "牛乳を飲む。", "Sữa bò", "Uống sữa bò.", "Sữa động vật", "ja_food_beginner"),
    ("水", "Mizu", "noun", "水をください。", "Nước", "Cho tôi nước.", "Để uống", "ja_food_beginner"),
    ("お茶", "Ocha", "noun", "お茶を飲む。", "Trà", "Uống trà.", "Nước lá", "ja_food_beginner"),
    ("コーヒー", "Kōhī", "noun", "コーヒーを淹れる。", "Cà phê", "Pha cà phê.", "Nước đắng màu đen", "ja_food_beginner"),
    ("ジュース", "Jūsu", "noun", "りんごジュース。", "Nước ép", "Nước ép táo.", "Nước hoa quả", "ja_food_beginner"),
    ("料理", "Ryouri", "noun/verb", "料理をする。", "Món ăn, nấu ăn", "Nấu ăn.", "Chế biến thực phẩm", "ja_food_beginner"),
    ("朝ご飯", "Asagohan", "noun", "朝ご飯を食べる。", "Bữa sáng", "Ăn sáng.", "Bữa đầu ngày", "ja_food_beginner"),
    ("昼ご飯", "Hirugohan", "noun", "昼ご飯を作る。", "Bữa trưa", "Làm bữa trưa.", "Bữa giữa ngày", "ja_food_beginner"),
    ("晩ご飯", "Bangohan", "noun", "晩ご飯は何？", "Bữa tối", "Bữa tối ăn gì?", "Bữa cuối ngày", "ja_food_beginner"),
    ("美味しい", "Oishii", "adjective", "とても美味しい。", "Ngon", "Rất ngon.", "Vị ngon", "ja_food_beginner"),
    ("まずい", "Mazui", "adjective", "この料理はまずい。", "Dở, không ngon", "Món này dở tệ.", "Vị tồi", "ja_food_beginner"),
    ("甘い", "Amai", "adjective", "甘いケーキ。", "Ngọt", "Bánh ngọt.", "Vị của đường", "ja_food_beginner"),
    ("辛い", "Karai", "adjective", "辛いカレー。", "Cay", "Cà ri cay.", "Vị của ớt", "ja_food_beginner"),
    ("苦い", "Nigai", "adjective", "苦い薬。", "Đắng", "Thuốc đắng.", "Vị khó uống", "ja_food_beginner"),
    ("酸っぱい", "Suppai", "adjective", "酸っぱいレモン。", "Chua", "Chanh chua.", "Vị của chanh", "ja_food_beginner"),
    ("食べる", "Taberu", "verb", "りんごを食べる。", "Ăn", "Ăn táo.", "Đưa vào miệng nhai", "ja_food_beginner"),
    ("飲む", "Nomu", "verb", "ジュースを飲む。", "Uống", "Uống nước ép.", "Nuốt chất lỏng", "ja_food_beginner"),
    ("お腹が空く", "Onaka ga suku", "verb", "お腹が空いた。", "Đói bụng", "Tôi đói rồi.", "Bụng trống rỗng", "ja_food_beginner"),
    ("喉が渇く", "Nodo ga kawaku", "verb", "喉が渇いた。", "Khát nước", "Tôi khát nước.", "Muốn uống", "ja_food_beginner"),
    ("レストラン", "Resutoran", "noun", "レストランに行く。", "Nhà hàng", "Đi nhà hàng.", "Quán ăn lớn", "ja_food_beginner"),
    ("メニュー", "Menyū", "noun", "メニューを見る。", "Thực đơn", "Xem thực đơn.", "Danh sách món", "ja_food_beginner"),

    # Intermediate (1)
    ("食事", "Shokuji", "noun/verb", "食事に出かける。", "Bữa ăn", "Ra ngoài ăn bữa ăn.", "Việc ăn uống", "ja_food_intermediate"),
    ("朝食", "Choushoku", "noun", "ホテルの朝食。", "Bữa sáng (trang trọng)", "Bữa sáng ở khách sạn.", "Ăn sáng", "ja_food_intermediate"),
    ("昼食", "Chuushoku", "noun", "昼食の時間だ。", "Bữa trưa (trang trọng)", "Đến giờ ăn trưa rồi.", "Ăn trưa", "ja_food_intermediate"),
    ("夕食", "Yuushoku", "noun", "家族で夕食をとる。", "Bữa tối (trang trọng)", "Ăn tối cùng gia đình.", "Ăn tối", "ja_food_intermediate"),
    ("外食", "Gaishoku", "noun/verb", "今日は外食しよう。", "Đi ăn ngoài", "Hôm nay đi ăn tiệm đi.", "Ăn ở hàng quán", "ja_food_intermediate"),
    ("自炊", "Jisui", "noun/verb", "毎日自炊する。", "Tự nấu ăn", "Tự nấu ăn mỗi ngày.", "Nấu ăn ở nhà", "ja_food_intermediate"),
    ("和食", "Washoku", "noun", "和食が好きだ。", "Đồ ăn Nhật", "Tôi thích món Nhật.", "Ẩm thực Nhật Bản", "ja_food_intermediate"),
    ("洋食", "Youshoku", "noun", "洋食のレストラン。", "Đồ ăn Tây", "Nhà hàng đồ Âu.", "Ẩm thực phương Tây", "ja_food_intermediate"),
    ("中華", "Chuuka", "noun", "中華料理。", "Đồ ăn Trung Quốc", "Món ăn Trung Hoa.", "Ẩm thực Trung Quốc", "ja_food_intermediate"),
    ("定食", "Teishoku", "noun", "焼き魚定食。", "Suất ăn, cơm phần", "Cơm phần cá nướng.", "Set ăn", "ja_food_intermediate"),
    ("弁当", "Bentou", "noun", "弁当を作る。", "Cơm hộp", "Làm cơm hộp.", "Hộp đồ ăn", "ja_food_intermediate"),
    ("惣菜", "Souzai", "noun", "スーパーの惣菜。", "Thức ăn chế biến sẵn", "Thức ăn chế biến sẵn ở siêu thị.", "Món ăn nấu sẵn", "ja_food_intermediate"),
    ("おかず", "Okazu", "noun", "今日のおかずは何？", "Đồ ăn kèm với cơm", "Đồ ăn kèm hôm nay là gì?", "Món mặn ăn cùng cơm", "ja_food_intermediate"),
    ("スープ", "Sūpu", "noun", "温かいスープ。", "Súp", "Súp nóng hổi.", "Canh súp tây", "ja_food_intermediate"),
    ("サラダ", "Sarada", "noun", "野菜サラダ。", "Salad", "Salad rau củ.", "Món rau trộn", "ja_food_intermediate"),
    ("デザート", "Dezāto", "noun", "食後のデザート。", "Tráng miệng", "Đồ tráng miệng sau bữa ăn.", "Đồ ngọt cuối bữa", "ja_food_intermediate"),
    ("おやつ", "Oyatsu", "noun", "３時のおやつ。", "Đồ ăn vặt", "Bữa phụ lúc 3 giờ.", "Snack", "ja_food_intermediate"),
    ("居酒屋", "Izakaya", "noun", "居酒屋で飲む。", "Quán nhậu", "Uống rượu ở quán nhậu.", "Quán rượu kiểu Nhật", "ja_food_intermediate"),
    ("注文", "Chuumon", "noun/verb", "ピザを注文する。", "Đặt món, gọi món", "Đặt mua bánh pizza.", "Order đồ ăn", "ja_food_intermediate"),
    ("会計", "Kaikei", "noun", "お会計をお願いします。", "Tính tiền", "Làm ơn tính tiền giúp.", "Thanh toán bữa ăn", "ja_food_intermediate"),
    ("割り勘", "Warikan", "noun", "割り勘にしよう。", "Chia tiền", "Chúng ta cưa đôi tiền nhé.", "Campuchia", "ja_food_intermediate"),
    ("奢る", "Ogoru", "verb", "友達に奢る。", "Đãi, khao", "Mời bạn một bữa.", "Bao tiền", "ja_food_intermediate"),
    ("味が濃い", "Aji ga koi", "adjective", "このスープは味が濃い。", "Vị đậm", "Món súp này có vị đậm.", "Mặn mà", "ja_food_intermediate"),
    ("味が薄い", "Aji ga usui", "adjective", "味が薄いので塩を足す。", "Vị nhạt", "Vị nhạt nên cho thêm muối.", "Lạt lẽo", "ja_food_intermediate"),
    ("しょっぱい", "Shoppai", "adjective", "しょっぱいスープ。", "Mặn", "Món súp bị mặn.", "Vị của muối (gắt)", "ja_food_intermediate"),
    ("新鮮", "Shinsen", "adjective", "新鮮な魚。", "Tươi", "Cá tươi sống.", "Mới mẻ, chưa ươn", "ja_food_intermediate"),
    ("腐る", "Kusaru", "verb", "肉が腐る。", "Ôi thiu, thối", "Thịt bị hỏng rồi.", "Hỏng", "ja_food_intermediate"),
    ("沸かす", "Wakasu", "verb", "お湯を沸かす。", "Đun sôi (nước)", "Đun sôi nước.", "Nấu nước nóng", "ja_food_intermediate"),
    ("焼く", "Yaku", "verb", "肉を焼く。", "Nướng, rán", "Nướng thịt.", "Dùng nhiệt", "ja_food_intermediate"),
    ("煮る", "Niru", "verb", "野菜を煮る。", "Ninh, hầm", "Ninh rau củ.", "Nấu trong nước", "ja_food_intermediate"),

    # Advanced (2)
    ("栄養", "Eiyou", "noun", "栄養のバランスが良い。", "Dinh dưỡng", "Cân bằng dinh dưỡng tốt.", "Chất bổ", "ja_food_advanced"),
    ("カロリー", "Karorī", "noun", "カロリーが高い。", "Calo", "Lượng calo cao.", "Năng lượng thực phẩm", "ja_food_advanced"),
    ("添加物", "Tenkabutsu", "noun", "食品添加物。", "Chất phụ gia", "Phụ gia thực phẩm.", "Chất thêm vào thức ăn", "ja_food_advanced"),
    ("賞味期限", "Shoumi kigen", "noun", "賞味期限が切れる。", "Hạn sử dụng (để ăn ngon)", "Quá hạn sử dụng tốt nhất.", "Hạn dùng (chất lượng)", "ja_food_advanced"),
    ("消費期限", "Shouhi kigen", "noun", "消費期限を確認する。", "Hạn sử dụng (để an toàn)", "Kiểm tra hạn sử dụng an toàn.", "Hạn dùng (vứt bỏ)", "ja_food_advanced"),
    ("有機栽培", "Yuuki saibai", "noun", "有機栽培の野菜。", "Trồng trọt hữu cơ", "Rau củ trồng hữu cơ.", "Canh tác không hóa chất", "ja_food_advanced"),
    ("旬", "Shun", "noun", "旬の食材。", "Mùa (đồ ăn ngon nhất)", "Nguyên liệu đúng mùa vụ.", "Thời điểm ngon nhất", "ja_food_advanced"),
    ("味わう", "Ajiwau", "verb", "料理を味わう。", "Thưởng thức", "Từ từ thưởng thức món ăn.", "Nếm hương vị", "ja_food_advanced"),
    ("香り", "Kaori", "noun", "いい香りがする。", "Mùi hương", "Có mùi hương thơm ngát.", "Mùi thơm thức ăn", "ja_food_advanced"),
    ("食感", "Shokkan", "noun", "サクサクとした食感。", "Kết cấu món ăn", "Kết cấu giòn rụm.", "Cảm giác nhai", "ja_food_advanced"),
    ("歯ごたえ", "Hagotae", "noun", "歯ごたえがある。", "Độ giòn, dai", "Nhai rất giòn dai sần sật.", "Cảm giác khi cắn", "ja_food_advanced"),
    ("喉越し", "Nodogoshi", "noun", "ビールの喉越し。", "Cảm giác trôi qua họng", "Cảm giác bia trôi qua cổ họng.", "Sự êm ái khi nuốt", "ja_food_advanced"),
    ("まろやか", "Maroyaka", "adjective", "まろやかな味。", "Vị dịu, tròn vị", "Hương vị dịu êm.", "Mềm mại", "ja_food_advanced"),
    ("さっぱり", "Sappari", "adjective/adverb", "さっぱりした料理。", "Vị thanh mát", "Món ăn có vị thanh mát.", "Nhẹ nhàng không ngấy", "ja_food_advanced"),
    ("こってり", "Kotteri", "adjective/adverb", "こってりしたラーメン。", "Vị đậm, béo ngậy", "Ramen béo ngậy nước cốt.", "Đậm đặc và béo", "ja_food_advanced"),
    ("発酵", "Hakkou", "noun/verb", "発酵食品。", "Lên men", "Thực phẩm lên men.", "Quá trình ủ vi sinh", "ja_food_advanced"),
    ("熟成", "Jukusei", "noun/verb", "熟成肉。", "Ủ, làm chín", "Thịt ủ tuổi (Dry-aged).", "Làm cho tăng hương vị", "ja_food_advanced"),
    ("蒸す", "Musu", "verb", "餃子を蒸す。", "Hấp", "Hấp bánh xếp.", "Nấu bằng hơi nước", "ja_food_advanced"),
    ("揚げる", "Ageru", "verb", "天ぷらを揚げる。", "Chiên, rán", "Chiên món Tempura.", "Chiên ngập dầu", "ja_food_advanced"),
    ("炒める", "Itameru", "verb", "野菜を炒める。", "Xào", "Xào rau củ.", "Đảo qua dầu", "ja_food_advanced"),
    ("ゆでる", "Yuderu", "verb", "卵をゆでる。", "Luộc", "Luộc quả trứng.", "Nấu trong nước sôi", "ja_food_advanced"),
    ("炊く", "Taku", "verb", "ご飯を炊く。", "Nấu (cơm)", "Nấu cơm.", "Nấu gạo thành cơm", "ja_food_advanced"),
    ("刻む", "Kizamu", "verb", "ネギを刻む。", "Thái nhỏ, băm", "Thái nhỏ hành lá.", "Thái vụn", "ja_food_advanced"),
    ("混ぜる", "Mazeru", "verb", "材料を混ぜる。", "Trộn", "Trộn các nguyên liệu lại.", "Đảo đều", "ja_food_advanced"),
    ("盛り付ける", "Moritsukeru", "verb", "皿に盛り付ける。", "Bày biện món ăn", "Bày thức ăn ra đĩa.", "Xếp lên đĩa", "ja_food_advanced"),
    ("満腹", "Manpuku", "noun", "満腹になる。", "No bụng", "Ăn no căng bụng.", "Bụng đầy thức ăn", "ja_food_advanced"),
    ("空腹", "Kuufuku", "noun", "空腹を覚える。", "Bụng đói", "Cảm thấy bụng đói cồn cào.", "Bụng rỗng", "ja_food_advanced"),
    ("偏食", "Henshoku", "noun/verb", "偏食を直す。", "Chán ăn, kén ăn", "Chữa tật kén ăn.", "Ăn uống thiên lệch", "ja_food_advanced"),
    ("大食い", "Oogui", "noun", "大食いの人。", "Ăn nhiều", "Người ăn khỏe, ăn nhiều.", "Ăn thùng uống vại", "ja_food_advanced"),
    ("拒食症", "Kyoshokushou", "noun", "拒食症の治療。", "Chứng chán ăn", "Điều trị bệnh chán ăn.", "Chứng sợ ăn", "ja_food_advanced"),

    # Expert (3)
    ("美食家", "Bishokuka", "noun", "彼は美食家だ。", "Người sành ăn", "Ông ấy là một người sành ăn.", "Sành sỏi ẩm thực", "ja_food_expert"),
    ("郷土料理", "Kyoudo ryouri", "noun", "その土地の郷土料理。", "Đặc sản địa phương", "Đặc sản ẩm thực của vùng đó.", "Món ăn quê hương", "ja_food_expert"),
    ("懐石料理", "Kaiseki ryouri", "noun", "懐石料理をいただく。", "Ẩm thực Kaiseki", "Thưởng thức bữa tiệc Kaiseki.", "Bữa ăn truyền thống trang trọng", "ja_food_expert"),
    ("精進料理", "Shoujin ryouri", "noun", "お寺で精進料理を食べる。", "Đồ chay", "Ăn đồ chay tại chùa.", "Ẩm thực Phật giáo", "ja_food_expert"),
    ("B級グルメ", "Bī-kyuu gurume", "noun", "B級グルメを楽しむ。", "Ẩm thực bình dân", "Tận hưởng những món ăn bình dân ngon.", "Đồ ăn rẻ mà ngon", "ja_food_expert"),
    ("食糧危機", "Shokuryou kiki", "noun", "食糧危機が懸念される。", "Khủng hoảng lương thực", "Lo ngại về khủng hoảng lương thực.", "Thiếu thức ăn toàn cầu", "ja_food_expert"),
    ("食品ロス", "Shokuhin rosu", "noun", "食品ロスを減らす。", "Lãng phí thực phẩm", "Giảm thiểu lượng thức ăn bị vứt bỏ.", "Đồ ăn thừa bị bỏ", "ja_food_expert"),
    ("自給率", "Jikyuuritsu", "noun", "食料自給率。", "Tỉ lệ tự cung tự cấp", "Tỉ lệ tự cung tự cấp lương thực.", "Mức tự sản xuất", "ja_food_expert"),
    ("遺伝子組み換え", "Idenshi kumikae", "noun", "遺伝子組み換え食品。", "Biến đổi gen", "Thực phẩm biến đổi gen (GMO).", "GMO", "ja_food_expert"),
    ("人工肉", "Jinkouniku", "noun", "人工肉の開発。", "Thịt nhân tạo", "Phát triển các loại thịt nhân tạo.", "Thịt giả", "ja_food_expert"),
    ("培養肉", "Baiyouniku", "noun", "培養肉の研究。", "Thịt nuôi cấy", "Nghiên cứu về thịt nuôi cấy trong phòng thí nghiệm.", "Thịt tế bào gốc", "ja_food_expert"),
    ("昆虫食", "Konchuushoku", "noun", "昆虫食が注目される。", "Ăn côn trùng", "Xu hướng ăn côn trùng đang được chú ý.", "Món ăn từ sâu bọ", "ja_food_expert"),
    ("フードテック", "Fūdotekku", "noun", "フードテックの企業。", "Công nghệ thực phẩm", "Doanh nghiệp trong ngành công nghệ thực phẩm.", "FoodTech", "ja_food_expert"),
    ("栄養失調", "Eiyou shicchou", "noun", "栄養失調で倒れる。", "Suy dinh dưỡng", "Ngã gục vì suy dinh dưỡng.", "Thiếu chất", "ja_food_expert"),
    ("糖尿病", "Tounyoubyou", "noun", "糖尿病の食事療法。", "Bệnh tiểu đường", "Ăn kiêng trị liệu cho bệnh tiểu đường.", "Tiểu ra đường", "ja_food_expert"),
    ("痛風", "Tsuufuu", "noun", "痛風の原因。", "Bệnh gout", "Nguyên nhân gây ra bệnh gout.", "Bệnh nhà giàu", "ja_food_expert"),
    ("食中毒", "Shokuchuudoku", "noun", "食中毒になる。", "Ngộ độc thực phẩm", "Bị ngộ độc thực phẩm.", "Trúng độc thức ăn", "ja_food_expert"),
    ("アナフィラキシー", "Anafirakishī", "noun", "アナフィラキシーショック。", "Sốc phản vệ", "Bị sốc phản vệ do dị ứng đồ ăn.", "Phản ứng dị ứng cấp", "ja_food_expert"),
    ("ビーガン", "Bīgan", "noun", "ビーガンのレストラン。", "Thuần chay (Vegan)", "Nhà hàng dành cho người thuần chay.", "Không dùng sản phẩm động vật", "ja_food_expert"),
    ("ハラール", "Harāru", "noun", "ハラール認証。", "Chứng nhận Halal", "Chứng nhận Halal cho thực phẩm Hồi giáo.", "Đồ ăn đạo Hồi", "ja_food_expert"),
    ("グルテンフリー", "Gurutenfurī", "noun", "グルテンフリーのパン。", "Không chứa gluten", "Bánh mì không chứa gluten.", "Dành cho người dị ứng lúa mì", "ja_food_expert"),
    ("糖質制限", "Toushitsu seigen", "noun", "糖質制限ダイエット。", "Hạn chế tinh bột", "Chế độ ăn kiêng cắt giảm tinh bột/đường.", "Low-carb diet", "ja_food_expert"),
    ("旨味", "Umami", "noun", "昆布の旨味。", "Vị umami", "Vị ngon ngọt thanh của tảo bẹ kelp.", "Ngọt thịt tự nhiên", "ja_food_expert"),
    ("渋み", "Shibumi", "noun", "お茶の渋み。", "Vị chát", "Vị chát của lá trà.", "Hơi tê lưỡi", "ja_food_expert"),
    ("えぐみ", "Egumi", "noun", "アクのえぐみ。", "Vị gắt, hăng", "Vị hăng gắt của nhựa cây hay bọt luộc thịt.", "Vị khó chịu", "ja_food_expert"),
    ("隠し味", "Kakushiaji", "noun", "隠し味に醤油を入れる。", "Gia vị bí mật", "Thêm một chút nước tương làm gia vị bí mật.", "Hương vị ẩn giấu", "ja_food_expert"),
    ("出汁", "Dashi", "noun", "鰹節で出汁をとる。", "Nước dùng (Nhật)", "Nấu nước dùng Dashi từ cá ngừ bào.", "Nước cốt hầm", "ja_food_expert"),
    ("とろみ", "Toromi", "noun", "スープにとろみをつける。", "Độ sệt", "Làm cho món súp có độ sệt quánh lại.", "Độ sánh", "ja_food_expert"),
    ("下ごしらえ", "Shitahoshirae", "noun/verb", "肉の下ごしらえをする。", "Sơ chế", "Làm sơ chế ướp gia vị cho thịt.", "Chuẩn bị nấu", "ja_food_expert"),
    ("盛り付け", "Moritsuke", "noun", "盛り付けが美しい。", "Bày trí đồ ăn", "Cách bày trí món ăn trên đĩa rất đẹp.", "Trình bày món ăn", "ja_food_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_ja, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "ja",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_ja,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Weather & Food - Japanese) to DB!")
