import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Family
    {"id": "zh_family_beginner", "languageCode": "zh", "title": "家庭", "subtitle": "Gia đình - Beginner", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Beginner", "colorHex": "#10B981", "cardCount": 30},
    {"id": "zh_family_intermediate", "languageCode": "zh", "title": "家庭", "subtitle": "Gia đình - Intermediate", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Intermediate", "colorHex": "#059669", "cardCount": 30},
    {"id": "zh_family_advanced", "languageCode": "zh", "title": "家庭", "subtitle": "Gia đình - Advanced", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Advanced", "colorHex": "#047857", "cardCount": 30},
    {"id": "zh_family_expert", "languageCode": "zh", "title": "家庭", "subtitle": "Gia đình - Expert", "iconEmoji": "👨‍👩‍👧‍👦", "level": "Expert", "colorHex": "#065F46", "cardCount": 30},
    
    # Shopping
    {"id": "zh_shopping_beginner", "languageCode": "zh", "title": "购物", "subtitle": "Mua sắm - Beginner", "iconEmoji": "🛒", "level": "Beginner", "colorHex": "#F59E0B", "cardCount": 30},
    {"id": "zh_shopping_intermediate", "languageCode": "zh", "title": "购物", "subtitle": "Mua sắm - Intermediate", "iconEmoji": "🛒", "level": "Intermediate", "colorHex": "#D97706", "cardCount": 30},
    {"id": "zh_shopping_advanced", "languageCode": "zh", "title": "购物", "subtitle": "Mua sắm - Advanced", "iconEmoji": "🛒", "level": "Advanced", "colorHex": "#B45309", "cardCount": 30},
    {"id": "zh_shopping_expert", "languageCode": "zh", "title": "购物", "subtitle": "Mua sắm - Expert", "iconEmoji": "🛒", "level": "Expert", "colorHex": "#92400E", "cardCount": 30}
]

vocab_data = [
    # ---- FAMILY ----
    # Beginner (0)
    ("家", "Jiā", "noun", "我的家。", "Nhà, gia đình", "Nhà của tôi.", "Home", "zh_family_beginner"),
    ("家人", "Jiārén", "noun", "我的家人。", "Người nhà", "Người nhà của tôi.", "Family member", "zh_family_beginner"),
    ("爸爸", "Bàba", "noun", "爸爸去上班。", "Bố", "Bố đi làm.", "Dad", "zh_family_beginner"),
    ("妈妈", "Māma", "noun", "妈妈做饭。", "Mẹ", "Mẹ nấu ăn.", "Mom", "zh_family_beginner"),
    ("哥哥", "Gēge", "noun", "我哥哥。", "Anh trai", "Anh trai tôi.", "Older brother", "zh_family_beginner"),
    ("姐姐", "Jiějie", "noun", "我姐姐。", "Chị gái", "Chị gái tôi.", "Older sister", "zh_family_beginner"),
    ("弟弟", "Dìdi", "noun", "我弟弟。", "Em trai", "Em trai tôi.", "Younger brother", "zh_family_beginner"),
    ("妹妹", "Mèimei", "noun", "我妹妹。", "Em gái", "Em gái tôi.", "Younger sister", "zh_family_beginner"),
    ("爷爷", "Yéye", "noun", "爷爷喝茶。", "Ông nội", "Ông nội uống trà.", "Grandpa", "zh_family_beginner"),
    ("奶奶", "Nǎinai", "noun", "奶奶看电视。", "Bà nội", "Bà nội xem tivi.", "Grandma", "zh_family_beginner"),
    ("丈夫", "Zhàngfu", "noun", "她的丈夫。", "Chồng", "Chồng cô ấy.", "Husband", "zh_family_beginner"),
    ("妻子", "Qīzi", "noun", "他的妻子。", "Vợ", "Vợ anh ấy.", "Wife", "zh_family_beginner"),
    ("儿子", "Érzi", "noun", "我儿子。", "Con trai", "Con trai tôi.", "Son", "zh_family_beginner"),
    ("女儿", "Nǚ'ér", "noun", "我女儿。", "Con gái", "Con gái tôi.", "Daughter", "zh_family_beginner"),
    ("孩子", "Háizi", "noun", "好孩子。", "Đứa trẻ", "Đứa bé ngoan.", "Child", "zh_family_beginner"),
    ("爱", "Ài", "verb", "我爱你。", "Yêu", "Anh yêu em.", "Love", "zh_family_beginner"),
    ("喜欢", "Xǐhuan", "verb", "喜欢家人。", "Thích", "Thích người nhà.", "Like", "zh_family_beginner"),
    ("叫", "Jiào", "verb", "叫妈妈。", "Gọi", "Gọi mẹ.", "Call", "zh_family_beginner"),
    ("帮", "Bāng", "verb", "帮妈妈。", "Giúp đỡ", "Giúp mẹ.", "Help", "zh_family_beginner"),
    ("笑", "Xiào", "verb", "孩子笑了。", "Cười", "Đứa bé cười rồi.", "Smile", "zh_family_beginner"),
    ("哭", "Kū", "verb", "弟弟哭了。", "Khóc", "Em trai khóc rồi.", "Cry", "zh_family_beginner"),
    ("抱", "Bào", "verb", "抱孩子。", "Ôm", "Bế/ôm đứa bé.", "Hug", "zh_family_beginner"),
    ("亲", "Qīn", "verb", "亲一下。", "Hôn", "Hôn một cái.", "Kiss", "zh_family_beginner"),
    ("男", "Nán", "adjective/noun", "男孩。", "Nam", "Con trai.", "Male", "zh_family_beginner"),
    ("女", "Nǚ", "adjective/noun", "女孩。", "Nữ", "Con gái.", "Female", "zh_family_beginner"),
    ("老", "Lǎo", "adjective", "老人。", "Già", "Người già.", "Old", "zh_family_beginner"),
    ("小", "Xiǎo", "adjective", "小孩子。", "Nhỏ", "Đứa trẻ nhỏ.", "Small", "zh_family_beginner"),
    ("大", "Dà", "adjective", "大哥。", "Lớn", "Anh cả.", "Big", "zh_family_beginner"),
    ("高", "Gāo", "adjective", "爸爸很高。", "Cao", "Bố rất cao.", "Tall", "zh_family_beginner"),
    ("胖", "Pàng", "adjective", "弟弟很胖。", "Béo", "Em trai rất béo.", "Fat", "zh_family_beginner"),

    # Intermediate (1)
    ("父母", "Fùmǔ", "noun", "尊敬父母。", "Bố mẹ", "Tôn trọng bố mẹ.", "Parents", "zh_family_intermediate"),
    ("兄弟", "Xiōngdì", "noun", "亲兄弟。", "Anh em", "Anh em ruột.", "Brothers", "zh_family_intermediate"),
    ("姐妹", "Jiěmèi", "noun", "好姐妹。", "Chị em", "Chị em tốt.", "Sisters", "zh_family_intermediate"),
    ("亲戚", "Qīnqi", "noun", "走亲戚。", "Họ hàng", "Đi thăm họ hàng.", "Relative", "zh_family_intermediate"),
    ("叔叔", "Shūshu", "noun", "叔叔好。", "Chú", "Chào chú.", "Uncle", "zh_family_intermediate"),
    ("阿姨", "Āyí", "noun", "阿姨好。", "Dì, cô", "Chào dì.", "Aunt", "zh_family_intermediate"),
    ("姑姑", "Gūgu", "noun", "我的姑姑。", "Cô", "Cô của tôi (chị em của bố).", "Paternal aunt", "zh_family_intermediate"),
    ("舅舅", "Jiùjiu", "noun", "我的舅舅。", "Cậu", "Cậu của tôi (anh em của mẹ).", "Maternal uncle", "zh_family_intermediate"),
    ("外公", "Wàigōng", "noun", "外公外婆。", "Ông ngoại", "Ông bà ngoại.", "Maternal grandpa", "zh_family_intermediate"),
    ("外婆", "Wàipó", "noun", "外婆家。", "Bà ngoại", "Nhà bà ngoại.", "Maternal grandma", "zh_family_intermediate"),
    ("孙子", "Sūnzi", "noun", "抱孙子。", "Cháu trai", "Bế cháu trai (nội).", "Grandson", "zh_family_intermediate"),
    ("孙女", "Sūnnǚ", "noun", "可爱的孙女。", "Cháu gái", "Cháu gái đáng yêu (nội).", "Granddaughter", "zh_family_intermediate"),
    ("结婚", "Jiéhūn", "verb", "他们结婚了。", "Kết hôn", "Họ kết hôn rồi.", "Marry", "zh_family_intermediate"),
    ("离婚", "Líhūn", "verb", "父母离婚了。", "Ly hôn", "Bố mẹ đã ly hôn.", "Divorce", "zh_family_intermediate"),
    ("恋爱", "Liàn'ài", "noun/verb", "谈恋爱。", "Yêu đương", "Đang yêu nhau.", "Love", "zh_family_intermediate"),
    ("吵架", "Chǎojià", "verb", "夫妻吵架。", "Cãi nhau", "Vợ chồng cãi nhau.", "Quarrel", "zh_family_intermediate"),
    ("原谅", "Yuánliàng", "verb", "请原谅我。", "Tha thứ", "Xin hãy tha thứ cho tôi.", "Forgive", "zh_family_intermediate"),
    ("照顾", "Zhàogù", "verb", "照顾老人。", "Chăm sóc", "Chăm sóc người già.", "Take care", "zh_family_intermediate"),
    ("陪伴", "Péibàn", "verb", "陪伴孩子。", "Bầu bạn", "Bên cạnh con cái.", "Accompany", "zh_family_intermediate"),
    ("分享", "Fēnxiǎng", "verb", "分享快乐。", "Chia sẻ", "Chia sẻ niềm vui.", "Share", "zh_family_intermediate"),
    ("责任", "Zérèn", "noun", "家庭责任。", "Trách nhiệm", "Trách nhiệm gia đình.", "Responsibility", "zh_family_intermediate"),
    ("幸福", "Xìngfú", "adjective/noun", "幸福的家庭。", "Hạnh phúc", "Gia đình hạnh phúc.", "Happy", "zh_family_intermediate"),
    ("温暖", "Wēnnuǎn", "adjective", "温暖的家。", "Ấm áp", "Ngôi nhà ấm áp.", "Warm", "zh_family_intermediate"),
    ("热闹", "Rènao", "adjective", "家里很热闹。", "Náo nhiệt", "Trong nhà rất náo nhiệt.", "Lively", "zh_family_intermediate"),
    ("安静", "Ānjìng", "adjective", "孩子睡了，很安静。", "Yên tĩnh", "Con ngủ rồi, rất yên tĩnh.", "Quiet", "zh_family_intermediate"),
    ("乖", "Guāi", "adjective", "孩子很乖。", "Ngoan", "Đứa trẻ rất ngoan.", "Well-behaved", "zh_family_intermediate"),
    ("淘气", "Táoqì", "adjective", "淘气的弟弟。", "Nghịch ngợm", "Cậu em trai nghịch ngợm.", "Naughty", "zh_family_intermediate"),
    ("孝顺", "Xiàoshùn", "adjective/verb", "孝顺父母。", "Có hiếu", "Hiếu thảo với bố mẹ.", "Filial", "zh_family_intermediate"),
    ("严厉", "Yánlì", "adjective", "爸爸很严厉。", "Nghiêm khắc", "Bố rất nghiêm khắc.", "Strict", "zh_family_intermediate"),
    ("慈祥", "Cíxiáng", "adjective", "慈祥的奶奶。", "Hiền từ", "Bà nội hiền từ.", "Kindly", "zh_family_intermediate"),

    # Advanced (2)
    ("婚姻", "Hūnyīn", "noun", "幸福的婚姻。", "Hôn nhân", "Cuộc hôn nhân hạnh phúc.", "Marriage", "zh_family_advanced"),
    ("伴侣", "Bànlǚ", "noun", "终身伴侣。", "Bạn đời", "Người bạn đời.", "Partner", "zh_family_advanced"),
    ("婆婆", "Pópo", "noun", "婆媳关系。", "Mẹ chồng", "Mối quan hệ mẹ chồng nàng dâu.", "Mother-in-law", "zh_family_advanced"),
    ("公公", "Gōnggong", "noun", "我的公公。", "Bố chồng", "Bố chồng tôi.", "Father-in-law", "zh_family_advanced"),
    ("岳父", "Yuèfù", "noun", "拜见岳父。", "Bố vợ", "Bái kiến bố vợ.", "Father-in-law", "zh_family_advanced"),
    ("岳母", "Yuèmǔ", "noun", "岳母大人。", "Mẹ vợ", "Mẹ vợ đại nhân.", "Mother-in-law", "zh_family_advanced"),
    ("嫂子", "Sǎozi", "noun", "我的嫂子。", "Chị dâu", "Chị dâu của tôi.", "Sister-in-law", "zh_family_advanced"),
    ("弟妹", "Dìmèi", "noun", "弟妹很贤惠。", "Em dâu", "Em dâu rất hiền thục.", "Sister-in-law", "zh_family_advanced"),
    ("姐夫", "Jiěfu", "noun", "我的姐夫。", "Anh rể", "Anh rể của tôi.", "Brother-in-law", "zh_family_advanced"),
    ("妹夫", "Mèifu", "noun", "我的妹夫。", "Em rể", "Em rể của tôi.", "Brother-in-law", "zh_family_advanced"),
    ("侄子", "Zhízi", "noun", "侄子很聪明。", "Cháu trai (con anh/em trai)", "Cháu trai rất thông minh.", "Nephew", "zh_family_advanced"),
    ("侄女", "Zhínǚ", "noun", "漂亮的侄女。", "Cháu gái (con anh/em trai)", "Cháu gái xinh đẹp.", "Niece", "zh_family_advanced"),
    ("外甥", "Wàishēng", "noun", "我的外甥。", "Cháu trai (con chị/em gái)", "Cháu trai của tôi.", "Nephew", "zh_family_advanced"),
    ("外甥女", "Wàishēngnǚ", "noun", "我的外甥女。", "Cháu gái (con chị/em gái)", "Cháu gái của tôi.", "Niece", "zh_family_advanced"),
    ("抚养", "Fǔyǎng", "verb", "抚养孩子。", "Nuôi dưỡng", "Nuôi dưỡng con cái.", "Raise", "zh_family_advanced"),
    ("赡养", "Shànyǎng", "verb", "赡养父母。", "Phụng dưỡng", "Phụng dưỡng cha mẹ.", "Support", "zh_family_advanced"),
    ("继承", "Jìchéng", "verb", "继承遗产。", "Kế thừa", "Thừa kế di sản.", "Inherit", "zh_family_advanced"),
    ("团聚", "Tuánjù", "verb", "中秋节团聚。", "Đoàn tụ", "Đoàn tụ vào Tết Trung Thu.", "Reunite", "zh_family_advanced"),
    ("沟通", "Gōutōng", "verb", "缺乏沟通。", "Giao tiếp", "Thiếu sự giao tiếp.", "Communicate", "zh_family_advanced"),
    ("体谅", "Tǐliàng", "verb", "互相体谅。", "Cảm thông", "Cảm thông cho nhau.", "Considerate", "zh_family_advanced"),
    ("依赖", "Yīlài", "verb", "依赖父母。", "Dựa dẫm", "Phụ thuộc vào bố mẹ.", "Rely on", "zh_family_advanced"),
    ("独立", "Dúlì", "adjective/verb", "独立生活。", "Độc lập", "Sống tự lập.", "Independent", "zh_family_advanced"),
    ("宠爱", "Chǒng'ài", "verb", "宠爱孩子。", "Nuông chiều", "Yêu chiều con cái.", "Dote on", "zh_family_advanced"),
    ("溺爱", "Nì'ài", "verb", "溺爱是不好的。", "Nuông chiều thái quá", "Làm hư con là không tốt.", "Spoil", "zh_family_advanced"),
    ("叛逆", "Pànnì", "adjective/verb", "叛逆期。", "Nổi loạn", "Thời kỳ nổi loạn.", "Rebellious", "zh_family_advanced"),
    ("融洽", "Róngqià", "adjective", "关系融洽。", "Hòa thuận", "Mối quan hệ hòa hợp.", "Harmonious", "zh_family_advanced"),
    ("隔阂", "Géhé", "noun", "消除隔阂。", "Khoảng cách, bất hòa", "Xóa bỏ rào cản.", "Estrangement", "zh_family_advanced"),
    ("矛盾", "Máodùn", "noun", "家庭矛盾。", "Mâu thuẫn", "Mâu thuẫn gia đình.", "Conflict", "zh_family_advanced"),
    ("代沟", "Dàigōu", "noun", "有代沟。", "Khoảng cách thế hệ", "Có khoảng cách thế hệ.", "Generation gap", "zh_family_advanced"),
    ("基因", "Jīyīn", "noun", "遗传基因。", "Gen", "Gen di truyền.", "Gene", "zh_family_advanced"),

    # Expert (3)
    ("伦理", "Lúnlǐ", "noun", "家庭伦理。", "Luân lý", "Đạo đức gia đình.", "Ethics", "zh_family_expert"),
    ("家规", "Jiāguī", "noun", "遵守家规。", "Gia quy", "Tuân thủ gia quy.", "Family rules", "zh_family_expert"),
    ("家训", "Jiāxùn", "noun", "传承家训。", "Gia huấn", "Truyền lại những lời dạy của gia đình.", "Family precept", "zh_family_expert"),
    ("门风", "Ménfēng", "noun", "门风严谨。", "Gia phong", "Gia phong nghiêm ngặt.", "Family tradition", "zh_family_expert"),
    ("血缘", "Xuèyuán", "noun", "血缘关系。", "Huyết thống", "Quan hệ ruột thịt.", "Blood tie", "zh_family_expert"),
    ("嫡系", "Díxì", "noun", "嫡系亲属。", "Đích tôn, dòng chính", "Họ hàng dòng chính.", "Direct descent", "zh_family_expert"),
    ("旁系", "Pángxì", "noun", "旁系亲属。", "Dòng bàng hệ", "Họ hàng nhánh phụ.", "Collateral relative", "zh_family_expert"),
    ("晚辈", "Wǎnbèi", "noun", "关爱晚辈。", "Bậc hậu bối", "Quan tâm đến lớp con cháu.", "Younger generation", "zh_family_expert"),
    ("长辈", "Zhǎngbèi", "noun", "尊敬长辈。", "Bậc tiền bối", "Tôn trọng người lớn tuổi.", "Elder generation", "zh_family_expert"),
    ("同辈", "Tóngbèi", "noun", "同辈之间。", "Người cùng thế hệ", "Giữa những người cùng lứa.", "Same generation", "zh_family_expert"),
    ("丧偶", "Sàng'ǒu", "verb", "丧偶老人。", "Góa bụa", "Người già mất vợ/chồng.", "Widowed", "zh_family_expert"),
    ("继父", "Jìfù", "noun", "我的继父。", "Bố dượng", "Bố dượng của tôi.", "Stepfather", "zh_family_expert"),
    ("继母", "Jìmǔ", "noun", "我的继母。", "Mẹ kế", "Mẹ kế của tôi.", "Stepmother", "zh_family_expert"),
    ("领养", "Lǐngyǎng", "verb", "领养孤儿。", "Nhận nuôi", "Nhận nuôi trẻ mồ côi.", "Adopt", "zh_family_expert"),
    ("寄养", "Jìyǎng", "verb", "寄养家庭。", "Gửi nuôi", "Gia đình nhận nuôi tạm.", "Foster", "zh_family_expert"),
    ("监护人", "Jiānhùrén", "noun", "法定监护人。", "Người giám hộ", "Người giám hộ hợp pháp.", "Guardian", "zh_family_expert"),
    ("抚养权", "Fǔyǎngquán", "noun", "争夺抚养权。", "Quyền nuôi dưỡng", "Giành quyền nuôi con.", "Custody", "zh_family_expert"),
    ("探视权", "Tànshìquán", "noun", "行使探视权。", "Quyền thăm viếng", "Thực hiện quyền thăm con.", "Visitation rights", "zh_family_expert"),
    ("赡养费", "Shànyǎngfèi", "noun", "支付赡养费。", "Tiền cấp dưỡng", "Trả tiền cấp dưỡng.", "Alimony", "zh_family_expert"),
    ("财产分割", "Cáichǎn fēngē", "noun", "离婚财产分割。", "Phân chia tài sản", "Chia tài sản ly hôn.", "Property division", "zh_family_expert"),
    ("遗嘱", "Yízhǔ", "noun", "立遗嘱。", "Di chúc", "Lập di chúc.", "Will", "zh_family_expert"),
    ("丁克", "Dīngkè", "noun", "丁克家庭。", "Gia đình DINK", "Gia đình không sinh con.", "DINK", "zh_family_expert"),
    ("空巢", "Kōngcháo", "noun", "空巢老人。", "Tổ ấm trống vắng", "Người già sống cô đơn (con xa nhà).", "Empty nest", "zh_family_expert"),
    ("啃老", "Kěnlǎo", "verb", "啃老族。", "Ăn bám bố mẹ", "Thanh niên ăn bám.", "Boomerang child", "zh_family_expert"),
    ("丧偶式育儿", "Sàng'ǒu shì yù'ér", "noun", "丧偶式育儿的困境。", "Nuôi con một mình", "Hoàn cảnh nuôi con như góa bụa.", "Widowed-style parenting", "zh_family_expert"),
    ("原生家庭", "Yuánshēng jiātíng", "noun", "原生家庭的影响。", "Gia đình gốc", "Ảnh hưởng từ gia đình mình sinh ra.", "Family of origin", "zh_family_expert"),
    ("重男轻女", "Zhòngnán qīngnǚ", "idiom", "重男轻女的观念。", "Trọng nam khinh nữ", "Tư tưởng trọng nam khinh nữ.", "Favor boys over girls", "zh_family_expert"),
    ("传宗接代", "Chuánzōng jiēdài", "idiom", "传宗接代的思想。", "Nối dõi tông đường", "Tư tưởng sinh con trai nối dõi.", "Carry on family line", "zh_family_expert"),
    ("天伦之乐", "Tiānlún zhī lè", "idiom", "享受天伦之乐。", "Thú vui sum vầy", "Hưởng thú vui gia đình đoàn tụ.", "Family happiness", "zh_family_expert"),
    ("望子成龙", "Wàngzǐ chénglóng", "idiom", "望子成龙的心态。", "Mong con thành tài", "Tâm lý hy vọng con cái thành đạt.", "Expect son to succeed", "zh_family_expert"),

    # ---- SHOPPING ----
    # Beginner (0)
    ("买", "Mǎi", "verb", "买东西。", "Mua", "Mua đồ.", "Buy", "zh_shopping_beginner"),
    ("卖", "Mài", "verb", "卖衣服。", "Bán", "Bán quần áo.", "Sell", "zh_shopping_beginner"),
    ("钱", "Qián", "noun", "多少钱？", "Tiền", "Bao nhiêu tiền?", "Money", "zh_shopping_beginner"),
    ("贵", "Guì", "adjective", "太贵了。", "Đắt", "Đắt quá.", "Expensive", "zh_shopping_beginner"),
    ("便宜", "Piányi", "adjective", "很便宜。", "Rẻ", "Rất rẻ.", "Cheap", "zh_shopping_beginner"),
    ("商店", "Shāngdiàn", "noun", "去商店。", "Cửa hàng", "Đi đến cửa hàng.", "Store", "zh_shopping_beginner"),
    ("市场", "Shìchǎng", "noun", "菜市场。", "Chợ", "Chợ rau.", "Market", "zh_shopping_beginner"),
    ("超市", "Chāoshì", "noun", "去超市买菜。", "Siêu thị", "Đi siêu thị mua rau.", "Supermarket", "zh_shopping_beginner"),
    ("东西", "Dōngxi", "noun", "买东西。", "Đồ vật, hàng hóa", "Mua đồ.", "Thing", "zh_shopping_beginner"),
    ("水果", "Shuǐguǒ", "noun", "买水果。", "Hoa quả", "Mua trái cây.", "Fruit", "zh_shopping_beginner"),
    ("苹果", "Píngguǒ", "noun", "买苹果。", "Quả táo", "Mua quả táo.", "Apple", "zh_shopping_beginner"),
    ("衣服", "Yīfu", "noun", "买衣服。", "Quần áo", "Mua quần áo.", "Clothes", "zh_shopping_beginner"),
    ("鞋", "Xié", "noun", "一双鞋。", "Giày", "Một đôi giày.", "Shoe", "zh_shopping_beginner"),
    ("包", "Bāo", "noun", "买个包。", "Túi xách", "Mua một cái túi.", "Bag", "zh_shopping_beginner"),
    ("手机", "Shǒujī", "noun", "新手机。", "Điện thoại", "Điện thoại mới.", "Mobile phone", "zh_shopping_beginner"),
    ("块", "Kuài", "measure word", "十块钱。", "Đồng, tệ", "Mười đồng.", "Yuan (buck)", "zh_shopping_beginner"),
    ("毛", "Máo", "measure word", "五毛钱。", "Hào", "Năm hào.", "Mao (cent)", "zh_shopping_beginner"),
    ("百", "Bǎi", "number", "一百块。", "Trăm", "Một trăm tệ.", "Hundred", "zh_shopping_beginner"),
    ("千", "Qiān", "number", "两千块。", "Nghìn", "Hai nghìn tệ.", "Thousand", "zh_shopping_beginner"),
    ("万", "Wàn", "number", "一万块。", "Mười nghìn (vạn)", "Một vạn tệ.", "Ten thousand", "zh_shopping_beginner"),
    ("多少", "Duōshao", "pronoun", "多少钱？", "Bao nhiêu", "Bao nhiêu tiền?", "How much", "zh_shopping_beginner"),
    ("找", "Zhǎo", "verb", "找你钱。", "Trả lại", "Thối lại bạn tiền.", "Give change", "zh_shopping_beginner"),
    ("给", "Gěi", "verb", "给你钱。", "Đưa cho", "Đưa bạn tiền.", "Give", "zh_shopping_beginner"),
    ("要", "Yào", "verb", "我要这个。", "Muốn, cần", "Tôi muốn cái này.", "Want", "zh_shopping_beginner"),
    ("看看", "Kànkan", "verb", "我随便看看。", "Xem thử", "Tôi chỉ xem thử thôi.", "Look", "zh_shopping_beginner"),
    ("试", "Shì", "verb", "试一下。", "Thử", "Thử một chút.", "Try", "zh_shopping_beginner"),
    ("好看", "Hǎokàn", "adjective", "这件很好看。", "Đẹp", "Cái này rất đẹp.", "Good-looking", "zh_shopping_beginner"),
    ("喜欢", "Xǐhuan", "verb", "喜欢这个。", "Thích", "Thích cái này.", "Like", "zh_shopping_beginner"),
    ("收", "Shōu", "verb", "收钱。", "Nhận, thu", "Thu tiền.", "Receive", "zh_shopping_beginner"),
    ("现金", "Xiànjīn", "noun", "用现金。", "Tiền mặt", "Dùng tiền mặt.", "Cash", "zh_shopping_beginner"),

    # Intermediate (1)
    ("顾客", "Gùkè", "noun", "欢迎顾客。", "Khách hàng", "Hoan nghênh khách hàng.", "Customer", "zh_shopping_intermediate"),
    ("售货员", "Shòuhuòyuán", "noun", "问售货员。", "Nhân viên bán hàng", "Hỏi nhân viên bán hàng.", "Salesperson", "zh_shopping_intermediate"),
    ("营业员", "Yíngyèyuán", "noun", "营业员态度好。", "Nhân viên giao dịch", "Nhân viên thái độ tốt.", "Clerk", "zh_shopping_intermediate"),
    ("老板", "Lǎobǎn", "noun", "问老板。", "Ông chủ", "Hỏi ông chủ.", "Boss", "zh_shopping_intermediate"),
    ("价格", "Jiàgé", "noun", "价格合理。", "Giá cả", "Giá cả hợp lý.", "Price", "zh_shopping_intermediate"),
    ("定价", "Dìngjià", "noun/verb", "商品定价。", "Định giá", "Định giá sản phẩm.", "Pricing", "zh_shopping_intermediate"),
    ("打折", "Dǎzhé", "verb", "打八折。", "Giảm giá", "Giảm giá 20% (bán bằng 8 phần).", "Discount", "zh_shopping_intermediate"),
    ("降价", "Jiàngjià", "verb", "手机降价了。", "Giảm giá", "Điện thoại giảm giá rồi.", "Price drop", "zh_shopping_intermediate"),
    ("涨价", "Zhǎngjià", "verb", "蔬菜涨价了。", "Tăng giá", "Rau tăng giá rồi.", "Price rise", "zh_shopping_intermediate"),
    ("讨价还价", "Tǎojià huánjià", "idiom", "和老板讨价还价。", "Mặc cả", "Mặc cả với ông chủ.", "Bargain", "zh_shopping_intermediate"),
    ("质量", "Zhìliàng", "noun", "质量很好。", "Chất lượng", "Chất lượng rất tốt.", "Quality", "zh_shopping_intermediate"),
    ("品牌", "Pǐnpái", "noun", "知名品牌。", "Thương hiệu", "Thương hiệu nổi tiếng.", "Brand", "zh_shopping_intermediate"),
    ("款式", "Kuǎnshì", "noun", "最新款式。", "Kiểu dáng", "Mẫu mã mới nhất.", "Style", "zh_shopping_intermediate"),
    ("尺码", "Chǐmǎ", "noun", "尺码合适。", "Kích cỡ", "Kích cỡ phù hợp.", "Size", "zh_shopping_intermediate"),
    ("试衣间", "Shìyījiān", "noun", "去试衣间。", "Phòng thử đồ", "Vào phòng thay đồ.", "Fitting room", "zh_shopping_intermediate"),
    ("包装", "Bāozhuāng", "noun/verb", "精美包装。", "Bao bì", "Đóng gói đẹp mắt.", "Packaging", "zh_shopping_intermediate"),
    ("购物", "Gòuwù", "noun/verb", "购物中心。", "Mua sắm", "Trung tâm mua sắm.", "Shopping", "zh_shopping_intermediate"),
    ("商场", "Shāngchǎng", "noun", "逛商场。", "Trung tâm thương mại", "Đi dạo TTTM.", "Mall", "zh_shopping_intermediate"),
    ("逛街", "Guàngjiē", "verb", "周末逛街。", "Đi dạo phố", "Cuối tuần đi dạo mua sắm.", "Go shopping", "zh_shopping_intermediate"),
    ("结账", "Jiézhàng", "verb", "去前台结账。", "Tính tiền", "Ra quầy tính tiền.", "Checkout", "zh_shopping_intermediate"),
    ("发票", "Fāpiào", "noun", "开一张发票。", "Hóa đơn", "Xuất một tờ hóa đơn đỏ.", "Invoice", "zh_shopping_intermediate"),
    ("收据", "Shōujù", "noun", "拿好收据。", "Biên lai", "Cầm kỹ biên lai.", "Receipt", "zh_shopping_intermediate"),
    ("信用卡", "Xìnyòngkǎ", "noun", "刷信用卡。", "Thẻ tín dụng", "Quẹt thẻ tín dụng.", "Credit card", "zh_shopping_intermediate"),
    ("刷卡", "Shuākǎ", "verb", "可以刷卡吗？", "Quẹt thẻ", "Có thể quẹt thẻ không?", "Swipe card", "zh_shopping_intermediate"),
    ("扫码", "Sǎomǎ", "verb", "扫码支付。", "Quét mã", "Quét mã thanh toán.", "Scan code", "zh_shopping_intermediate"),
    ("退货", "Tuìhuò", "verb", "不满意可以退货。", "Trả hàng", "Không hài lòng có thể trả hàng.", "Return goods", "zh_shopping_intermediate"),
    ("换货", "Huànhuò", "verb", "尺码不对，我要换货。", "Đổi hàng", "Sai size, tôi muốn đổi.", "Exchange goods", "zh_shopping_intermediate"),
    ("保修", "Bǎoxiū", "verb", "保修一年。", "Bảo hành", "Bảo hành 1 năm.", "Warranty", "zh_shopping_intermediate"),
    ("免费", "Miǎnfèi", "adjective/adverb", "免费送货。", "Miễn phí", "Giao hàng miễn phí.", "Free", "zh_shopping_intermediate"),
    ("快递", "Kuàidì", "noun", "发快递。", "Chuyển phát nhanh", "Gửi chuyển phát nhanh.", "Express delivery", "zh_shopping_intermediate"),

    # Advanced (2)
    ("消费", "Xiāofèi", "noun/verb", "促进消费。", "Tiêu dùng", "Thúc đẩy tiêu dùng.", "Consumption", "zh_shopping_advanced"),
    ("消费者", "Xiāofèizhě", "noun", "消费者权益。", "Người tiêu dùng", "Quyền lợi người tiêu dùng.", "Consumer", "zh_shopping_advanced"),
    ("零售", "Língshòu", "noun/verb", "零售价。", "Bán lẻ", "Giá bán lẻ.", "Retail", "zh_shopping_advanced"),
    ("批发", "Pīfā", "noun/verb", "批发市场。", "Bán buôn", "Chợ đầu mối.", "Wholesale", "zh_shopping_advanced"),
    ("专卖店", "Zhuānmàidiàn", "noun", "品牌专卖店。", "Cửa hàng chuyên", "Cửa hàng bán đồ hiệu độc quyền.", "Specialty store", "zh_shopping_advanced"),
    ("免税店", "Miǎnshuìdiàn", "noun", "机场免税店。", "Cửa hàng miễn thuế", "Cửa hàng miễn thuế sân bay.", "Duty-free shop", "zh_shopping_advanced"),
    ("旗舰店", "Qíjiàndiàn", "noun", "官方旗舰店。", "Cửa hàng flagship", "Cửa hàng đại diện chính hãng.", "Flagship store", "zh_shopping_advanced"),
    ("网购", "Wǎnggòu", "noun/verb", "经常网购。", "Mua sắm online", "Thường xuyên mua online.", "Online shopping", "zh_shopping_advanced"),
    ("电商", "Diànshāng", "noun", "电商平台。", "Thương mại điện tử", "Sàn thương mại điện tử.", "E-commerce", "zh_shopping_advanced"),
    ("购物车", "Gòuwùchē", "noun", "加入购物车。", "Giỏ hàng", "Thêm vào giỏ hàng.", "Shopping cart", "zh_shopping_advanced"),
    ("订单", "Dìngdān", "noun", "提交订单。", "Đơn đặt hàng", "Gửi đơn hàng.", "Order", "zh_shopping_advanced"),
    ("物流", "Wùliú", "noun", "查看物流信息。", "Hậu cần", "Xem thông tin giao hàng.", "Logistics", "zh_shopping_advanced"),
    ("运费", "Yùnfèi", "noun", "免运费。", "Phí vận chuyển", "Miễn phí ship.", "Shipping fee", "zh_shopping_advanced"),
    ("包邮", "Bāoyóu", "verb", "满百包邮。", "Bao ship", "Đơn trên 100 thì bao ship.", "Free shipping", "zh_shopping_advanced"),
    ("评价", "Píngjià", "noun/verb", "给个好评。", "Đánh giá", "Đánh giá 5 sao.", "Review", "zh_shopping_advanced"),
    ("差评", "Chàpíng", "noun", "留下差评。", "Đánh giá xấu", "Để lại đánh giá tệ.", "Bad review", "zh_shopping_advanced"),
    ("爆款", "Bàokuǎn", "noun", "今年的爆款。", "Hàng hot", "Mẫu bán chạy nhất năm nay.", "Hot item", "zh_shopping_advanced"),
    ("促销", "Cùxiāo", "noun/verb", "促销活动。", "Khuyến mãi", "Chương trình khuyến mãi.", "Promotion", "zh_shopping_advanced"),
    ("优惠券", "Yōuhuìjuàn", "noun", "使用优惠券。", "Phiếu giảm giá", "Dùng mã giảm giá.", "Coupon", "zh_shopping_advanced"),
    ("秒杀", "Miǎoshā", "verb", "限时秒杀。", "Săn sale", "Săn sale giờ vàng.", "Flash sale", "zh_shopping_advanced"),
    ("囤货", "Túnhuò", "verb", "囤货过冬。", "Trữ hàng", "Tích trữ đồ qua mùa đông.", "Stock up", "zh_shopping_advanced"),
    ("砍手", "Kǎnshǒu", "verb", "双十一砍手。", "Chặt tay (mua sắm điên cuồng)", "Mua sắm điên cuồng vào ngày 11/11.", "Chop hand", "zh_shopping_advanced"),
    ("假货", "Jiǎhuò", "noun", "买到假货。", "Hàng giả", "Mua trúng hàng nhái.", "Fake goods", "zh_shopping_advanced"),
    ("正品", "Zhèngpǐn", "noun", "保证正品。", "Hàng chính hãng", "Bảo đảm hàng Auth.", "Authentic product", "zh_shopping_advanced"),
    ("验货", "Yànhuò", "verb", "当面验货。", "Kiểm hàng", "Đồng kiểm khi nhận hàng.", "Inspect goods", "zh_shopping_advanced"),
    ("售后", "Shòuhòu", "noun", "售后服务。", "Hậu mãi", "Dịch vụ sau bán hàng.", "After-sales", "zh_shopping_advanced"),
    ("投诉", "Tóusù", "verb", "向客服投诉。", "Khiếu nại", "Khiếu nại lên chăm sóc khách hàng.", "Complain", "zh_shopping_advanced"),
    ("客服", "Kèfú", "noun", "联系客服。", "Chăm sóc khách hàng", "Liên hệ hỗ trợ viên.", "Customer service", "zh_shopping_advanced"),
    ("理赔", "Lǐpéi", "verb", "申请理赔。", "Bồi thường", "Yêu cầu bồi thường tiền.", "Claim settlement", "zh_shopping_advanced"),
    ("分期付款", "Fēnqī fùkuǎn", "phrase", "手机分期付款。", "Trả góp", "Mua điện thoại trả góp.", "Installment", "zh_shopping_advanced"),

    # Expert (3)
    ("购买力", "Gòumǎilì", "noun", "提高购买力。", "Sức mua", "Nâng cao sức mua.", "Purchasing power", "zh_shopping_expert"),
    ("消费降级", "Xiāofèi jiàngjí", "noun", "消费降级的趋势。", "Giảm cấp tiêu dùng", "Xu hướng thắt lưng buộc bụng.", "Consumption downgrade", "zh_shopping_expert"),
    ("消费升级", "Xiāofèi shēngjí", "noun", "消费升级的需求。", "Nâng cấp tiêu dùng", "Nhu cầu nâng cấp tiêu dùng.", "Consumption upgrade", "zh_shopping_expert"),
    ("冲动消费", "Chōngdòng xiāofèi", "noun", "避免冲动消费。", "Tiêu dùng bốc đồng", "Tránh vung tiền bốc đồng.", "Impulse buying", "zh_shopping_expert"),
    ("理性消费", "Lǐxìng xiāofèi", "noun", "提倡理性消费。", "Tiêu dùng lý trí", "Cổ vũ chi tiêu hợp lý.", "Rational consumption", "zh_shopping_expert"),
    ("饥饿营销", "Jī'è yíngxiāo", "noun", "采用饥饿营销策略。", "Tiếp thị khan hiếm", "Dùng chiêu trò tạo khan hiếm giả.", "Hunger marketing", "zh_shopping_expert"),
    ("捆绑销售", "Kǔnbǎng xiāoshòu", "noun/verb", "捆绑销售模式。", "Bán kèm", "Mô hình bán bia kèm lạc.", "Bundling", "zh_shopping_expert"),
    ("直播带货", "Zhībō dàihuò", "noun/verb", "看直播带货买东西。", "Livestream bán hàng", "Xem livestream chốt đơn.", "Livestream selling", "zh_shopping_expert"),
    ("种草", "Zhǒngcǎo", "verb", "被网红种草。", "Được khuyên dùng (cấy cỏ)", "Bị KOL làm mờ mắt muốn mua.", "Be recommended", "zh_shopping_expert"),
    ("拔草", "Bácǎo", "verb", "终于拔草了。", "Quyết định mua (nhổ cỏ)", "Cuối cùng cũng mua được.", "Buy desired item", "zh_shopping_expert"),
    ("割韭菜", "Gē jiǔcài", "idiom", "消费者被割韭菜。", "Bị lùa gà (cắt hẹ)", "Khách hàng bị lừa tiền trắng trợn.", "Fleece", "zh_shopping_expert"),
    ("羊毛党", "Yángmáo dǎng", "noun", "羊毛党薅羊毛。", "Hội săn đồ miễn phí", "Hội thích săn mã free.", "Bargain hunters", "zh_shopping_expert"),
    ("尾款", "Wěikuǎn", "noun", "付尾款。", "Số tiền còn lại", "Thanh toán nốt đợt cuối.", "Balance payment", "zh_shopping_expert"),
    ("定金", "Dìngjīn", "noun", "交定金。", "Tiền cọc", "Nộp tiền cọc trước.", "Deposit", "zh_shopping_expert"),
    ("预售", "Yùshòu", "noun/verb", "开启预售。", "Bán trước", "Mở bán suất pre-order.", "Presale", "zh_shopping_expert"),
    ("下沉市场", "Xiàchén shìchǎng", "noun", "开发下沉市场。", "Thị trường tuyến dưới", "Khai thác thị trường nông thôn.", "Lower-tier market", "zh_shopping_expert"),
    ("跨境电商", "Kuàjìng diànshāng", "noun", "跨境电商业务。", "Thương mại điện tử xuyên biên giới", "Bán hàng xuyên quốc gia.", "Cross-border e-commerce", "zh_shopping_expert"),
    ("海淘", "Hǎitáo", "noun/verb", "喜欢海淘化妆品。", "Mua hàng nước ngoài", "Order đồ xách tay.", "Overseas online shopping", "zh_shopping_expert"),
    ("代发", "Dàifā", "noun/verb", "一件代发。", "Drop shipping", "Mô hình drop-shipping 1 món.", "Drop shipping", "zh_shopping_expert"),
    ("供应链", "Gōngyìngliàn", "noun", "完善供应链。", "Chuỗi cung ứng", "Hoàn thiện chuỗi cung ứng.", "Supply chain", "zh_shopping_expert"),
    ("渠道", "Qúdào", "noun", "销售渠道。", "Kênh phân phối", "Mạng lưới phân phối hàng.", "Channel", "zh_shopping_expert"),
    ("经销", "Jīngxiāo", "noun/verb", "独家经销。", "Phân phối", "Phân phối độc quyền.", "Distribute", "zh_shopping_expert"),
    ("垄断", "Lǒngduàn", "noun/verb", "垄断市场。", "Độc quyền", "Độc quyền thị trường.", "Monopoly", "zh_shopping_expert"),
    ("反倾销", "Fǎn qīngxiāo", "noun/adjective", "反倾销调查。", "Chống bán phá giá", "Điều tra bán phá giá.", "Anti-dumping", "zh_shopping_expert"),
    ("关税", "Guānshuì", "noun", "提高关税。", "Thuế quan", "Tăng thuế nhập khẩu.", "Tariff", "zh_shopping_expert"),
    ("通货膨胀", "Tōnghuò péngzhàng", "noun", "通货膨胀导致物价上涨。", "Lạm phát", "Lạm phát làm giá tăng.", "Inflation", "zh_shopping_expert"),
    ("贬值", "Biǎnzhí", "verb", "货币贬值。", "Mất giá", "Tiền tệ rớt giá.", "Depreciation", "zh_shopping_expert"),
    ("溢价", "Yìjià", "noun/verb", "品牌溢价。", "Giá trị tăng thêm", "Giá trị thương hiệu đội lên.", "Premium", "zh_shopping_expert"),
    ("成本价", "Chéngběnjià", "noun", "成本价出售。", "Giá gốc", "Bán xả lỗ giá gốc.", "Cost price", "zh_shopping_expert"),
    ("性价比", "Xìngjiàbǐ", "noun", "性价比高。", "Tỷ lệ p/p (hiệu năng/giá)", "Ngon bổ rẻ.", "Cost-performance ratio", "zh_shopping_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_zh, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "zh",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_zh,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Family & Shopping - Chinese) to DB!")
