import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Travel
    {"id": "zh_travel_beginner", "languageCode": "zh", "title": "旅游", "subtitle": "Du lịch - Beginner", "iconEmoji": "✈️", "level": "Beginner", "colorHex": "#8B5CF6", "cardCount": 30},
    {"id": "zh_travel_intermediate", "languageCode": "zh", "title": "旅游", "subtitle": "Du lịch - Intermediate", "iconEmoji": "✈️", "level": "Intermediate", "colorHex": "#7C3AED", "cardCount": 30},
    {"id": "zh_travel_advanced", "languageCode": "zh", "title": "旅游", "subtitle": "Du lịch - Advanced", "iconEmoji": "✈️", "level": "Advanced", "colorHex": "#6D28D9", "cardCount": 30},
    {"id": "zh_travel_expert", "languageCode": "zh", "title": "旅游", "subtitle": "Du lịch - Expert", "iconEmoji": "✈️", "level": "Expert", "colorHex": "#5B21B6", "cardCount": 30},
    
    # Daily Life
    {"id": "zh_daily_beginner", "languageCode": "zh", "title": "日常", "subtitle": "Cuộc sống - Beginner", "iconEmoji": "☕", "level": "Beginner", "colorHex": "#A855F7", "cardCount": 30},
    {"id": "zh_daily_intermediate", "languageCode": "zh", "title": "日常", "subtitle": "Cuộc sống - Intermediate", "iconEmoji": "☕", "level": "Intermediate", "colorHex": "#9333EA", "cardCount": 30},
    {"id": "zh_daily_advanced", "languageCode": "zh", "title": "日常", "subtitle": "Cuộc sống - Advanced", "iconEmoji": "☕", "level": "Advanced", "colorHex": "#7E22CE", "cardCount": 30},
    {"id": "zh_daily_expert", "languageCode": "zh", "title": "日常", "subtitle": "Cuộc sống - Expert", "iconEmoji": "☕", "level": "Expert", "colorHex": "#6B21A8", "cardCount": 30}
]

vocab_data = [
    # ---- TRAVEL ----
    # Beginner (0)
    ("旅游", "Lǚyóu", "noun/verb", "去旅游。", "Du lịch", "Đi du lịch.", "Travel", "zh_travel_beginner"),
    ("汽车", "Qìchē", "noun", "开汽车。", "Ô tô", "Lái xe ô tô.", "Car", "zh_travel_beginner"),
    ("火车", "Huǒchē", "noun", "坐火车。", "Tàu hỏa", "Đi tàu hỏa.", "Train", "zh_travel_beginner"),
    ("飞机", "Fēijī", "noun", "坐飞机。", "Máy bay", "Đi máy bay.", "Airplane", "zh_travel_beginner"),
    ("自行车", "Zìxíngchē", "noun", "骑自行车。", "Xe đạp", "Đạp xe đạp.", "Bicycle", "zh_travel_beginner"),
    ("船", "Chuán", "noun", "坐船。", "Thuyền, tàu thủy", "Đi tàu thủy.", "Boat/Ship", "zh_travel_beginner"),
    ("票", "Piào", "noun", "买票。", "Vé", "Mua vé.", "Ticket", "zh_travel_beginner"),
    ("路", "Lù", "noun", "迷路了。", "Đường", "Lạc đường rồi.", "Road/Way", "zh_travel_beginner"),
    ("远", "Yuǎn", "adjective", "很远。", "Xa", "Rất xa.", "Far", "zh_travel_beginner"),
    ("近", "Jìn", "adjective", "很近。", "Gần", "Rất gần.", "Near", "zh_travel_beginner"),
    ("去", "Qù", "verb", "去中国。", "Đi", "Đi Trung Quốc.", "Go", "zh_travel_beginner"),
    ("来", "Lái", "verb", "来这里。", "Đến", "Đến đây.", "Come", "zh_travel_beginner"),
    ("走", "Zǒu", "verb", "走路。", "Đi (bộ)", "Đi bộ.", "Walk", "zh_travel_beginner"),
    ("跑", "Pǎo", "verb", "跑步。", "Chạy", "Chạy bộ.", "Run", "zh_travel_beginner"),
    ("坐", "Zuò", "verb", "请坐。", "Ngồi (đi xe/tàu)", "Mời ngồi.", "Sit/Take (vehicle)", "zh_travel_beginner"),
    ("骑", "Qí", "verb", "骑马。", "Cưỡi, đạp (xe)", "Cưỡi ngựa.", "Ride", "zh_travel_beginner"),
    ("开", "Kāi", "verb", "开车。", "Lái (xe)", "Lái xe.", "Drive", "zh_travel_beginner"),
    ("停", "Tíng", "verb", "停车。", "Dừng, đỗ", "Đỗ xe.", "Stop", "zh_travel_beginner"),
    ("左", "Zuǒ", "noun", "向左走。", "Trái", "Đi về bên trái.", "Left", "zh_travel_beginner"),
    ("右", "Yòu", "noun", "向右转。", "Phải", "Rẽ phải.", "Right", "zh_travel_beginner"),
    ("前", "Qián", "noun", "前面。", "Trước", "Phía trước.", "Front", "zh_travel_beginner"),
    ("后", "Hòu", "noun", "后面。", "Sau", "Phía sau.", "Back", "zh_travel_beginner"),
    ("旁边", "Pángbiān", "noun", "在旁边。", "Bên cạnh", "Ở bên cạnh.", "Beside", "zh_travel_beginner"),
    ("机场", "Jīchǎng", "noun", "去机场。", "Sân bay", "Đi ra sân bay.", "Airport", "zh_travel_beginner"),
    ("车站", "Chēzhàn", "noun", "火车站。", "Nhà ga, bến xe", "Nhà ga xe lửa.", "Station", "zh_travel_beginner"),
    ("酒店", "Jiǔdiàn", "noun", "住酒店。", "Khách sạn", "Ở khách sạn.", "Hotel", "zh_travel_beginner"),
    ("房间", "Fángjiān", "noun", "酒店房间。", "Phòng", "Phòng khách sạn.", "Room", "zh_travel_beginner"),
    ("行李", "Xínglǐ", "noun", "拿行李。", "Hành lý", "Lấy hành lý.", "Luggage", "zh_travel_beginner"),
    ("护照", "Hùzhào", "noun", "带护照。", "Hộ chiếu", "Mang theo hộ chiếu.", "Passport", "zh_travel_beginner"),
    ("签证", "Qiānzhèng", "noun", "办签证。", "Visa (thị thực)", "Làm thủ tục xin Visa.", "Visa", "zh_travel_beginner"),

    # Intermediate (1)
    ("目的地", "Mùdìdì", "noun", "到达目的地。", "Điểm đến", "Đến nơi.", "Destination", "zh_travel_intermediate"),
    ("路线", "Lùxiàn", "noun", "旅游路线。", "Tuyến đường", "Tuyến đường du lịch.", "Route", "zh_travel_intermediate"),
    ("导游", "Dǎoyóu", "noun", "跟着导游。", "Hướng dẫn viên", "Đi theo hướng dẫn viên.", "Tour guide", "zh_travel_intermediate"),
    ("游客", "Yóukè", "noun", "很多游客。", "Du khách", "Rất nhiều du khách.", "Tourist", "zh_travel_intermediate"),
    ("景点", "Jǐngdiǎn", "noun", "旅游景点。", "Điểm tham quan", "Điểm tham quan du lịch.", "Scenic spot", "zh_travel_intermediate"),
    ("门票", "Ménpiào", "noun", "买门票。", "Vé vào cửa", "Mua vé vào cổng.", "Entrance ticket", "zh_travel_intermediate"),
    ("纪念品", "Jìniànpǐn", "noun", "买纪念品。", "Đồ lưu niệm", "Mua quà lưu niệm.", "Souvenir", "zh_travel_intermediate"),
    ("风景", "Fēngjǐng", "noun", "风景很美。", "Phong cảnh", "Phong cảnh rất đẹp.", "Scenery", "zh_travel_intermediate"),
    ("拍照", "Pāizhào", "verb", "给我们拍照。", "Chụp ảnh", "Chụp ảnh cho chúng tôi nhé.", "Take a photo", "zh_travel_intermediate"),
    ("航班", "Hángbān", "noun", "航班延误。", "Chuyến bay", "Chuyến bay bị hoãn.", "Flight", "zh_travel_intermediate"),
    ("登机牌", "Dēngjīpái", "noun", "换登机牌。", "Thẻ lên máy bay", "Lấy thẻ lên máy bay.", "Boarding pass", "zh_travel_intermediate"),
    ("安检", "Ānjiǎn", "noun/verb", "通过安检。", "Kiểm tra an ninh", "Đi qua cửa kiểm tra an ninh.", "Security check", "zh_travel_intermediate"),
    ("海关", "Hǎiguān", "noun", "过海关。", "Hải quan", "Đi qua hải quan.", "Customs", "zh_travel_intermediate"),
    ("高铁", "Gāotiě", "noun", "坐高铁。", "Đường sắt cao tốc", "Đi tàu cao tốc.", "High-speed rail", "zh_travel_intermediate"),
    ("地铁", "Dìtiě", "noun", "坐地铁。", "Tàu điện ngầm", "Đi tàu điện ngầm.", "Subway", "zh_travel_intermediate"),
    ("公交车", "Gōngjiāochē", "noun", "挤公交车。", "Xe buýt", "Chen chúc trên xe buýt.", "Bus", "zh_travel_intermediate"),
    ("出租车", "Chūzūchē", "noun", "叫出租车。", "Xe taxi", "Gọi taxi.", "Taxi", "zh_travel_intermediate"),
    ("打车", "Dǎchē", "verb", "打车去酒店。", "Bắt xe, gọi xe", "Bắt taxi về khách sạn.", "Take a taxi", "zh_travel_intermediate"),
    ("租车", "Zūchē", "verb", "租车自驾游。", "Thuê xe", "Thuê xe đi phượt.", "Rent a car", "zh_travel_intermediate"),
    ("加油站", "Jiāyóuzhàn", "noun", "找加油站。", "Trạm xăng", "Tìm trạm xăng.", "Gas station", "zh_travel_intermediate"),
    ("高速公路", "Gāosù gōnglù", "noun", "上高速公路。", "Đường cao tốc", "Lên đường cao tốc.", "Highway", "zh_travel_intermediate"),
    ("堵车", "Dǔchē", "verb", "路上堵车。", "Tắc đường", "Trên đường bị tắc.", "Traffic jam", "zh_travel_intermediate"),
    ("导航", "Dǎoháng", "noun/verb", "用手机导航。", "Chỉ đường (GPS)", "Dùng điện thoại để chỉ đường.", "Navigation", "zh_travel_intermediate"),
    ("预订", "Yùdìng", "verb", "预订酒店。", "Đặt trước", "Đặt phòng khách sạn.", "Book/Reserve", "zh_travel_intermediate"),
    ("办理入住", "Bànlǐ rùzhù", "phrase", "去前台办理入住。", "Nhận phòng (Check-in)", "Ra quầy lễ tân check-in.", "Check in", "zh_travel_intermediate"),
    ("退房", "Tuìfáng", "verb", "中午退房。", "Trả phòng (Check-out)", "Check-out vào buổi trưa.", "Check out", "zh_travel_intermediate"),
    ("换钱", "Huànqián", "verb", "去银行换钱。", "Đổi tiền", "Ra ngân hàng đổi ngoại tệ.", "Exchange money", "zh_travel_intermediate"),
    ("汇率", "Huìlǜ", "noun", "今天的汇率是多少？", "Tỷ giá hối đoái", "Tỷ giá hôm nay là bao nhiêu?", "Exchange rate", "zh_travel_intermediate"),
    ("日程", "Rìchéng", "noun", "安排日程。", "Lịch trình", "Lên lịch trình.", "Schedule", "zh_travel_intermediate"),
    ("出发", "Chūfā", "verb", "准备出发。", "Xuất phát", "Chuẩn bị lên đường.", "Depart", "zh_travel_intermediate"),

    # Advanced (2)
    ("探险", "Tànxiǎn", "noun/verb", "去丛林探险。", "Thám hiểm", "Đi khám phá rừng rậm.", "Explore/Adventure", "zh_travel_advanced"),
    ("徒步", "Túbù", "noun/verb", "徒步旅行。", "Đi bộ đường dài (Trekking)", "Du lịch bằng cách đi bộ.", "Hike", "zh_travel_advanced"),
    ("露营", "Lùyíng", "noun/verb", "在野外露营。", "Cắm trại", "Cắm trại ngoài trời.", "Camp", "zh_travel_advanced"),
    ("房车", "Fángchē", "noun", "房车旅行。", "Xe nhà di động (RV)", "Du lịch bằng xe RV.", "RV/Motorhome", "zh_travel_advanced"),
    ("邮轮", "Yóulún", "noun", "坐豪华邮轮。", "Du thuyền", "Đi du thuyền hạng sang.", "Cruise", "zh_travel_advanced"),
    ("潜水", "Qiánshuǐ", "noun/verb", "去海边潜水。", "Lặn", "Đi ra biển lặn.", "Dive", "zh_travel_advanced"),
    ("冲浪", "Chōnglàng", "noun/verb", "在海上冲浪。", "Lướt sóng", "Lướt sóng trên biển.", "Surf", "zh_travel_advanced"),
    ("滑雪", "Huáxuě", "noun/verb", "去冬天滑雪。", "Trượt tuyết", "Đi trượt tuyết vào mùa đông.", "Ski", "zh_travel_advanced"),
    ("温泉", "Wēnquán", "noun", "泡温泉。", "Suối nước nóng", "Ngâm suối nước nóng.", "Hot spring", "zh_travel_advanced"),
    ("度假村", "Dùjiācūn", "noun", "海滨度假村。", "Khu nghỉ dưỡng (Resort)", "Khu resort ven biển.", "Resort", "zh_travel_advanced"),
    ("民宿", "Mínsù", "noun", "住当地民宿。", "Homestay", "Ở homestay của người dân địa phương.", "Homestay", "zh_travel_advanced"),
    ("青年旅舍", "Qīngnián lǚshè", "noun", "便宜的青年旅舍。", "Nhà nghỉ thanh niên (Hostel)", "Nhà nghỉ cho thanh niên giá rẻ.", "Youth hostel", "zh_travel_advanced"),
    ("攻略", "Gōnglüè", "noun", "做旅游攻略。", "Cẩm nang, kinh nghiệm", "Tìm hiểu kinh nghiệm du lịch.", "Travel guide", "zh_travel_advanced"),
    ("穷游", "Qióngyóu", "verb", "大学生喜欢穷游。", "Du lịch bụi (ngon bổ rẻ)", "Sinh viên thích đi du lịch kiểu tiết kiệm.", "Budget travel", "zh_travel_advanced"),
    ("自由行", "Zìyóuxíng", "noun", "我们选择自由行。", "Du lịch tự túc", "Chúng tôi chọn đi tự túc.", "Independent travel", "zh_travel_advanced"),
    ("跟团游", "Gēntuányóu", "noun", "报名跟团游。", "Du lịch theo tour", "Đăng ký đi tour ghép.", "Group tour", "zh_travel_advanced"),
    ("时差", "Shíchā", "noun", "倒时差。", "Chênh lệch múi giờ", "Làm quen với múi giờ.", "Time difference/Jet lag", "zh_travel_advanced"),
    ("倒时差", "Dǎo shíchā", "phrase", "刚回国，还在倒时差。", "Làm quen với múi giờ", "Vừa về nước, vẫn đang bị jetlag.", "Get over jet lag", "zh_travel_advanced"),
    ("晕车", "Yùnchē", "verb", "我有点晕车。", "Say xe", "Tôi bị say xe một chút.", "Carsick", "zh_travel_advanced"),
    ("晕船", "Yùnchuán", "verb", "吃晕船药。", "Say sóng", "Uống thuốc chống say sóng.", "Seasick", "zh_travel_advanced"),
    ("航班取消", "Hángbān qǔxiāo", "phrase", "抱歉，航班取消了。", "Hủy chuyến bay", "Xin lỗi, chuyến bay đã bị hủy.", "Flight canceled", "zh_travel_advanced"),
    ("改签", "Gǎiqiān", "verb", "免费改签机票。", "Đổi vé", "Đổi vé máy bay miễn phí.", "Change ticket", "zh_travel_advanced"),
    ("托运", "Tuōyùn", "verb", "托运行李。", "Ký gửi (hành lý)", "Ký gửi hành lý.", "Check in (luggage)", "zh_travel_advanced"),
    ("超重", "Chāozhòng", "verb/adjective", "行李超重了。", "Quá cân", "Hành lý bị lố ký rồi.", "Overweight", "zh_travel_advanced"),
    ("免税", "Miǎnshuì", "adjective", "免税商品。", "Miễn thuế", "Hàng hóa miễn thuế.", "Duty-free", "zh_travel_advanced"),
    ("报关", "Bàoguān", "verb", "申报报关。", "Khai báo hải quan", "Đứng ra làm thủ tục hải quan.", "Declare at customs", "zh_travel_advanced"),
    ("违禁品", "Wéijìnpǐn", "noun", "严禁携带违禁品。", "Hàng cấm", "Nghiêm cấm mang theo hàng cấm.", "Contraband", "zh_travel_advanced"),
    ("旅游旺季", "Lǚyóu wàngjì", "noun", "现在是旅游旺季。", "Mùa du lịch cao điểm", "Bây giờ đang là mùa cao điểm.", "Peak tourist season", "zh_travel_advanced"),
    ("旅游淡季", "Lǚyóu dànjì", "noun", "淡季去比较便宜。", "Mùa du lịch thấp điểm", "Đi vào mùa thấp điểm sẽ rẻ hơn.", "Off-season", "zh_travel_advanced"),
    ("行程单", "Xíngchéngdān", "noun", "打印行程单。", "Tờ lịch trình (Itinerary)", "In bản lịch trình ra.", "Itinerary", "zh_travel_advanced"),

    # Expert (3)
    ("申根签证", "Shēngēn qiānzhèng", "noun", "办理申根签证。", "Visa Schengen", "Làm Visa Schengen (châu Âu).", "Schengen visa", "zh_travel_expert"),
    ("落地签", "Luòdìqiān", "noun", "这个国家支持落地签。", "Visa cấp tại sân bay", "Quốc gia này cho phép làm visa tại sân bay.", "Visa on arrival", "zh_travel_expert"),
    ("免签", "Miǎnqiān", "noun/verb", "两国互免签证。", "Miễn visa", "Hai nước miễn visa cho nhau.", "Visa exemption", "zh_travel_expert"),
    ("电子签", "Diànzǐqiān", "noun", "申请电子签证 (e-Visa)。", "Visa điện tử", "Xin visa điện tử (e-Visa).", "e-Visa", "zh_travel_expert"),
    ("遣返", "Qiǎnfǎn", "verb", "被海关遣返。", "Trục xuất, gửi trả", "Bị hải quan trục xuất về nước.", "Repatriate", "zh_travel_expert"),
    ("滞留", "Zhìliú", "verb", "旅客滞留机场。", "Mắc kẹt, đình trệ", "Hành khách bị mắc kẹt tại sân bay.", "Stranded", "zh_travel_expert"),
    ("索道", "Suǒdào", "noun", "坐高山索道。", "Cáp treo", "Đi cáp treo lên núi cao.", "Cableway", "zh_travel_expert"),
    ("邮轮母港", "Yóulún mǔgǎng", "noun", "国际邮轮母港。", "Cảng mẹ của du thuyền", "Cảng chính quốc tế dành cho du thuyền.", "Cruise homeport", "zh_travel_expert"),
    ("生态旅游", "Shēngtài lǚyóu", "noun", "发展生态旅游。", "Du lịch sinh thái", "Phát triển du lịch sinh thái.", "Ecotourism", "zh_travel_expert"),
    ("文化遗产", "Wénhuà yíchǎn", "noun", "世界文化遗产。", "Di sản văn hóa", "Di sản văn hóa thế giới.", "Cultural heritage", "zh_travel_expert"),
    ("走马观花", "Zǒumǎ guānhuā", "idiom", "走马观花式的旅游。", "Cưỡi ngựa xem hoa", "Du lịch kiểu cưỡi ngựa xem hoa.", "Superficial tour", "zh_travel_expert"),
    ("深度游", "Shēndùyóu", "noun", "体验当地生活的深度游。", "Du lịch trải nghiệm sâu", "Chuyến đi thâm nhập để hiểu đời sống bản địa.", "In-depth tour", "zh_travel_expert"),
    ("朝圣", "Cháoshèng", "noun/verb", "去西藏朝圣。", "Hành hương", "Hành hương về Tây Tạng.", "Pilgrimage", "zh_travel_expert"),
    ("驴友", "Lǘyǒu", "noun", "结伴而行的驴友。", "Bạn phượt (Backpacker)", "Những người bạn phượt đi cùng nhau.", "Backpacker", "zh_travel_expert"),
    ("穷乡僻壤", "Qióngxiāng pìrǎng", "noun", "远离城市的穷乡僻壤。", "Nơi khỉ ho cò gáy", "Vùng sâu vùng xa vắng vẻ.", "Remote place", "zh_travel_expert"),
    ("异国风情", "Yìguó fēngqíng", "noun", "充满异国风情。", "Phong cách nước ngoài", "Tràn ngập vẻ đẹp kỳ lạ của nước ngoài.", "Exotic charm", "zh_travel_expert"),
    ("流连忘返", "Liúlián wàngfǎn", "idiom", "美景让人流连忘返。", "Lưu luyến không muốn về", "Cảnh đẹp khiến người ta quên cả lối về.", "Linger on", "zh_travel_expert"),
    ("水土不服", "Shuǐtǔ bùfú", "idiom", "刚到国外，有点水土不服。", "Không hợp thổ nhưỡng", "Mới ra nước ngoài nên hơi lạ nước lạ cái.", "Unaccustomed to a new place", "zh_travel_expert"),
    ("舟车劳顿", "Zhōuchē láodùn", "idiom", "经过长途的舟车劳顿。", "Mệt mỏi vì đi đường dài", "Trải qua nỗi mệt nhọc khi đi tàu xe đường dài.", "Travel-worn", "zh_travel_expert"),
    ("风餐露宿", "Fēngcān lùsù", "idiom", "探险家风餐露宿。", "Ăn gió nằm sương", "Nhà thám hiểm phải dầm sương dãi nắng.", "Brave the wind and dew", "zh_travel_expert"),
    ("跋山涉水", "Báshān shèshuǐ", "idiom", "跋山涉水才到达那里。", "Trèo đèo lội suối", "Trèo đèo lội suối mới tới được đó.", "Cross mountains and rivers", "zh_travel_expert"),
    ("游山玩水", "Yóushān wánshuǐ", "idiom", "退休后去游山玩水。", "Du ngoạn non nước", "Sau khi nghỉ hưu đi du sơn ngoạn thủy.", "Sightseeing tour", "zh_travel_expert"),
    ("满载而归", "Mǎnzài érguī", "idiom", "购物回来满载而归。", "Mua sắm đầy ắp mang về", "Đi mua đồ xong tay xách nách mang trở về.", "Return fully loaded", "zh_travel_expert"),
    ("避暑胜地", "Bìshǔ shèngdì", "noun", "著名的避暑胜地。", "Nơi nghỉ mát", "Địa điểm tránh nóng nổi tiếng.", "Summer resort", "zh_travel_expert"),
    ("世外桃源", "Shìwài táoyuán", "idiom", "这里简直是世外桃源。", "Chốn bồng lai tiên cảnh", "Nơi này y như là thế ngoại đào nguyên.", "Paradise/Utopia", "zh_travel_expert"),
    ("鬼斧神工", "Guǐfǔ shéngōng", "idiom", "大自然的鬼斧神工。", "Tuyệt tác của tạo hóa", "Bàn tay nhào nặn kỳ diệu của mẹ thiên nhiên.", "Uncanny workmanship", "zh_travel_expert"),
    ("叹为观止", "Tànwéi guānzhǐ", "idiom", "让人叹为观止的建筑。", "Đẹp đến ngỡ ngàng", "Công trình khiến người ta phải trầm trồ khen ngợi.", "Breathtaking", "zh_travel_expert"),
    ("名胜古迹", "Míngshèng gǔjì", "noun", "参观名胜古迹。", "Danh lam thắng cảnh", "Thăm viếng các di tích lịch sử và danh lam.", "Places of historic interest", "zh_travel_expert"),
    ("人山人海", "Rénshān rénhǎi", "idiom", "节假日景点人山人海。", "Biển người đông đúc", "Ngày lễ ở các điểm du lịch đông như kiến.", "Huge crowds", "zh_travel_expert"),
    ("到此一游", "Dàocǐ yīyóu", "phrase", "在墙上刻“到此一游”。", "Đã từng đến đây chơi", "Khắc chữ 'XXX đã ở đây' trên tường.", "Was here", "zh_travel_expert"),

    # ---- DAILY LIFE ----
    # Beginner (0)
    ("早上", "Zǎoshang", "noun", "早上起床。", "Buổi sáng", "Ngủ dậy vào buổi sáng.", "Morning", "zh_daily_beginner"),
    ("下午", "Xiàwǔ", "noun", "下午喝茶。", "Buổi chiều", "Uống trà vào buổi chiều.", "Afternoon", "zh_daily_beginner"),
    ("晚上", "Wǎnshang", "noun", "晚上睡觉。", "Buổi tối", "Đi ngủ vào buổi tối.", "Evening/Night", "zh_daily_beginner"),
    ("起床", "Qǐchuáng", "verb", "早上七点起床。", "Ngủ dậy", "7 giờ sáng ngủ dậy.", "Wake up", "zh_daily_beginner"),
    ("睡觉", "Shuìjiào", "verb", "早点睡觉。", "Đi ngủ", "Đi ngủ sớm một chút.", "Sleep", "zh_daily_beginner"),
    ("刷牙", "Shuāyá", "verb", "每天刷牙。", "Đánh răng", "Đánh răng mỗi ngày.", "Brush teeth", "zh_daily_beginner"),
    ("洗脸", "Xǐliǎn", "verb", "洗脸。", "Rửa mặt", "Rửa mặt.", "Wash face", "zh_daily_beginner"),
    ("洗澡", "Xǐzǎo", "verb", "晚上洗澡。", "Tắm", "Buổi tối tắm rửa.", "Shower", "zh_daily_beginner"),
    ("穿衣服", "Chuān yīfu", "phrase", "穿衣服出门。", "Mặc quần áo", "Mặc quần áo ra ngoài.", "Put on clothes", "zh_daily_beginner"),
    ("吃早饭", "Chī zǎofàn", "phrase", "吃早饭。", "Ăn sáng", "Ăn cơm sáng.", "Eat breakfast", "zh_daily_beginner"),
    ("上班", "Shàngbān", "verb", "去上班。", "Đi làm", "Đi làm.", "Go to work", "zh_daily_beginner"),
    ("下班", "Xiàbān", "verb", "五点下班。", "Tan làm", "5 giờ tan ca.", "Get off work", "zh_daily_beginner"),
    ("上学", "Shàngxué", "verb", "孩子去上学。", "Đi học", "Trẻ con đi học.", "Go to school", "zh_daily_beginner"),
    ("放学", "Fàngxué", "verb", "下午放学。", "Tan học", "Buổi chiều tan học.", "Finish school", "zh_daily_beginner"),
    ("回家", "Huíjiā", "verb", "下班回家。", "Về nhà", "Tan làm về nhà.", "Go home", "zh_daily_beginner"),
    ("做饭", "Zuòfàn", "verb", "妈妈做饭。", "Nấu cơm", "Mẹ nấu cơm.", "Cook", "zh_daily_beginner"),
    ("吃饭", "Chīfàn", "verb", "大家一起吃饭。", "Ăn cơm", "Mọi người cùng ăn cơm.", "Eat a meal", "zh_daily_beginner"),
    ("洗碗", "Xǐwǎn", "verb", "吃完饭洗碗。", "Rửa bát", "Ăn xong rồi rửa bát.", "Wash dishes", "zh_daily_beginner"),
    ("看电视", "Kàn diànshì", "phrase", "晚上看电视。", "Xem tivi", "Buổi tối xem TV.", "Watch TV", "zh_daily_beginner"),
    ("看书", "Kànshū", "verb", "睡前看书。", "Đọc sách", "Trước khi ngủ thì xem sách.", "Read a book", "zh_daily_beginner"),
    ("玩手机", "Wán shǒujī", "phrase", "别一直玩手机。", "Chơi điện thoại", "Đừng cứ chơi điện thoại suốt thế.", "Play on phone", "zh_daily_beginner"),
    ("听音乐", "Tīng yīnyuè", "phrase", "听音乐放松。", "Nghe nhạc", "Nghe nhạc để thư giãn.", "Listen to music", "zh_daily_beginner"),
    ("聊天", "Liáotiān", "verb", "和朋友聊天。", "Nói chuyện", "Tám chuyện với bạn bè.", "Chat", "zh_daily_beginner"),
    ("买东西", "Mǎi dōngxi", "phrase", "去超市买东西。", "Mua sắm", "Đi siêu thị mua sắm.", "Buy things", "zh_daily_beginner"),
    ("打扫", "Dǎsǎo", "verb", "打扫房间。", "Dọn dẹp", "Quét dọn phòng ốc.", "Clean", "zh_daily_beginner"),
    ("垃圾", "Lājī", "noun", "倒垃圾。", "Rác", "Đổ rác.", "Trash", "zh_daily_beginner"),
    ("洗衣服", "Xǐ yīfu", "phrase", "周末洗衣服。", "Giặt quần áo", "Cuối tuần đem giặt quần áo.", "Wash clothes", "zh_daily_beginner"),
    ("累", "Lèi", "adjective", "今天很累。", "Mệt", "Hôm nay tôi rất mệt.", "Tired", "zh_daily_beginner"),
    ("忙", "Máng", "adjective", "工作很忙。", "Bận", "Công việc rất bận rộn.", "Busy", "zh_daily_beginner"),
    ("闲", "Xián", "adjective", "周末很闲。", "Rảnh rỗi", "Cuối tuần tôi khá rảnh.", "Free/Idle", "zh_daily_beginner"),

    # Intermediate (1)
    ("日常", "Rìcháng", "adjective", "日常生活。", "Thường ngày", "Cuộc sống hàng ngày.", "Daily", "zh_daily_intermediate"),
    ("习惯", "Xíguàn", "noun/verb", "好习惯。", "Thói quen", "Thói quen tốt.", "Habit", "zh_daily_intermediate"),
    ("闹钟", "Nàozhōng", "noun", "闹钟响了。", "Đồng hồ báo thức", "Chuông báo thức reo rồi.", "Alarm clock", "zh_daily_intermediate"),
    ("叫醒", "Jiàoxǐng", "verb", "把我叫醒。", "Gọi dậy", "Gọi tôi thức dậy với.", "Wake someone up", "zh_daily_intermediate"),
    ("梳头", "Shūtóu", "verb", "梳头发。", "Chải đầu", "Chải tóc.", "Comb hair", "zh_daily_intermediate"),
    ("化妆", "Huàzhuāng", "verb", "化妆出门。", "Trang điểm", "Trang điểm trước khi ra phố.", "Put on makeup", "zh_daily_intermediate"),
    ("刮胡子", "Guā húzi", "phrase", "爸爸在刮胡子。", "Cạo râu", "Bố đang cạo râu.", "Shave", "zh_daily_intermediate"),
    ("挤地铁", "Jǐ dìtiě", "phrase", "早上挤地铁。", "Chen chúc tàu điện ngầm", "Chen lấn đi tàu điện vào buổi sáng.", "Squeeze on subway", "zh_daily_intermediate"),
    ("堵车", "Dǔchē", "verb", "路上又堵车了。", "Tắc đường", "Trên đường lại bị kẹt xe rồi.", "Traffic jam", "zh_daily_intermediate"),
    ("打卡", "Dǎkǎ", "verb", "上班打卡。", "Chấm công (quẹt thẻ)", "Quẹt thẻ khi tới chỗ làm.", "Clock in", "zh_daily_intermediate"),
    ("开会", "Kāihuì", "verb", "下午开会。", "Họp", "Buổi chiều có cuộc họp.", "Have a meeting", "zh_daily_intermediate"),
    ("加班", "Jiābān", "verb", "经常加班。", "Tăng ca", "Hay phải làm thêm giờ.", "Work overtime", "zh_daily_intermediate"),
    ("聚餐", "Jùcān", "verb", "同事聚餐。", "Tụ tập ăn uống", "Đồng nghiệp đi ăn chung.", "Dine together", "zh_daily_intermediate"),
    ("散步", "Sànbù", "verb", "晚饭后散步。", "Đi dạo", "Đi dạo sau khi ăn cơm tối.", "Take a walk", "zh_daily_intermediate"),
    ("遛狗", "Liùgǒu", "verb", "去公园遛狗。", "Dắt chó đi dạo", "Đưa cún ra công viên đi dạo.", "Walk the dog", "zh_daily_intermediate"),
    ("健身", "Jiànshēn", "verb/noun", "去健身房健身。", "Tập thể hình (Gym)", "Đến phòng gym tập tành.", "Work out", "zh_daily_intermediate"),
    ("瑜伽", "Yújiā", "noun", "练瑜伽。", "Yoga", "Tập Yoga.", "Yoga", "zh_daily_intermediate"),
    ("跑步机", "Pǎobùjī", "noun", "在跑步机上跑步。", "Máy chạy bộ", "Chạy bộ trên máy.", "Treadmill", "zh_daily_intermediate"),
    ("做家务", "Zuò jiāwù", "phrase", "周末做家务。", "Làm việc nhà", "Làm việc nhà vào hai ngày cuối tuần.", "Do housework", "zh_daily_intermediate"),
    ("拖地", "Tuōdì", "verb", "扫地和拖地。", "Lau nhà", "Quét nhà và lau sàn.", "Mop the floor", "zh_daily_intermediate"),
    ("擦桌子", "Cā zhuōzi", "phrase", "擦干净桌子。", "Lau bàn", "Lau dọn bàn ăn cho sạch.", "Wipe the table", "zh_daily_intermediate"),
    ("晾衣服", "Liàng yīfu", "phrase", "把衣服晾干。", "Phơi quần áo", "Đem quần áo đi phơi.", "Hang clothes out", "zh_daily_intermediate"),
    ("叠被子", "Dié bèizi", "phrase", "起床后叠被子。", "Gấp chăn", "Ngủ dậy thì nhớ gấp chăn lại.", "Fold the quilt", "zh_daily_intermediate"),
    ("交电费", "Jiāo diànfèi", "phrase", "上网交电费。", "Đóng tiền điện", "Đóng tiền điện qua mạng.", "Pay electricity bill", "zh_daily_intermediate"),
    ("缴费", "Jiǎofèi", "verb", "手机缴费。", "Nộp phí", "Thanh toán cước điện thoại.", "Pay fees", "zh_daily_intermediate"),
    ("邻居", "Línjū", "noun", "友好的邻居。", "Hàng xóm", "Người hàng xóm thân thiện.", "Neighbor", "zh_daily_intermediate"),
    ("拜访", "Bàifǎng", "verb", "拜访亲戚。", "Thăm viếng", "Đi thăm họ hàng.", "Visit", "zh_daily_intermediate"),
    ("约会", "Yuēhuì", "noun/verb", "周末有约会。", "Hẹn hò", "Cuối tuần này tớ có hẹn rồi.", "Date", "zh_daily_intermediate"),
    ("逛超市", "Guàng chāoshì", "phrase", "陪妈妈逛超市。", "Đi siêu thị", "Cùng mẹ đi siêu thị.", "Go to supermarket", "zh_daily_intermediate"),
    ("熬夜", "Áoyè", "verb", "不要熬夜。", "Thức khuya", "Cậu đừng có thức khuya nữa.", "Stay up late", "zh_daily_intermediate"),

    # Advanced (2)
    ("节奏", "Jiézòu", "noun", "生活节奏快。", "Nhịp độ", "Nhịp sống rất nhanh và hối hả.", "Pace/Rhythm", "zh_daily_advanced"),
    ("压力", "Yālì", "noun", "工作压力大。", "Áp lực", "Áp lực công việc rất cao.", "Pressure", "zh_daily_advanced"),
    ("放松", "Fàngsōng", "verb", "听音乐放松一下。", "Thư giãn", "Mở nhạc lên nghe để thư giãn đầu óc.", "Relax", "zh_daily_advanced"),
    ("娱乐", "Yúlè", "noun", "娱乐活动。", "Giải trí", "Tham gia các hoạt động giải trí.", "Entertainment", "zh_daily_advanced"),
    ("消遣", "Xiāoqiǎn", "verb/noun", "拿看书当消遣。", "Tiêu khiển", "Coi việc đọc sách như một thú vui tiêu khiển.", "Pastime", "zh_daily_advanced"),
    ("业余", "Yèyú", "adjective", "业余爱好。", "Lúc rảnh rỗi / Nghiệp dư", "Sở thích lúc rảnh rỗi.", "Amateur/Spare time", "zh_daily_advanced"),
    ("规律", "Guīlǜ", "noun/adjective", "生活有规律。", "Quy luật, nề nếp", "Sinh hoạt rất nề nếp.", "Regular/Disciplined", "zh_daily_advanced"),
    ("拖延", "Tuōyán", "verb", "拖延症。", "Trì hoãn", "Mắc bệnh hay trì hoãn.", "Procrastinate", "zh_daily_advanced"),
    ("效率", "Xiàolǜ", "noun", "提高工作效率。", "Hiệu suất", "Tăng cường hiệu suất làm việc.", "Efficiency", "zh_daily_advanced"),
    ("琐事", "Suǒshì", "noun", "生活琐事。", "Việc vặt", "Những chuyện lặt vặt trong sinh hoạt.", "Trifles", "zh_daily_advanced"),
    ("理财", "Lǐcái", "verb", "学习理财。", "Quản lý tài chính", "Học cách quản lý tiền bạc cá nhân.", "Wealth management", "zh_daily_advanced"),
    ("记账", "Jìzhàng", "verb", "坚持每天记账。", "Ghi sổ thu chi", "Duy trì việc ghi chép chi tiêu mỗi ngày.", "Keep accounts", "zh_daily_advanced"),
    ("存款", "Cúnkuǎn", "noun/verb", "银行存款。", "Gửi tiền tiết kiệm", "Tiền gửi ở ngân hàng.", "Deposit", "zh_daily_advanced"),
    ("贷款", "Dàikuǎn", "noun/verb", "还房贷。", "Vay vốn", "Trả tiền nợ mua nhà.", "Loan", "zh_daily_advanced"),
    ("房租", "Fángzū", "noun", "每个月交房租。", "Tiền thuê nhà", "Mỗi tháng đều phải đóng tiền nhà.", "Rent", "zh_daily_advanced"),
    ("装修", "Zhuāngxiū", "verb", "新房装修。", "Sửa chữa, trang trí nhà", "Trang hoàng lại nhà mới mua.", "Renovate", "zh_daily_advanced"),
    ("物业", "Wùyè", "noun", "物业管理。", "Ban quản lý tòa nhà", "Công ty quản lý dịch vụ khu đô thị.", "Property management", "zh_daily_advanced"),
    ("快递", "Kuàidì", "noun", "去拿快递。", "Bưu kiện, chuyển phát nhanh", "Ra lấy đồ shipper giao.", "Express delivery", "zh_daily_advanced"),
    ("驿站", "Yìzhàn", "noun", "快递驿站。", "Trạm nhận hàng", "Điểm gửi và nhận bưu kiện.", "Courier station", "zh_daily_advanced"),
    ("保姆", "Bǎomǔ", "noun", "请个保姆。", "Người giúp việc", "Thuê một cô bảo mẫu.", "Nanny", "zh_daily_advanced"),
    ("钟点工", "Zhōngdiǎngōng", "noun", "找个钟点工打扫。", "Người làm theo giờ", "Tìm người giúp việc theo giờ để dọn dẹp.", "Part-time worker", "zh_daily_advanced"),
    ("育儿", "Yù'ér", "noun", "育儿经验。", "Nuôi dạy con", "Chia sẻ kinh nghiệm chăm con.", "Parenting", "zh_daily_advanced"),
    ("养老", "Yǎnglǎo", "verb", "养老保险。", "Dưỡng lão", "Đóng bảo hiểm hưu trí.", "Elderly care", "zh_daily_advanced"),
    ("退休", "Tuìxiū", "verb", "退休金。", "Nghỉ hưu", "Lương nhận được khi về hưu.", "Retire", "zh_daily_advanced"),
    ("广场舞", "Guǎngchǎngwǔ", "noun", "大妈跳广场舞。", "Múa quảng trường", "Các thím đang nhảy múa ở quảng trường.", "Square dance", "zh_daily_advanced"),
    ("宅", "Zhái", "verb/adjective", "周末宅在家里。", "Ở rịt trong nhà (Otaku)", "Cuối tuần ru rú ở trong phòng.", "Stay at home", "zh_daily_advanced"),
    ("社交", "Shèjiāo", "noun", "社交圈。", "Giao tiếp xã hội", "Vòng tròn quan hệ xã hội.", "Social intercourse", "zh_daily_advanced"),
    ("独处", "Dúchǔ", "verb", "享受独处时光。", "Ở một mình", "Tận hưởng khoảnh khắc được ở một mình.", "Be alone", "zh_daily_advanced"),
    ("仪式感", "Yíshìgǎn", "noun", "生活需要仪式感。", "Cảm giác nghi thức", "Sống cũng cần tạo ra một chút nghi thức tinh thần.", "Sense of ceremony", "zh_daily_advanced"),
    ("小确幸", "Xiǎoquèxìng", "noun", "生活中的小确幸。", "Niềm hạnh phúc bé nhỏ", "Tìm thấy hạnh phúc nhỏ bé mà chắc chắn trong đời.", "Small happiness", "zh_daily_advanced"),

    # Expert (3)
    ("柴米油盐", "Cháimǐ yóuyán", "idiom", "柴米油盐的平淡生活。", "Cơm áo gạo tiền", "Cuộc sống bình dị xoay quanh cơm áo gạo tiền.", "Daily necessities", "zh_daily_expert"),
    ("鸡毛蒜皮", "Jīmáo suànpí", "idiom", "为鸡毛蒜皮的小事吵架。", "Lông gà vỏ tỏi", "Toàn cãi nhau vì dăm ba thứ vặt vãnh.", "Trivialities", "zh_daily_expert"),
    ("斤斤计较", "Jīnjīn jìjiào", "idiom", "买菜斤斤计较。", "So đo tính toán", "Đi chợ mua rau mà cũng phải mặc cả từng đồng.", "Haggle over every ounce", "zh_daily_expert"),
    ("朝九晚五", "Zhāojiǔ wǎnwǔ", "phrase", "朝九晚五的工作。", "Làm việc 9h sáng đến 5h chiều", "Công việc hành chính làm giờ cố định.", "9-to-5 job", "zh_daily_expert"),
    ("996工作制", "Jiǔjiǔliù gōngzuòzhì", "phrase", "互联网公司的996工作制。", "Chế độ 996", "Làm việc từ 9h sáng đến 9h tối, 6 ngày/tuần.", "996 working hour system", "zh_daily_expert"),
    ("内卷", "Nèijuǎn", "noun/verb", "行业内卷严重。", "Cuộn trong (cạnh tranh tiêu cực)", "Sự cạnh tranh khốc liệt không mang lại giá trị.", "Involution", "zh_daily_expert"),
    ("躺平", "Tǎngpíng", "verb", "年轻人选择躺平。", "Nằm thẳng", "Lựa chọn buông xuôi, không muốn nỗ lực nữa.", "Lie flat", "zh_daily_expert"),
    ("摸鱼", "Mōyú", "verb", "上班偷偷摸鱼。", "Bắt cá (lười biếng)", "Đi làm toàn lén lút lướt mạng chơi điện thoại.", "Slack off at work", "zh_daily_expert"),
    ("打工人", "Dǎgōngrén", "noun", "努力的打工人。", "Người làm thuê", "Phận làm công ăn lương luôn phải cố gắng.", "Wage earner", "zh_daily_expert"),
    ("社畜", "Shèchù", "noun", "每天加班的社畜。", "Gia súc công ty", "Nhân viên vắt kiệt sức vì công ty.", "Corporate slave", "zh_daily_expert"),
    ("佛系", "Fóxì", "adjective", "佛系青年。", "Thanh niên hệ Phật", "Tuýp người sống sao cũng được, không bon chen.", "Buddha-like", "zh_daily_expert"),
    ("极简生活", "Jíjiǎn shēnghuó", "noun", "推崇极简生活。", "Lối sống tối giản", "Cổ xúy phong cách sống giảm thiểu đồ đạc.", "Minimalist life", "zh_daily_expert"),
    ("断舍离", "Duànshělí", "phrase", "进行一次断舍离。", "Đoạn, xả, ly", "Vứt bỏ những vật dụng không thực sự cần thiết.", "Decluttering", "zh_daily_expert"),
    ("消费降级", "Xiāofèi jiàngjí", "noun", "面对经济压力的消费降级。", "Giảm thiểu chi tiêu", "Thắt chặt hầu bao trước áp lực kinh tế.", "Consumption downgrade", "zh_daily_expert"),
    ("财务自由", "Cáiwù zìyóu", "noun", "实现财务自由。", "Tự do tài chính", "Cố gắng đạt đến ngưỡng độc lập tài chính.", "Financial freedom", "zh_daily_expert"),
    ("被动收入", "Bèidòng shōurù", "noun", "增加被动收入。", "Thu nhập thụ động", "Tìm cách gia tăng nguồn tiền tự sinh lời.", "Passive income", "zh_daily_expert"),
    ("斜杠青年", "Xiégàng qīngnián", "noun", "身兼数职的斜杠青年。", "Thanh niên gạch chéo", "Những người trẻ làm một lúc nhiều công việc.", "Slash youth", "zh_daily_expert"),
    ("自由职业者", "Zìyóu zhíyèzhě", "noun", "成为自由职业者。", "Người làm nghề tự do", "Quyết định trở thành một freelancer.", "Freelancer", "zh_daily_expert"),
    ("丁克家族", "Dīngkè jiāzú", "noun", "选择做丁克家族。", "Gia đình DINK", "Vợ chồng thỏa thuận không sinh con.", "DINK family", "zh_daily_expert"),
    ("空巢老人", "Kōngcháo lǎorén", "noun", "关注空巢老人。", "Người già neo đơn", "Cần quan tâm tới người già sống thui thủi một mình.", "Empty-nest elderly", "zh_daily_expert"),
    ("留守儿童", "Liúshǒu értóng", "noun", "乡村留守儿童。", "Trẻ em ở lại quê", "Thương xót những đứa bé ở quê không có bố mẹ kề bên.", "Left-behind children", "zh_daily_expert"),
    ("婆媳关系", "Póxí guānxì", "noun", "难处的婆媳关系。", "Quan hệ mẹ chồng nàng dâu", "Bài toán hóc búa mang tên mẹ chồng - con dâu.", "Mother-in-law and daughter-in-law relationship", "zh_daily_expert"),
    ("代沟", "Dàigōu", "noun", "和父母有代沟。", "Khoảng cách thế hệ", "Tôi với bố mẹ thường khó nói chuyện vì khác biệt.", "Generation gap", "zh_daily_expert"),
    ("丧偶式育儿", "Sàng'ǒu shì yù'ér", "noun", "反对丧偶式育儿。", "Nuôi con như góa bụa", "Chống lại việc một người phó mặc chuyện chăm con.", "Widowed-style parenting", "zh_daily_expert"),
    ("妈宝男", "Mābǎonán", "noun", "遇到一个妈宝男。", "Con trai cưng của mẹ", "Đen đủi quen trúng anh chàng lúc nào cũng hỏi ý mẹ.", "Mama's boy", "zh_daily_expert"),
    ("扶弟魔", "Fúdìmó", "noun", "被称为扶弟魔。", "Gái cuồng giúp em trai", "Cô chị hy sinh quá đáng để chu cấp cho cậu em.", "Monster who helps younger brother", "zh_daily_expert"),
    ("随份子", "Suífènzi", "verb", "结婚要随份子。", "Tiền mừng (cưới hỏi)", "Đi đám cưới là lại phải bỏ bao lì xì.", "Give gift money", "zh_daily_expert"),
    ("人情世故", "Rénqíng shìgù", "noun", "不懂人情世故。", "Đối nhân xử thế", "Trẻ người non dạ chưa rành chuyện xã giao đời thường.", "Ways of the world", "zh_daily_expert"),
    ("走亲戚", "Zǒu qīnqi", "phrase", "过年走亲戚。", "Đi thăm hỏi họ hàng", "Ngày tết thì phải đi chúc tết bà con.", "Visit relatives", "zh_daily_expert"),
    ("柴米油盐酱醋茶", "Cháimǐ yóuyán jiàngcù chá", "phrase", "生活的七件事。", "Bảy nhu yếu phẩm", "Bảy thứ không thể thiếu trong bếp người phương Đông.", "Seven necessities of life", "zh_daily_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_zh, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "zh",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_zh,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Travel & Daily Life - Chinese) to DB!")
