import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Health
    {"id": "zh_health_beginner", "languageCode": "zh", "title": "健康", "subtitle": "Sức khoẻ - Beginner", "iconEmoji": "🏥", "level": "Beginner", "colorHex": "#EF4444", "cardCount": 30},
    {"id": "zh_health_intermediate", "languageCode": "zh", "title": "健康", "subtitle": "Sức khoẻ - Intermediate", "iconEmoji": "🏥", "level": "Intermediate", "colorHex": "#DC2626", "cardCount": 30},
    {"id": "zh_health_advanced", "languageCode": "zh", "title": "健康", "subtitle": "Sức khoẻ - Advanced", "iconEmoji": "🏥", "level": "Advanced", "colorHex": "#B91C1C", "cardCount": 30},
    {"id": "zh_health_expert", "languageCode": "zh", "title": "健康", "subtitle": "Sức khoẻ - Expert", "iconEmoji": "🏥", "level": "Expert", "colorHex": "#991B1B", "cardCount": 30},
    
    # Weather
    {"id": "zh_weather_beginner", "languageCode": "zh", "title": "天气", "subtitle": "Thời tiết - Beginner", "iconEmoji": "☀️", "level": "Beginner", "colorHex": "#38BDF8", "cardCount": 30},
    {"id": "zh_weather_intermediate", "languageCode": "zh", "title": "天气", "subtitle": "Thời tiết - Intermediate", "iconEmoji": "☀️", "level": "Intermediate", "colorHex": "#0EA5E9", "cardCount": 30},
    {"id": "zh_weather_advanced", "languageCode": "zh", "title": "天气", "subtitle": "Thời tiết - Advanced", "iconEmoji": "☀️", "level": "Advanced", "colorHex": "#0284C7", "cardCount": 30},
    {"id": "zh_weather_expert", "languageCode": "zh", "title": "天气", "subtitle": "Thời tiết - Expert", "iconEmoji": "☀️", "level": "Expert", "colorHex": "#0369A1", "cardCount": 30}
]

vocab_data = [
    # ---- HEALTH ----
    # Beginner (0)
    ("身体", "Shēntǐ", "noun", "身体好。", "Cơ thể, sức khỏe", "Sức khỏe tốt.", "Body", "zh_health_beginner"),
    ("头", "Tóu", "noun", "头疼。", "Đầu", "Đau đầu.", "Head", "zh_health_beginner"),
    ("眼睛", "Yǎnjing", "noun", "睁开眼睛。", "Mắt", "Mở mắt ra.", "Eyes", "zh_health_beginner"),
    ("耳朵", "Ěrduo", "noun", "用耳朵听。", "Tai", "Nghe bằng tai.", "Ear", "zh_health_beginner"),
    ("鼻子", "Bízi", "noun", "鼻子出血。", "Mũi", "Chảy máu mũi.", "Nose", "zh_health_beginner"),
    ("嘴", "Zuǐ", "noun", "张开嘴。", "Miệng", "Mở miệng ra.", "Mouth", "zh_health_beginner"),
    ("牙齿", "Yáchǐ", "noun", "刷牙。", "Răng", "Đánh răng.", "Tooth", "zh_health_beginner"),
    ("手", "Shǒu", "noun", "洗手。", "Tay", "Rửa tay.", "Hand", "zh_health_beginner"),
    ("脚", "Jiǎo", "noun", "脚疼。", "Chân (bàn chân)", "Đau chân.", "Foot", "zh_health_beginner"),
    ("腿", "Tuǐ", "noun", "大长腿。", "Chân (cẳng chân)", "Chân dài.", "Leg", "zh_health_beginner"),
    ("病", "Bìng", "noun/verb", "生病了。", "Bệnh, ốm", "Bị ốm rồi.", "Sick", "zh_health_beginner"),
    ("医生", "Yīshēng", "noun", "看医生。", "Bác sĩ", "Đi khám bác sĩ.", "Doctor", "zh_health_beginner"),
    ("医院", "Yīyuàn", "noun", "去医院。", "Bệnh viện", "Đến bệnh viện.", "Hospital", "zh_health_beginner"),
    ("药", "Yào", "noun", "吃药。", "Thuốc", "Uống thuốc.", "Medicine", "zh_health_beginner"),
    ("疼", "Téng", "adjective", "很疼。", "Đau", "Rất đau.", "Pain", "zh_health_beginner"),
    ("痛", "Tòng", "adjective", "肚子痛。", "Đau", "Đau bụng.", "Pain/Ache", "zh_health_beginner"),
    ("发烧", "Fāshāo", "verb", "发高烧。", "Sốt", "Sốt cao.", "Fever", "zh_health_beginner"),
    ("感冒", "Gǎnmào", "noun/verb", "经常感冒。", "Cảm cúm", "Thường xuyên bị cảm.", "Catch a cold", "zh_health_beginner"),
    ("咳嗽", "Késou", "verb", "咳嗽得很厉害。", "Ho", "Ho rất dữ dội.", "Cough", "zh_health_beginner"),
    ("舒服", "Shūfu", "adjective", "不舒服。", "Thoải mái", "Không khỏe, khó chịu.", "Comfortable", "zh_health_beginner"),
    ("休息", "Xiūxi", "noun/verb", "在家休息。", "Nghỉ ngơi", "Nghỉ ngơi ở nhà.", "Rest", "zh_health_beginner"),
    ("睡", "Shuì", "verb", "睡不着。", "Ngủ", "Không ngủ được.", "Sleep", "zh_health_beginner"),
    ("水", "Shuǐ", "noun", "多喝水。", "Nước", "Uống nhiều nước.", "Water", "zh_health_beginner"),
    ("健康", "Jiànkāng", "adjective/noun", "祝你健康。", "Khỏe mạnh", "Chúc bạn mạnh khỏe.", "Health", "zh_health_beginner"),
    ("胖", "Pàng", "adjective", "变胖了。", "Béo", "Béo lên rồi.", "Fat", "zh_health_beginner"),
    ("瘦", "Shòu", "adjective", "太瘦了。", "Gầy", "Gầy quá.", "Thin", "zh_health_beginner"),
    ("累", "Lèi", "adjective", "我很累。", "Mệt", "Tôi rất mệt.", "Tired", "zh_health_beginner"),
    ("饿", "È", "adjective", "肚子饿。", "Đói", "Đói bụng.", "Hungry", "zh_health_beginner"),
    ("饱", "Bǎo", "adjective", "吃饱了。", "No", "Ăn no rồi.", "Full", "zh_health_beginner"),
    ("渴", "Kě", "adjective", "口渴了。", "Khát", "Khát nước rồi.", "Thirsty", "zh_health_beginner"),

    # Intermediate (1)
    ("护士", "Hùshi", "noun", "白衣护士。", "Y tá", "Y tá áo trắng.", "Nurse", "zh_health_intermediate"),
    ("诊所", "Zhěnsuǒ", "noun", "私人诊所。", "Phòng khám", "Phòng khám tư nhân.", "Clinic", "zh_health_intermediate"),
    ("救护车", "Jiùhùchē", "noun", "叫救护车。", "Xe cứu thương", "Gọi xe cứu thương.", "Ambulance", "zh_health_intermediate"),
    ("药店", "Yàodiàn", "noun", "去药店买药。", "Hiệu thuốc", "Ra hiệu thuốc mua thuốc.", "Pharmacy", "zh_health_intermediate"),
    ("挂号", "Guàhào", "verb", "挂号看病。", "Đăng ký khám", "Lấy số khám bệnh.", "Register (hospital)", "zh_health_intermediate"),
    ("检查", "Jiǎnchá", "noun/verb", "身体检查。", "Kiểm tra, khám", "Kiểm tra sức khỏe.", "Checkup", "zh_health_intermediate"),
    ("抽血", "Chōuxuè", "verb", "抽血化验。", "Lấy máu", "Lấy máu xét nghiệm.", "Draw blood", "zh_health_intermediate"),
    ("打针", "Dǎzhēn", "verb", "怕打针。", "Tiêm", "Sợ tiêm.", "Injection", "zh_health_intermediate"),
    ("输液", "Shūyè", "verb", "在医院输液。", "Truyền dịch", "Truyền dịch trong bệnh viện.", "IV drip", "zh_health_intermediate"),
    ("手术", "Shǒushù", "noun/verb", "做手术。", "Phẫu thuật", "Làm phẫu thuật.", "Surgery", "zh_health_intermediate"),
    ("出院", "Chūyuàn", "verb", "明天出院。", "Xuất viện", "Ngày mai xuất viện.", "Discharged from hospital", "zh_health_intermediate"),
    ("症状", "Zhèngzhuàng", "noun", "感冒症状。", "Triệu chứng", "Triệu chứng của cảm cúm.", "Symptom", "zh_health_intermediate"),
    ("传染", "Chuánrǎn", "verb", "会传染吗？", "Truyền nhiễm", "Có lây không?", "Contagious", "zh_health_intermediate"),
    ("病毒", "Bìngdú", "noun", "感染病毒。", "Virus", "Nhiễm virus.", "Virus", "zh_health_intermediate"),
    ("细菌", "Xìjūn", "noun", "杀死细菌。", "Vi khuẩn", "Tiêu diệt vi khuẩn.", "Bacteria", "zh_health_intermediate"),
    ("肚子", "Dùzi", "noun", "肚子疼。", "Bụng", "Đau bụng.", "Stomach", "zh_health_intermediate"),
    ("胃", "Wèi", "noun", "胃疼。", "Dạ dày", "Đau dạ dày.", "Stomach (organ)", "zh_health_intermediate"),
    ("心脏", "Xīnzàng", "noun", "心脏跳动。", "Trái tim", "Tim đập.", "Heart", "zh_health_intermediate"),
    ("血压", "Xuèyā", "noun", "量血压。", "Huyết áp", "Đo huyết áp.", "Blood pressure", "zh_health_intermediate"),
    ("减肥", "Jiǎnféi", "noun/verb", "运动减肥。", "Giảm cân", "Tập thể dục giảm cân.", "Lose weight", "zh_health_intermediate"),
    ("锻炼", "Duànliàn", "verb", "每天锻炼身体。", "Tập thể dục", "Rèn luyện cơ thể mỗi ngày.", "Exercise", "zh_health_intermediate"),
    ("饮食", "Yǐnshí", "noun", "注意饮食。", "Ăn uống", "Chú ý ăn uống.", "Diet", "zh_health_intermediate"),
    ("营养", "Yíngyǎng", "noun", "营养丰富。", "Dinh dưỡng", "Giàu dinh dưỡng.", "Nutrition", "zh_health_intermediate"),
    ("失眠", "Shīmián", "noun/verb", "昨晚失眠了。", "Mất ngủ", "Tối qua bị mất ngủ.", "Insomnia", "zh_health_intermediate"),
    ("疲劳", "Píláo", "noun/adjective", "缓解疲劳。", "Mệt mỏi", "Giảm bớt sự mệt mỏi.", "Fatigue", "zh_health_intermediate"),
    ("恢复", "Huīfù", "verb", "身体恢复。", "Hồi phục", "Cơ thể hồi phục.", "Recover", "zh_health_intermediate"),
    ("治病", "Zhìbìng", "verb", "治病救人。", "Chữa bệnh", "Chữa bệnh cứu người.", "Treat illness", "zh_health_intermediate"),
    ("过敏", "Guòmǐn", "noun/verb", "对花粉过敏。", "Dị ứng", "Dị ứng với phấn hoa.", "Allergy", "zh_health_intermediate"),
    ("严重", "Yánzhòng", "adjective", "病情严重。", "Nghiêm trọng", "Tình trạng bệnh nghiêm trọng.", "Serious", "zh_health_intermediate"),
    ("预防", "Yùfáng", "noun/verb", "预防感冒。", "Phòng ngừa", "Phòng ngừa cảm cúm.", "Prevent", "zh_health_intermediate"),

    # Advanced (2)
    ("体质", "Tǐzhì", "noun", "体质虚弱。", "Thể chất", "Thể chất ốm yếu.", "Constitution (body)", "zh_health_advanced"),
    ("免疫力", "Miǎnyìlì", "noun", "提高免疫力。", "Sức đề kháng", "Nâng cao hệ miễn dịch.", "Immunity", "zh_health_advanced"),
    ("慢性病", "Mànxìngbìng", "noun", "患有慢性病。", "Bệnh mãn tính", "Mắc bệnh mãn tính.", "Chronic disease", "zh_health_advanced"),
    ("急诊", "Jízhěn", "noun", "看急诊。", "Cấp cứu", "Đi khám cấp cứu.", "Emergency", "zh_health_advanced"),
    ("门诊", "Ménzhěn", "noun", "门诊大楼。", "Phòng khám ngoại trú", "Tòa nhà khám bệnh ngoại trú.", "Outpatient clinic", "zh_health_advanced"),
    ("处方", "Chǔfāng", "noun", "开处方药。", "Đơn thuốc", "Kê đơn thuốc.", "Prescription", "zh_health_advanced"),
    ("诊断", "Zhěnduàn", "noun/verb", "确诊。", "Chẩn đoán", "Chẩn đoán xác định.", "Diagnosis", "zh_health_advanced"),
    ("康复", "Kāngfù", "noun/verb", "康复中心。", "Phục hồi", "Trung tâm phục hồi chức năng.", "Rehabilitation", "zh_health_advanced"),
    ("疗程", "Liáochéng", "noun", "一个疗程。", "Liệu trình", "Một liệu trình điều trị.", "Course of treatment", "zh_health_advanced"),
    ("副作用", "Fùzuòyòng", "noun", "药物副作用。", "Tác dụng phụ", "Tác dụng phụ của thuốc.", "Side effect", "zh_health_advanced"),
    ("疫苗", "Yìmiáo", "noun", "打疫苗。", "Vắc-xin", "Tiêm vắc xin.", "Vaccine", "zh_health_advanced"),
    ("抗体", "Kàngtǐ", "noun", "产生抗体。", "Kháng thể", "Sản sinh kháng thể.", "Antibody", "zh_health_advanced"),
    ("癌症", "Áizhèng", "noun", "癌症晚期。", "Bệnh ung thư", "Ung thư giai đoạn cuối.", "Cancer", "zh_health_advanced"),
    ("肿瘤", "Zhǒngliú", "noun", "良性肿瘤。", "Khối u", "Khối u lành tính.", "Tumor", "zh_health_advanced"),
    ("糖尿病", "Tángniàobìng", "noun", "糖尿病患者。", "Bệnh tiểu đường", "Bệnh nhân tiểu đường.", "Diabetes", "zh_health_advanced"),
    ("高血压", "Gāoxuèyā", "noun", "预防高血压。", "Huyết áp cao", "Phòng chống cao huyết áp.", "High blood pressure", "zh_health_advanced"),
    ("抑郁症", "Yìyùzhèng", "noun", "治疗抑郁症。", "Bệnh trầm cảm", "Điều trị bệnh trầm cảm.", "Depression", "zh_health_advanced"),
    ("焦虑", "Jiāolǜ", "noun/adjective", "感到焦虑。", "Lo âu", "Cảm thấy lo âu.", "Anxiety", "zh_health_advanced"),
    ("心理", "Xīnlǐ", "noun", "心理健康。", "Tâm lý", "Sức khỏe tâm lý.", "Psychology", "zh_health_advanced"),
    ("保健", "Bǎojiàn", "noun/verb", "保健品。", "Chăm sóc sức khỏe", "Thực phẩm chức năng (bảo vệ sức khỏe).", "Health care", "zh_health_advanced"),
    ("养生", "Yǎngshēng", "noun/verb", "注重养生。", "Dưỡng sinh", "Chú trọng dưỡng sinh.", "Health preservation", "zh_health_advanced"),
    ("针灸", "Zhēnjiǔ", "noun/verb", "中医针灸。", "Châm cứu", "Châm cứu Đông y.", "Acupuncture", "zh_health_advanced"),
    ("中药", "Zhōngyào", "noun", "喝中药。", "Thuốc Đông y", "Uống thuốc Bắc.", "Chinese medicine", "zh_health_advanced"),
    ("西药", "Xīyào", "noun", "西药见效快。", "Thuốc Tây y", "Thuốc Tây có hiệu quả nhanh.", "Western medicine", "zh_health_advanced"),
    ("脉搏", "Màibó", "noun", "摸脉搏。", "Mạch đập", "Bắt mạch.", "Pulse", "zh_health_advanced"),
    ("呼吸", "Hūxī", "noun/verb", "深呼吸。", "Hô hấp, thở", "Hít thở sâu.", "Breathe", "zh_health_advanced"),
    ("消化", "Xiāohuà", "noun/verb", "消化不良。", "Tiêu hóa", "Khó tiêu.", "Digestion", "zh_health_advanced"),
    ("骨折", "Gǔzhé", "noun/verb", "腿部骨折。", "Gãy xương", "Bị gãy xương chân.", "Fracture", "zh_health_advanced"),
    ("感染", "Gǎnrǎn", "noun/verb", "伤口感染。", "Nhiễm trùng", "Vết thương bị nhiễm trùng.", "Infection", "zh_health_advanced"),
    ("急救", "Jíjiù", "noun/verb", "掌握急救知识。", "Sơ cứu", "Nắm vững kiến thức sơ cứu.", "First aid", "zh_health_advanced"),

    # Expert (3)
    ("临床", "Línchuáng", "noun", "临床试验。", "Lâm sàng", "Thử nghiệm lâm sàng.", "Clinical", "zh_health_expert"),
    ("病理", "Bìnglǐ", "noun", "病理分析。", "Bệnh lý", "Phân tích bệnh lý.", "Pathology", "zh_health_expert"),
    ("基因突变", "Jīyīn tūbiàn", "noun", "基因突变导致疾病。", "Đột biến gen", "Đột biến gen gây bệnh.", "Gene mutation", "zh_health_expert"),
    ("靶向治疗", "Bǎxiàng zhìliáo", "noun", "癌症靶向治疗。", "Điều trị trúng đích", "Liệu pháp nhắm trúng đích trị ung thư.", "Targeted therapy", "zh_health_expert"),
    ("干细胞", "Gànxìbāo", "noun", "干细胞移植。", "Tế bào gốc", "Cấy ghép tế bào gốc.", "Stem cell", "zh_health_expert"),
    ("微生物", "Wēishēngwù", "noun", "肠道微生物。", "Vi sinh vật", "Hệ vi sinh vật đường ruột.", "Microorganism", "zh_health_expert"),
    ("流行病学", "Liúxíng bìngxué", "noun", "流行病学调查。", "Dịch tễ học", "Điều tra dịch tễ học.", "Epidemiology", "zh_health_expert"),
    ("亚健康", "Yàjiànkāng", "noun", "处于亚健康状态。", "Trạng thái kém khỏe mạnh", "Đang ở trong tình trạng ủ bệnh.", "Sub-health", "zh_health_expert"),
    ("安慰剂效应", "Ānwèijì xiàoyìng", "noun", "安慰剂效应起作用。", "Hiệu ứng giả dược", "Tác dụng của thuốc giả dược.", "Placebo effect", "zh_health_expert"),
    ("并发症", "Bìngfāzhèng", "noun", "预防并发症。", "Biến chứng", "Ngăn ngừa các biến chứng.", "Complication", "zh_health_expert"),
    ("慢性阻塞性肺疾病", "Mànxìng zǔsè xìng fèi jíbìng", "noun", "COPD（慢阻肺）。", "Bệnh COPD", "Bệnh phổi tắc nghẽn mãn tính.", "COPD", "zh_health_expert"),
    ("冠心病", "Guānxīnbìng", "noun", "冠心病发作。", "Bệnh mạch vành", "Lên cơn đau tim (bệnh mạch vành).", "Coronary heart disease", "zh_health_expert"),
    ("阿尔茨海默症", "Ā'ěrcíhǎimòzhèng", "noun", "俗称老年痴呆。", "Bệnh Alzheimer", "Thường gọi là chứng mất trí nhớ tuổi già.", "Alzheimer's disease", "zh_health_expert"),
    ("自身免疫性疾病", "Zìshēn miǎnyìxìng jíbìng", "noun", "患有自身免疫性疾病。", "Bệnh tự miễn", "Mắc bệnh tự miễn dịch.", "Autoimmune disease", "zh_health_expert"),
    ("神经衰弱", "Shénjīng shuāiruò", "noun", "长期熬夜导致神经衰弱。", "Suy nhược thần kinh", "Thức khuya lâu ngày dẫn đến suy nhược.", "Neurasthenia", "zh_health_expert"),
    ("创伤后应激障碍", "Chuàngshāng hòu yìngjī zhàng'ài", "noun", "PTSD的治疗。", "Rối loạn PTSD", "Điều trị rối loạn căng thẳng sau sang chấn.", "PTSD", "zh_health_expert"),
    ("内分泌失调", "Nèifēnmì shītiáo", "noun", "内分泌失调长痘痘。", "Rối loạn nội tiết", "Nổi mụn do rối loạn nội tiết.", "Endocrine disorder", "zh_health_expert"),
    ("新陈代谢", "Xīnchéndàixiè", "noun", "促进新陈代谢。", "Trao đổi chất", "Thúc đẩy sự trao đổi chất.", "Metabolism", "zh_health_expert"),
    ("胆固醇", "Dǎngùchún", "noun", "胆固醇偏高。", "Cholesterol", "Mức Cholesterol hơi cao.", "Cholesterol", "zh_health_expert"),
    ("血糖", "Xuètáng", "noun", "测血糖。", "Đường huyết", "Đo lượng đường trong máu.", "Blood sugar", "zh_health_expert"),
    ("血压计", "Xuèyājì", "noun", "电子血压计。", "Máy đo huyết áp", "Máy đo huyết áp điện tử.", "Sphygmomanometer", "zh_health_expert"),
    ("心电图", "Xīndiàntú", "noun", "做心电图。", "Điện tâm đồ", "Đo điện tâm đồ (ECG).", "Electrocardiogram", "zh_health_expert"),
    ("核磁共振", "Hécí gòngzhèn", "noun", "做核磁共振检查。", "Chụp MRI", "Chụp cộng hưởng từ.", "MRI", "zh_health_expert"),
    ("超声波", "Chāoshēngbō", "noun", "B超检查。", "Siêu âm", "Khám siêu âm.", "Ultrasound", "zh_health_expert"),
    ("医患纠纷", "Yīhuàn jiūfēn", "noun", "解决医患纠纷。", "Tranh chấp y tế", "Giải quyết bất đồng giữa y bác sĩ và bệnh nhân.", "Medical dispute", "zh_health_expert"),
    ("医疗事故", "Yīliáo shìgù", "noun", "发生医疗事故。", "Sự cố y khoa", "Xảy ra tai biến y khoa.", "Medical malpractice", "zh_health_expert"),
    ("安乐死", "Ānlèsǐ", "noun", "安乐死合法化。", "Cái chết nhân đạo", "Hợp pháp hóa cái chết êm ái.", "Euthanasia", "zh_health_expert"),
    ("基因编辑", "Jīyīn biānjí", "noun", "基因编辑技术。", "Chỉnh sửa gen", "Công nghệ chỉnh sửa Gen.", "Gene editing", "zh_health_expert"),
    ("远程医疗", "Yuǎnchéng yīliáo", "noun", "远程医疗服务。", "Y tế từ xa", "Dịch vụ khám chữa bệnh từ xa.", "Telemedicine", "zh_health_expert"),
    ("公共卫生", "Gōnggòng wèishēng", "noun", "公共卫生危机。", "Y tế công cộng", "Khủng hoảng y tế cộng đồng.", "Public health", "zh_health_expert"),

    # ---- WEATHER ----
    # Beginner (0)
    ("天气", "Tiānqì", "noun", "天气很好。", "Thời tiết", "Thời tiết rất đẹp.", "Weather", "zh_weather_beginner"),
    ("晴天", "Qíngtiān", "noun", "今天是晴天。", "Ngày nắng", "Hôm nay trời nắng.", "Sunny day", "zh_weather_beginner"),
    ("阴天", "Yīntiān", "noun", "明天阴天。", "Ngày râm, âm u", "Ngày mai trời nhiều mây.", "Cloudy day", "zh_weather_beginner"),
    ("雨", "Yǔ", "noun", "下雨了。", "Mưa", "Trời mưa rồi.", "Rain", "zh_weather_beginner"),
    ("雪", "Xuě", "noun", "下雪了。", "Tuyết", "Tuyết rơi rồi.", "Snow", "zh_weather_beginner"),
    ("风", "Fēng", "noun", "刮风了。", "Gió", "Gió thổi rồi.", "Wind", "zh_weather_beginner"),
    ("云", "Yún", "noun", "白云。", "Mây", "Đám mây trắng.", "Cloud", "zh_weather_beginner"),
    ("太阳", "Tàiyáng", "noun", "太阳出来了。", "Mặt trời", "Mặt trời ló rạng.", "Sun", "zh_weather_beginner"),
    ("月亮", "Yuèliang", "noun", "月亮很圆。", "Mặt trăng", "Mặt trăng rất tròn.", "Moon", "zh_weather_beginner"),
    ("星星", "Xīngxing", "noun", "看星星。", "Ngôi sao", "Ngắm sao.", "Star", "zh_weather_beginner"),
    ("天空", "Tiānkōng", "noun", "蓝蓝的天空。", "Bầu trời", "Bầu trời xanh thẳm.", "Sky", "zh_weather_beginner"),
    ("气温", "Qìwēn", "noun", "气温很高。", "Nhiệt độ", "Nhiệt độ rất cao.", "Temperature", "zh_weather_beginner"),
    ("度", "Dù", "noun/measure word", "三十度。", "Độ", "30 độ.", "Degree", "zh_weather_beginner"),
    ("冷", "Lěng", "adjective", "今天很冷。", "Lạnh", "Hôm nay rất lạnh.", "Cold", "zh_weather_beginner"),
    ("热", "Rè", "adjective", "夏天很热。", "Nóng", "Mùa hè rất nóng.", "Hot", "zh_weather_beginner"),
    ("暖和", "Nuǎnhuo", "adjective", "春天很暖和。", "Ấm áp", "Mùa xuân thật ấm áp.", "Warm", "zh_weather_beginner"),
    ("凉快", "Liángkuai", "adjective", "秋天很凉快。", "Mát mẻ", "Mùa thu rất mát mẻ.", "Cool", "zh_weather_beginner"),
    ("下", "Xià", "verb", "下大雨。", "Rơi (mưa, tuyết)", "Mưa to đổ xuống.", "Fall (rain/snow)", "zh_weather_beginner"),
    ("刮", "Guā", "verb", "刮大风。", "Thổi (gió)", "Gió to thổi.", "Blow (wind)", "zh_weather_beginner"),
    ("春天", "Chūntiān", "noun", "春天来了。", "Mùa xuân", "Mùa xuân đến rồi.", "Spring", "zh_weather_beginner"),
    ("夏天", "Xiàtiān", "noun", "夏天很热。", "Mùa hè", "Mùa hè nóng bức.", "Summer", "zh_weather_beginner"),
    ("秋天", "Qiūtiān", "noun", "秋天的树叶。", "Mùa thu", "Lá cây mùa thu.", "Autumn", "zh_weather_beginner"),
    ("冬天", "Dōngtiān", "noun", "冬天很冷。", "Mùa đông", "Mùa đông rất lạnh.", "Winter", "zh_weather_beginner"),
    ("早上", "Zǎoshang", "noun", "早上好。", "Buổi sáng", "Chào buổi sáng.", "Morning", "zh_weather_beginner"),
    ("中午", "Zhōngwǔ", "noun", "中午吃饭。", "Buổi trưa", "Ăn cơm trưa.", "Noon", "zh_weather_beginner"),
    ("晚上", "Wǎnshang", "noun", "晚上见。", "Buổi tối", "Hẹn gặp tối nay.", "Evening", "zh_weather_beginner"),
    ("今天", "Jīntiān", "noun", "今天天气不错。", "Hôm nay", "Thời tiết hôm nay không tệ.", "Today", "zh_weather_beginner"),
    ("明天", "Míngtiān", "noun", "明天会下雨。", "Ngày mai", "Ngày mai sẽ có mưa.", "Tomorrow", "zh_weather_beginner"),
    ("昨天", "Zuótiān", "noun", "昨天是晴天。", "Hôm qua", "Hôm qua trời nắng.", "Yesterday", "zh_weather_beginner"),
    ("季节", "Jìjié", "noun", "四个季节。", "Mùa", "Bốn mùa.", "Season", "zh_weather_beginner"),

    # Intermediate (1)
    ("天气预报", "Tiānqì yùbào", "noun", "看天气预报。", "Dự báo thời tiết", "Xem dự báo thời tiết.", "Weather forecast", "zh_weather_intermediate"),
    ("气候", "Qìhòu", "noun", "气候变化。", "Khí hậu", "Sự thay đổi khí hậu.", "Climate", "zh_weather_intermediate"),
    ("湿度", "Shīdù", "noun", "湿度很大。", "Độ ẩm", "Độ ẩm rất cao.", "Humidity", "zh_weather_intermediate"),
    ("台风", "Táifēng", "noun", "台风来了。", "Bão", "Bão ập đến rồi.", "Typhoon", "zh_weather_intermediate"),
    ("雷", "Léi", "noun", "打雷了。", "Sấm", "Có sấm chớp.", "Thunder", "zh_weather_intermediate"),
    ("闪电", "Shǎndiàn", "noun", "有闪电。", "Chớp", "Có tia chớp.", "Lightning", "zh_weather_intermediate"),
    ("雾", "Wù", "noun", "早上有雾。", "Sương mù", "Buổi sáng có sương mù.", "Fog", "zh_weather_intermediate"),
    ("彩虹", "Cǎihóng", "noun", "雨后彩虹。", "Cầu vồng", "Cầu vồng sau cơn mưa.", "Rainbow", "zh_weather_intermediate"),
    ("阵雨", "Zhènyǔ", "noun", "局部有阵雨。", "Mưa rào", "Có mưa rào rải rác.", "Shower", "zh_weather_intermediate"),
    ("暴雨", "Bàoyǔ", "noun", "暴雨警告。", "Mưa to", "Cảnh báo mưa lớn.", "Heavy rain", "zh_weather_intermediate"),
    ("暴风雪", "Bàofēngxuě", "noun", "遇到暴风雪。", "Bão tuyết", "Gặp phải bão tuyết.", "Blizzard", "zh_weather_intermediate"),
    ("冰雹", "Bīngbáo", "noun", "下冰雹了。", "Mưa đá", "Trời đổ mưa đá.", "Hail", "zh_weather_intermediate"),
    ("干燥", "Gānzào", "adjective", "空气很干燥。", "Khô hanh", "Không khí rất hanh khô.", "Dry", "zh_weather_intermediate"),
    ("潮湿", "Cháoshī", "adjective", "天气潮湿。", "Ẩm ướt", "Thời tiết nồm ẩm.", "Humid", "zh_weather_intermediate"),
    ("闷热", "Mēnrè", "adjective", "闷热的夏天。", "Oi bức", "Mùa hè oi ả.", "Muggy", "zh_weather_intermediate"),
    ("寒冷", "Hánlěng", "adjective", "寒冷的冬天。", "Rét mướt", "Mùa đông rét căm căm.", "Cold", "zh_weather_intermediate"),
    ("冰", "Bīng", "noun", "结冰了。", "Băng, đá", "Nước đóng băng rồi.", "Ice", "zh_weather_intermediate"),
    ("零下", "Língxià", "noun", "零下十度。", "Âm độ", "Âm mười độ.", "Below zero", "zh_weather_intermediate"),
    ("阳光", "Yángguāng", "noun", "阳光明媚。", "Ánh nắng", "Ánh nắng chan hòa.", "Sunshine", "zh_weather_intermediate"),
    ("紫外线", "Zǐwàixiàn", "noun", "防紫外线。", "Tia cực tím", "Chống tia tử ngoại.", "UV rays", "zh_weather_intermediate"),
    ("灾害", "Zāihài", "noun", "自然灾害。", "Thảm họa, thiên tai", "Thiên tai tự nhiên.", "Disaster", "zh_weather_intermediate"),
    ("洪水", "Hóngshuǐ", "noun", "发洪水。", "Lũ lụt", "Xảy ra ngập lụt.", "Flood", "zh_weather_intermediate"),
    ("旱灾", "Hànzāi", "noun", "发生旱灾。", "Hạn hán", "Hạn hán diễn ra.", "Drought", "zh_weather_intermediate"),
    ("地震", "Dìzhèn", "noun", "发生了地震。", "Động đất", "Xảy ra động đất.", "Earthquake", "zh_weather_intermediate"),
    ("海啸", "Hǎixiào", "noun", "海啸预警。", "Sóng thần", "Cảnh báo sóng thần.", "Tsunami", "zh_weather_intermediate"),
    ("预警", "Yùjǐng", "noun/verb", "红色预警。", "Cảnh báo", "Báo động đỏ.", "Warning", "zh_weather_intermediate"),
    ("防灾", "Fángzāi", "noun/verb", "防灾减灾。", "Phòng chống thiên tai", "Phòng chống giảm nhẹ thiên tai.", "Disaster prevention", "zh_weather_intermediate"),
    ("融化", "Rónghuà", "verb", "雪融化了。", "Tan chảy", "Tuyết đã tan rồi.", "Melt", "zh_weather_intermediate"),
    ("结冰", "Jiébīng", "verb", "湖面结冰了。", "Đóng băng", "Mặt hồ đóng băng.", "Freeze", "zh_weather_intermediate"),
    ("避雨", "Bìyǔ", "verb", "找个地方避雨。", "Trú mưa", "Tìm chỗ để trú mưa.", "Shelter from rain", "zh_weather_intermediate"),

    # Advanced (2)
    ("异常气候", "Yìcháng qìhòu", "noun", "异常气候频发。", "Thời tiết bất thường", "Khí hậu dị thường xuất hiện nhiều.", "Abnormal climate", "zh_weather_advanced"),
    ("厄尔尼诺", "È'ěrnínuò", "noun", "厄尔尼诺现象。", "Hiện tượng El Nino", "Hiện tượng El Niño.", "El Nino", "zh_weather_advanced"),
    ("拉尼娜", "Lānínà", "noun", "拉尼娜现象。", "Hiện tượng La Nina", "Hiện tượng La Niña.", "La Nina", "zh_weather_advanced"),
    ("气压", "Qìyā", "noun", "低气压。", "Khí áp", "Áp suất thấp.", "Air pressure", "zh_weather_advanced"),
    ("冷锋", "Lěngfēng", "noun", "冷锋过境。", "Frông lạnh", "Khối không khí lạnh đi qua.", "Cold front", "zh_weather_advanced"),
    ("暖锋", "Nuǎnfēng", "noun", "暖锋带来降水。", "Frông nóng", "Ranh giới ấm mang đến mưa.", "Warm front", "zh_weather_advanced"),
    ("降水量", "Jiàngshuǐliàng", "noun", "年降水量。", "Lượng mưa", "Lượng nước mưa hàng năm.", "Precipitation", "zh_weather_advanced"),
    ("能见度", "Néngjiàndù", "noun", "能见度低。", "Tầm nhìn xa", "Tầm nhìn bị hạn chế.", "Visibility", "zh_weather_advanced"),
    ("霜冻", "Shuāngdòng", "noun", "霜冻警报。", "Sương giá", "Cảnh báo băng giá.", "Frost", "zh_weather_advanced"),
    ("露水", "Lùshuǐ", "noun", "早晨的露水。", "Sương mai", "Giọt sương sớm.", "Dew", "zh_weather_advanced"),
    ("雾霾", "Wùmái", "noun", "严重的雾霾。", "Sương mù độc hại", "Khói bụi mù mịt.", "Smog", "zh_weather_advanced"),
    ("沙尘暴", "Shāchénbào", "noun", "遭遇沙尘暴。", "Bão cát", "Gặp bão cát sa mạc.", "Sandstorm", "zh_weather_advanced"),
    ("龙卷风", "Lóngjuǎnfēng", "noun", "龙卷风袭击。", "Lốc xoáy", "Bị vòi rồng càn quét.", "Tornado", "zh_weather_advanced"),
    ("泥石流", "Níshíliú", "noun", "防范泥石流。", "Sạt lở đất, lũ bùn", "Đề phòng sạt lở bùn đá.", "Mudslide", "zh_weather_advanced"),
    ("全球变暖", "Quánqiú biànnuǎn", "noun", "全球变暖加剧。", "Sự nóng lên toàn cầu", "Trái đất nóng lên.", "Global warming", "zh_weather_advanced"),
    ("温室效应", "Wēnshì xiàoyìng", "noun", "温室效应的影响。", "Hiệu ứng nhà kính", "Ảnh hưởng của hiệu ứng nhà kính.", "Greenhouse effect", "zh_weather_advanced"),
    ("碳排放", "Tànpáifàng", "noun", "减少碳排放。", "Khí thải carbon", "Giảm thiểu lượng khí thải carbon.", "Carbon emission", "zh_weather_advanced"),
    ("季风", "Jìfēng", "noun", "季风气候。", "Gió mùa", "Khí hậu gió mùa.", "Monsoon", "zh_weather_advanced"),
    ("寒潮", "Háncháo", "noun", "寒潮来袭。", "Đợt không khí lạnh", "Đợt rét đậm tràn về.", "Cold wave", "zh_weather_advanced"),
    ("热浪", "Rèlàng", "noun", "席卷欧洲的热浪。", "Đợt sóng nóng", "Làn sóng nhiệt thiêu đốt châu Âu.", "Heatwave", "zh_weather_advanced"),
    ("气象局", "Qìxiàngjú", "noun", "气象局发布消息。", "Cục khí tượng", "Cơ quan khí tượng báo tin.", "Meteorological Bureau", "zh_weather_advanced"),
    ("观测", "Guāncè", "noun/verb", "气象观测站。", "Quan trắc", "Trạm theo dõi thời tiết.", "Observation", "zh_weather_advanced"),
    ("卫星云图", "Wèixīng yúntú", "noun", "分析卫星云图。", "Bản đồ mây vệ tinh", "Phân tích ảnh chụp mây từ vệ tinh.", "Satellite cloud map", "zh_weather_advanced"),
    ("局部", "Júbù", "noun/adjective", "局部地区有雨。", "Cục bộ, một phần", "Có mưa rào rải rác một vài nơi.", "Local", "zh_weather_advanced"),
    ("预计", "Yùjì", "verb", "预计明天转晴。", "Dự kiến", "Dự báo ngày mai trời hửng nắng.", "Expect", "zh_weather_advanced"),
    ("持续", "Chíxù", "verb", "降雨将持续三天。", "Kéo dài, liên tục", "Mưa sẽ kéo dài trong 3 ngày.", "Continue", "zh_weather_advanced"),
    ("缓解", "Huǎnjiě", "verb", "旱情得到缓解。", "Làm dịu", "Tình trạng hạn hán đã thuyên giảm.", "Alleviate", "zh_weather_advanced"),
    ("登陆", "Dēnglù", "verb", "台风即将在沿海登陆。", "Đổ bộ", "Bão sắp đổ bộ vào vùng duyên hải.", "Land", "zh_weather_advanced"),
    ("疏散", "Shūsàn", "verb", "疏散群众。", "Sơ tán", "Di tản người dân.", "Evacuate", "zh_weather_advanced"),
    ("救援", "Jiùyuán", "noun/verb", "灾后救援工作。", "Cứu trợ", "Công tác cứu hộ sau thảm họa.", "Rescue", "zh_weather_advanced"),

    # Expert (3)
    ("气象学", "Qìxiàngxué", "noun", "研究气象学。", "Khí tượng học", "Nghiên cứu về khí tượng.", "Meteorology", "zh_weather_expert"),
    ("对流层", "Duìliúcéng", "noun", "对流层的天气现象。", "Tầng đối lưu", "Hiện tượng thời tiết ở tầng đối lưu.", "Troposphere", "zh_weather_expert"),
    ("平流层", "Píngliúcéng", "noun", "飞机在平流层飞行。", "Tầng bình lưu", "Máy bay bay ở tầng bình lưu.", "Stratosphere", "zh_weather_expert"),
    ("臭氧层", "Chòuyǎngcéng", "noun", "臭氧层空洞。", "Tầng ozone", "Lỗ hổng tầng ô-zôn.", "Ozone layer", "zh_weather_expert"),
    ("辐射", "Fúshè", "noun/verb", "太阳辐射。", "Bức xạ", "Bức xạ mặt trời.", "Radiation", "zh_weather_expert"),
    ("逆温层", "Nìwēncéng", "noun", "逆温层阻碍污染物扩散。", "Tầng nghịch nhiệt", "Tầng nghịch nhiệt cản trở phát tán ô nhiễm.", "Inversion layer", "zh_weather_expert"),
    ("城市热岛效应", "Chéngshì rèdǎo xiàoyìng", "noun", "城市热岛效应明显。", "Hiệu ứng đảo nhiệt đô thị", "Thành phố nóng hơn vùng ven rõ rệt.", "Urban heat island effect", "zh_weather_expert"),
    ("PM2.5", "Pī-ěm-èr-diǎn-wǔ", "noun", "PM2.5浓度。", "Bụi mịn PM2.5", "Nồng độ bụi siêu mịn PM 2.5.", "PM2.5", "zh_weather_expert"),
    ("光化学烟雾", "Guānghuàxué yānwù", "noun", "光化学烟雾污染。", "Sương mù quang hóa", "Ô nhiễm sương mù quang học.", "Photochemical smog", "zh_weather_expert"),
    ("酸雨", "Suānyǔ", "noun", "酸雨腐蚀建筑。", "Mưa axit", "Mưa a-xít ăn mòn công trình.", "Acid rain", "zh_weather_expert"),
    ("极地涡旋", "Jídì wōxuán", "noun", "极地涡旋分裂。", "Lốc xoáy cực", "Khối gió xoáy vùng cực.", "Polar vortex", "zh_weather_expert"),
    ("副热带高压", "Fùrèdài gāoyā", "noun", "受副热带高压控制。", "Áp cao cận nhiệt đới", "Bị chi phối bởi áp cao cận nhiệt đới.", "Subtropical high", "zh_weather_expert"),
    ("锋面雨", "Fēngmiànyǔ", "noun", "锋面雨带。", "Mưa front", "Dải mưa do frông tạo ra.", "Frontal rain", "zh_weather_expert"),
    ("地形雨", "Dìxíngyǔ", "noun", "迎风坡的地形雨。", "Mưa địa hình", "Mưa ở sườn đón gió.", "Orographic rain", "zh_weather_expert"),
    ("对流雨", "Duìliúyǔ", "noun", "夏后的对流雨。", "Mưa đối lưu", "Mưa dông nhiệt buổi chiều hè.", "Convectional rain", "zh_weather_expert"),
    ("梅雨", "Méiyǔ", "noun", "江南的梅雨季节。", "Mùa mưa phùn", "Mùa mưa dầm ở vùng Giang Nam.", "Plum rain", "zh_weather_expert"),
    ("龙舟水", "Lóngzhōushuǐ", "noun", "华南的龙舟水。", "Mưa mùa Tết Đoan Ngọ", "Mưa lớn dịp đua thuyền rồng.", "Dragon boat rain", "zh_weather_expert"),
    ("倒春寒", "Dàochūnhán", "noun", "提防倒春寒。", "Rét nàng Bân (rét muộn)", "Cảnh giác cái lạnh nàng Bân.", "Late spring coldness", "zh_weather_expert"),
    ("秋老虎", "Qiūlǎohǔ", "noun", "秋老虎发威。", "Nắng nóng cuối thu", "Trời nóng oi ả giữa mùa thu.", "Indian summer", "zh_weather_expert"),
    ("气团", "Qìtuán", "noun", "极地大陆气团。", "Khối khí", "Khối khí lục địa vùng cực.", "Air mass", "zh_weather_expert"),
    ("露点", "Lùdiǎn", "noun", "露点温度。", "Điểm sương", "Nhiệt độ điểm sương.", "Dew point", "zh_weather_expert"),
    ("蒸发量", "Zhēngfāliàng", "noun", "蒸发量大于降水量。", "Lượng bốc hơi", "Lượng bốc hơi lớn hơn lượng mưa.", "Evaporation amount", "zh_weather_expert"),
    ("气候带", "Qìhòudài", "noun", "热带气候带。", "Đới khí hậu", "Vành đai khí hậu nhiệt đới.", "Climate zone", "zh_weather_expert"),
    ("海洋性气候", "Hǎiyángxìng qìhòu", "noun", "温带海洋性气候。", "Khí hậu ôn đới hải dương", "Khí hậu ôn đới ảnh hưởng biển.", "Marine climate", "zh_weather_expert"),
    ("大陆性气候", "Dàlùxìng qìhòu", "noun", "温带大陆性气候。", "Khí hậu ôn đới lục địa", "Khí hậu ôn đới nằm sâu trong đất liền.", "Continental climate", "zh_weather_expert"),
    ("碳中和", "Tànzhōnghé", "noun", "实现碳中和目标。", "Trung hòa carbon", "Đạt mục tiêu phát thải ròng bằng 0.", "Carbon neutrality", "zh_weather_expert"),
    ("碳达峰", "Tàndáfēng", "noun", "碳达峰时间表。", "Đỉnh điểm xả carbon", "Lộ trình đạt đỉnh phát thải CO2.", "Carbon peak", "zh_weather_expert"),
    ("气候公约", "Qìhòu gōngyuē", "noun", "巴黎气候公约。", "Công ước khí hậu", "Hiệp định Paris về khí hậu.", "Climate convention", "zh_weather_expert"),
    ("人工降雨", "Réngōng jiàngyǔ", "noun", "实施人工降雨。", "Làm mưa nhân tạo", "Tiến hành gieo hạt làm mưa.", "Artificial rainfall", "zh_weather_expert"),
    ("气象卫星", "Qìxiàng wèixīng", "noun", "发射气象卫星。", "Vệ tinh khí tượng", "Phóng vệ tinh theo dõi thời tiết.", "Meteorological satellite", "zh_weather_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_zh, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "zh",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_zh,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Health & Weather - Chinese) to DB!")
