import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Education
    {"id": "zh_education_beginner", "languageCode": "zh", "title": "教育", "subtitle": "Giáo dục - Beginner", "iconEmoji": "📚", "level": "Beginner", "colorHex": "#3B82F6", "cardCount": 30},
    {"id": "zh_education_intermediate", "languageCode": "zh", "title": "教育", "subtitle": "Giáo dục - Intermediate", "iconEmoji": "📚", "level": "Intermediate", "colorHex": "#2563EB", "cardCount": 30},
    {"id": "zh_education_advanced", "languageCode": "zh", "title": "教育", "subtitle": "Giáo dục - Advanced", "iconEmoji": "📚", "level": "Advanced", "colorHex": "#1D4ED8", "cardCount": 30},
    {"id": "zh_education_expert", "languageCode": "zh", "title": "教育", "subtitle": "Giáo dục - Expert", "iconEmoji": "📚", "level": "Expert", "colorHex": "#1E40AF", "cardCount": 30},
    
    # Fashion
    {"id": "zh_fashion_beginner", "languageCode": "zh", "title": "时尚", "subtitle": "Thời trang - Beginner", "iconEmoji": "👗", "level": "Beginner", "colorHex": "#EC4899", "cardCount": 30},
    {"id": "zh_fashion_intermediate", "languageCode": "zh", "title": "时尚", "subtitle": "Thời trang - Intermediate", "iconEmoji": "👗", "level": "Intermediate", "colorHex": "#DB2777", "cardCount": 30},
    {"id": "zh_fashion_advanced", "languageCode": "zh", "title": "时尚", "subtitle": "Thời trang - Advanced", "iconEmoji": "👗", "level": "Advanced", "colorHex": "#BE185D", "cardCount": 30},
    {"id": "zh_fashion_expert", "languageCode": "zh", "title": "时尚", "subtitle": "Thời trang - Expert", "iconEmoji": "👗", "level": "Expert", "colorHex": "#9D174D", "cardCount": 30}
]

vocab_data = [
    # ---- EDUCATION ----
    # Beginner (0)
    ("学校", "Xuéxiào", "noun", "去学校。", "Trường học", "Đi đến trường.", "School", "zh_education_beginner"),
    ("老师", "Lǎoshī", "noun", "老师好。", "Giáo viên", "Chào thầy/cô giáo.", "Teacher", "zh_education_beginner"),
    ("学生", "Xuéshēng", "noun", "好学生。", "Học sinh", "Học sinh ngoan.", "Student", "zh_education_beginner"),
    ("学习", "Xuéxí", "noun/verb", "学习中文。", "Học tập", "Học tiếng Trung.", "Study", "zh_education_beginner"),
    ("课", "Kè", "noun", "上课。", "Bài học, tiết học", "Vào lớp / Đi học.", "Class", "zh_education_beginner"),
    ("书", "Shū", "noun", "看书。", "Sách", "Đọc sách.", "Book", "zh_education_beginner"),
    ("笔", "Bǐ", "noun", "用笔写。", "Bút", "Viết bằng bút.", "Pen", "zh_education_beginner"),
    ("纸", "Zhǐ", "noun", "一张纸。", "Giấy", "Một tờ giấy.", "Paper", "zh_education_beginner"),
    ("词典", "Cídiǎn", "noun", "查词典。", "Từ điển", "Tra từ điển.", "Dictionary", "zh_education_beginner"),
    ("本子", "Běnzi", "noun", "练习本子。", "Vở", "Vở bài tập.", "Notebook", "zh_education_beginner"),
    ("考试", "Kǎoshì", "noun/verb", "考试难。", "Thi, bài thi", "Kỳ thi khó.", "Exam", "zh_education_beginner"),
    ("成绩", "Chéngjì", "noun", "成绩好。", "Thành tích, điểm", "Thành tích tốt.", "Grades", "zh_education_beginner"),
    ("问题", "Wèntí", "noun", "问问题。", "Câu hỏi, vấn đề", "Hỏi câu hỏi.", "Question", "zh_education_beginner"),
    ("知道", "Zhīdào", "verb", "不知道。", "Biết", "Không biết.", "Know", "zh_education_beginner"),
    ("懂", "Dǒng", "verb", "听懂了。", "Hiểu", "Nghe hiểu rồi.", "Understand", "zh_education_beginner"),
    ("问", "Wèn", "verb", "问老师。", "Hỏi", "Hỏi thầy giáo.", "Ask", "zh_education_beginner"),
    ("回答", "Huídá", "verb", "回答问题。", "Trả lời", "Trả lời câu hỏi.", "Answer", "zh_education_beginner"),
    ("写", "Xiě", "verb", "写字。", "Viết", "Viết chữ.", "Write", "zh_education_beginner"),
    ("读", "Dú", "verb", "读书。", "Đọc", "Đọc sách.", "Read", "zh_education_beginner"),
    ("听", "Tīng", "verb", "听音乐。", "Nghe", "Nghe nhạc.", "Listen", "zh_education_beginner"),
    ("班", "Bān", "noun", "同班同学。", "Lớp học", "Bạn cùng lớp.", "Class", "zh_education_beginner"),
    ("同学", "Tóngxué", "noun", "我的同学。", "Bạn cùng lớp", "Bạn học của tôi.", "Classmate", "zh_education_beginner"),
    ("大学", "Dàxué", "noun", "上大学。", "Đại học", "Học đại học.", "University", "zh_education_beginner"),
    ("小学", "Xiǎoxué", "noun", "小学生。", "Tiểu học", "Học sinh tiểu học.", "Primary school", "zh_education_beginner"),
    ("教室", "Jiàoshì", "noun", "在教室里。", "Phòng học", "Ở trong lớp học.", "Classroom", "zh_education_beginner"),
    ("黑板", "Hēibǎn", "noun", "看黑板。", "Bảng đen", "Nhìn lên bảng đen.", "Blackboard", "zh_education_beginner"),
    ("作业", "Zuòyè", "noun", "写作业。", "Bài tập về nhà", "Làm bài tập.", "Homework", "zh_education_beginner"),
    ("容易", "Róngyì", "adjective", "很容易。", "Dễ", "Rất dễ.", "Easy", "zh_education_beginner"),
    ("难", "Nán", "adjective", "太难了。", "Khó", "Khó quá.", "Difficult", "zh_education_beginner"),
    ("对", "Duì", "adjective", "说得对。", "Đúng", "Nói đúng rồi.", "Correct", "zh_education_beginner"),

    # Intermediate (1)
    ("教育", "Jiàoyù", "noun", "教育很重要。", "Giáo dục", "Giáo dục rất quan trọng.", "Education", "zh_education_intermediate"),
    ("中学", "Zhōngxué", "noun", "中学生。", "Trung học", "Học sinh trung học.", "Middle school", "zh_education_intermediate"),
    ("教授", "Jiàoshòu", "noun", "大学教授。", "Giáo sư", "Giáo sư đại học.", "Professor", "zh_education_intermediate"),
    ("院长", "Yuànzhǎng", "noun", "学院的院长。", "Viện trưởng", "Viện trưởng của trường.", "Dean", "zh_education_intermediate"),
    ("毕业", "Bìyè", "verb", "大学毕业。", "Tốt nghiệp", "Tốt nghiệp đại học.", "Graduate", "zh_education_intermediate"),
    ("学位", "Xuéwèi", "noun", "取得学位。", "Học vị, bằng cấp", "Giành được học vị.", "Degree", "zh_education_intermediate"),
    ("博士", "Bóshì", "noun", "博士生。", "Tiến sĩ", "Nghiên cứu sinh tiến sĩ.", "Doctor (PhD)", "zh_education_intermediate"),
    ("硕士", "Shuòshì", "noun", "硕士学位。", "Thạc sĩ", "Bằng thạc sĩ.", "Master", "zh_education_intermediate"),
    ("学士", "Xuéshì", "noun", "学士学位。", "Cử nhân", "Bằng cử nhân.", "Bachelor", "zh_education_intermediate"),
    ("专业", "Zhuānyè", "noun", "你的专业是什么？", "Chuyên ngành", "Chuyên ngành của bạn là gì?", "Major", "zh_education_intermediate"),
    ("课程", "Kèchéng", "noun", "安排课程。", "Chương trình học", "Sắp xếp chương trình học.", "Curriculum", "zh_education_intermediate"),
    ("讲座", "Jiǎngzuò", "noun", "听讲座。", "Bài giảng, tọa đàm", "Nghe tọa đàm.", "Lecture", "zh_education_intermediate"),
    ("论文", "Lùnwén", "noun", "写论文。", "Luận văn", "Viết luận văn.", "Thesis", "zh_education_intermediate"),
    ("研究", "Yánjiū", "noun/verb", "做研究。", "Nghiên cứu", "Làm nghiên cứu.", "Research", "zh_education_intermediate"),
    ("实验", "Shíyàn", "noun/verb", "做实验。", "Thí nghiệm", "Làm thí nghiệm.", "Experiment", "zh_education_intermediate"),
    ("图书馆", "Túshūguǎn", "noun", "去图书馆借书。", "Thư viện", "Vào thư viện mượn sách.", "Library", "zh_education_intermediate"),
    ("奖学金", "Jiǎngxuéjīn", "noun", "获得奖学金。", "Học bổng", "Nhận được học bổng.", "Scholarship", "zh_education_intermediate"),
    ("学费", "Xuéfèi", "noun", "交学费。", "Học phí", "Nộp học phí.", "Tuition", "zh_education_intermediate"),
    ("报名", "Bàomíng", "verb", "报名参加。", "Đăng ký", "Đăng ký tham gia.", "Sign up", "zh_education_intermediate"),
    ("申请", "Shēnqǐng", "verb", "申请大学。", "Ứng tuyển, xin", "Ứng tuyển vào đại học.", "Apply", "zh_education_intermediate"),
    ("录取", "Lùqǔ", "verb", "被录取了。", "Trúng tuyển", "Đã được trúng tuyển.", "Admit", "zh_education_intermediate"),
    ("考试卷", "Kǎoshì juàn", "noun", "发考试卷。", "Bài thi, giấy thi", "Phát giấy thi.", "Exam paper", "zh_education_intermediate"),
    ("及格", "Jígé", "verb", "考试及格。", "Thi đậu, qua môn", "Thi đậu.", "Pass", "zh_education_intermediate"),
    ("辅导", "Fǔdǎo", "noun/verb", "课后辅导。", "Phụ đạo", "Phụ đạo sau giờ học.", "Tutoring", "zh_education_intermediate"),
    ("预习", "Yùxí", "verb", "预习课文。", "Chuẩn bị bài", "Xem trước bài mới.", "Preview", "zh_education_intermediate"),
    ("复习", "Fùxí", "verb", "复习功课。", "Ôn tập", "Ôn lại bài cũ.", "Review", "zh_education_intermediate"),
    ("知识", "Zhīshi", "noun", "丰富的知识。", "Kiến thức", "Kiến thức phong phú.", "Knowledge", "zh_education_intermediate"),
    ("讨论", "Tǎolùn", "noun/verb", "讨论问题。", "Thảo luận", "Thảo luận vấn đề.", "Discuss", "zh_education_intermediate"),
    ("解释", "Jiěshì", "noun/verb", "解释清楚。", "Giải thích", "Giải thích rõ ràng.", "Explain", "zh_education_intermediate"),
    ("句子", "Jùzi", "noun", "造句子。", "Câu", "Đặt câu.", "Sentence", "zh_education_intermediate"),

    # Advanced (2)
    ("学术", "Xuéshù", "noun", "学术交流。", "Học thuật", "Giao lưu học thuật.", "Academic", "zh_education_advanced"),
    ("理论", "Lǐlùn", "noun", "基础理论。", "Lý thuyết", "Lý thuyết cơ bản.", "Theory", "zh_education_advanced"),
    ("实践", "Shíjiàn", "noun/verb", "理论联系实践。", "Thực tiễn", "Lý thuyết gắn với thực tiễn.", "Practice", "zh_education_advanced"),
    ("思考", "Sīkǎo", "noun/verb", "独立思考。", "Suy nghĩ", "Suy nghĩ độc lập.", "Think", "zh_education_advanced"),
    ("逻辑", "Luóji", "noun", "逻辑思维。", "Logic", "Tư duy logic.", "Logic", "zh_education_advanced"),
    ("概念", "Gàiniàn", "noun", "基本概念。", "Khái niệm", "Khái niệm cơ bản.", "Concept", "zh_education_advanced"),
    ("课题", "Kètí", "noun", "研究课题。", "Đề tài", "Đề tài nghiên cứu.", "Project", "zh_education_advanced"),
    ("调查", "Diàochá", "noun/verb", "问卷调查。", "Khảo sát, điều tra", "Điều tra bằng bảng hỏi.", "Survey", "zh_education_advanced"),
    ("分析", "Fēnxī", "noun/verb", "数据分析。", "Phân tích", "Phân tích dữ liệu.", "Analyze", "zh_education_advanced"),
    ("总结", "Zǒngjié", "noun/verb", "总结经验。", "Tổng kết", "Tổng kết kinh nghiệm.", "Summarize", "zh_education_advanced"),
    ("评价", "Píngjià", "noun/verb", "综合评价。", "Đánh giá", "Đánh giá tổng hợp.", "Evaluate", "zh_education_advanced"),
    ("创新", "Chuàngxīn", "noun/verb", "创新精神。", "Sáng tạo", "Tinh thần sáng tạo.", "Innovate", "zh_education_advanced"),
    ("培养", "Péiyǎng", "verb", "培养人才。", "Đào tạo", "Bồi dưỡng nhân tài.", "Cultivate", "zh_education_advanced"),
    ("素质", "Sùzhì", "noun", "提高素质。", "Tố chất", "Nâng cao tố chất.", "Quality", "zh_education_advanced"),
    ("纪律", "Jìlǜ", "noun", "遵守纪律。", "Kỷ luật", "Tuân thủ kỷ luật.", "Discipline", "zh_education_advanced"),
    ("规范", "Guīfàn", "noun/adjective", "行为规范。", "Quy phạm", "Quy phạm hành vi.", "Norm", "zh_education_advanced"),
    ("评估", "Pínggū", "noun/verb", "项目评估。", "Thẩm định", "Thẩm định dự án.", "Assess", "zh_education_advanced"),
    ("启发", "Qǐfā", "noun/verb", "启发式教学。", "Gợi mở", "Phương pháp dạy học gợi mở.", "Inspire", "zh_education_advanced"),
    ("激励", "Jīlì", "noun/verb", "激励学生。", "Khuyến khích", "Động viên học sinh.", "Motivate", "zh_education_advanced"),
    ("辅导员", "Fǔdǎoyuán", "noun", "大学的辅导员。", "Cố vấn học tập", "Cố vấn học tập ở đại học.", "Counselor", "zh_education_advanced"),
    ("讲师", "Jiǎngshī", "noun", "大学讲师。", "Giảng viên", "Giảng viên đại học.", "Lecturer", "zh_education_advanced"),
    ("实习", "Shíxí", "noun/verb", "去公司实习。", "Thực tập", "Đi thực tập ở công ty.", "Internship", "zh_education_advanced"),
    ("就业", "Jiùyè", "noun/verb", "就业指导。", "Việc làm", "Hướng dẫn việc làm.", "Employment", "zh_education_advanced"),
    ("简历", "Jiǎnlì", "noun", "投简历。", "Sơ yếu lý lịch", "Gửi CV/sơ yếu lý lịch.", "Resume", "zh_education_advanced"),
    ("推荐", "Tuījiàn", "noun/verb", "教授推荐信。", "Giới thiệu", "Thư giới thiệu của giáo sư.", "Recommend", "zh_education_advanced"),
    ("资格", "Zīgé", "noun", "教师资格证。", "Tư cách, bằng cấp", "Bằng chứng nhận tư cách giáo viên.", "Qualification", "zh_education_advanced"),
    ("答辩", "Dábiàn", "noun/verb", "论文答辩。", "Bảo vệ luận văn", "Bảo vệ luận văn.", "Defense", "zh_education_advanced"),
    ("出版", "Chūbǎn", "verb", "出版书籍。", "Xuất bản", "Xuất bản sách.", "Publish", "zh_education_advanced"),
    ("期刊", "Qīkān", "noun", "学术期刊。", "Tạp chí định kỳ", "Tạp chí học thuật.", "Journal", "zh_education_advanced"),
    ("著作", "Zhùzuò", "noun", "他的著作。", "Tác phẩm", "Tác phẩm của ông ấy.", "Work", "zh_education_advanced"),

    # Expert (3)
    ("认知", "Rènzhī", "noun", "认知能力。", "Nhận thức", "Năng lực nhận thức.", "Cognition", "zh_education_expert"),
    ("哲学", "Zhéxué", "noun", "哲学思想。", "Triết học", "Tư tưởng triết học.", "Philosophy", "zh_education_expert"),
    ("心理学", "Xīnlǐxué", "noun", "心理学实验。", "Tâm lý học", "Thí nghiệm tâm lý học.", "Psychology", "zh_education_expert"),
    ("社会学", "Shèhuìxué", "noun", "社会学调查。", "Xã hội học", "Khảo sát xã hội học.", "Sociology", "zh_education_expert"),
    ("人文", "Rénwén", "noun", "人文科学。", "Nhân văn", "Khoa học nhân văn.", "Humanities", "zh_education_expert"),
    ("范式", "Fànshì", "noun", "范式转移。", "Hệ biến hóa (Paradigm)", "Sự dịch chuyển mô thức.", "Paradigm", "zh_education_expert"),
    ("辩证", "Biànzhèng", "adjective", "辩证思维。", "Biện chứng", "Tư duy biện chứng.", "Dialectical", "zh_education_expert"),
    ("唯物主义", "Wéiwù zhǔyì", "noun", "唯物主义者。", "Chủ nghĩa duy vật", "Người theo chủ nghĩa duy vật.", "Materialism", "zh_education_expert"),
    ("经验主义", "Jīngyàn zhǔyì", "noun", "经验主义方法。", "Chủ nghĩa kinh nghiệm", "Phương pháp chủ nghĩa kinh nghiệm.", "Empiricism", "zh_education_expert"),
    ("理性", "Lǐxìng", "noun/adjective", "保持理性。", "Lý trí", "Giữ vững lý trí.", "Rationality", "zh_education_expert"),
    ("感性", "Gǎnxìng", "noun/adjective", "感性认识。", "Cảm tính", "Nhận thức cảm tính.", "Perceptual", "zh_education_expert"),
    ("抽象", "Chōuxiàng", "adjective", "抽象的概念。", "Trừu tượng", "Khái niệm trừu tượng.", "Abstract", "zh_education_expert"),
    ("具象", "Jùxiàng", "adjective", "具象的艺术。", "Cụ thể", "Nghệ thuật cụ thể.", "Concrete", "zh_education_expert"),
    ("推理", "Tuīlǐ", "noun/verb", "逻辑推理。", "Suy luận", "Suy luận logic.", "Reasoning", "zh_education_expert"),
    ("假设", "Jiǎshè", "noun/verb", "提出假设。", "Giả thuyết", "Đưa ra giả thuyết.", "Hypothesis", "zh_education_expert"),
    ("验证", "Yànzhèng", "noun/verb", "验证假设。", "Kiểm chứng", "Kiểm chứng giả thuyết.", "Verify", "zh_education_expert"),
    ("演绎", "Yǎnyì", "noun/verb", "演绎推理。", "Diễn dịch", "Suy luận diễn dịch.", "Deduction", "zh_education_expert"),
    ("归纳", "Guīnà", "noun/verb", "归纳总结。", "Quy nạp", "Tổng kết quy nạp.", "Induction", "zh_education_expert"),
    ("变量", "Biànliàng", "noun", "控制变量。", "Biến số", "Kiểm soát các biến số.", "Variable", "zh_education_expert"),
    ("定量", "Dìngliàng", "adjective", "定量分析。", "Định lượng", "Phân tích định lượng.", "Quantitative", "zh_education_expert"),
    ("定性", "Dìngxìng", "adjective", "定性研究。", "Định tính", "Nghiên cứu định tính.", "Qualitative", "zh_education_expert"),
    ("文献", "Wénxiàn", "noun", "查阅文献。", "Tài liệu tham khảo", "Tra cứu tài liệu tham khảo.", "Literature", "zh_education_expert"),
    ("引用", "Yǐnyòng", "verb", "引用别人的话。", "Trích dẫn", "Trích lời của người khác.", "Quote", "zh_education_expert"),
    ("抄袭", "Chāoxí", "verb", "抄袭论文。", "Đạo văn", "Đạo luận văn.", "Plagiarize", "zh_education_expert"),
    ("知识产权", "Zhīshi chǎnquán", "noun", "保护知识产权。", "Sở hữu trí tuệ", "Bảo vệ quyền sở hữu trí tuệ.", "Intellectual property", "zh_education_expert"),
    ("专利", "Zhuānlì", "noun", "申请专利。", "Bằng sáng chế", "Xin cấp bằng sáng chế.", "Patent", "zh_education_expert"),
    ("跨学科", "Kuà xuékē", "adjective", "跨学科研究。", "Liên ngành", "Nghiên cứu liên ngành.", "Interdisciplinary", "zh_education_expert"),
    ("前沿", "Qiányán", "noun/adjective", "科学前沿。", "Tiền tuyến", "Nơi tuyến đầu của khoa học.", "Frontier", "zh_education_expert"),
    ("启蒙", "Qǐméng", "noun/verb", "思想启蒙。", "Khai sáng", "Khai sáng tư tưởng.", "Enlightenment", "zh_education_expert"),
    ("终身学习", "Zhōngshēn xuéxí", "noun", "终身学习的理念。", "Học tập suốt đời", "Khái niệm về học tập suốt đời.", "Lifelong learning", "zh_education_expert"),

    # ---- FASHION ----
    # Beginner (0)
    ("衣服", "Yīfu", "noun", "穿衣服。", "Quần áo", "Mặc quần áo.", "Clothes", "zh_fashion_beginner"),
    ("裤子", "Kùzi", "noun", "一条裤子。", "Quần", "Một chiếc quần.", "Pants", "zh_fashion_beginner"),
    ("裙子", "Qúnzi", "noun", "漂亮的裙子。", "Váy", "Chiếc váy đẹp.", "Skirt", "zh_fashion_beginner"),
    ("鞋子", "Xiézi", "noun", "买鞋子。", "Giày", "Mua giày.", "Shoes", "zh_fashion_beginner"),
    ("袜子", "Wàzi", "noun", "穿袜子。", "Tất", "Đi tất.", "Socks", "zh_fashion_beginner"),
    ("帽子", "Màozi", "noun", "戴帽子。", "Mũ", "Đội mũ.", "Hat", "zh_fashion_beginner"),
    ("衬衫", "Chènshān", "noun", "白色的衬衫。", "Áo sơ mi", "Áo sơ mi trắng.", "Shirt", "zh_fashion_beginner"),
    ("外套", "Wàitào", "noun", "穿外套。", "Áo khoác", "Mặc áo khoác.", "Coat", "zh_fashion_beginner"),
    ("毛衣", "Máoyī", "noun", "红毛衣。", "Áo len", "Áo len đỏ.", "Sweater", "zh_fashion_beginner"),
    ("大衣", "Dàyī", "noun", "冬天的大衣。", "Áo măng tô", "Áo măng tô mùa đông.", "Overcoat", "zh_fashion_beginner"),
    ("颜色", "Yánsè", "noun", "什么颜色？", "Màu sắc", "Màu gì?", "Color", "zh_fashion_beginner"),
    ("红色", "Hóngsè", "noun", "红色的衣服。", "Màu đỏ", "Quần áo màu đỏ.", "Red", "zh_fashion_beginner"),
    ("黑色", "Hēisè", "noun", "黑色的鞋子。", "Màu đen", "Giày đen.", "Black", "zh_fashion_beginner"),
    ("白色", "Báisè", "noun", "白色的裙子。", "Màu trắng", "Váy trắng.", "White", "zh_fashion_beginner"),
    ("蓝色", "Lánsè", "noun", "蓝色的天空。", "Màu xanh dương", "Bầu trời xanh.", "Blue", "zh_fashion_beginner"),
    ("绿色", "Lǜsè", "noun", "绿色的草。", "Màu xanh lá", "Cỏ xanh.", "Green", "zh_fashion_beginner"),
    ("黄色", "Huángsè", "noun", "黄色的花。", "Màu vàng", "Hoa vàng.", "Yellow", "zh_fashion_beginner"),
    ("穿", "Chuān", "verb", "穿裙子。", "Mặc (quần áo)", "Mặc váy.", "Wear", "zh_fashion_beginner"),
    ("脱", "Tuō", "verb", "脱鞋。", "Cởi", "Cởi giày.", "Take off", "zh_fashion_beginner"),
    ("戴", "Dài", "verb", "戴帽子。", "Đội, đeo", "Đội mũ.", "Put on (accessories)", "zh_fashion_beginner"),
    ("摘", "Zhāi", "verb", "摘眼镜。", "Tháo (phụ kiện)", "Tháo kính mắt.", "Take off (accessories)", "zh_fashion_beginner"),
    ("买", "Mǎi", "verb", "买衣服。", "Mua", "Mua quần áo.", "Buy", "zh_fashion_beginner"),
    ("卖", "Mài", "verb", "卖鞋子。", "Bán", "Bán giày.", "Sell", "zh_fashion_beginner"),
    ("试", "Shì", "verb", "试穿一下。", "Thử", "Mặc thử một chút.", "Try on", "zh_fashion_beginner"),
    ("大", "Dà", "adjective", "这件衣服太大。", "Lớn, rộng", "Bộ quần áo này lớn quá.", "Big", "zh_fashion_beginner"),
    ("小", "Xiǎo", "adjective", "鞋子太小。", "Nhỏ, chật", "Giày chật quá.", "Small", "zh_fashion_beginner"),
    ("长", "Cháng", "adjective", "裤子很长。", "Dài", "Quần rất dài.", "Long", "zh_fashion_beginner"),
    ("短", "Duǎn", "adjective", "裙子很短。", "Ngắn", "Váy rất ngắn.", "Short", "zh_fashion_beginner"),
    ("新", "Xīn", "adjective", "新衣服。", "Mới", "Quần áo mới.", "New", "zh_fashion_beginner"),
    ("旧", "Jiù", "adjective", "旧鞋。", "Cũ", "Giày cũ.", "Old", "zh_fashion_beginner"),

    # Intermediate (1)
    ("时尚", "Shíshàng", "noun/adjective", "很时尚。", "Thời trang", "Rất thời trang.", "Fashion", "zh_fashion_intermediate"),
    ("流行", "Liúxíng", "verb/adjective", "今年流行什么？", "Thịnh hành", "Năm nay thịnh hành cái gì?", "Popular", "zh_fashion_intermediate"),
    ("品牌", "Pǐnpái", "noun", "名牌包。", "Thương hiệu", "Túi xách hàng hiệu.", "Brand", "zh_fashion_intermediate"),
    ("设计", "Shèjì", "noun/verb", "衣服的设计。", "Thiết kế", "Thiết kế của quần áo.", "Design", "zh_fashion_intermediate"),
    ("款式", "Kuǎnshì", "noun", "这种款式。", "Kiểu dáng", "Kiểu dáng này.", "Style", "zh_fashion_intermediate"),
    ("尺码", "Chǐmǎ", "noun", "你的尺码是多少？", "Kích cỡ", "Size của bạn là bao nhiêu?", "Size", "zh_fashion_intermediate"),
    ("试衣间", "Shìyījiān", "noun", "试衣间在哪里？", "Phòng thử đồ", "Phòng thử đồ ở đâu?", "Fitting room", "zh_fashion_intermediate"),
    ("打折", "Dǎzhé", "verb", "这件衣服打折吗？", "Giảm giá", "Quần áo này có giảm giá không?", "Discount", "zh_fashion_intermediate"),
    ("搭配", "Dāpèi", "verb", "衣服搭配得好。", "Phối đồ", "Quần áo phối rất đẹp.", "Match", "zh_fashion_intermediate"),
    ("牛仔裤", "Niúzǎikù", "noun", "穿牛仔裤。", "Quần jeans", "Mặc quần jean.", "Jeans", "zh_fashion_intermediate"),
    ("T恤", "T-xù", "noun", "白T恤。", "Áo thun", "Áo thun trắng.", "T-shirt", "zh_fashion_intermediate"),
    ("连衣裙", "Liányīqún", "noun", "漂亮的连衣裙。", "Váy liền", "Chiếc váy liền tuyệt đẹp.", "Dress", "zh_fashion_intermediate"),
    ("西装", "Xīzhuāng", "noun", "穿西装。", "Áo vest", "Mặc bộ đồ tây/vest.", "Suit", "zh_fashion_intermediate"),
    ("领带", "Lǐngdài", "noun", "打领带。", "Cà vạt", "Thắt cà vạt.", "Tie", "zh_fashion_intermediate"),
    ("皮鞋", "Píxié", "noun", "黑皮鞋。", "Giày da", "Giày da đen.", "Leather shoes", "zh_fashion_intermediate"),
    ("运动鞋", "Yùndòngxié", "noun", "买运动鞋。", "Giày thể thao", "Mua giày thể thao.", "Sneakers", "zh_fashion_intermediate"),
    ("高跟鞋", "Gāogēnxié", "noun", "穿高跟鞋。", "Giày cao gót", "Mang giày cao gót.", "High heels", "zh_fashion_intermediate"),
    ("眼镜", "Yǎnjìng", "noun", "戴眼镜。", "Kính mắt", "Đeo kính mắt.", "Glasses", "zh_fashion_intermediate"),
    ("手表", "Shǒubiǎo", "noun", "戴手表。", "Đồng hồ đeo tay", "Đeo đồng hồ.", "Watch", "zh_fashion_intermediate"),
    ("项链", "Xiàngliàn", "noun", "金项链。", "Dây chuyền", "Dây chuyền vàng.", "Necklace", "zh_fashion_intermediate"),
    ("戒指", "Jièzhi", "noun", "戴戒指。", "Nhẫn", "Đeo nhẫn.", "Ring", "zh_fashion_intermediate"),
    ("耳环", "Ěrhuán", "noun", "戴耳环。", "Bông tai", "Đeo bông tai.", "Earrings", "zh_fashion_intermediate"),
    ("包包", "Bāobāo", "noun", "买包包。", "Túi xách", "Mua túi xách.", "Bag", "zh_fashion_intermediate"),
    ("口红", "Kǒuhóng", "noun", "涂口红。", "Son môi", "Thoa son môi.", "Lipstick", "zh_fashion_intermediate"),
    ("香水", "Xiāngshuǐ", "noun", "喷香水。", "Nước hoa", "Xịt nước hoa.", "Perfume", "zh_fashion_intermediate"),
    ("棉", "Mián", "noun", "纯棉的。", "Vải cotton", "Làm từ 100% cotton.", "Cotton", "zh_fashion_intermediate"),
    ("丝绸", "Sīchóu", "noun", "丝绸衣服。", "Lụa", "Quần áo lụa.", "Silk", "zh_fashion_intermediate"),
    ("羊毛", "Yángmáo", "noun", "羊毛衫。", "Lông cừu, len", "Áo len lông cừu.", "Wool", "zh_fashion_intermediate"),
    ("皮革", "Pígé", "noun", "皮革包。", "Đồ da", "Túi xách da.", "Leather", "zh_fashion_intermediate"),
    ("化妆", "Huàzhuāng", "verb", "化妆出门。", "Trang điểm", "Trang điểm trước khi ra ngoài.", "Make up", "zh_fashion_intermediate"),

    # Advanced (2)
    ("潮流", "Cháoliú", "noun", "跟着潮流走。", "Xu hướng", "Chạy theo xu hướng.", "Trend", "zh_fashion_advanced"),
    ("审美", "Shěnměi", "noun", "审美观。", "Thẩm mỹ", "Quan điểm thẩm mỹ.", "Aesthetics", "zh_fashion_advanced"),
    ("品味", "Pǐnwèi", "noun", "品味很好。", "Gu thẩm mỹ", "Gu ăn mặc rất tốt.", "Taste", "zh_fashion_advanced"),
    ("剪裁", "Jiǎncái", "noun/verb", "剪裁得体。", "Đường may, cắt xén", "Đường cắt may rất vừa vặn.", "Tailor", "zh_fashion_advanced"),
    ("质地", "Zhìdì", "noun", "质地柔软。", "Chất liệu", "Chất vải mềm mại.", "Texture", "zh_fashion_advanced"),
    ("图案", "Tú'àn", "noun", "衣服上的图案。", "Họa tiết", "Họa tiết trên quần áo.", "Pattern", "zh_fashion_advanced"),
    ("限量版", "Xiànliàng bǎn", "noun", "限量版球鞋。", "Phiên bản giới hạn", "Giày thể thao bản giới hạn.", "Limited edition", "zh_fashion_advanced"),
    ("定制", "Dìngzhì", "verb", "定制西服。", "Đặt may riêng", "Bộ vest đặt may riêng.", "Custom-made", "zh_fashion_advanced"),
    ("奢侈品", "Shēchǐ pǐn", "noun", "奢侈品店。", "Đồ xa xỉ", "Cửa hàng đồ hiệu xa xỉ.", "Luxury goods", "zh_fashion_advanced"),
    ("仿制品", "Fǎngzhì pǐn", "noun", "买仿制品。", "Hàng nhái", "Mua hàng fake/nhái.", "Counterfeit", "zh_fashion_advanced"),
    ("模特", "Mótè", "noun", "时装模特。", "Người mẫu", "Người mẫu thời trang.", "Model", "zh_fashion_advanced"),
    ("走秀", "Zǒuxiù", "verb", "在巴黎走秀。", "Trình diễn thời trang", "Trình diễn thời trang ở Paris.", "Walk runway", "zh_fashion_advanced"),
    ("街拍", "Jiēpāi", "noun/verb", "街拍风格。", "Chụp ảnh dạo phố", "Phong cách chụp ảnh đường phố.", "Street snap", "zh_fashion_advanced"),
    ("百搭", "Bǎidā", "adjective", "这件衣服很百搭。", "Dễ phối đồ", "Quần áo này rất dễ phối đồ.", "Versatile", "zh_fashion_advanced"),
    ("撞衫", "Zhuàngshān", "verb", "和别人撞衫。", "Đụng hàng", "Mặc đụng hàng với người khác.", "Outfit clash", "zh_fashion_advanced"),
    ("过时", "Guòshí", "adjective", "这款已经过时了。", "Lỗi thời", "Mẫu này đã lỗi mốt rồi.", "Out of date", "zh_fashion_advanced"),
    ("复古", "Fùgǔ", "adjective", "复古风。", "Phong cách cổ điển", "Phong cách Vintage.", "Retro", "zh_fashion_advanced"),
    ("前卫", "Qiánwèi", "adjective", "前卫的设计。", "Phá cách", "Thiết kế đi trước thời đại.", "Avant-garde", "zh_fashion_advanced"),
    ("休闲", "Xiūxián", "adjective", "休闲装。", "Trang phục thường ngày", "Đồ mặc thoải mái hàng ngày.", "Casual", "zh_fashion_advanced"),
    ("正装", "Zhèngzhuāng", "noun", "穿正装出席。", "Trang phục trang trọng", "Mặc âu phục đến dự.", "Formal wear", "zh_fashion_advanced"),
    ("晚礼服", "Wǎnlǐfú", "noun", "穿晚礼服。", "Đồ dạ hội", "Mặc váy dạ hội.", "Evening gown", "zh_fashion_advanced"),
    ("睡衣", "Shuìyī", "noun", "换上睡衣。", "Đồ ngủ", "Thay đồ ngủ.", "Pajamas", "zh_fashion_advanced"),
    ("泳装", "Yǒngzhuāng", "noun", "买泳装。", "Đồ bơi", "Mua đồ bơi.", "Swimsuit", "zh_fashion_advanced"),
    ("内衣", "Nèiyī", "noun", "内衣店。", "Đồ lót", "Cửa hàng đồ lót.", "Underwear", "zh_fashion_advanced"),
    ("饰品", "Shìpǐn", "noun", "挑选饰品。", "Phụ kiện", "Chọn lựa phụ kiện trang sức.", "Accessories", "zh_fashion_advanced"),
    ("护肤品", "Hùfūpǐn", "noun", "买护肤品。", "Đồ dưỡng da", "Mua sản phẩm chăm sóc da.", "Skincare", "zh_fashion_advanced"),
    ("卸妆", "Xièzhuāng", "verb", "睡前要卸妆。", "Tẩy trang", "Phải tẩy trang trước khi ngủ.", "Remove makeup", "zh_fashion_advanced"),
    ("发型", "Fàxíng", "noun", "换个发型。", "Kiểu tóc", "Thay đổi kiểu tóc.", "Hairstyle", "zh_fashion_advanced"),
    ("染发", "Rǎnfà", "verb", "染发。", "Nhuộm tóc", "Nhuộm tóc.", "Dye hair", "zh_fashion_advanced"),
    ("烫发", "Tàngfà", "verb", "烫发。", "Làm tóc xoăn", "Uốn tóc.", "Perm hair", "zh_fashion_advanced"),

    # Expert (3)
    ("高级定制", "Gāojí dìngzhì", "noun", "高定服装。", "May đo cao cấp", "Đồ Haute Couture.", "Haute couture", "zh_fashion_expert"),
    ("裁缝", "Cáiféng", "noun", "老裁缝。", "Thợ may", "Thợ may lâu năm.", "Tailor", "zh_fashion_expert"),
    ("纺织", "Fǎngzhī", "noun/verb", "纺织工业。", "Dệt may", "Công nghiệp dệt may.", "Textile", "zh_fashion_expert"),
    ("纤维", "Xiānwéi", "noun", "合成纤维。", "Sợi", "Sợi tổng hợp.", "Fiber", "zh_fashion_expert"),
    ("亚麻", "Yàmá", "noun", "亚麻布。", "Vải lanh", "Vải đệt lanh.", "Linen", "zh_fashion_expert"),
    ("蕾丝", "Lěisī", "noun", "蕾丝裙。", "Vải ren", "Váy ren.", "Lace", "zh_fashion_expert"),
    ("刺绣", "Cìxiù", "noun/verb", "手工刺绣。", "Thêu thùa", "Thêu tay.", "Embroidery", "zh_fashion_expert"),
    ("染色", "Rǎnsè", "noun/verb", "衣服掉色是因为染色不好。", "Nhuộm màu", "Áo ra màu do nhuộm không tốt.", "Dyeing", "zh_fashion_expert"),
    ("褪色", "Tuìsè", "verb", "这件衣服褪色了。", "Phai màu", "Quần áo này bị phai màu.", "Fade", "zh_fashion_expert"),
    ("起球", "Qǐqiú", "verb", "毛衣起球了。", "Bị xù lông", "Áo len bị đổ lông/xù lông.", "Pill", "zh_fashion_expert"),
    ("缩水", "Suōshuǐ", "verb", "洗后缩水。", "Bị co rút", "Giặt xong bị co lại.", "Shrink", "zh_fashion_expert"),
    ("熨烫", "Yùntàng", "verb", "熨烫平整。", "Là ủi", "Ủi cho phẳng.", "Ironing", "zh_fashion_expert"),
    ("干洗", "Gānxǐ", "verb", "这件大衣需要干洗。", "Giặt khô", "Áo này cần giặt khô ngoài tiệm.", "Dry cleaning", "zh_fashion_expert"),
    ("水洗", "Shuǐxǐ", "verb", "可以水洗。", "Giặt nước", "Có thể giặt bằng nước bình thường.", "Wash", "zh_fashion_expert"),
    ("漂白", "Piǎobái", "verb", "用漂白剂。", "Tẩy trắng", "Sử dụng thuốc tẩy trắng.", "Bleach", "zh_fashion_expert"),
    ("版型", "Bǎnxíng", "noun", "衣服的版型很好。", "Dáng áo/quần", "Phom dáng áo rất đẹp.", "Cut/Fit", "zh_fashion_expert"),
    ("轮廓", "Lúnkuò", "noun", "服装的轮廓。", "Đường nét", "Đường nét cắt may của trang phục.", "Silhouette", "zh_fashion_expert"),
    ("色彩搭配", "Sècǎi dāpèi", "noun", "色彩搭配学。", "Phối màu", "Quy tắc phối màu sắc.", "Color matching", "zh_fashion_expert"),
    ("饱和度", "Bǎohédù", "noun", "颜色饱和度高。", "Độ bão hòa màu", "Màu sắc rất sặc sỡ (độ bão hòa cao).", "Saturation", "zh_fashion_expert"),
    ("对比色", "Duìbǐsè", "noun", "对比色搭配。", "Màu tương phản", "Phối hai màu đối lập.", "Contrasting color", "zh_fashion_expert"),
    ("极简主义", "Jíjiǎn zhǔyì", "noun", "极简主义风格。", "Chủ nghĩa tối giản", "Phong cách tối giản Minimalism.", "Minimalism", "zh_fashion_expert"),
    ("混搭", "Hùndā", "verb/noun", "混搭风。", "Phối đồ hỗn hợp", "Mix & match nhiều kiểu.", "Mix and match", "zh_fashion_expert"),
    ("买手", "Mǎishǒu", "noun", "时尚买手。", "Người săn đồ", "Người chuyên đi mua đồ thời trang (Fashion Buyer).", "Buyer", "zh_fashion_expert"),
    ("代购", "Dàigòu", "noun/verb", "找代购买包。", "Mua hộ, order", "Nhờ dịch vụ mua hộ túi xách.", "Personal shopper", "zh_fashion_expert"),
    ("旗舰店", "Qíjiàndiàn", "noun", "品牌旗舰店。", "Cửa hàng flagship", "Cửa hàng đại diện của nhãn hiệu.", "Flagship store", "zh_fashion_expert"),
    ("快时尚", "Kuài shíshàng", "noun", "快时尚品牌。", "Thời trang nhanh", "Thương hiệu Fast Fashion.", "Fast fashion", "zh_fashion_expert"),
    ("可持续时尚", "Kěchíxù shíshàng", "noun", "倡导可持续时尚。", "Thời trang bền vững", "Ủng hộ thời trang bảo vệ môi trường.", "Sustainable fashion", "zh_fashion_expert"),
    ("二手市场", "Èrshǒu shìchǎng", "noun", "二手市场买衣服。", "Chợ đồ cũ", "Mua đồ ở chợ hàng thùng.", "Second-hand market", "zh_fashion_expert"),
    ("古着", "Gǔzhuó", "noun", "古着店。", "Đồ vintage", "Shop bán đồ cổ xưa (Vintage).", "Vintage clothing", "zh_fashion_expert"),
    ("走光", "Zǒuguāng", "verb", "防止走光。", "Lộ hàng", "Phòng hớ hênh, lộ hàng.", "Exposure", "zh_fashion_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_zh, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "zh",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_zh,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Education & Fashion - Chinese) to DB!")
