import json
import os

DB_FILE = "app/src/main/assets/vocab_data.json"

decks = [
    # Food & Drinks
    {"id": "zh_food_beginner", "languageCode": "zh", "title": "饮食", "subtitle": "Đồ ăn-uống - Beginner", "iconEmoji": "🍔", "level": "Beginner", "colorHex": "#F97316", "cardCount": 30},
    {"id": "zh_food_intermediate", "languageCode": "zh", "title": "饮食", "subtitle": "Đồ ăn-uống - Intermediate", "iconEmoji": "🍔", "level": "Intermediate", "colorHex": "#EA580C", "cardCount": 30},
    {"id": "zh_food_advanced", "languageCode": "zh", "title": "饮食", "subtitle": "Đồ ăn-uống - Advanced", "iconEmoji": "🍔", "level": "Advanced", "colorHex": "#C2410C", "cardCount": 30},
    {"id": "zh_food_expert", "languageCode": "zh", "title": "饮食", "subtitle": "Đồ ăn-uống - Expert", "iconEmoji": "🍔", "level": "Expert", "colorHex": "#9A3412", "cardCount": 30},
    
    # Technology
    {"id": "zh_tech_beginner", "languageCode": "zh", "title": "科技", "subtitle": "Công nghệ - Beginner", "iconEmoji": "💻", "level": "Beginner", "colorHex": "#6366F1", "cardCount": 30},
    {"id": "zh_tech_intermediate", "languageCode": "zh", "title": "科技", "subtitle": "Công nghệ - Intermediate", "iconEmoji": "💻", "level": "Intermediate", "colorHex": "#4F46E5", "cardCount": 30},
    {"id": "zh_tech_advanced", "languageCode": "zh", "title": "科技", "subtitle": "Công nghệ - Advanced", "iconEmoji": "💻", "level": "Advanced", "colorHex": "#4338CA", "cardCount": 30},
    {"id": "zh_tech_expert", "languageCode": "zh", "title": "科技", "subtitle": "Công nghệ - Expert", "iconEmoji": "💻", "level": "Expert", "colorHex": "#3730A3", "cardCount": 30}
]

vocab_data = [
    # ---- FOOD & DRINKS ----
    # Beginner (0)
    ("吃", "Chī", "verb", "吃饭。", "Ăn", "Ăn cơm.", "Eat", "zh_food_beginner"),
    ("喝", "Hē", "verb", "喝水。", "Uống", "Uống nước.", "Drink", "zh_food_beginner"),
    ("饭", "Fàn", "noun", "做饭。", "Cơm, bữa ăn", "Nấu ăn.", "Meal/Rice", "zh_food_beginner"),
    ("菜", "Cài", "noun", "买菜。", "Rau, món ăn", "Đi chợ mua đồ ăn.", "Dish/Vegetable", "zh_food_beginner"),
    ("水", "Shuǐ", "noun", "喝水。", "Nước", "Uống nước.", "Water", "zh_food_beginner"),
    ("茶", "Chá", "noun", "喝茶。", "Trà", "Uống trà.", "Tea", "zh_food_beginner"),
    ("咖啡", "Kāfēi", "noun", "喝咖啡。", "Cà phê", "Uống cà phê.", "Coffee", "zh_food_beginner"),
    ("牛奶", "Niúnǎi", "noun", "喝牛奶。", "Sữa bò", "Uống sữa bò.", "Milk", "zh_food_beginner"),
    ("苹果", "Píngguǒ", "noun", "吃苹果。", "Quả táo", "Ăn táo.", "Apple", "zh_food_beginner"),
    ("米饭", "Mǐfàn", "noun", "吃米饭。", "Cơm tẻ", "Ăn cơm.", "Cooked rice", "zh_food_beginner"),
    ("面条", "Miàntiáo", "noun", "吃面条。", "Mì sợi", "Ăn mì.", "Noodles", "zh_food_beginner"),
    ("包子", "Bāozi", "noun", "吃包子。", "Bánh bao", "Ăn bánh bao.", "Steamed bun", "zh_food_beginner"),
    ("饺子", "Jiǎozi", "noun", "吃饺子。", "Há cảo, sủi cảo", "Ăn sủi cảo.", "Dumplings", "zh_food_beginner"),
    ("汤", "Tāng", "noun", "喝汤。", "Canh", "Uống canh.", "Soup", "zh_food_beginner"),
    ("肉", "Ròu", "noun", "吃肉。", "Thịt", "Ăn thịt.", "Meat", "zh_food_beginner"),
    ("鱼", "Yú", "noun", "吃鱼。", "Cá", "Ăn cá.", "Fish", "zh_food_beginner"),
    ("鸡", "Jī", "noun", "鸡肉。", "Gà", "Thịt gà.", "Chicken", "zh_food_beginner"),
    ("蛋", "Dàn", "noun", "鸡蛋。", "Trứng", "Trứng gà.", "Egg", "zh_food_beginner"),
    ("盐", "Yán", "noun", "加点盐。", "Muối", "Cho thêm chút muối.", "Salt", "zh_food_beginner"),
    ("糖", "Táng", "noun", "吃糖。", "Đường, kẹo", "Ăn kẹo / ăn đường.", "Sugar/Candy", "zh_food_beginner"),
    ("好吃", "Hǎochī", "adjective", "很好吃。", "Ngon (ăn)", "Rất ngon.", "Delicious", "zh_food_beginner"),
    ("好喝", "Hǎohē", "adjective", "很好喝。", "Ngon (uống)", "Uống rất ngon.", "Tasty (drink)", "zh_food_beginner"),
    ("饿", "È", "adjective", "我饿了。", "Đói", "Tôi đói rồi.", "Hungry", "zh_food_beginner"),
    ("饱", "Bǎo", "adjective", "我饱了。", "No", "Tôi no rồi.", "Full", "zh_food_beginner"),
    ("甜", "Tián", "adjective", "很甜。", "Ngọt", "Rất ngọt.", "Sweet", "zh_food_beginner"),
    ("咸", "Xián", "adjective", "太咸了。", "Mặn", "Mặn quá.", "Salty", "zh_food_beginner"),
    ("酸", "Suān", "adjective", "很酸。", "Chua", "Rất chua.", "Sour", "zh_food_beginner"),
    ("辣", "Là", "adjective", "太辣了。", "Cay", "Cay quá.", "Spicy", "zh_food_beginner"),
    ("苦", "Kǔ", "adjective", "咖啡很苦。", "Đắng", "Cà phê rất đắng.", "Bitter", "zh_food_beginner"),
    ("热", "Rè", "adjective", "菜很热。", "Nóng", "Món ăn đang nóng.", "Hot", "zh_food_beginner"),

    # Intermediate (1)
    ("餐厅", "Cāntīng", "noun", "去餐厅吃饭。", "Nhà hàng", "Đến nhà hàng ăn cơm.", "Restaurant", "zh_food_intermediate"),
    ("菜单", "Càidān", "noun", "看菜单。", "Thực đơn", "Xem thực đơn.", "Menu", "zh_food_intermediate"),
    ("点菜", "Diǎncài", "verb", "请点菜。", "Gọi món", "Xin mời gọi món.", "Order food", "zh_food_intermediate"),
    ("买单", "Mǎidān", "verb", "服务员，买单。", "Thanh toán", "Phục vụ, tính tiền.", "Pay the bill", "zh_food_intermediate"),
    ("服务员", "Fúwùyuán", "noun", "叫服务员。", "Nhân viên phục vụ", "Gọi nhân viên phục vụ.", "Waiter", "zh_food_intermediate"),
    ("早餐", "Zǎocān", "noun", "吃早餐。", "Bữa sáng", "Ăn sáng.", "Breakfast", "zh_food_intermediate"),
    ("午餐", "Wǔcān", "noun", "吃午餐。", "Bữa trưa", "Ăn trưa.", "Lunch", "zh_food_intermediate"),
    ("晚餐", "Wǎncān", "noun", "吃晚餐。", "Bữa tối", "Ăn tối.", "Dinner", "zh_food_intermediate"),
    ("零食", "Língshí", "noun", "吃零食。", "Đồ ăn vặt", "Ăn đồ ăn vặt.", "Snack", "zh_food_intermediate"),
    ("饮料", "Yǐnliào", "noun", "喝饮料。", "Đồ uống", "Uống nước giải khát.", "Beverage", "zh_food_intermediate"),
    ("果汁", "Guǒzhī", "noun", "苹果汁。", "Nước ép hoa quả", "Nước ép táo.", "Juice", "zh_food_intermediate"),
    ("啤酒", "Píjiǔ", "noun", "喝啤酒。", "Bia", "Uống bia.", "Beer", "zh_food_intermediate"),
    ("葡萄酒", "Pútaojiǔ", "noun", "红葡萄酒。", "Rượu vang", "Rượu vang đỏ.", "Wine", "zh_food_intermediate"),
    ("蔬菜", "Shūcài", "noun", "多吃蔬菜。", "Rau củ", "Ăn nhiều rau củ.", "Vegetable", "zh_food_intermediate"),
    ("水果", "Shuǐguǒ", "noun", "买水果。", "Hoa quả", "Mua trái cây.", "Fruit", "zh_food_intermediate"),
    ("海鲜", "Hǎixiān", "noun", "吃海鲜。", "Hải sản", "Ăn hải sản.", "Seafood", "zh_food_intermediate"),
    ("牛肉", "Niúròu", "noun", "烤牛肉。", "Thịt bò", "Thịt bò nướng.", "Beef", "zh_food_intermediate"),
    ("猪肉", "Zhūròu", "noun", "猪肉炖粉条。", "Thịt lợn", "Thịt heo hầm miến.", "Pork", "zh_food_intermediate"),
    ("羊肉", "Yángròu", "noun", "羊肉串。", "Thịt cừu", "Thịt cừu xiên nướng.", "Mutton", "zh_food_intermediate"),
    ("豆腐", "Dòufu", "noun", "麻婆豆腐。", "Đậu phụ", "Đậu hũ ma bà.", "Tofu", "zh_food_intermediate"),
    ("炒饭", "Chǎofàn", "noun", "蛋炒饭。", "Cơm rang", "Cơm rang trứng.", "Fried rice", "zh_food_intermediate"),
    ("火锅", "Huǒguō", "noun", "吃火锅。", "Lẩu", "Ăn lẩu.", "Hotpot", "zh_food_intermediate"),
    ("烤鸭", "Kǎoyā", "noun", "北京烤鸭。", "Vịt quay", "Vịt quay Bắc Kinh.", "Roast duck", "zh_food_intermediate"),
    ("汉堡包", "Hànbǎobāo", "noun", "吃汉堡包。", "Bánh Hamburger", "Ăn hamburger.", "Hamburger", "zh_food_intermediate"),
    ("披萨", "Pīsà", "noun", "吃披萨。", "Bánh Pizza", "Ăn pizza.", "Pizza", "zh_food_intermediate"),
    ("蛋糕", "Dàngāo", "noun", "生日蛋糕。", "Bánh kem", "Bánh sinh nhật.", "Cake", "zh_food_intermediate"),
    ("冰淇淋", "Bīngqílín", "noun", "吃冰淇淋。", "Kem", "Ăn kem lạnh.", "Ice cream", "zh_food_intermediate"),
    ("筷子", "Kuàizi", "noun", "用筷子。", "Đũa", "Dùng đũa.", "Chopsticks", "zh_food_intermediate"),
    ("勺子", "Sháozi", "noun", "用勺子喝汤。", "Thìa, muỗng", "Dùng thìa uống canh.", "Spoon", "zh_food_intermediate"),
    ("碗", "Wǎn", "noun", "一碗饭。", "Bát, chén", "Một bát cơm.", "Bowl", "zh_food_intermediate"),

    # Advanced (2)
    ("烹饪", "Pēngrèn", "noun/verb", "烹饪学校。", "Nấu ăn, ẩm thực", "Trường dạy nấu ăn.", "Cooking/Culinary", "zh_food_advanced"),
    ("厨师", "Chúshī", "noun", "主厨。", "Đầu bếp", "Bếp trưởng.", "Chef", "zh_food_advanced"),
    ("食材", "Shícái", "noun", "新鲜的食材。", "Nguyên liệu nấu ăn", "Nguyên liệu tươi mới.", "Ingredients", "zh_food_advanced"),
    ("调料", "Tiáoliào", "noun", "加调料。", "Gia vị", "Thêm gia vị.", "Seasoning", "zh_food_advanced"),
    ("酱油", "Jiàngyóu", "noun", "加点酱油。", "Nước tương (xì dầu)", "Thêm chút xì dầu.", "Soy sauce", "zh_food_advanced"),
    ("醋", "Cù", "noun", "吃饺子蘸醋。", "Giấm", "Ăn sủi cảo chấm giấm.", "Vinegar", "zh_food_advanced"),
    ("辣椒", "Làjiāo", "noun", "切辣椒。", "Ớt", "Thái ớt.", "Chili pepper", "zh_food_advanced"),
    ("葱姜蒜", "Cōng jiāng suàn", "phrase", "葱姜蒜爆香。", "Hành, gừng, tỏi", "Phi thơm hành gừng tỏi.", "Scallion, ginger, garlic", "zh_food_advanced"),
    ("煎", "Jiān", "verb", "煎鸡蛋。", "Chiên, rán", "Trứng ốp la (chiên).", "Pan-fry", "zh_food_advanced"),
    ("炒", "Chǎo", "verb", "炒菜。", "Xào", "Xào rau.", "Stir-fry", "zh_food_advanced"),
    ("炸", "Zhá", "verb", "炸鸡腿。", "Chiên (ngập dầu)", "Đùi gà chiên giòn.", "Deep-fry", "zh_food_advanced"),
    ("煮", "Zhǔ", "verb", "煮饺子。", "Luộc, nấu", "Luộc sủi cảo.", "Boil", "zh_food_advanced"),
    ("蒸", "Zhēng", "verb", "蒸鱼。", "Hấp", "Cá hấp.", "Steam", "zh_food_advanced"),
    ("烤", "Kǎo", "verb", "烤肉。", "Nướng", "Thịt nướng.", "Roast/Bake", "zh_food_advanced"),
    ("炖", "Dùn", "verb", "炖排骨。", "Hầm", "Sườn hầm.", "Stew", "zh_food_advanced"),
    ("凉拌", "Liángbàn", "verb", "凉拌黄瓜。", "Trộn (gỏi/nộm)", "Dưa chuột trộn nộm.", "Cold toss", "zh_food_advanced"),
    ("口味", "Kǒuwèi", "noun", "口味很重。", "Khẩu vị", "Khẩu vị rất đậm.", "Taste/Flavor preference", "zh_food_advanced"),
    ("清淡", "Qīngdàn", "adjective", "吃的清淡。", "Thanh đạm", "Ăn uống thanh đạm.", "Light (flavor)", "zh_food_advanced"),
    ("油腻", "Yóunì", "adjective", "太油腻了。", "Béo ngậy, nhiều dầu mỡ", "Nhiều dầu mỡ quá.", "Greasy", "zh_food_advanced"),
    ("营养", "Yíngyǎng", "noun", "营养均衡。", "Dinh dưỡng", "Dinh dưỡng cân bằng.", "Nutrition", "zh_food_advanced"),
    ("素食", "Sùshí", "noun", "素食主义者。", "Đồ chay", "Người ăn chay.", "Vegetarian food", "zh_food_advanced"),
    ("荤菜", "Hūncài", "noun", "荤菜和素菜。", "Món mặn (có thịt)", "Món mặn và món chay.", "Meat dish", "zh_food_advanced"),
    ("特色菜", "Tèsècài", "noun", "这里的特色菜是什么？", "Món đặc sản", "Đặc sản ở đây là gì?", "Specialty dish", "zh_food_advanced"),
    ("招牌菜", "Zhāopáicài", "noun", "餐厅的招牌菜。", "Món tủ", "Món tủ của nhà hàng.", "Signature dish", "zh_food_advanced"),
    ("自助餐", "Zìzhùcān", "noun", "吃自助餐。", "Buffet", "Ăn buffet.", "Buffet", "zh_food_advanced"),
    ("夜宵", "Yèxiāo", "noun", "吃夜宵。", "Bữa ăn đêm", "Ăn đêm.", "Midnight snack", "zh_food_advanced"),
    ("外卖", "Wàimài", "noun", "点外卖。", "Đồ ăn mang đi", "Gọi đồ ăn ship đến.", "Takeout", "zh_food_advanced"),
    ("预订", "Yùdìng", "verb", "预订座位。", "Đặt trước", "Đặt bàn trước.", "Reserve", "zh_food_advanced"),
    ("包厢", "Bāoxiāng", "noun", "订一个包厢。", "Phòng riêng (VIP)", "Đặt một phòng VIP.", "Private room", "zh_food_advanced"),
    ("结账", "Jiézhàng", "verb", "请结账。", "Tính tiền", "Xin thanh toán.", "Pay the bill", "zh_food_advanced"),

    # Expert (3)
    ("美食家", "Měishíjiā", "noun", "著名的美食家。", "Nhà ẩm thực", "Nhà phê bình ẩm thực nổi tiếng.", "Gourmet", "zh_food_expert"),
    ("品鉴", "Pǐnjiàn", "verb", "品鉴红酒。", "Thưởng thức, thẩm định", "Thẩm định rượu vang đỏ.", "Taste and appreciate", "zh_food_expert"),
    ("八大菜系", "Bādà càixì", "phrase", "中国八大菜系。", "Bát đại thái hệ", "Tám trường phái ẩm thực Trung Hoa.", "Eight culinary traditions", "zh_food_expert"),
    ("色香味", "Sè xiāng wèi", "phrase", "色香味俱全。", "Sắc, hương, vị", "Hội tụ đủ cả sắc, hương và vị.", "Color, aroma, and taste", "zh_food_expert"),
    ("火候", "Huǒhòu", "noun", "掌握火候。", "Mức độ lửa", "Làm chủ mức độ lửa khi nấu.", "Control of heat", "zh_food_expert"),
    ("刀工", "Dāogōng", "noun", "刀工精湛。", "Kỹ thuật dùng dao", "Kỹ thuật thái thái cắt tỉa điêu luyện.", "Knife skills", "zh_food_expert"),
    ("摆盘", "Bǎipán", "noun/verb", "讲究摆盘。", "Trình bày món ăn", "Rất chú trọng cách trang trí món ăn.", "Plating", "zh_food_expert"),
    ("原汁原味", "Yuánzhī yuánwèi", "idiom", "保持原汁原味。", "Hương vị nguyên bản", "Giữ được mùi vị nguyên chất.", "Original taste and flavor", "zh_food_expert"),
    ("提鲜", "Tíxiān", "verb", "用高汤提鲜。", "Làm dậy mùi/vị ngọt", "Dùng nước hầm xương để tăng vị umami.", "Enhance umami flavor", "zh_food_expert"),
    ("去腥", "Qùxīng", "verb", "用姜去腥。", "Khử mùi tanh", "Dùng gừng khử mùi tanh.", "Remove fishy smell", "zh_food_expert"),
    ("勾芡", "Gōuqiàn", "verb", "勾芡收汁。", "Làm sệt nước sốt", "Cho bột năng vào làm sánh nước sốt.", "Thicken soup", "zh_food_expert"),
    ("腌制", "Yānzhì", "verb", "腌制肉类。", "Tẩm ướp", "Tẩm ướp các loại thịt.", "Marinate", "zh_food_expert"),
    ("发酵", "Fājiào", "verb", "发酵面团。", "Lên men", "Ủ lên men bột mì.", "Ferment", "zh_food_expert"),
    ("烘焙", "Hōngbèi", "verb", "烘焙面包。", "Nướng bánh", "Làm bánh mì nướng.", "Baking", "zh_food_expert"),
    ("碳水化合物", "Tànshuǐ huàhéwù", "noun", "减少碳水化合物摄入。", "Tinh bột", "Giảm lượng hấp thụ carbohydrate.", "Carbohydrate", "zh_food_expert"),
    ("蛋白质", "Dànbáizhì", "noun", "补充蛋白质。", "Protein", "Bổ sung chất đạm.", "Protein", "zh_food_expert"),
    ("脂肪", "Zhīfáng", "noun", "燃烧脂肪。", "Chất béo", "Đốt cháy mỡ thừa.", "Fat", "zh_food_expert"),
    ("维生素", "Wéishēngsù", "noun", "补充维生素C。", "Vitamin", "Bổ sung vitamin C.", "Vitamin", "zh_food_expert"),
    ("膳食纤维", "Shànshí xiānwéi", "noun", "富含膳食纤维。", "Chất xơ", "Giàu chất xơ.", "Dietary fiber", "zh_food_expert"),
    ("卡路里", "Kǎlùlǐ", "noun", "计算卡路里。", "Calorie", "Tính toán lượng calo.", "Calorie", "zh_food_expert"),
    ("有机食品", "Yǒujī shípǐn", "noun", "购买有机食品。", "Thực phẩm hữu cơ", "Mua thực phẩm organic.", "Organic food", "zh_food_expert"),
    ("转基因", "Zhuǎnjīyīn", "adjective", "转基因大豆。", "Biến đổi gen", "Đậu nành biến đổi gen.", "Genetically modified", "zh_food_expert"),
    ("食品添加剂", "Shípǐn tiānjiājì", "noun", "含有食品添加剂。", "Chất phụ gia", "Có chứa chất phụ gia thực phẩm.", "Food additive", "zh_food_expert"),
    ("防腐剂", "Fángfǔjì", "noun", "不含防腐剂。", "Chất bảo quản", "Không chứa chất bảo quản.", "Preservative", "zh_food_expert"),
    ("农药残留", "Nóngyào cánliú", "noun", "清洗农药残留。", "Dư lượng thuốc trừ sâu", "Rửa sạch dư lượng thuốc trừ sâu.", "Pesticide residue", "zh_food_expert"),
    ("食品安全", "Shípǐn ānquán", "noun", "重视食品安全。", "An toàn thực phẩm", "Coi trọng an toàn vệ sinh thực phẩm.", "Food safety", "zh_food_expert"),
    ("饮食文化", "Yǐnshí wénhuà", "noun", "了解饮食文化。", "Văn hóa ẩm thực", "Tìm hiểu văn hóa ẩm thực.", "Food culture", "zh_food_expert"),
    ("餐桌礼仪", "Cānzhuō lǐyí", "noun", "遵守餐桌礼仪。", "Phép tắc trên bàn ăn", "Tuân thủ phép lịch sự trên bàn ăn.", "Table manners", "zh_food_expert"),
    ("敬酒", "Jìngjiǔ", "verb", "互相敬酒。", "Mời rượu", "Mời rượu chúc tụng lẫn nhau.", "Toast", "zh_food_expert"),
    ("光盘行动", "Guāngpán xíngdòng", "phrase", "参与光盘行动。", "Chiến dịch sạch đĩa", "Tham gia chiến dịch không bỏ mứa đồ ăn.", "Clean Plate campaign", "zh_food_expert"),

    # ---- TECHNOLOGY ----
    # Beginner (0)
    ("电脑", "Diànnǎo", "noun", "用电脑上网。", "Máy tính", "Dùng máy tính lướt web.", "Computer", "zh_tech_beginner"),
    ("手机", "Shǒujī", "noun", "玩手机。", "Điện thoại di động", "Chơi điện thoại.", "Mobile phone", "zh_tech_beginner"),
    ("电视", "Diànshì", "noun", "看电视。", "Tivi", "Xem tivi.", "Television", "zh_tech_beginner"),
    ("电话", "Diànhuà", "noun", "打电话。", "Điện thoại (bàn)", "Gọi điện thoại.", "Telephone", "zh_tech_beginner"),
    ("网", "Wǎng", "noun", "上网。", "Mạng internet", "Lên mạng.", "Internet", "zh_tech_beginner"),
    ("电池", "Diànchí", "noun", "换电池。", "Pin", "Thay pin.", "Battery", "zh_tech_beginner"),
    ("充电", "Chōngdiàn", "verb", "手机充电。", "Sạc pin", "Sạc điện thoại.", "Charge", "zh_tech_beginner"),
    ("开", "Kāi", "verb", "开电脑。", "Mở, bật", "Bật máy tính.", "Turn on", "zh_tech_beginner"),
    ("关", "Guān", "verb", "关电视。", "Tắt", "Tắt tivi.", "Turn off", "zh_tech_beginner"),
    ("打", "Dǎ", "verb", "打印文件。", "Đánh, gõ, in", "In tài liệu.", "Type/Print", "zh_tech_beginner"),
    ("密码", "Mìmǎ", "noun", "输入密码。", "Mật khẩu", "Nhập mật khẩu.", "Password", "zh_tech_beginner"),
    ("游戏", "Yóuxì", "noun", "玩游戏。", "Trò chơi", "Chơi game.", "Game", "zh_tech_beginner"),
    ("照片", "Zhàopiàn", "noun", "拍照片。", "Bức ảnh", "Chụp ảnh.", "Photo", "zh_tech_beginner"),
    ("视频", "Shìpín", "noun", "看视频。", "Video", "Xem video.", "Video", "zh_tech_beginner"),
    ("音乐", "Yīnyuè", "noun", "听音乐。", "Âm nhạc", "Nghe nhạc.", "Music", "zh_tech_beginner"),
    ("电影", "Diànyǐng", "noun", "看电影。", "Phim điện ảnh", "Xem phim.", "Movie", "zh_tech_beginner"),
    ("发", "Fā", "verb", "发短信。", "Gửi", "Gửi tin nhắn.", "Send", "zh_tech_beginner"),
    ("收", "Shōu", "verb", "收邮件。", "Nhận", "Nhận email.", "Receive", "zh_tech_beginner"),
    ("短信", "Duǎnxìn", "noun", "发短信。", "Tin nhắn", "Gắn tin nhắn.", "Text message", "zh_tech_beginner"),
    ("邮件", "Yóujiàn", "noun", "电子邮件。", "Thư điện tử", "Email.", "Email", "zh_tech_beginner"),
    ("微信", "Wēixìn", "noun", "发微信。", "WeChat", "Gắn tin WeChat.", "WeChat", "zh_tech_beginner"),
    ("百度", "Bǎidù", "noun", "百度一下。", "Baidu", "Lên Baidu tìm thử.", "Baidu", "zh_tech_beginner"),
    ("淘宝", "Táobǎo", "noun", "逛淘宝。", "Taobao", "Dạo xem Taobao.", "Taobao", "zh_tech_beginner"),
    ("鼠标", "Shǔbiāo", "noun", "用鼠标。", "Chuột máy tính", "Dùng chuột.", "Mouse", "zh_tech_beginner"),
    ("键盘", "Jiànpán", "noun", "敲键盘。", "Bàn phím", "Gõ bàn phím.", "Keyboard", "zh_tech_beginner"),
    ("屏幕", "Píngmù", "noun", "电脑屏幕。", "Màn hình", "Màn hình máy tính.", "Screen", "zh_tech_beginner"),
    ("耳机", "Ěrjī", "noun", "戴耳机。", "Tai nghe", "Đeo tai nghe.", "Earphones", "zh_tech_beginner"),
    ("坏", "Huài", "adjective", "电脑坏了。", "Hỏng", "Máy tính bị hỏng rồi.", "Broken", "zh_tech_beginner"),
    ("修", "Xiū", "verb", "修手机。", "Sửa chữa", "Sửa điện thoại.", "Repair", "zh_tech_beginner"),
    ("快", "Kuài", "adjective", "网速很快。", "Nhanh", "Tốc độ mạng rất nhanh.", "Fast", "zh_tech_beginner"),

    # Intermediate (1)
    ("科技", "Kējì", "noun", "科技发展。", "Khoa học công nghệ", "Sự phát triển công nghệ.", "Technology", "zh_tech_intermediate"),
    ("网络", "Wǎngluò", "noun", "网络连接。", "Mạng (network)", "Kết nối mạng.", "Network", "zh_tech_intermediate"),
    ("网站", "Wǎngzhàn", "noun", "访问网站。", "Trang web", "Truy cập trang web.", "Website", "zh_tech_intermediate"),
    ("网页", "Wǎngyè", "noun", "浏览网页。", "Trình duyệt web", "Lướt xem trang web.", "Webpage", "zh_tech_intermediate"),
    ("软件", "Ruǎnjiàn", "noun", "下载软件。", "Phần mềm", "Tải phần mềm.", "Software", "zh_tech_intermediate"),
    ("硬件", "Yìngjiàn", "noun", "硬件设备。", "Phần cứng", "Thiết bị phần cứng.", "Hardware", "zh_tech_intermediate"),
    ("应用程序", "Yìngyòng chéngxù", "noun", "手机App。", "Ứng dụng (App)", "Ứng dụng trên điện thoại di động.", "Application (App)", "zh_tech_intermediate"),
    ("下载", "Xiàzài", "verb", "下载文件。", "Tải xuống", "Tải tệp tin.", "Download", "zh_tech_intermediate"),
    ("上传", "Shàngchuán", "verb", "上传照片。", "Tải lên", "Tải ảnh lên mạng.", "Upload", "zh_tech_intermediate"),
    ("安装", "Ānzhuāng", "verb", "安装软件。", "Cài đặt", "Cài đặt phần mềm.", "Install", "zh_tech_intermediate"),
    ("卸载", "Xièzài", "verb", "卸载游戏。", "Gỡ cài đặt", "Xóa cài đặt game.", "Uninstall", "zh_tech_intermediate"),
    ("更新", "Gēngxīn", "verb", "更新系统。", "Cập nhật", "Cập nhật hệ thống.", "Update", "zh_tech_intermediate"),
    ("系统", "Xìtǒng", "noun", "操作系统。", "Hệ thống", "Hệ điều hành.", "System", "zh_tech_intermediate"),
    ("文件", "Wénjiàn", "noun", "文件夹。", "Tệp tin", "Thư mục chứa file.", "File", "zh_tech_intermediate"),
    ("复制", "Fùzhì", "verb", "复制文本。", "Sao chép", "Copy đoạn văn bản.", "Copy", "zh_tech_intermediate"),
    ("粘贴", "Zhāntiē", "verb", "粘贴链接。", "Dán", "Dán đường link vào.", "Paste", "zh_tech_intermediate"),
    ("删除", "Shānchú", "verb", "删除文件。", "Xóa", "Xóa file này đi.", "Delete", "zh_tech_intermediate"),
    ("保存", "Bǎocún", "verb", "保存图片。", "Lưu", "Lưu lại bức ảnh.", "Save", "zh_tech_intermediate"),
    ("账号", "Zhànghào", "noun", "登录账号。", "Tài khoản", "Đăng nhập vào tài khoản.", "Account", "zh_tech_intermediate"),
    ("登录", "Dēnglù", "verb", "登录系统。", "Đăng nhập", "Đăng nhập vào hệ thống.", "Log in", "zh_tech_intermediate"),
    ("退出", "Tuìchū", "verb", "退出账号。", "Đăng xuất", "Thoát khỏi tài khoản.", "Log out", "zh_tech_intermediate"),
    ("注册", "Zhùcè", "verb", "注册新账号。", "Đăng ký", "Tạo một tài khoản mới.", "Register", "zh_tech_intermediate"),
    ("搜索", "Sōusuǒ", "verb", "搜索引擎。", "Tìm kiếm", "Công cụ tìm kiếm.", "Search", "zh_tech_intermediate"),
    ("链接", "Liànjiē", "noun", "点击链接。", "Đường link", "Bấm vào đường link.", "Link", "zh_tech_intermediate"),
    ("路由器", "Lùyóuqì", "noun", "重启路由器。", "Bộ định tuyến (Router wifi)", "Khởi động lại router wifi.", "Router", "zh_tech_intermediate"),
    ("信号", "Xìnhào", "noun", "手机信号不好。", "Tín hiệu", "Sóng điện thoại yếu.", "Signal", "zh_tech_intermediate"),
    ("宽带", "Kuāndài", "noun", "安装宽带。", "Băng thông rộng", "Lắp đặt internet cáp quang.", "Broadband", "zh_tech_intermediate"),
    ("蓝牙", "Lányá", "noun", "蓝牙耳机。", "Bluetooth", "Tai nghe bluetooth.", "Bluetooth", "zh_tech_intermediate"),
    ("摄像头", "Shèxiàngtóu", "noun", "打开摄像头。", "Camera", "Mở webcam lên.", "Webcam/Camera", "zh_tech_intermediate"),
    ("麦克风", "Màikèfēng", "noun", "麦克风没声音。", "Micro", "Mic không thu được tiếng.", "Microphone", "zh_tech_intermediate"),

    # Advanced (2)
    ("互联网", "Hùliánwǎng", "noun", "移动互联网。", "Internet", "Internet di động.", "Internet", "zh_tech_advanced"),
    ("物联网", "Wùliánwǎng", "noun", "物联网技术。", "Internet vạn vật (IoT)", "Công nghệ IoT.", "Internet of Things", "zh_tech_advanced"),
    ("人工智能", "Réngōng zhìnéng", "noun", "AI人工智能。", "Trí tuệ nhân tạo (AI)", "Trí tuệ nhân tạo (AI).", "Artificial Intelligence", "zh_tech_advanced"),
    ("大数据", "Dàshùjù", "noun", "大数据分析。", "Dữ liệu lớn (Big Data)", "Phân tích Big Data.", "Big Data", "zh_tech_advanced"),
    ("云计算", "Yúnjìsuàn", "noun", "云计算服务。", "Điện toán đám mây", "Dịch vụ Cloud computing.", "Cloud computing", "zh_tech_advanced"),
    ("区块链", "Qūkuàiliàn", "noun", "区块链技术。", "Chuỗi khối (Blockchain)", "Công nghệ blockchain.", "Blockchain", "zh_tech_advanced"),
    ("虚拟现实", "Xūnǐ xiànshí", "noun", "VR虚拟现实。", "Thực tế ảo (VR)", "Công nghệ VR.", "Virtual Reality", "zh_tech_advanced"),
    ("增强现实", "Zēngqiáng xiànshí", "noun", "AR增强现实。", "Thực tế tăng cường (AR)", "Công nghệ AR.", "Augmented Reality", "zh_tech_advanced"),
    ("算法", "Suànfǎ", "noun", "推荐算法。", "Thuật toán", "Thuật toán đề xuất nội dung.", "Algorithm", "zh_tech_advanced"),
    ("编程", "Biānchéng", "noun/verb", "学习编程。", "Lập trình", "Học lập trình.", "Programming", "zh_tech_advanced"),
    ("代码", "Dàimǎ", "noun", "写代码。", "Mã code", "Viết mã nguồn (code).", "Code", "zh_tech_advanced"),
    ("数据库", "Shùjùkù", "noun", "建立数据库。", "Cơ sở dữ liệu", "Xây dựng database.", "Database", "zh_tech_advanced"),
    ("服务器", "Fúwùqì", "noun", "服务器宕机。", "Máy chủ (Server)", "Máy chủ bị sập (down).", "Server", "zh_tech_advanced"),
    ("客户端", "Kèhùduān", "noun", "手机客户端。", "Ứng dụng khách (Client)", "Ứng dụng trên máy khách.", "Client", "zh_tech_advanced"),
    ("浏览器", "Liúlǎnqì", "noun", "网页浏览器。", "Trình duyệt", "Trình duyệt web.", "Browser", "zh_tech_advanced"),
    ("操作系统", "Cāozuò xìtǒng", "noun", "Windows操作系统。", "Hệ điều hành", "Hệ điều hành Windows.", "Operating system", "zh_tech_advanced"),
    ("黑客", "Hēikè", "noun", "黑客攻击。", "Hacker", "Cuộc tấn công của tin tặc.", "Hacker", "zh_tech_advanced"),
    ("病毒", "Bìngdú", "noun", "电脑中了病毒。", "Virus máy tính", "Máy tính bị nhiễm virus.", "Virus", "zh_tech_advanced"),
    ("防火墙", "Fánghuǒqiáng", "noun", "设置防火墙。", "Tường lửa", "Thiết lập tường lửa bảo vệ.", "Firewall", "zh_tech_advanced"),
    ("加密", "Jiāmì", "verb", "数据加密。", "Mã hóa", "Mã hóa dữ liệu.", "Encrypt", "zh_tech_advanced"),
    ("隐私", "Yǐnsī", "noun", "保护隐私。", "Quyền riêng tư", "Bảo vệ thông tin cá nhân.", "Privacy", "zh_tech_advanced"),
    ("像素", "Xiàngsù", "noun", "摄像头像素高。", "Điểm ảnh (Pixel)", "Camera có độ phân giải cao.", "Pixel", "zh_tech_advanced"),
    ("分辨率", "Fēnbiànlǜ", "noun", "屏幕分辨率。", "Độ phân giải", "Độ phân giải màn hình.", "Resolution", "zh_tech_advanced"),
    ("内存", "Nèicún", "noun", "手机内存不足。", "Bộ nhớ trong, RAM", "Điện thoại hết dung lượng.", "Memory/RAM", "zh_tech_advanced"),
    ("硬盘", "Yìngpán", "noun", "移动硬盘。", "Ổ cứng", "Ổ cứng di động.", "Hard drive", "zh_tech_advanced"),
    ("芯片", "Xīnpiàn", "noun", "研发芯片。", "Con chip", "Nghiên cứu phát triển con chip.", "Chip", "zh_tech_advanced"),
    ("处理器", "Chǔlǐqì", "noun", "中央处理器 (CPU)。", "Bộ vi xử lý", "Vi xử lý trung tâm (CPU).", "Processor", "zh_tech_advanced"),
    ("升级", "Shēngjí", "verb", "固件升级。", "Nâng cấp", "Nâng cấp phần sụn (firmware).", "Upgrade", "zh_tech_advanced"),
    ("兼容", "Jiānróng", "adjective", "系统不兼容。", "Tương thích", "Hệ thống không tương thích.", "Compatible", "zh_tech_advanced"),
    ("漏洞", "Lòudòng", "noun", "修复系统漏洞。", "Lỗ hổng (Bug)", "Vá lỗ hổng bảo mật.", "Vulnerability/Bug", "zh_tech_advanced"),

    # Expert (3)
    ("机器学习", "Jīqì xuéxí", "noun", "机器学习模型。", "Học máy (Machine Learning)", "Mô hình Machine Learning.", "Machine learning", "zh_tech_expert"),
    ("深度学习", "Shēndù xuéxí", "noun", "深度学习算法。", "Học sâu (Deep Learning)", "Thuật toán học sâu.", "Deep learning", "zh_tech_expert"),
    ("神经网络", "Shénjīng wǎngluò", "noun", "人工神经网络。", "Mạng nơ-ron", "Mạng nơ-ron nhân tạo.", "Neural network", "zh_tech_expert"),
    ("自然语言处理", "Zìrán yǔyán chǔlǐ", "noun", "NLP技术。", "Xử lý ngôn ngữ tự nhiên", "Công nghệ NLP.", "Natural Language Processing", "zh_tech_expert"),
    ("计算机视觉", "Jìsuànjī shìjué", "noun", "计算机视觉应用。", "Thị giác máy tính", "Ứng dụng Computer Vision.", "Computer vision", "zh_tech_expert"),
    ("自动驾驶", "Zìdòng jiàshǐ", "noun", "自动驾驶汽车。", "Lái xe tự động", "Xe hơi tự hành.", "Autonomous driving", "zh_tech_expert"),
    ("边缘计算", "Biānyuán jìsuàn", "noun", "边缘计算节点。", "Điện toán biên", "Nút Edge computing.", "Edge computing", "zh_tech_expert"),
    ("量子计算", "Liàngzǐ jìsuàn", "noun", "量子计算机。", "Điện toán lượng tử", "Máy tính lượng tử.", "Quantum computing", "zh_tech_expert"),
    ("元宇宙", "Yuányǔzhòu", "noun", "元宇宙概念。", "Vũ trụ ảo (Metaverse)", "Khái niệm Metaverse.", "Metaverse", "zh_tech_expert"),
    ("Web3.0", "Wěi-bù-sān-diǎn-líng", "noun", "Web3.0时代。", "Web 3.0", "Kỷ nguyên Web 3.", "Web 3.0", "zh_tech_expert"),
    ("去中心化", "Qù zhōngxīnhuà", "noun/verb", "去中心化金融。", "Phi tập trung", "Tài chính phi tập trung (DeFi).", "Decentralization", "zh_tech_expert"),
    ("智能合约", "Zhìnéng héyuē", "noun", "部署智能合约。", "Hợp đồng thông minh", "Triển khai Smart Contract.", "Smart contract", "zh_tech_expert"),
    ("NFT", "N-F-T", "noun", "非同质化代币。", "NFT", "Tài sản kỹ thuật số độc nhất (NFT).", "NFT", "zh_tech_expert"),
    ("开源", "Kāiyuán", "adjective", "开源软件。", "Mã nguồn mở", "Phần mềm Open-source.", "Open source", "zh_tech_expert"),
    ("敏捷开发", "Mǐnjié kāifā", "noun", "采用敏捷开发。", "Phát triển linh hoạt", "Áp dụng phương pháp Agile.", "Agile development", "zh_tech_expert"),
    ("架构", "Jiàgòu", "noun", "系统架构设计。", "Kiến trúc (hệ thống)", "Thiết kế kiến trúc hệ thống.", "Architecture", "zh_tech_expert"),
    ("微服务", "Wēifúwù", "noun", "微服务架构。", "Vi dịch vụ", "Kiến trúc Microservices.", "Microservices", "zh_tech_expert"),
    ("API", "A-P-I", "noun", "应用程序接口。", "API", "Giao tiếp lập trình ứng dụng.", "API", "zh_tech_expert"),
    ("SDK", "S-D-K", "noun", "软件开发工具包。", "Bộ công cụ phát triển phần mềm", "Tài nguyên SDK.", "SDK", "zh_tech_expert"),
    ("调试", "Tiáoshì", "verb", "调试代码。", "Sửa lỗi (Debug)", "Quá trình debug code.", "Debug", "zh_tech_expert"),
    ("迭代", "Diédài", "verb/noun", "产品快速迭代。", "Lặp lại, cập nhật", "Liên tục ra mắt phiên bản mới.", "Iterate", "zh_tech_expert"),
    ("部署", "Bùshǔ", "verb", "部署到云端。", "Triển khai (Deploy)", "Đưa sản phẩm lên môi trường live.", "Deploy", "zh_tech_expert"),
    ("运维", "Yùnwéi", "noun", "IT运维。", "Vận hành và bảo trì", "Bộ phận DevOps/IT Ops.", "Operations and maintenance", "zh_tech_expert"),
    ("渗透测试", "Shèntòu cèshì", "noun", "进行渗透测试。", "Kiểm thử xâm nhập", "Thử nghiệm tấn công bảo mật.", "Penetration testing", "zh_tech_expert"),
    ("勒索软件", "Lèsuǒ ruǎnjiàn", "noun", "遭到勒索软件攻击。", "Phần mềm tống tiền", "Bị mã độc tống tiền tấn công.", "Ransomware", "zh_tech_expert"),
    ("零日漏洞", "Língrì lòudòng", "noun", "发现零日漏洞。", "Lỗ hổng zero-day", "Phát hiện lỗi bảo mật chưa từng biết.", "Zero-day vulnerability", "zh_tech_expert"),
    ("极客", "Jíkè", "noun", "极客精神。", "Geek (Người cuồng công nghệ)", "Tinh thần của một Geek.", "Geek", "zh_tech_expert"),
    ("创客", "Chuàngkè", "noun", "创客空间。", "Maker (Người tự chế tạo)", "Không gian dành cho các Maker.", "Maker", "zh_tech_expert"),
    ("孵化器", "Fūhuàqì", "noun", "创业孵化器。", "Vườn ươm khởi nghiệp", "Chương trình hỗ trợ startup.", "Incubator", "zh_tech_expert"),
    ("独角兽", "Dújiǎoshòu", "noun", "独角兽企业。", "Kỳ lân", "Công ty startup tỷ đô (Unicorn).", "Unicorn company", "zh_tech_expert")
]

new_flashcards = []
for word, phonetic, pos, ex_zh, meaning, ex_vi, tip, deck_id in vocab_data:
    new_flashcards.append({
        "deckId": deck_id,
        "languageCode": "zh",
        "frontWord": word,
        "phonetic": phonetic,
        "partOfSpeech": pos,
        "frontExample": ex_zh,
        "backMeaning": meaning,
        "backExampleTranslation": ex_vi,
        "memoryTip": tip
    })

if os.path.exists(DB_FILE):
    with open(DB_FILE, "r", encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {"decks": [], "flashCards": []}

data["decks"].extend(decks)
data["flashCards"].extend(new_flashcards)

with open(DB_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Successfully appended 240 words (Food & Drinks, Technology - Chinese) to DB!")
